from cardio_1 import a, G
# Glossaire J21 — Bronchiolite aiguë et infection aiguë des voies respiratoires inférieures (P-02-Pneumologie).
# Clés absentes de glossary/*.py au 09.10.2026 (vérification par chargement de tous les modules).
a('J21.0', [('J21.0', 'code CIM-10-GM 2024')], 'Bronchiolite aiguë due au virus respiratoire syncytial', '<p>Sous-catégorie traitée dans le cours J21 — Bronchiolite aiguë et infection aiguë des voies respiratoires inférieures (catalogue BfArM, version 2024).</p>')
a('J21.1', [('J21.1', 'code CIM-10-GM 2024')], 'Bronchiolite aiguë due au métapneumovirus humain', '<p>Sous-catégorie traitée dans le cours J21 — Bronchiolite aiguë et infection aiguë des voies respiratoires inférieures (catalogue BfArM, version 2024).</p>')
a('J21.8', [('J21.8', 'code CIM-10-GM 2024')], 'Bronchiolite aiguë due à d’autres micro-organismes précisés', '<p>Sous-catégorie traitée dans le cours J21 — Bronchiolite aiguë et infection aiguë des voies respiratoires inférieures (catalogue BfArM, version 2024).</p>')
a('J21.9', [('J21.9', 'code CIM-10-GM 2024')], 'Bronchiolite aiguë, sans précision', '<p>Sous-catégorie traitée dans le cours J21 — Bronchiolite aiguë et infection aiguë des voies respiratoires inférieures (catalogue BfArM, version 2024).</p>')
a('SSPP', [('S', 'Société'), ('S', 'Suisse de'), ('P', 'Pneumologie'), ('P', 'Pédiatrique')], 'Société suisse de pneumologie pédiatrique', '<p>Société savante suisse de pneumologie de l’enfant. Ses membres ont publié en 2020 la mise à jour suisse sur la bronchiolite aiguë (Barben, Regamey et Hammer, Forum Médical Suisse), qui succède aux recommandations de 2003.</p>', 'j21-sspp')
a('SAPP', [('S', 'Schweizerische (suisse)'), ('A', 'Arbeitsgemeinschaft für (groupe de travail de)'), ('P', 'Pädiatrische (pédiatrique)'), ('P', 'Pneumologie')], 'Groupe de travail suisse de pneumologie pédiatrique', '<p>Ancien nom du groupe suisse de pneumologie pédiatrique. Ses recommandations de 2003 sur le traitement de la bronchiolite aiguë du nourrisson (Paediatrica, vol. 14, n° 6) ont été remplacées par la mise à jour de 2020.</p>', 'j21-sspp')
a('CFV', [('C', 'Commission'), ('F', 'Fédérale pour les'), ('V', 'Vaccinations')], 'Commission fédérale pour les vaccinations', '<p>Commission d’experts qui élabore, avec l’Office fédéral de la santé publique, le Plan de vaccination suisse et les recommandations sur l’immunisation contre le virus respiratoire syncytial.</p>', 'j21-algorithme')
a('NS2', [('N', 'Non-'), ('S', 'Structural (non structurale)'), ('2', 'protéine numéro 2')], 'Protéine non structurale 2 du virus respiratoire syncytial', '<p>Protéine virale qui provoque l’arrondissement et l’extrusion des cellules ciliées infectées ; ces cellules desquamées s’accumulent dans la lumière des bronchioles et l’obstruent (Pickles et DeVincenzo, 2015).</p>', 'j21-ns2')
a('NaCl', [('Na', 'Natrium (sodium)'), ('Cl', 'Chlore (chlorure)')], 'Chlorure de sodium', '<p>Sel dont la solution à 0,9 % (sérum physiologique) sert au lavage nasal ; les solutions à 3 % ou plus sont dites hypertoniques.</p>', 'j21-desobstruction')
a('mRESVIA', [('m', 'messager (vaccin à ARN messager)'), ('RESVIA', 'nom commercial, non développable lettre à lettre')], 'Vaccin à ARN messager contre le virus respiratoire syncytial (Moderna)', '<p>Vaccin autorisé en Suisse chez l’adulte dès 18 ans ; il code pour la protéine F du virus de sous-groupe A stabilisée en conformation préfusionnelle. Contre-indiqué avant l’âge de 8 mois.</p>', 'j21-d-mresvia')
a('MELODY', [('MELODY', 'nom propre de l’essai de phase 3 du nirsévimab chez le nourrisson né à 35 semaines ou plus, non développable lettre à lettre')], 'Essai MELODY (nirsévimab, 2022)', '<p>Essai randomisé contre placebo chez 1490 nourrissons : infection respiratoire basse à virus respiratoire syncytial médicalement prise en charge chez 1,2 % contre 5,0 %, soit une efficacité de 74,5 % (Hammitt, 2022).</p>', 'j21-d-nirsevimab')
a('HARMONIE', [('HARMONIE', 'nom propre de l’essai pragmatique du nirsévimab en France, en Allemagne et au Royaume-Uni, non développable lettre à lettre')], 'Essai HARMONIE (nirsévimab, 2023)', '<p>Essai randomisé ouvert chez 8058 nourrissons : hospitalisation pour infection respiratoire basse à virus respiratoire syncytial chez 0,3 % contre 1,5 %, soit une efficacité de 83,2 % (Drysdale, 2023).</p>', 'j21-d-nirsevimab')
a('MATISSE', [('MATISSE', 'Maternal Immunization Study for Safety and Efficacy (étude d’immunisation maternelle sur la sécurité et l’efficacité)')], 'Essai MATISSE (vaccin maternel bivalent, 2023)', '<p>Essai de phase 3 chez des femmes enceintes de 24 à 36 semaines : efficacité de 81,8 % contre l’infection respiratoire basse sévère du nourrisson dans les 90 jours suivant la naissance et de 69,4 % dans les 180 jours (Kampmann, 2023).</p>', 'j21-d-abrysvo')
a('CLEVER', [('CLEVER', 'nom propre de l’essai de phase 2b/3 du clesrovimab, non développable lettre à lettre')], 'Essai CLEVER (clesrovimab, 2025)', '<p>Essai randomisé contre placebo chez 3614 nourrissons : efficacité de 60,4 % contre l’infection respiratoire basse médicalement prise en charge et de 84,2 % contre l’hospitalisation dans les 150 jours (Zar, 2025).</p>', 'j21-d-clesrovimab')
a('ProHOSP', [('Pro', 'Procalcitonine'), ('HOSP', 'HOSPitalier (essai mené dans les urgences hospitalières suisses)')], 'Essai ProHOSP (procalcitonine, 2009)', '<p>Essai suisse de non-infériorité chez 1359 adultes atteints d’infection respiratoire basse : un algorithme fondé sur la procalcitonine a réduit l’exposition aux antibiotiques de 8,7 à 5,7 jours sans augmenter les événements indésirables (Schuetz, 2009).</p>', 'j21-prohosp')
a('NG9', [('NG', 'NICE Guideline (recommandation du NICE)'), ('9', 'numéro 9 de la série')], 'Recommandation NICE n° 9 : bronchiolite de l’enfant', '<p>Recommandation britannique « Bronchiolitis in children: diagnosis and management », publiée en juin 2015 et mise à jour en août 2021 pour les seuils de saturation.</p>', 'j21-nice')
