from cardio_1 import a, G
a('BTS',[('B','British'),('T','Thoracic'),('S','Society')],'British Thoracic Society (Société thoracique britannique)','<p>Société savante britannique de pneumologie. Sa guideline sur les maladies pleurales (Thorax, août 2023) sert de référence au cours J90.</p>','j90-bts')
a('ESTS',[('E','European'),('S','Society of'),('T','Thoracic'),('S','Surgeons')],'European Society of Thoracic Surgeons (Société européenne des chirurgiens thoraciques)','<p>Société savante européenne de chirurgie thoracique ; coautrice avec l’ERS de la déclaration de 2023 sur l’infection pleurale de l’adulte.</p>')
a('TIPS',[('T','Transjugular'),('I','Intrahepatic'),('P','Portosystemic'),('S','Shunt')],'Shunt portosystémique intrahépatique transjugulaire','<p>Prothèse posée par voie jugulaire entre une veine sus-hépatique et une branche de la veine porte ; elle abaisse la pression portale et réduit l’ascite et l’hydrothorax hépatique réfractaires.</p>','j90-hydrothorax')
a('LENT',[('L','Lactate déshydrogénase pleurale'),('E','ECOG, indice de performance de l’Eastern Cooperative Oncology Group'),('N','Neutrophiles sur lymphocytes, rapport sanguin'),('T','Type tumoral')],'Score pronostique LENT de l’épanchement pleural malin','<p>Score de 0 à 7 (Clive, Thorax 2014) ; survie médiane de 319, 130 et 44 jours pour les risques faible, modéré et élevé.</p>','j90-lent')
a('RAPID',[('R','Renal (urée)'),('A','Age (âge)'),('P','Purulence'),('I','Infection source (origine communautaire ou nosocomiale)'),('D','Dietary factors (albumine)')],'Score pronostique RAPID de l’infection pleurale','<p>Score de 0 à 7 (Rahman, Chest 2014) qui stratifie le risque de décès à trois mois.</p>','j90-rapid')
a('MIST',[('M','Multicenter'),('I','Intrapleural'),('S','Sepsis'),('T','Trial')],'Essais MIST sur l’infection pleurale','<p>Série d’essais britanniques multicentriques sur le traitement intrapleural de l’infection pleurale.</p>','j90-d-iet')
a('MIST1',[('M','Multicenter'),('I','Intrapleural'),('S','Sepsis'),('T','Trial'),('1','premier essai')],'Essai MIST1 (2005)','<p>Streptokinase intrapleurale contre placebo dans l’infection pleurale : pas de bénéfice sur la mortalité ni le recours chirurgical.</p>','j90-d-iet')
a('MIST2',[('M','Multicenter'),('I','Intrapleural'),('S','Sepsis'),('T','Trial'),('2','deuxième essai')],'Essai MIST2 (2011)','<p>Altéplase et dornase alfa intrapleurales : seule l’association améliore le drainage et réduit le recours chirurgical et la durée d’hospitalisation.</p>','j90-d-iet')
a('TIME1',[('T','Therapeutic'),('I','Interventions in'),('M','Malignant'),('E','Effusion'),('1','premier essai')],'Essai TIME1 (2015)','<p>Anti-inflammatoires non stéroïdiens contre opioïdes et drains de 12 ou 24 French lors du talcage : anti-inflammatoires non inférieurs pour la symphyse.</p>','j90-d-ains')
a('TIME2',[('T','Therapeutic'),('I','Intervention in'),('M','Malignant'),('E','Effusion'),('2','deuxième essai')],'Essai TIME2 (2012)','<p>Cathéter pleural tunnelisé contre drain et talc dans l’épanchement malin : dyspnée équivalente à 42 jours, hospitalisation plus courte sous cathéter.</p>','j90-cath')
a('IPC-PLUS',[('IPC','Indwelling Pleural Catheter (cathéter pleural à demeure)'),('PLUS','nom d’essai, non développable lettre à lettre')],'Essai IPC-PLUS (2018)','<p>Talc ou placebo administré par cathéter pleural tunnelisé : symphyse à 35 jours chez 43 % contre 23 % des patients.</p>','j90-talc')
for c,t in [('J92.0','Plaque pleurale avec mise en évidence d’amiante'),('J92.9','Plaque pleurale sans mise en évidence d’amiante'),('J94.0','Épanchement chyleux'),('J94.1','Fibrothorax'),('J94.2','Hémothorax'),('J94.8','Autres affections pleurales précisées'),('J94.9','Affection pleurale, sans précision'),('R09.1','Pleurésie'),('S27.1','Hémothorax traumatique'),('S27.2','Hémopneumothorax traumatique'),('C78.2','Tumeur maligne secondaire de la plèvre'),('C45.0','Mésothéliome de la plèvre')]:
    a(c,[(c,'code de la Classification internationale des maladies, 10e révision, modification allemande')],t,'<p>Code CIM-10-GM 2024.</p>')
