# Connecteurs logiques et transitions du cours K25 (règle linguistique du propriétaire, 09.10.2026).
L = {
 'k25-0': [['', 'Or', 'À l’inverse', 'Dès lors'], ['Pour y répondre']],
 'k25-1': [['Avant toute décision, il faut nommer correctement la lésion.', 'En revanche', 'Par ailleurs'], ['Ainsi']],
 'k25-2': [['Une fois la lésion définie, sa fréquence et sa gravité situent l’enjeu.', 'Parmi ces complications'], ['Cependant', 'En effet', 'De plus']],
 'k25-3': [['Ces chiffres s’expliquent par un déséquilibre entre agression et défense.', 'Dès lors'], ['Le premier agresseur est connu.', 'Plus précisément', 'Toutefois'], ['Le second agresseur est médicamenteux.', 'En revanche']],
 'k25-4': [['De ces mécanismes découle la recherche étiologique.', 'En effet', 'À l’inverse'], ['']],
 'k25-5': [['La cause et la gravité se recherchent d’abord par l’interrogatoire.', ''], ['']],
 'k25-6': [['L’examen physique complète l’interrogatoire.', 'C’est pourquoi', 'Ainsi', 'De son côté', 'Enfin']],
 'k25-7': [['Parmi ces complications, la perforation est la plus urgente.', 'Par ailleurs'], ['Ensuite', 'En revanche', 'En outre'], ['Quant à lui']],
 'k25-8': [['Hors urgence, le diagnostic repose sur l’endoscopie.', 'En pratique', 'De plus'], ['Parallèlement', 'Ainsi', 'Par ailleurs', 'En revanche']],
 'k25-9': [['Le diagnostic posé, le traitement découle directement de la cause.'], ['D’abord', 'De même', 'Par ailleurs'], ['Enfin', 'En revanche', 'Dans tous les cas']],
 'k25-10': [['Le choix du schéma d’éradication mérite une attention particulière.', 'Concrètement'], ['En revanche', 'En effet'], ['Ainsi', 'En outre']],
 'k25-11': [['Au-delà du traitement, la prévention concerne surtout le patient qui doit garder un médicament à risque.', 'En revanche'], ['', 'À l’inverse', 'Enfin']],
 'k25-12': [['Il reste les ulcères sans cause évidente.', 'Dans tous les cas'], ['Sur le plan thérapeutique', 'Quant à elle']],
 'k25-13': [['Certaines situations modifient ces règles.'], ['Pour conclure, reprenons la patiente du début.', 'Ensuite', 'Dès lors', 'Finalement']],
 'k25-14': [['']],
 'k25-e-1': [['Les examens complémentaires prolongent la démarche clinique.'], ['Ainsi', 'En revanche']],
 'k25-e-2': [['Parmi ces examens, les tests de Helicobacter pylori demandent une lecture prudente.', 'En revanche'], ['Pourtant', 'Par conséquent']],
 'k25-e-3': [['Au-delà de la biologie, l’endoscopie et l’imagerie se lisent selon des critères précis.', 'Inversement'], ['', 'En comparaison']],
 'k25-p-1': [['Les principes thérapeutiques étant posés, il reste à préciser les médicaments.'], ['Ainsi']],
 'k25-p-2': [['Une fois la classe choisie, la dose et la durée décident de l’efficacité.'], ['']],
 'k25-p-3': [['Enfin, la sécurité du traitement dépend des interactions et de la surveillance.'], ['Pour préserver l’adhésion au traitement', 'En effet', 'De plus'], ['Par ailleurs', 'C’est pourquoi']],
 'k25-s-anat': [['', 'Or', 'En outre']],
 'k25-s-histo': [['', 'En revanche', 'C’est dans ce contexte que'], ['Une fois la paroi lésée']],
 'k25-s-phys': [['', 'Pour cela', 'À l’inverse', 'Or'], ['De plus', 'Dès lors']],
 'k25-s-micro': [['', 'Pour survivre dans l’estomac', 'Sur le plan génétique'], ['Ces mécanismes ont une traduction locale.']],
}
