# RAPPEL VERITE : vraies images uniquement · doses exactes (sources suisses/europeennes verifiees) · codes CIM-10-GM verifies · connecteurs logiques · termes et fenetres interactifs · aucune invention.
import sys, os; sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__)))); sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from medina_gen import *
from images import credit

C = Chapter('K59', 'Autres troubles fonctionnels de l’intestin : constipation chronique',
    'K59 — Autres troubles fonctionnels de l’intestin · CIM-10-GM 2024 · Côlon, rectum et anus',
    'Adulte · centré sur la constipation chronique (K59.0), constipation médicamenteuse et induite par les opioïdes ; diarrhée fonctionnelle, intestin neurogène, mégacôlon et spasme anal signalés · rédaction du 10.10.2026 · référentiel S2k DGVS/DGNM 2022 (constipation chronique), informations professionnelles suisses',
    'Pharmacologie de la constipation')
w = C.w
S2K = ('Andresen V. et al., Aktualisierte S2k-Leitlinie chronische Obstipation der DGVS und der DGNM, Z Gastroenterol 2022;60:1528-1572 (AWMF 021-019)', 'https://register.awmf.org/assets/guidelines/021-019l_S2k_Chronische_Obstipation_2022-11.pdf')
FI = lambda n: ('Information professionnelle suisse ' + n + ', Swissmedic (AIPS), consultée le 10.10.2026', 'https://www.swissmedicinfo.ch/')
FEC = ('Di Saverio S. et al., A 54-year-old man with a huge fecaloma, PLoS Med 2009;6(6):e1000092 (figure 2)', 'https://commons.wikimedia.org/wiki/File:Journal.pmed.1000092.g002_fecal_impaction.png')
HIN = credit({'auteur': 'Hellerhoff', 'licence': 'CC BY-SA 4.0', 'url': 'https://commons.wikimedia.org/wiki/File:Hinton-Test_65W_-_CR_ap_-_001_-_Annotation.jpg'})
FCR = credit({'auteur': 'Di Saverio S. et al.', 'licence': 'CC BY 2.5', 'url': 'https://commons.wikimedia.org/wiki/File:Journal.pmed.1000092.g002_fecal_impaction.png'})
STE = credit({'auteur': 'Emily Bae, Jacqueline Tran, Kaushal Shah', 'licence': 'CC BY 4.0', 'url': 'https://commons.wikimedia.org/wiki/File:Stercoralcolitis2024.webp'})
MEL = credit({'auteur': 'Nephron', 'licence': 'CC BY-SA 3.0', 'url': 'https://commons.wikimedia.org/wiki/File:Melanosis_coli_intermed_mag.jpg'})
BRI = credit({'auteur': 'Jaipasdepseudo', 'licence': 'CC BY-SA 4.0', 'url': 'https://commons.wikimedia.org/wiki/File:Bristol_stool_scale.png'})

C.a(0, 'Question clinique et objectifs', P(
 'Une femme de 58 ans consulte parce qu’elle va à selle deux fois par semaine depuis plusieurs années ; elle pousse fort, elle a l’impression de ne pas se vider complètement et elle s’aide parfois avec les doigts. Elle prend depuis six mois un antidépresseur tricyclique. <b>La question est donc triple : s’agit-il d’une ' + w('k59-cc', 'constipation chronique') + ' au sens des critères, faut-il chercher une cause organique avant de traiter, et quel traitement choisir, dans quel ordre ?</b>',
 'Pour y répondre, le médecin doit savoir appliquer la définition, qui repose sur plusieurs symptômes et non sur la seule fréquence des selles ; ensuite, il doit repérer les ' + w('k59-alarme', 'signes d’alarme') + ' qui imposent des examens immédiats ; de plus, il doit reconnaître les causes médicamenteuses ; enfin, il doit conduire le ' + w('k59-palier', 'traitement par paliers') + ' de la recommandation S2k et savoir quand explorer un ' + w('k59-dysen', 'trouble de l’évacuation') + '.')
 + P('<i>Pourquoi ce cas ?</i> En effet, la constipation est l’un des troubles digestifs les plus fréquents, et sa prise en charge est souvent répétitive et peu raisonnée. Ainsi, contrairement à un manuel figé qui énumère des laxatifs, ce cours suit le raisonnement : chaque mot vert ouvre le critère, l’examen, la dose suisse ou l’image correspondante, de sorte que la décision peut être refaite pas à pas, puis appliquée à la patiente.')
 + key('La patiente remplit-elle les critères ? A-t-elle un signe d’alarme ? Un médicament est-il en cause ? Ensuite seulement, on traite par paliers et l’on explore si le traitement échoue.', 'Point de départ.'))

C.a(1, 'Définitions et épidémiologie', P(
 'Selon la S2k DGVS/DGNM 2022, qui reprend les critères de ' + w('k59-rome', 'Rome IV') + ', on parle de constipation chronique lorsque trois conditions sont réunies depuis au moins 3 mois, avec un début des symptômes au moins 6 mois avant le diagnostic. D’abord, le patient présente au moins deux des symptômes suivants : des selles dures ou en grumeaux (types 1 à 2 de l’' + w('k59-bristol', 'échelle de Bristol') + '), un effort de poussée, une sensation d’évacuation incomplète, une sensation d’obstruction anorectale ou des manœuvres manuelles, chacun lors de plus de 25 % des défécations, ou encore moins de 3 selles spontanées par semaine. Ensuite, les selles molles sont rares sans laxatif. Enfin, les critères du ' + w('k59-sii', 'syndrome de l’intestin irritable') + ' ne sont pas remplis.',
 'Or, cette définition est volontairement large : en effet, beaucoup de patients vont à selle chaque jour, mais au prix d’efforts importants, et la S2k rappelle que le temps de transit est mieux corrélé à la consistance des selles qu’à leur fréquence. Par ailleurs, la prévalence dépend fortement de la définition employée : dans une même cohorte, elle variait de 9,4 à 58,9 %. C’est pourquoi la S2k retient une prévalence moyenne d’environ 15 % en Europe, nettement plus élevée chez les femmes et les personnes âgées.')
 + table(['Code CIM-10-GM', 'Libellé officiel', 'Ce que le code décrit'], [
   ['K59.00', 'Constipation lors d’un trouble du transit colique', 'Le côlon progresse lentement ; c’est le ' + w('k59-stc', 'transit lent') + '.'],
   ['K59.01', 'Constipation lors d’un trouble de la défécation', 'Le rectum ne se vide pas bien ; c’est le trouble de l’évacuation.'],
   ['K59.02', 'Constipation d’origine médicamenteuse', 'Un médicament ralentit le transit, par exemple un opioïde.'],
   ['K59.09', 'Constipation, autre et sans précision', 'Le mécanisme n’est pas précisé.'],
   ['K59.1 à K59.9', 'Diarrhée fonctionnelle, intestin neurogène, mégacôlon, spasme de l’anus, autres', 'Ces troubles sont signalés à la fin du cours.']])
 + P('<i>Que montre le tableau ?</i> La classification suisse distingue d’emblée les deux grands mécanismes, le transit lent et le trouble de la défécation ; or, ils ne se traitent pas de la même façon, puisque le second relève surtout de la rééducation par ' + w('k59-biofb', 'biofeedback') + '. C’est pourquoi le code n’est précis que lorsque le mécanisme a été démontré par des examens fonctionnels ; avant cela, on code K59.09.')
 + key('La constipation chronique se définit par au moins deux symptômes (selles dures, poussée, évacuation incomplète, obstruction, manœuvres manuelles, moins de 3 selles par semaine) depuis 3 mois, avec un début 6 mois avant le diagnostic. Sa prévalence est d’environ 15 % en Europe, plus élevée chez les femmes et les personnes âgées.')
 + src(S2K))

C.a(2, 'Physiopathologie : transit lent, évacuation difficile et causes secondaires', P(
 'La progression des selles dépend d’un système sensorimoteur propre à l’intestin. Ainsi, les ' + w('k59-icc', 'cellules interstitielles de Cajal') + ' jouent le rôle de stimulateurs, le système nerveux entérique coordonne les contractions, et la musculature lisse les exécute ; or, selon la S2k, la constipation peut s’associer à des anomalies de ces cellules, à des neuropathies ou à des myopathies entériques. Dans ce cas, le côlon progresse lentement, l’eau des selles est davantage réabsorbée, et les selles deviennent dures : c’est le transit lent.',
 'En revanche, dans le trouble de l’évacuation, le côlon fonctionne, mais la sortie ne s’ouvre pas correctement. En effet, lors de la poussée, le muscle puborectal et le sphincter externe devraient se relâcher pendant que la pression abdominale augmente ; s’ils se contractent au contraire, on parle de ' + w('k59-dyssyn', 'dyssynergie du plancher pelvien') + '. De plus, un obstacle anatomique, comme une rectocèle, une intussusception rectale ou un prolapsus, peut gêner l’évacuation. Par ailleurs, la S2k souligne que les facteurs de mode de vie classiquement invoqués, une alimentation pauvre en fibres, un apport hydrique faible, la sédentarité ou la répression du besoin, sont associés à la constipation, mais qu’un lien causal direct n’est pas démontré ; ils révèlent plutôt une tendance préexistante.')
 + table(['Groupe de causes secondaires (S2k)', 'Exemples cités par la recommandation'], [
   ['Médicaments', 'Opioïdes, anticholinergiques, antidépresseurs tricycliques, neuroleptiques, IMAO, antiépileptiques, antihistaminiques, antiacides contenant du calcium, antihypertenseurs, spasmolytiques, sympathomimétiques, diurétiques, colestyramine'],
   ['Maladies neurologiques', 'Maladie de Parkinson, sclérose en plaques, maladies cérébrovasculaires (accident vasculaire, démence), neurofibromatose, tabès'],
   ['Obstacles anorectaux', 'Rectocèle, entérocèle, intussusception rectale, prolapsus, descente marquée du plancher pelvien'],
   ['Causes endocriniennes', 'Hypothyroïdie : le transit n’est pas allongé, mais la sensibilité rectale est modifiée']])
 + P('<i>Que montre le tableau ?</i> Chaque groupe agit à un étage différent : les médicaments freinent la motricité ou la sécrétion, les maladies neurologiques désorganisent la commande, et les obstacles anorectaux bloquent la sortie. Ainsi, le tricyclique de la patiente, qui est anticholinergique, peut à lui seul freiner la motricité du côlon ; c’est pourquoi l’anamnèse médicamenteuse précède tout examen.')
 + key('Le transit lent provient d’une atteinte des cellules de Cajal, des nerfs ou des muscles entériques ; le trouble de l’évacuation provient d’une dyssynergie ou d’un obstacle anorectal. Les médicaments, en particulier les opioïdes et les anticholinergiques, sont la première cause secondaire à rechercher.')
 + src(S2K))

C.a(3, 'Démarche diagnostique de base', P(
 'Selon la S2k, le bilan de base doit comprendre une anamnèse précise, qui analyse le comportement défécatoire, les médicaments, les symptômes associés et les maladies possiblement causales ; de plus, il comprend un examen clinique avec inspection de l’anus et ' + w('k59-tr', 'toucher rectal') + ', au cours duquel on apprécie le tonus de repos, la contraction volontaire et la tentative de poussée (recommandation forte). Ensuite, la S2k recommande de quantifier les selles, si possible par un journal des selles qui inclut l’échelle de Bristol.',
 'Cependant, l’anamnèse ne sépare pas sûrement les mécanismes : en effet, des selles rares et dures sans difficulté d’évacuation orientent vers un transit lent, mais la S2k rappelle que les symptômes ne sont pas univoques. De même, un toucher rectal normal n’exclut pas un trouble de l’évacuation, puisque sa valeur prédictive négative n’est que de 64 %. Par ailleurs, si le patient décrit aussi des douleurs abdominales, il faut appliquer la recommandation sur l’intestin irritable (cours ' + w('k59-sii', 'K58') + '), car les deux troubles se recouvrent largement.')
 + C.img('k59_bristol.gif', 'Échelle de Bristol : sept dessins de selles, des billes dures séparées (type 1) aux selles entièrement liquides (type 7).', 'Échelle de Bristol des formes de selles : les types 1 et 2 correspondent aux selles dures de la constipation.', BRI)
 + P('<i>Que montre l’image ?</i> Plus la selle séjourne longtemps dans le côlon, plus elle perd d’eau ; ainsi, les billes dures du type 1 traduisent un séjour prolongé, alors que les types 6 et 7 traduisent un passage rapide. C’est pourquoi la S2k préfère cette échelle à la seule fréquence : la forme des selles reflète mieux le temps de transit, et elle permet ensuite de juger objectivement l’effet du traitement.')
 + quiz('Une patiente va à selle chaque jour, mais elle pousse fort et s’aide avec les doigts lors de la plupart des défécations. Peut-elle avoir une constipation chronique ?',
   [('Non, puisqu’elle va à selle chaque jour', False), ('Oui, car deux symptômes suffisent, même avec une fréquence normale', True), ('Seulement si ses selles sont de type 7', False)],
   'La définition exige au moins deux symptômes, dont l’effort de poussée et les manœuvres manuelles ; la fréquence n’est qu’un critère parmi d’autres. De plus, ces deux symptômes orientent vers un trouble de l’évacuation.')
 + key('On analyse les selles, les médicaments et les maladies, puis on examine l’anus et l’on fait un toucher rectal avec tentative de poussée ; on tient un journal des selles avec l’échelle de Bristol. Un toucher rectal normal n’exclut pas un trouble de l’évacuation (valeur prédictive négative de 64 %).')
 + src(S2K))

C.a(4, 'Signes d’alarme et examens de seconde intention', P(
 'La décision suivante consiste à savoir si l’on peut traiter d’emblée. Ainsi, selon la S2k, en l’absence de signe d’alarme et si le bilan de base est normal, on peut commencer par un traitement d’épreuve, dont l’effet est évalué après environ 4 semaines ; il faut toutefois respecter les recommandations de dépistage du cancer colorectal. En revanche, des plaintes sévères ou un signe d’alarme imposent des examens immédiats, sans traitement d’épreuve préalable (recommandation forte).',
 'Les examens procèdent alors en deux temps. D’abord, on exclut une cause organique : une formule sanguine et des marqueurs de l’inflammation, complétés selon le contexte par les électrolytes, la fonction rénale, les enzymes hépatiques et pancréatiques, la TSH, la glycémie ou l’HbA1c et la calprotectine fécale, puis une échographie abdominale et surtout une ' + w('k59-colo', 'iléocoloscopie') + '. Ensuite, si la constipation résiste au traitement, on précise le mécanisme par des examens fonctionnels : la ' + w('k59-mano', 'manométrie anorectale') + ', le ' + w('k59-ballon', 'test d’expulsion du ballonnet') + ', la ' + w('k59-defeco', 'défécographie') + ' et l’étude du ' + w('k59-hinton', 'temps de transit colique') + '. À l’inverse, la S2k déconseille la culture bactérienne ou fongique des selles, qui n’apporte aucun résultat utile.')
 + alert('Selon la S2k, les signes d’alarme comprennent un saignement ou du sang dans les selles, une anémie, une perte de poids inexpliquée de plus de 10 %, des antécédents personnels ou familiaux de tumeur digestive, des adénopathies, une masse palpable, une dénutrition, une fausse diarrhée, un âge de plus de 50 ans, une évolution progressive et une histoire courte avec des plaintes sévères. Chacun de ces signes fait rechercher d’abord une cause organique, en particulier un cancer colorectal (cours C18).', 'Gravité d’abord.')
 + key('Sans signe d’alarme, on fait un traitement d’épreuve et on le réévalue à 4 semaines ; avec un signe d’alarme ou des plaintes sévères, on exclut d’abord une cause organique (biologie, échographie, iléocoloscopie). Ensuite, en cas d’échec, on précise le mécanisme par la manométrie, le ballonnet, la défécographie et le transit colique.')
 + src(S2K))

C.a(5, 'Mesures de base : boissons, fibres et habitudes', P(
 'Le premier palier ne demande pas de médicament. Ainsi, la S2k recommande un apport hydrique quotidien de 1,5 à 2 litres ; en revanche, boire davantage n’a pas d’effet thérapeutique et ne doit donc pas être conseillé. De même, il faut éviter l’inactivité physique ; toutefois, on ne doit pas promettre qu’une activité supérieure à la normale pour l’âge améliorera la constipation. Par ailleurs, il faut éviter de réprimer régulièrement le besoin d’aller à selle, car le réflexe s’émousse lorsqu’il est ignoré.',
 'Ensuite, les fibres augmentent la fréquence des selles ; c’est pourquoi la S2k vise un apport de 30 g par jour, comme pour la population générale. Or, les preuves sont meilleures pour les fibres solubles, en particulier le ' + w('k59-psyl', 'psyllium') + ', que pour les fibres insolubles comme le son. Cependant, les fibres provoquent souvent des ballonnements et des crampes ; dans ce cas, la S2k conseille de réduire les fibres à titre d’essai et de préférer d’abord un laxatif osmotique, surtout si les selles stagnent déjà. De plus, deux portions par jour de fruits riches en fibres peuvent protéger de la constipation, alors que la transplantation de microbiote fécal ne doit pas être proposée.')
 + key('Le patient boit 1,5 à 2 L par jour, sans excès inutile ; il reste actif et ne réprime pas le besoin. Il vise 30 g de fibres par jour, de préférence du psyllium, et il réduit les fibres si elles provoquent des ballonnements, au profit d’un laxatif osmotique.')
 + src(S2K))

C.a(6, 'Traitement médicamenteux par paliers', P(
 'Si les mesures de base sont insuffisantes ou mal tolérées, la S2k recommande fortement les laxatifs. Ainsi, le ' + w('k59-mcg', 'macrogol') + ', le ' + w('k59-pico', 'picosulfate de sodium') + ' et le ' + w('k59-bisa', 'bisacodyl') + ' sont les médicaments de premier choix ; de plus, la S2k précise qu’il n’y a aucune raison de limiter la durée de leur prise. En effet, l’accoutumance souvent redoutée est en réalité très rare, même après des décennies d’utilisation. Par ailleurs, les sucres comme le ' + w('k59-lactu', 'lactulose') + ' sont une alternative, alors que les laxatifs salins, comme l’hydroxyde de magnésium, sont efficaces mais déconseillés en raison de leurs effets indésirables ; enfin, l’huile de paraffine ne doit pas être utilisée.',
 'Ensuite, si un laxatif est inefficace ou mal toléré, il faut passer à une autre classe, puis, si la monothérapie reste insuffisante, associer un laxatif osmotique et un laxatif stimulant. Si ces options échouent, la S2k recommande fortement le ' + w('k59-pruca', 'prucalopride') + ', un agoniste des récepteurs 5-HT4 qui stimule la motricité propulsive. Puis, au palier suivant, elle recommande le ' + w('k59-lina', 'linaclotide') + ', un sécrétagogue ; or, en Suisse, son information professionnelle ne l’autorise que dans le syndrome de l’intestin irritable avec constipation, si bien que son emploi dans la constipation chronique est hors indication. De plus, pour l’évacuation rectale, la S2k préfère les suppositoires de bisacodyl ou les suppositoires qui libèrent du CO2, et elle interdit l’usage prolongé des lavements phosphatés.')
 + table(['Palier', 'Traitement', 'Pourquoi à ce rang ?'], [
   ['1', 'Boissons, activité, fibres (30 g par jour)', 'Ces mesures sont sûres, mais leur effet est modeste.'],
   ['2', 'Macrogol, picosulfate ou bisacodyl ; changement de classe, puis association', 'Leur efficacité est prouvée, et leur usage prolongé est sûr.'],
   ['3', 'Prucalopride', 'Il agit sur la motricité par un autre mécanisme, après l’échec des laxatifs.'],
   ['4', 'Linaclotide (hors indication en Suisse)', 'Il augmente la sécrétion intestinale ; la S2k le place après le prucalopride.'],
   ['En parallèle', 'Biofeedback si une dyssynergie est démontrée', 'Le problème est la sortie, non le côlon : un laxatif ne corrige pas une coordination défectueuse.']])
 + P('<i>Que montre le tableau ?</i> Chaque palier ajoute un mécanisme nouveau plutôt qu’une dose plus forte du même produit ; ainsi, on passe de l’eau retenue dans la lumière (osmotiques) à la stimulation de la muqueuse (stimulants), puis à la motricité (5-HT4) et enfin à la sécrétion (linaclotide). Or, le trouble de l’évacuation échappe à cette logique ; c’est pourquoi il se traite en parallèle, par la rééducation.')
 + key('Les laxatifs de premier choix sont le macrogol, le picosulfate et le bisacodyl, sans limite de durée. En cas d’échec, on change de classe, puis on associe, puis on prescrit le prucalopride, enfin le linaclotide (hors indication en Suisse). On n’utilise jamais l’huile de paraffine, ni les lavements phosphatés au long cours.')
 + src(S2K, FI('Constella®')))

C.a(7, 'Trouble de l’évacuation, opioïdes et situations particulières', P(
 'Lorsque les examens montrent une dyssynergie du plancher pelvien, le ' + w('k59-biofb', 'biofeedback') + ' est le traitement de choix. En effet, une sonde anale affiche au patient l’état de contraction de ses sphincters, par exemple par des signaux lumineux, si bien qu’il apprend à les relâcher au moment de la poussée. En revanche, la S2k déconseille le biofeedback dans le transit lent isolé, mais elle l’admet si un transit lent et une dyssynergie coexistent.',
 'Par ailleurs, la ' + w('k59-cio', 'constipation induite par les opioïdes') + ' touche 15 à 80 % des patients sous opioïdes, selon leurs facteurs de risque ; c’est pourquoi la S2k recommande de la rechercher chez chaque patient traité et de commencer une prophylaxie dès l’instauration de l’opioïde. Si les laxatifs ne suffisent pas, elle recommande fortement, au deuxième palier, un ' + w('k59-pamora', 'antagoniste opioïde périphérique') + ', comme le naloxégol ou le méthylnaltrexone, ou, chez le patient sous oxycodone, l’association fixe oxycodone-naloxone. De plus, chez la personne âgée, les laxatifs osmotiques et stimulants restent utilisables, et le prucalopride convient aussi ; chez la femme enceinte, le macrogol, le bisacodyl, le picosulfate et le lactulose peuvent être employés, avec une prudence particulière liée à l’absence d’autorisation pour cette situation. Enfin, la chirurgie, en particulier la colectomie avec anastomose iléorectale, n’est envisagée que dans le transit lent réfractaire, après épuisement des traitements conservateurs, démonstration d’un transit allongé et évaluation psychosomatique.')
 + C.img('k59_fecalome.gif', 'Radiographie de l’abdomen : énorme masse stercorale hétérogène, mouchetée de gaz, qui occupe le pelvis et remonte jusqu’à l’hypochondre gauche ; deux lignes de mesure la traversent.', 'Fécalome géant chez un homme de 54 ans : la masse de selles mesure plus de 40 cm de long et 33 cm de large.', FCR)
 + P('<i>Que montre l’image ?</i> L’aspect moucheté vient des bulles de gaz piégées dans des selles déshydratées ; ainsi, le côlon s’est rempli sans pouvoir se vider. Or, ce ' + w('k59-fecal', 'fécalome') + ' est la complication mécanique de la constipation négligée : il peut provoquer une occlusion, une ulcération de la paroi, voire une perforation. C’est pourquoi, chez la personne âgée, une fausse diarrhée doit faire chercher un fécalome au toucher rectal plutôt que prescrire un antidiarrhéique.')
 + C.img('k59_stercoral.gif', 'Scanner du bassin en coupe axiale : rectum très dilaté rempli de selles (étoile), paroi rectale épaissie (flèche) et infiltration de la graisse autour du rectum (têtes de flèches).', 'Colite stercorale chez un homme de 30 ans : la masse fécale distend le rectum, épaissit sa paroi et infiltre la graisse voisine.', STE)
 + P('<i>Que montre l’image ?</i> La masse fécale comprime la paroi de l’intérieur ; ainsi, la pression gêne la microcirculation, la paroi s’œdématie, puis s’enflamme, ce qui explique l’épaississement et l’infiltration de la graisse. Dès lors, la colite stercorale est une étape vers l’ulcère de pression et la perforation ; elle justifie une évacuation rapide et une surveillance chirurgicale.')
 + key('La dyssynergie se traite par biofeedback, qui ne convient pas au transit lent isolé. La constipation des opioïdes se prévient dès le début du traitement ; ensuite, si les laxatifs échouent, on prescrit un antagoniste opioïde périphérique. Le fécalome et la colite stercorale sont les complications mécaniques, et la chirurgie reste exceptionnelle.')
 + src(S2K, FEC))

C.a(8, 'Autres troubles fonctionnels de K59', P(
 'Le code K59 regroupe aussi d’autres troubles. Ainsi, la diarrhée fonctionnelle (K59.1) désigne des selles molles ou liquides récurrentes sans douleur prédominante, ce qui la distingue de l’intestin irritable à diarrhée ; l’intestin neurogène (K59.2) résulte d’une atteinte de la commande nerveuse, par exemple après une lésion médullaire ; le mégacôlon (K59.3) est une dilatation chronique du côlon non classée ailleurs ; enfin, le spasme de l’anus (K59.4) désigne une contraction douloureuse du canal anal. Cependant, la S2k exclut explicitement de son champ la pseudo-obstruction intestinale, le mégacôlon idiopathique et la maladie de Hirschsprung, qui relèvent d’une autre recommandation S3 de la DGVS et de la DGNM. Par conséquent, leurs critères et leur traitement ne sont pas détaillés ici, faute de source lue (TODO).',
 'Toutefois, deux repères restent utiles. D’une part, la manométrie anorectale permet, selon la S2k, d’exclure une maladie de Hirschsprung chez l’adulte constipé, car elle montre si le réflexe recto-anal inhibiteur est présent. D’autre part, le mégacôlon toxique d’une colite est une urgence différente, traitée dans le cours K51 ; c’est pourquoi une dilatation colique fébrile ne doit jamais être rattachée à K59 sans avoir exclu une colite.')
 + C.pareto('pareto-k59-clinique', 'Constipation chronique', ['k59-1', 'k59-3', 'k59-4', 'k59-5', 'k59-6', 'k59-7'],
     ['On applique la définition, qui exige au moins deux symptômes et non une seule fréquence.',
      'On cherche les signes d’alarme et l’on revoit les médicaments avant tout traitement.',
      'Le patient boit 1,5 à 2 L par jour et vise 30 g de fibres.',
      'On prescrit d’abord le macrogol, le picosulfate ou le bisacodyl, sans limite de durée.',
      'En cas d’échec, on change de classe, on associe, puis on prescrit le prucalopride.',
      'On explore une dyssynergie et on la traite par biofeedback.',
      'On prévient la constipation des opioïdes dès le début du traitement.'])
 + src(S2K))

C.a(9, 'Synthèse et retour au cas', P(
 'Pour conclure, reprenons la patiente du début. Elle a moins de 3 selles par semaine, elle pousse et elle utilise des manœuvres manuelles depuis plusieurs années : elle remplit donc les critères de constipation chronique. Cependant, elle a plus de 50 ans ; c’est pourquoi, si elle n’a pas eu de coloscopie de dépistage, on la réalise d’emblée. Par ailleurs, le tricyclique est discuté avec son médecin, car il peut freiner le transit.',
 'Dès lors, la conduite suit la S2k. D’abord, elle boit 1,5 à 2 L par jour et ajoute du psyllium ; ensuite, elle prend du macrogol, réévalué à 4 semaines. Or, ses manœuvres manuelles et sa sensation d’obstruction orientent vers un trouble de l’évacuation ; si le traitement échoue, on demande donc une manométrie anorectale et un test du ballonnet. Si une dyssynergie est confirmée par deux examens, le biofeedback est proposé ; en revanche, si seul le transit est allongé, on passe au prucalopride.')
 + key('La patiente remplit les critères ; son âge impose la coloscopie, et l’on revoit le tricyclique. Elle reçoit des mesures de base et du macrogol, réévalués à 4 semaines ; en cas d’échec, on explore l’évacuation, on propose le biofeedback si la dyssynergie est confirmée, sinon le prucalopride.')
 + src(S2K))

C.a(10, 'Critères formels et paramètres clés', alert(
 '<p>Selon la S2k 2022 (critères de Rome IV), la <b>constipation chronique</b> associe depuis 3 mois, avec un début au moins 6 mois avant le diagnostic, au moins deux symptômes présents lors de plus de 25 % des défécations (selles de type Bristol 1-2, poussée, évacuation incomplète, obstruction, manœuvres manuelles) ou moins de 3 selles spontanées par semaine ; de plus, les selles molles sont rares sans laxatif, et les critères de l’intestin irritable ne sont pas remplis.</p>', 'Critères.')
 + '<div class="key"><b>Paramètres clés.</b> La prévalence est d’environ 15 % en Europe. On réévalue le traitement d’épreuve après environ 4 semaines. Le patient boit 1,5 à 2 L et vise 30 g de fibres par jour. Le temps de transit colique normal est inférieur à 68-72 h. La dyssynergie apparaît chez 20 à 75 % des patients examinés en manométrie, si bien qu’un second examen doit la confirmer. Le toucher rectal a une valeur prédictive négative de 64 %, et la constipation des opioïdes touche 15 à 80 % des patients traités.</div>'
 + src(S2K))

# ---------------- Examens
C.e(1, 'Hiérarchie des examens', P(
 'Chaque examen répond à une question précise ; c’est pourquoi leur ordre importe, et l’on ne demande pas d’examens fonctionnels avant d’avoir exclu une cause organique.')
 + table(['Question', 'Examen', 'Quand ?'], [
   ['Y a-t-il une cause organique ?', 'Formule sanguine, inflammation, TSH, glycémie, électrolytes, calprotectine ; échographie ; ' + w('k59-colo', 'iléocoloscopie'), 'D’emblée si signe d’alarme, sinon après l’échec du traitement d’épreuve'],
   ['Le rectum se vide-t-il ?', w('k59-mano', 'Manométrie anorectale') + ' et ' + w('k59-ballon', 'test du ballonnet'), 'Constipation réfractaire, suspicion de trouble de l’évacuation'],
   ['Y a-t-il un obstacle anatomique ?', w('k59-defeco', 'Défécographie') + ' (radiologique ou IRM)', 'Confirmation d’une dyssynergie, bilan avant chirurgie'],
   ['Le côlon est-il lent ?', w('k59-hinton', 'Transit aux marqueurs radio-opaques (test de Hinton)'), 'Constipation réfractaire ; bilan obligatoire avant colectomie'],
   ['Culture des selles ?', 'Aucune', 'La S2k la déconseille, car elle n’apporte rien']])
 + P('<i>Que montre le tableau ?</i> Les deux premières lignes séparent la maladie organique de la maladie fonctionnelle ; ensuite, les examens fonctionnels séparent le transit lent du trouble de l’évacuation. Or, ces deux mécanismes coexistent souvent : la S2k rappelle qu’un trouble de l’évacuation ralentit secondairement le transit chez jusqu’à deux tiers des patients. C’est pourquoi on explore toujours l’anorectum, même quand le transit est allongé.')
 + key('On exclut d’abord une cause organique, puis l’on explore l’anorectum (manométrie, ballonnet, défécographie) et le transit colique ; on ne fait pas de culture des selles.')
 + src(S2K))

C.e(2, 'Lire un test de transit aux marqueurs', P(
 'Le patient avale des marqueurs radio-opaques, puis une radiographie de l’abdomen les compte par segment du côlon. Ainsi, le nombre de marqueurs restants permet d’estimer le temps de transit colique, normalement inférieur à 68-72 heures selon la S2k ; de plus, leur répartition indique où ils stagnent. Cependant, une selle émise juste avant le cliché fausserait le résultat ; c’est pourquoi le patient tient un journal des selles pendant tout le test.')
 + C.img('k59_hinton.gif', 'Radiographie de l’abdomen de face avec marqueurs radio-opaques ; lignes de séparation des segments et chiffres annotés : 4 dans le côlon droit, 5 dans le côlon gauche, 18 dans la région rectosigmoïdienne, et le calcul 27 × 2,4 = 64,8.', 'Test de Hinton chez une femme de 65 ans : la plupart des marqueurs stagnent dans le rectosigmoïde.', HIN)
 + P('<i>Que montre l’image ?</i> Le radiologue a compté 4 marqueurs dans le côlon droit, 5 dans le côlon gauche et 18 dans le rectosigmoïde ; ensuite, il a multiplié le total, 27, par un facteur propre au protocole, ce qui donne un temps estimé de 64,8 heures. Or, ce temps reste sous la limite de 68-72 heures, mais les marqueurs s’accumulent à la sortie : ce profil oriente vers un trouble de l’évacuation plutôt que vers un côlon lent. Par conséquent, l’étape suivante est l’exploration anorectale, et non l’escalade des laxatifs.')
 + key('Le total des marqueurs estime le temps de transit (normal < 68-72 h), et leur répartition localise la stase ; une accumulation rectosigmoïdienne oriente vers un trouble de l’évacuation.')
 + C.pareto('pareto-k59-examens', 'Examens', ['k59-e-1', 'k59-e-2'],
     ['On exclut d’abord une cause organique, par une coloscopie si un signe d’alarme est présent.',
      'On confirme une dyssynergie par deux examens, car un seul peut être faussement positif.',
      'Le temps de transit normal est inférieur à 68-72 h.',
      'On ne demande pas de culture des selles.'])
 + src(S2K))

# ---------------- Sciences
C.s('anat', 'Anatomie', 'Anatomie : la sortie anorectale', P(
 'Le rectum est fermé par deux sphincters et par le muscle puborectal, qui forme une sangle autour de la jonction anorectale ; ainsi, au repos, cette sangle coude le rectum vers l’avant et assure la continence. Or, lors de la défécation, le puborectal et le sphincter externe doivent se relâcher, de sorte que l’angle s’ouvre et que la pression abdominale chasse les selles. C’est pourquoi une contraction paradoxale de ces muscles, la dyssynergie, ferme la sortie au moment même où le patient pousse.')
 + key('Quand le puborectal et le sphincter externe se relâchent, l’angle s’ouvre et le rectum se vide ; quand ils se contractent à contretemps, la sortie se ferme.', 'Science → clinique.'))
C.s('physio', 'Physiologie', 'Physiologie : motricité et absorption de l’eau', P(
 'Le côlon réabsorbe l’essentiel de l’eau qui lui parvient ; ainsi, plus la selle y séjourne, plus elle se dessèche et durcit. De plus, la motricité propulsive dépend des cellules de Cajal et du système nerveux entérique, sur lequel agissent la sérotonine, par les récepteurs 5-HT4, et les opioïdes, par les récepteurs μ. Par conséquent, un opioïde freine la propulsion et augmente l’absorption d’eau, tandis qu’un agoniste 5-HT4 comme le prucalopride relance la propulsion.')
 + key('Un séjour prolongé dessèche les selles ; les opioïdes freinent la propulsion par les récepteurs μ, alors que les agonistes 5-HT4 l’accélèrent.', 'Science → pharmacologie.'))
C.s('histo', 'Histologie', 'Histologie : la mélanose colique', P(
 'Après une prise prolongée de laxatifs anthraquinoniques, comme le séné, des macrophages chargés de pigment brun s’accumulent dans le chorion de la muqueuse colique ; c’est la mélanose colique. Or, la S2k la décrit comme une conséquence fonctionnellement insignifiante et réversible. Ainsi, sa découverte à la coloscopie témoigne d’une prise de laxatifs, mais elle ne justifie ni l’arrêt d’un traitement efficace ni une inquiétude pour le patient.')
 + C.img('k59_melanose_histo.gif', 'Coupe histologique de muqueuse colique colorée à l’hématoxyline-éosine : cryptes régulières et chorion parsemé de macrophages bruns.', 'Mélanose colique (grossissement intermédiaire) : macrophages chargés de pigment brun dans le chorion, entre des cryptes normales.', MEL)
 + P('<i>Que montre l’image ?</i> Les cryptes restent régulières, ce qui montre que l’épithélium n’est pas lésé ; ainsi, le pigment se trouve seulement dans les macrophages du chorion, qui ont phagocyté des cellules épithéliales mortes. C’est pourquoi cette anomalie est réversible à l’arrêt de l’anthraquinone et sans conséquence fonctionnelle, comme le rappelle la S2k.')
 + key('La mélanose colique correspond à des macrophages pigmentés après une prise d’anthraquinones ; elle est réversible et n’a pas de conséquence fonctionnelle.', 'Science → endoscopie.'))
C.s('radio', 'Physique de l’imagerie', 'Physique de l’imagerie : marqueurs et défécographie', P(
 'Les marqueurs du test de Hinton sont radio-opaques ; ainsi, ils restent visibles sur une radiographie standard, et leur nombre restant reflète le temps écoulé dans le côlon. Par ailleurs, la défécographie enregistre l’évacuation d’un produit de contraste placé dans le rectum, par radiologie ou par IRM ; de plus, elle montre une rectocèle ou une intussusception. Cependant, la S2k souligne que ces anomalies existent aussi chez beaucoup de sujets sains, la rectocèle chez 48 à 93 % et l’intussusception chez 20 à 50 % ; c’est pourquoi une image ne suffit pas, et il faut aussi un questionnaire fonctionnel validé.')
 + key('Les marqueurs radio-opaques servent de chronomètre du côlon, et la défécographie filme l’évacuation ; on interprète toujours ces images avec la clinique.', 'Science → lecture.'))

# ---------------- Pharmacologie
C.p(1, 'Stratégie et classes', P(
 'Les laxatifs n’agissent pas tous de la même manière ; c’est pourquoi, en cas d’échec, on change de mécanisme plutôt que d’augmenter sans fin la dose.')
 + table(['Classe', 'Molécule (spécialité suisse)', 'Mécanisme', 'Fenêtre'], [
   ['Osmotique', 'Macrogol 3350 (Movicol®) ; lactulose (Duphalac®)', 'Ils retiennent l’eau dans la lumière, ce qui ramollit et augmente le volume des selles.', w('k59-mcg', 'Monographie')],
   ['Stimulant', 'Bisacodyl (Dulcolax®) ; picosulfate de sodium (Laxoberon®)', 'Ils stimulent la motricité propulsive du côlon et la sécrétion d’eau.', w('k59-bisa', 'Monographie')],
   ['Prokinétique 5-HT4', 'Prucalopride (Resolor®)', 'Il stimule la motricité propulsive par les récepteurs sérotoninergiques.', w('k59-pruca', 'Monographie')],
   ['Sécrétagogue', 'Linaclotide (Constella®)', 'Il augmente la sécrétion de chlore et d’eau dans la lumière.', w('k59-lina', 'Monographie')],
   ['Antagoniste opioïde périphérique', 'Naloxégol (Moventig®) ; méthylnaltrexone (Relistor®)', 'Ils bloquent les récepteurs μ de l’intestin sans franchir la barrière hémato-encéphalique.', w('k59-pamora', 'Monographie')]])
 + P('<i>Que montre le tableau ?</i> Les deux premières classes agissent dans la lumière ou sur la muqueuse, alors que les suivantes ciblent un récepteur précis ; ainsi, l’escalade suit la logique des mécanismes. Or, les antagonistes opioïdes périphériques ne servent que si un opioïde est en cause : ils lèvent le frein μ sans annuler l’antalgie, puisqu’ils n’atteignent pas le cerveau.')
 + key('Les osmotiques retiennent l’eau, les stimulants activent la propulsion, le prucalopride agit par les récepteurs 5-HT4, le linaclotide stimule la sécrétion, et les antagonistes périphériques lèvent le frein des opioïdes.')
 + src(S2K, FI('Movicol®'), FI('Resolor®')))

C.p(2, 'Doses suisses et statut réglementaire', P(
 'Les doses ci-dessous proviennent des informations professionnelles suisses ; or, plusieurs différences avec la S2k doivent être comprises. Ainsi, l’information de Movicol® limite l’automédication à 3 mois sans prescription, alors que la S2k juge qu’une limitation de durée n’est pas justifiée : il n’y a pas de contradiction, car le traitement prolongé se fait alors sous prescription médicale.')
 + table(['Médicament', 'Dose chez l’adulte (FI suisse)', 'Point clé', 'Source'], [
   ['Macrogol 3350 (Movicol®)', '1 à 2 sachets par jour, chacun dilué dans 125 ml d’eau ; après 65 ans, 1 sachet suffit généralement', 'Fécalome : 8 sachets par jour en 6 heures, au maximum 3 jours', 'FI Movicol®'],
   ['Lactulose (Duphalac®)', '15-45 ml par jour les 3 premiers jours, puis 10-25 ml par jour', 'L’effet peut n’apparaître qu’après 2 à 3 jours', 'FI Duphalac®'],
   ['Bisacodyl (Dulcolax®)', '1 à 2 comprimés gastrorésistants (5-10 mg) le soir ; suppositoire 10 mg par jour', 'Effet en 6-12 h par voie orale, en 10-30 min par voie rectale ; ne pas prendre avec du lait, un antiacide ou un IPP', 'FI Dulcolax®'],
   ['Picosulfate de sodium (Laxoberon®)', '10-20 gouttes (5-10 mg) par jour, de préférence le soir', 'On commence par la dose la plus faible', 'FI Laxoberon®'],
   ['Prucalopride (Resolor®)', '1 mg une fois par jour, puis 2 mg si l’effet est insuffisant ; après 65 ans, 1 mg une fois par jour', 'On arrête si 2 mg restent inefficaces après 4 semaines', 'FI Resolor®'],
   ['Linaclotide (Constella®)', '290 µg une fois par jour, au moins 30 minutes avant un repas', 'Autorisé seulement dans l’intestin irritable avec constipation ; hors indication dans la constipation chronique', 'FI Constella®'],
   ['Naloxégol (Moventig®)', '25 mg une fois par jour ; 12,5 mg si intolérance ou insuffisance rénale modérée à sévère', 'On suspend les laxatifs d’entretien au début pour juger l’effet', 'FI Moventig®'],
   ['Méthylnaltrexone (Relistor®)', '8 mg s.c. de 38 à 61 kg, 12 mg s.c. dès 62 kg ; au maximum une dose par 48 h', 'Il est réservé aux soins palliatifs, en cas d’échec des laxatifs', 'FI Relistor®']])
 + P('<i>Que montre le tableau ?</i> Les laxatifs de premier choix ont des doses simples et s’adaptent au résultat, alors que le prucalopride a une règle d’arrêt précise ; en effet, son mécanisme ne gagne rien au-delà de 2 mg, selon son information professionnelle. Par ailleurs, la règle du bisacodyl s’explique par sa galénique : l’enrobage gastrorésistant se dissout trop tôt si l’acidité gastrique est neutralisée, ce qui irrite l’estomac et fait perdre l’effet colique. Enfin, la S2k cite le lubiprostone comme autorisé en Suisse depuis 2009 ; toutefois, aucune information professionnelle d’Amitiza® n’a été trouvée dans la base AIPS consultée, si bien que son statut actuel reste à vérifier (TODO).')
 + trap('Tous ces médicaments sont contre-indiqués en cas d’occlusion ou d’iléus, selon leurs informations professionnelles ; c’est pourquoi une constipation aiguë avec vomissements, ballonnement et arrêt des gaz doit faire chercher une occlusion (cours K56) avant tout laxatif.', 'Piège')
 + key('Le patient prend 1 à 2 sachets de macrogol par jour, ou 5-10 mg de bisacodyl le soir, ou 5-10 mg de picosulfate. Le prucalopride se donne à 1 mg puis 2 mg et s’arrête après 4 semaines d’échec ; le linaclotide est hors indication dans la constipation chronique en Suisse. Le naloxégol se donne à 25 mg par jour, et l’occlusion contre-indique tous ces produits.')
 + src(FI('Movicol®'), FI('Duphalac®'), FI('Dulcolax® Bisacodyl'), FI('Laxoberon®'), FI('Resolor®'), FI('Constella®'), FI('Moventig®'), FI('Relistor®'), S2K))

C.p(3, 'Surveillance', alert(
 'Le traitement d’épreuve se réévalue après environ 4 semaines, grâce au journal des selles et à l’échelle de Bristol ; de plus, toute apparition d’un signe d’alarme interrompt l’escalade et impose une recherche de cause organique. Par ailleurs, les laxatifs stimulants provoquent plus souvent des crampes et une diarrhée, alors que les troubles hydroélectrolytiques n’apparaissent qu’en cas de surdosage, selon la S2k.', 'Sécurité.')
 + P('Ensuite, chez le patient sous opioïdes, on interroge à chaque visite sur la constipation, car elle conduit souvent à l’arrêt de l’antalgique et donc à une douleur mal traitée, comme le souligne la S2k. Enfin, chez la personne âgée, une fausse diarrhée ou une agitation doit faire rechercher un fécalome.')
 + key('On réévalue à 4 semaines, avec le journal et l’échelle de Bristol, et un signe d’alarme arrête l’escalade. On interroge chaque patient sous opioïdes, et l’on cherche un fécalome chez la personne âgée.')
 + C.pareto('pareto-k59-pharma', 'Pharmacologie', ['k59-p-1', 'k59-p-2', 'k59-p-3'],
     ['On prescrit d’abord le macrogol, le bisacodyl ou le picosulfate.',
      'On change de classe plutôt que d’augmenter sans fin la dose.',
      'Le prucalopride se donne à 1 puis 2 mg et s’arrête après 4 semaines d’échec.',
      'On prévient la constipation des opioïdes dès la première prescription.'])
 + src(S2K, FI('Resolor®')))

# ---------------- Fenêtres
L = lab
C.pop('k59-cc', 'Constipation chronique', L(('Définition', 'Au moins deux symptômes présents lors de plus de 25 % des défécations, ou moins de 3 selles par semaine, persistent depuis 3 mois, avec un début au moins 6 mois avant le diagnostic.'), ('Pourquoi plusieurs symptômes ?', 'Beaucoup de patients vont à selle chaque jour au prix d’efforts importants ; la fréquence seule les manquerait.'), ('Fréquence', 'Elle touche environ 15 % de la population européenne, davantage les femmes et les personnes âgées.')) + C.img('k59_bristol.gif', 'Échelle de Bristol, types 1 à 7.', 'Les types 1 et 2 sont les selles dures de la constipation.', BRI) + src(S2K))
C.pop('k59-rome', 'Critères de Rome IV', L(('Rôle', 'Ces critères internationaux définissent les troubles digestifs fonctionnels ; la S2k 2022 s’en sert pour définir la constipation chronique.'), ('Pourquoi des critères ?', 'Ils rendent le diagnostic reproductible, car la prévalence varie de 9,4 à 58,9 % selon la définition utilisée.')) + src(S2K))
C.pop('k59-bristol', 'Échelle de Bristol', L(('Principe', 'Sept dessins classent les selles des billes dures (type 1) aux selles liquides (type 7).'), ('Pourquoi l’utiliser ?', 'La forme des selles reflète mieux le temps de transit que leur fréquence ; elle permet aussi de mesurer l’effet du traitement.')) + C.img('k59_bristol.gif', 'Échelle de Bristol.', 'Échelle de Bristol des formes de selles.', BRI) + src(S2K))
C.pop('k59-sii', 'Syndrome de l’intestin irritable', L(('Différence', 'La douleur abdominale liée aux selles domine dans l’intestin irritable ; dans la constipation chronique, elle n’est pas au premier plan.'), ('Conséquence', 'Si le patient a des douleurs, on applique la recommandation de l’intestin irritable, traitée dans le cours K58, car les deux troubles se recouvrent.')) + src(S2K))
C.pop('k59-alarme', 'Signes d’alarme', L(('Liste S2k', 'Ce sont un saignement, une anémie, une perte de poids de plus de 10 %, des antécédents de tumeur digestive, des adénopathies, une masse, une dénutrition, une fausse diarrhée, un âge de plus de 50 ans, une évolution progressive et une histoire courte avec des plaintes sévères.'), ('Pourquoi ?', 'Ces signes font craindre une cause organique, en particulier un cancer colorectal ; on explore donc avant de traiter.')) + src(S2K))
C.pop('k59-palier', 'Traitement par paliers', L(('Ordre', 'On commence par les mesures de base, puis on prescrit le macrogol, le picosulfate ou le bisacodyl, ensuite le prucalopride, enfin le linaclotide.'), ('Règle', 'En cas d’échec, on change de classe, puis on associe deux classes, avant de monter d’un palier.'), ('Pourquoi ?', 'Chaque palier ajoute un mécanisme nouveau ; les médicaments les plus sûrs et les mieux étudiés passent en premier.')) + src(S2K))
C.pop('k59-dysen', 'Trouble de l’évacuation', L(('Définition', 'Le côlon progresse normalement, mais le rectum ne se vide pas bien, par dyssynergie ou par obstacle anatomique.'), ('Indices', 'Le patient pousse fort, se sent mal vidé, a une sensation d’obstruction ou s’aide avec les doigts.'), ('Code', 'Ce trouble correspond à K59.01.')) + src(S2K))
C.pop('k59-stc', 'Transit lent', L(('Définition', 'Le côlon fait progresser lentement son contenu, si bien que les selles se dessèchent.'), ('Preuve', 'Le test aux marqueurs montre un temps de transit supérieur à 68-72 h.'), ('Code', 'Ce trouble correspond à K59.00.')) + src(S2K))
C.pop('k59-icc', 'Cellules interstitielles de Cajal', L(('Rôle', 'Ces cellules génèrent le rythme électrique de base de la musculature digestive ; elles jouent le rôle de stimulateur.'), ('Lien avec la constipation', 'La S2k associe la constipation à des anomalies de ces cellules, ainsi qu’à des neuropathies et des myopathies entériques.')) + src(S2K))
C.pop('k59-dyssyn', 'Dyssynergie du plancher pelvien', L(('Mécanisme', 'Lors de la poussée, le puborectal et le sphincter externe se contractent au lieu de se relâcher.'), ('Fréquence', 'La manométrie la montre chez 20 à 75 % des patients examinés, mais aussi chez des sujets sains gênés par la situation.'), ('Conséquence', 'Un second examen doit la confirmer, puis on la traite par biofeedback.')) + src(S2K))
C.pop('k59-tr', 'Toucher rectal', L(('Ce qu’on évalue', 'On apprécie le tonus de repos, la contraction volontaire et la tentative de poussée, et l’on cherche un fécalome ou une masse.'), ('Limite', 'Sa valeur prédictive négative pour un trouble de l’évacuation n’est que de 64 %, si bien qu’un toucher normal n’exclut pas ce trouble.')) + src(S2K))
C.pop('k59-colo', 'Iléocoloscopie', L(('Indication', 'On la fait d’emblée en cas de signe d’alarme, ou lorsque le traitement d’épreuve échoue.'), ('Pourquoi ?', 'Elle exclut un cancer, une sténose ou une inflammation, qui seraient des causes organiques.'), ('Répétition', 'Sans changement des plaintes, on évite de la répéter en dehors des intervalles de dépistage.')) + src(S2K))
C.pop('k59-mano', 'Manométrie anorectale', L(('Principe', 'Une sonde mesure les pressions du rectum et du canal anal au repos, à la contraction et à la poussée.'), ('Apport', 'Elle montre une dyssynergie et permet d’exclure une maladie de Hirschsprung.'), ('Limite', 'Une dyssynergie peut apparaître chez un sujet sain gêné par l’examen ; c’est pourquoi un second test la confirme.')) + src(S2K))
C.pop('k59-ballon', 'Test d’expulsion du ballonnet', L(('Principe', 'Le patient doit expulser un ballonnet rempli d’eau, généralement de 50 ml, placé dans le rectum.'), ('Valeur', 'Ce test simple concorde bien avec la manométrie ; cependant, il peut être faussement positif en raison de la situation d’examen.')) + src(S2K))
C.pop('k59-defeco', 'Défécographie', L(('Principe', 'On filme l’évacuation d’un produit de contraste placé dans le rectum, par radiologie ou par IRM.'), ('Apport', 'Elle montre une rectocèle, une intussusception ou une entérocèle, et elle confirme une dyssynergie.'), ('Limite', 'Une rectocèle existe chez 48 à 93 % des sujets sains ; l’image s’interprète donc avec un questionnaire fonctionnel validé.')) + src(S2K))
C.pop('k59-hinton', 'Test de Hinton (transit aux marqueurs)', L(('Principe', 'Le patient avale des marqueurs radio-opaques, puis une radiographie les compte par segment du côlon.'), ('Valeur normale', 'Le temps de transit colique est normalement inférieur à 68-72 h.'), ('Précaution', 'Le patient tient un journal des selles, car une selle juste avant le cliché fausserait le résultat.')) + C.img('k59_hinton.gif', 'Radiographie avec marqueurs comptés par segment.', 'Marqueurs accumulés dans le rectosigmoïde.', HIN) + src(S2K))
C.pop('k59-psyl', 'Psyllium', L(('Nature', 'C’est une fibre soluble, issue de l’enveloppe des graines de plantain.'), ('Pourquoi lui ?', 'Parmi les fibres, c’est celle dont l’efficacité est la mieux démontrée par des études contre placebo.'), ('Limite', 'Comme toutes les fibres, il peut provoquer des ballonnements ; on réduit alors la dose et l’on préfère un laxatif osmotique.')) + src(S2K))
C.pop('k59-biofb', 'Biofeedback', L(('Principe', 'Une sonde anale affiche au patient, par exemple par des signaux lumineux, l’état de contraction de ses sphincters ; il apprend ainsi à les relâcher en poussant.'), ('Indication', 'On le propose dans la dyssynergie, même associée à un transit lent.'), ('Non-indication', 'Il ne sert pas dans le transit lent isolé, car la sortie fonctionne alors normalement.')) + src(S2K))
C.pop('k59-cio', 'Constipation induite par les opioïdes', L(('Fréquence', 'Elle touche 15 à 80 % des patients sous opioïdes, selon leurs facteurs de risque.'), ('Prévention', 'On commence une prophylaxie laxative dès la première prescription d’opioïde.'), ('Escalade', 'Si les laxatifs échouent, on prescrit un antagoniste opioïde périphérique, ou l’association oxycodone-naloxone chez le patient sous oxycodone.'), ('Code', 'Elle correspond à K59.02.')) + src(S2K))
C.pop('k59-pamora', 'Antagonistes opioïdes périphériques', L(('Mécanisme', 'Ils bloquent les récepteurs μ de l’intestin, mais ne franchissent pas la barrière hémato-encéphalique ; l’antalgie est donc préservée.'), ('Naloxégol (Moventig®)', 'On donne 25 mg une fois par jour, ou 12,5 mg en cas d’intolérance ou d’insuffisance rénale modérée à sévère.'), ('Méthylnaltrexone (Relistor®)', 'On injecte 8 mg s.c. de 38 à 61 kg, ou 12 mg dès 62 kg, au maximum une fois par 48 h, en soins palliatifs.'), ('Contre-indication', 'Une occlusion connue ou suspectée les contre-indique, car ils exposent à une perforation.')) + src(FI('Moventig®'), FI('Relistor®'), S2K))
C.pop('k59-fecal', 'Fécalome', L(('Définition', 'C’est une masse de selles durcies qui ne peut plus être évacuée.'), ('Risques', 'Elle peut provoquer une occlusion, une ulcération de pression ou une perforation, et elle peut se manifester par une fausse diarrhée.'), ('Traitement médicamenteux', 'Movicol® peut être donné à raison de 8 sachets par jour en 6 heures, au maximum 3 jours.')) + C.img('k59_fecalome.gif', 'Radiographie : fécalome géant.', 'Fécalome géant de plus de 40 cm.', FCR) + src(FI('Movicol®'), FEC))
C.pop('k59-mcg', 'Macrogol 3350 (Movicol®)', L(('Mécanisme', 'Ce polymère peu absorbé retient l’eau dans la lumière intestinale.'), ('Dose', 'On donne 1 à 2 sachets par jour, chacun dilué dans 125 ml d’eau ; après 65 ans, 1 sachet suffit généralement.'), ('Durée', 'La FI limite l’automédication à 3 mois ; au-delà, le traitement se poursuit sous prescription, ce que la S2k juge sûr.'), ('Grossesse', 'La S2k admet son emploi pendant la grossesse.')) + src(FI('Movicol®'), S2K))
C.pop('k59-lactu', 'Lactulose (Duphalac®)', L(('Mécanisme', 'Ce sucre non absorbé attire l’eau dans la lumière, puis il fermente dans le côlon.'), ('Dose', 'On donne 15-45 ml par jour les 3 premiers jours, puis 10-25 ml par jour.'), ('Délai', 'L’effet peut n’apparaître qu’après 2 à 3 jours.')) + src(FI('Duphalac®'), S2K))
C.pop('k59-bisa', 'Bisacodyl (Dulcolax®)', L(('Mécanisme', 'Il stimule la motricité propulsive du côlon et la sécrétion d’eau.'), ('Dose', 'On donne 1 à 2 comprimés gastrorésistants de 5 mg le soir, ou 1 suppositoire de 10 mg par jour.'), ('Précaution', 'On ne le prend pas avec du lait, un antiacide ou un IPP, car l’enrobage se dissoudrait trop tôt.')) + src(FI('Dulcolax® Bisacodyl'), S2K))
C.pop('k59-pico', 'Picosulfate de sodium (Laxoberon®)', L(('Mécanisme', 'C’est un dérivé du bisacodyl, d’effet identique, activé dans le côlon.'), ('Dose', 'On donne 10 à 20 gouttes (5 à 10 mg) par jour, de préférence le soir, en commençant par la dose la plus faible.'), ('Délai', 'L’effet apparaît en 6 à 12 heures.')) + src(FI('Laxoberon®'), S2K))
C.pop('k59-pruca', 'Prucalopride (Resolor®)', L(('Mécanisme', 'Cet agoniste des récepteurs 5-HT4 stimule la motricité propulsive.'), ('Indication', 'La FI le réserve à la constipation chronique idiopathique de l’adulte après l’échec des laxatifs et des mesures diététiques.'), ('Dose', 'On donne 1 mg une fois par jour, puis 2 mg si l’effet est insuffisant ; après 65 ans, on donne 1 mg.'), ('Arrêt', 'On l’arrête si 2 mg restent inefficaces après 4 semaines.')) + src(FI('Resolor®'), S2K))
C.pop('k59-lina', 'Linaclotide (Constella®)', L(('Mécanisme', 'Il augmente la sécrétion de chlore et d’eau dans la lumière intestinale.'), ('Statut suisse', 'Sa FI ne l’autorise que dans l’intestin irritable modéré à sévère avec constipation ; dans la constipation chronique, son emploi est donc hors indication.'), ('Dose', 'On donne 290 µg une fois par jour, au moins 30 minutes avant un repas.')) + src(FI('Constella®'), S2K))

C.termes = [
 (r'constipation chronique', 'k59-cc'), (r'Rome IV', 'k59-rome'), (r'échelle de Bristol', 'k59-bristol'), (r'signes? d’alarme', 'k59-alarme'),
 (r'trouble de l’évacuation', 'k59-dysen'), (r'transit lent', 'k59-stc'), (r'cellules de Cajal', 'k59-icc'), (r'dyssynergie', 'k59-dyssyn'),
 (r'toucher rectal', 'k59-tr'), (r'coloscopie', 'k59-colo'), (r'manométrie', 'k59-mano'), (r'ballonnet', 'k59-ballon'),
 (r'défécographie', 'k59-defeco'), (r'Hinton', 'k59-hinton'), (r'psyllium', 'k59-psyl'), (r'biofeedback', 'k59-biofb'),
 (r'constipation des opioïdes', 'k59-cio'), (r'antagonistes? opioïdes? périphériques?', 'k59-pamora'), (r'fécalome', 'k59-fecal'),
 (r'macrogol', 'k59-mcg'), (r'lactulose', 'k59-lactu'), (r'bisacodyl', 'k59-bisa'), (r'picosulfate', 'k59-pico'), (r'prucalopride', 'k59-pruca'), (r'linaclotide', 'k59-lina'),
]

C.write()
