# RAPPEL VERITE : vraies images uniquement · doses exactes (sources suisses/europeennes verifiees) · codes CIM-10-GM verifies · connecteurs logiques · termes et fenetres interactifs · aucune invention.
import sys, os; sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__)))); sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from medina_gen import *
from images import credit

C = Chapter('K60', 'Fissure et fistule des régions anale et rectale',
    'K60 — Fissure et fistule des régions anale et rectale · CIM-10-GM 2024 · Canal anal et rectum',
    'Adulte · fissure anale aiguë et chronique (K60.0 à K60.2), fistule anale cryptoglandulaire (K60.3 à K60.5) · rédaction du 10.10.2026 · référentiels S3 Analfissur 2020 (DGK, avec les sociétés suisse et autrichienne), S3 Kryptoglanduläre Analfistel 2026 (DGAV/DGK), information professionnelle suisse',
    'Pharmacologie de la fissure anale')
w = C.w
FIS = ('Marti L. et al., S3-Leitlinie: Analfissur (AWMF 081-010), coloproctology 2020;42:90-196', 'https://link.springer.com/article/10.1007/s00053-020-00448-7')
FST = ('Jaschke et al., S3-Leitlinie Kryptoglanduläre Analfistel, version 3.1, 2026 (AWMF 088-003)', 'https://register.awmf.org/assets/guidelines/088-003l_S3_Kryptoglandulaere_Analfisteln_2026-06.pdf')
FI = lambda n: ('Information professionnelle suisse ' + n + ', Swissmedic (AIPS), consultée le 10.10.2026', 'https://www.swissmedicinfo.ch/')
AIG = credit({'auteur': 'Bernardo Gui', 'licence': 'Public domain', 'url': 'https://commons.wikimedia.org/wiki/File:Anal_fissure_1.jpg'})
AIG2 = credit({'auteur': 'Bernardo Gui', 'licence': 'Public domain', 'url': 'https://commons.wikimedia.org/wiki/File:Anal_fissure_2.jpg'})
CHR = credit({'auteur': 'J. Guntau (de.wikipedia)', 'licence': 'CC BY-SA 3.0', 'url': 'https://commons.wikimedia.org/wiki/File:Analfissur-chron-aussen-1-06.jpg'})
EUS = credit({'auteur': 'Jmarchn', 'licence': 'CC BY 4.0', 'url': 'https://commons.wikimedia.org/wiki/File:Intersphincteric_anal_fistula_1.jpg'})

C.a(0, 'Question clinique et objectifs', P(
 'Une femme de 34 ans, qui a accouché il y a deux mois, décrit une douleur anale violente, « comme une déchirure », à chaque selle ; la douleur persiste une à deux heures, et elle voit du sang rouge sur le papier. <b>La question est donc double : s’agit-il d’une ' + w('k60-fis', 'fissure anale') + ', aiguë ou déjà chronique, et quel traitement choisir sans menacer sa continence ?</b>',
 'Pour y répondre, le médecin doit savoir reconnaître la fissure à l’anamnèse et à l’inspection ; ensuite, il doit distinguer la fissure aiguë de la ' + w('k60-chr', 'fissure chronique') + ' et la fissure primaire d’une ' + w('k60-sec', 'fissure secondaire') + ' ; de plus, il doit comprendre pourquoi le traitement cherche à relâcher le ' + w('k60-sai', 'sphincter interne') + ' ; enfin, il doit savoir reconnaître une ' + w('k60-fst', 'fistule anale') + ', dont le traitement est chirurgical et dont le risque principal est, là aussi, l’incontinence.')
 + P('<i>Pourquoi ce cas ?</i> En effet, la fissure est l’une des affections proctologiques les plus fréquentes, et la jeune accouchée cumule deux pièges : un sphincter parfois peu tonique après l’accouchement et un risque d’incontinence si l’on coupe le muscle. Ainsi, contrairement à un manuel figé qui juxtapose les traitements, ce cours relie chaque décision au mécanisme ; chaque mot vert ouvre le critère, la dose suisse ou l’image correspondante.')
 + key('Douleur anale déchirante à la selle et sang rouge : penser fissure → inspecter en écartant les fesses → chercher une localisation atypique → relâcher le sphincter avant de penser à opérer.', 'Point de départ.'))

C.a(1, 'Définitions et épidémiologie', P(
 'Selon la S3 2020, la fissure anale est une perte de substance radiaire de l’anoderme, située en dessous de la ligne pectinée. Ainsi, elle siège dans 80 à 90 % des cas à la commissure postérieure, c’est-à-dire à 6 heures en position gynécologique. Par ailleurs, on la dit chronique lorsque les symptômes durent plus de 6 à 8 semaines ; de plus, des modifications morphologiques s’y ajoutent généralement : une papille anale hypertrophique, un ' + w('k60-mar', 'repli sentinelle') + ', un ulcère à bords surélevés et des fibres du sphincter interne visibles au fond.',
 'En outre, les données épidémiologiques sont rares. Une étude cas-témoins de 1243 patients a calculé une incidence de 1,1 pour 1000 années-patients, soit un risque sur la vie de 7,8 % ; c’est pourquoi la S3 retient un risque sur la vie pouvant atteindre 8 à 11 %. De plus, aucun sexe ne prédomine nettement, mais la fissure est plus fréquente pendant la grossesse et après l’accouchement : une étude l’a diagnostiquée chez un tiers des accouchées.')
 + table(['Code CIM-10-GM', 'Libellé officiel', 'Ce que le code décrit'], [
   ['K60.0', 'Fissure anale aiguë', 'La fissure date de moins de 6 à 8 semaines.'],
   ['K60.1', 'Fissure anale chronique', 'Elle dure plus longtemps et s’accompagne en règle de lésions secondaires.'],
   ['K60.2', 'Fissure anale, sans précision', 'Son ancienneté n’est pas précisée.'],
   ['K60.3', 'Fistule anale', 'Le trajet relie le canal anal à la peau périanale.'],
   ['K60.4', 'Fistule rectale', 'Le trajet part du rectum.'],
   ['K60.5', 'Fistule ano-rectale', 'Le trajet concerne à la fois l’anus et le rectum.']])
 + P('<i>Que montre le tableau ?</i> Le code réunit deux maladies différentes du même carrefour anatomique : la fissure est une plaie de la muqueuse, alors que la fistule est un tunnel infecté. Or, leur point commun est le sphincter : on cherche à le relâcher dans la fissure, mais à le préserver lors de la chirurgie de la fistule. C’est pourquoi la continence domine toutes les décisions de ce cours.')
 + key('La fissure est une plaie radiaire de l’anoderme sous la ligne pectinée, postérieure dans 80-90 % des cas ; elle devient chronique au-delà de 6-8 semaines, avec papille hypertrophique, repli sentinelle, bords surélevés et fibres sphinctériennes visibles. Son risque sur la vie atteint environ 8 à 11 %.')
 + src(FIS))

C.a(2, 'Physiopathologie : le cercle vicieux du sphincter', P(
 'Selon la S3, le mécanisme exact reste inconnu ; cependant, la plupart des études placent au centre une hypertonie du sphincter interne. En effet, une étude de 1996 mesurait une pression anale de repos médiane de 121 mmHg chez les patients, contre 69 mmHg chez les témoins, alors qu’une pression normale est souvent définie comme inférieure à 90 mmHg. Or, cette hypertonie réduit le débit sanguin ; de plus, des études par Doppler laser et par artériographie post mortem ont montré que les branches de l’artère rectale inférieure sont raréfiées à la commissure postérieure, c’est-à-dire précisément là où siègent les fissures primaires.',
 'Dès lors, un cercle vicieux s’installe : l’hypertonie provoque une ischémie, l’ischémie empêche la cicatrisation et entretient l’inflammation, puis la douleur augmente encore le tonus par réflexe. C’est pourquoi presque tous les traitements, médicaux ou chirurgicaux, visent à abaisser la pression du sphincter. Cependant, certaines fissures surviennent avec une pression basse, en particulier après l’accouchement ; dans ce cas, couper le sphincter serait à la fois inutile et dangereux. Par ailleurs, la constipation et les selles dures favorisent la fissure, de même qu’une alimentation pauvre en fibres, l’obésité et l’hypothyroïdie ; paradoxalement, la diarrhée aussi, car le sphincter doit se contracter davantage pour retenir des selles liquides.')
 + C.img('k60_fissure_aigue.gif', 'Photographie de la marge anale : une flèche rouge désigne une petite plaie allongée et radiaire, entourée d’une muqueuse rosée.', 'Fissure anale : la flèche montre la plaie radiaire de l’anoderme.', AIG)
 + P('<i>Que montre l’image ?</i> La plaie est étroite, allongée dans l’axe d’un rayon de l’anus et à bords nets ; ainsi, elle correspond à une déchirure récente, sans les bords surélevés de la forme chronique. Or, il suffit d’écarter doucement les fesses pour la voir ; c’est pourquoi la S3 n’exige pas d’emblée l’anuscopie, souvent impossible à cause de la douleur et du spasme.')
 + key('Hypertonie du sphincter interne → ischémie de la commissure postérieure, mal vascularisée → absence de cicatrisation → douleur → tonus encore plus élevé. Tous les traitements cassent ce cercle en abaissant la pression, sauf quand le tonus est déjà bas, par exemple après l’accouchement.')
 + src(FIS))

C.a(3, 'Diagnostic et fissures secondaires', P(
 'Selon la S3, la douleur anale liée à la défécation est presque pathognomonique ; selon que la fissure est aiguë ou chronique, elle dure une à deux heures, voire plusieurs heures après la selle. De plus, le patient remarque souvent du sang rouge sur les selles ou sur le papier. Ensuite, l’examen comprend l’inspection et la palpation : l’écartement des fesses montre généralement déjà la fissure. Par ailleurs, une ' + w('k60-anusco', 'anuscopie') + ' devrait être faite, mais elle est souvent impossible au début ; c’est pourquoi, si le diagnostic est douteux, on examine le patient sous anesthésie. En outre, le toucher rectal apprécie mal le tonus : sa spécificité pour détecter une hypertonie n’était que de 16 % dans une étude en aveugle.',
 'Il faut ensuite distinguer la fissure primaire de la fissure secondaire, qui complique une autre maladie. Ainsi, la fissure secondaire est plus souvent latérale, atypique et multiple ; elle peut révéler une maladie de Crohn, une infection (VIH, CMV, herpès, chlamydia, tuberculose, syphilis, gonorrhée), un traumatisme, une chirurgie anale ou un médicament comme le nicorandil. C’est pourquoi, devant une fissure atypique, la S3 recommande un bilan par étapes, avec sérologies et prélèvements selon l’anamnèse ; de plus, une suspicion de Crohn impose une coloscopie avec biopsies. Enfin, si la fissure persiste après 6 à 8 semaines de traitement, une anuscopie doit être faite, au besoin sous anesthésie, pour ne pas manquer un abcès, une fistule, un lymphome ou un cancer de l’anus.')
 + C.img('k60_fissure_chron.gif', 'Vue endoscopique de la marge et du canal anal : défect allongé dans un repli de muqueuse, entouré d’une muqueuse épaissie.', 'Fissure anale en vue endoscopique ; le fichier source la décrit comme une fissure chronique.', CHR)
 + P('<i>Que montre l’image ?</i> Dans la forme chronique, la plaie ne cicatrise pas et ses bords s’épaississent, puis un repli de peau œdémateux, le repli sentinelle, se forme à son extrémité externe ; ainsi, l’aspect témoigne de semaines d’ischémie et d’inflammation. Or, ces lésions secondaires ne disparaissent pas avec un traitement médical ; c’est pourquoi la S3 recommande de les réséquer lors d’une éventuelle intervention.')
 + quiz('Un homme présente deux fissures latérales, indolores, et une diarrhée depuis trois mois. Quelle est la démarche la plus juste ?',
   [('Prescrire une pommade relaxante et revoir dans 6 semaines', False), ('Rechercher une cause secondaire, notamment par une coloscopie avec biopsies', True), ('Proposer d’emblée une sphinctérotomie', False)],
   'Une localisation latérale et multiple est atypique : selon la S3, elle impose de chercher une fissure secondaire, en particulier une maladie de Crohn, par une coloscopie avec biopsies.')
 + key('La douleur déchirante à la selle et le sang rouge orientent vers une fissure, et l’écartement des fesses la montre. Une fissure latérale, multiple ou atypique fait chercher un Crohn, une infection ou un médicament ; au-delà de 6-8 semaines d’échec, on fait une anuscopie, au besoin sous anesthésie.')
 + src(FIS))

C.a(4, 'Traitement de la fissure aiguë', P(
 'La fissure aiguë guérit souvent spontanément : selon la S3, 60 à 90 % des fissures aiguës cicatrisent sous traitement conservateur. Ainsi, la première mesure est de ramollir les selles, car une selle dure rouvre la plaie et relance le spasme : on recommande une alimentation riche en fibres ou un complément, par exemple du ' + w('k60-psyl', 'psyllium') + '. De plus, cette alimentation doit être poursuivie pour prévenir les récidives ; en effet, dans un essai, 68 % des patients sous placebo récidivaient en 18 mois, contre 16 % de ceux qui prenaient 15 g de son par jour pendant un an.',
 'Ensuite, la S3 recommande d’appliquer localement un ' + w('k60-icc', 'inhibiteur calcique') + ', par exemple la nifédipine, pendant 3 à 8 semaines ; en effet, il relâche le sphincter interne et rompt le cercle vicieux. Par ailleurs, les anesthésiques locaux soulagent la douleur sans changer la cicatrisation, et les bains de siège améliorent le confort, mais ils n’accélèrent pas la guérison et irritent parfois la peau. Enfin, les dérivés nitrés peuvent aussi être employés dans la fissure aiguë, mais leur niveau de preuve y est plus faible que celui de la nifédipine.')
 + key('La fissure aiguë guérit dans 60-90 % des cas sans chirurgie. On ramollit les selles par des fibres (psyllium), que l’on poursuit pour prévenir la récidive (16 % contre 68 %), et l’on applique un inhibiteur calcique pendant 3 à 8 semaines ; les anesthésiques locaux et les bains de siège ne servent qu’au confort.')
 + src(FIS))

C.a(5, 'Traitement de la fissure chronique', P(
 'Selon la S3, tout patient atteint de fissure chronique doit d’abord recevoir un traitement conservateur pendant 6 semaines avant une intervention (grade A) ; toutefois, on peut opérer d’emblée si le patient le souhaite, ou en cas de fistule associée ou de lésions secondaires marquées. Ainsi, le principe est une « ' + w('k60-chim', 'sphinctérotomie chimique') + ' » : on relâche le muscle par un médicament, de façon réversible, au lieu de le couper. Les inhibiteurs calciques locaux sont le premier choix (grade B), car leur efficacité égale celle des dérivés nitrés, avec moins d’effets systémiques ; en effet, une méta-analyse rapportait des céphalées chez 37,5 % des patients sous inhibiteur calcique oral, 16 % sous forme locale et 8,4 % sous placebo.',
 'Ensuite, les dérivés nitrés comme le ' + w('k60-gtn', 'trinitrate de glycéryle') + ' constituent une alternative, au prix de céphalées chez environ 30 % des patients selon la S3. Si le traitement local échoue, la ' + w('k60-botu', 'toxine botulique') + ' injectée dans le sphincter peut être discutée en deuxième ligne, à la place d’une chirurgie ; en effet, elle guérit un peu plus souvent que les pommades, mais son injection est douloureuse, coûteuse et parfois faite sous anesthésie. Enfin, lorsque la chirurgie est retenue, la ' + w('k60-fissurect', 'fissurectomie') + ' est le premier choix (grade B), éventuellement associée à la toxine ou à un lambeau d’avancement ; en revanche, la ' + w('k60-lis', 'sphinctérotomie latérale interne') + ', qui guérit le plus souvent, expose davantage à l’incontinence et ne doit donc pas être utilisée en première ligne (grade A).')
 + table(['Étape', 'Traitement', 'Justification'], [
   ['1', 'Fibres, puis inhibiteur calcique local pendant 6 semaines', 'Le traitement est réversible et sans risque pour la continence.'],
   ['2', 'Dérivé nitré local (alternative)', 'Il est aussi efficace, mais il provoque plus de céphalées.'],
   ['3', 'Toxine botulique intrasphinctérienne', 'Elle relâche le sphincter pendant des semaines, sans le couper.'],
   ['4', 'Fissurectomie, avec résection des lésions secondaires et examen histologique', 'Elle guérit mieux que les traitements médicaux, avec peu d’incontinence.'],
   ['Exception', 'Sphinctérotomie latérale interne', 'Elle guérit le mieux, mais elle coupe le muscle ; on la réserve à des cas choisis.'],
   ['Proscrit', 'Dilatation anale manuelle', 'Elle guérit moins et provoque le plus d’incontinence (grade A).']])
 + P('<i>Que montre le tableau ?</i> Plus on avance, plus l’effet sur le sphincter devient durable : d’abord pharmacologique et réversible, puis prolongé par la toxine, enfin définitif par la section. Or, chaque gain de guérison se paie en risque d’incontinence ; c’est pourquoi la S3 demande de réserver la sphinctérotomie, avec beaucoup de prudence après un accouchement, en cas de tonus bas ou d’opération anale antérieure (grade A). De plus, le tissu excisé lors d’une fissurectomie doit être examiné en histologie (grade A), afin de ne pas manquer une lésion maligne.')
 + key('Le patient reçoit 6 semaines de traitement conservateur, avec un inhibiteur calcique local en premier choix et un dérivé nitré en alternative. En cas d’échec, on discute la toxine botulique ou la fissurectomie, que l’on préfère, avec résection des lésions secondaires et histologie ; la sphinctérotomie reste une exception, et la dilatation manuelle est proscrite.')
 + src(FIS))

C.a(6, 'Fistule anale cryptoglandulaire', P(
 'La fistule anale est un trajet infecté qui relie le canal anal à la peau. Ainsi, selon la S3 2026, plus de 90 % des fistules sont d’origine cryptoglandulaire : une glande anale, qui s’ouvre dans une crypte au niveau de la ligne pectinée, s’infecte, forme un abcès, puis le trajet de drainage persiste. C’est pourquoi un tiers à la moitié des patients qui ont un ' + w('k60-abces', 'abcès anorectal') + ' présentent aussi une fistule. Par ailleurs, son incidence est d’environ 2 pour 10 000 habitants par an, avec un pic chez l’homme jeune.',
 'Ensuite, la S3 recommande de classer la fistule selon sa relation au sphincter, d’après la ' + w('k60-parks', 'classification de Parks') + ' : intersphinctérienne, transsphinctérienne ou suprasphinctérienne ; en revanche, les fistules sous-anodermiques et extrasphinctériennes ne sont pas des fistules typiques. Or, cette classification décide du geste : plus le trajet traverse de muscle, plus son ouverture menace la continence. C’est pourquoi l’' + w('k60-eus', 'échographie endoanale') + ' devrait évaluer le sphincter et ses éventuels défects (grade B), et l’IRM peut préciser les fistules complexes, récidivantes, extra- ou suprasphinctériennes.')
 + C.img('k60_fistule_irm.gif', 'Échographie endoanale circulaire : le canal anal apparaît comme un cercle noir central entouré des couches sphinctériennes ; la lettre F marque le trajet fistuleux dans l’espace intersphinctérien.', 'Fistule intersphinctérienne du bas canal anal chez une femme de 36 ans, en échographie endoanale (F = fistule).', EUS)
 + P('<i>Que montre l’image ?</i> La sonde, placée dans le canal, montre les anneaux des sphincters interne et externe ; ainsi, le trajet marqué F se situe entre eux, dans l’espace intersphinctérien, sans traverser le sphincter externe. Or, c’est exactement l’information dont le chirurgien a besoin : une fistule basse, qui ne traverse pas plus d’un tiers du muscle, peut être mise à plat sans menacer la continence.')
 + key('Plus de 90 % des fistules naissent d’une glande anale infectée, et un tiers à la moitié des abcès s’accompagnent d’une fistule. On les classe selon Parks (intersphinctérienne, transsphinctérienne, suprasphinctérienne) et l’on évalue le sphincter par échographie endoanale, puis par IRM si la fistule est complexe.')
 + src(FST))

C.a(7, 'Traitement de la fistule', P(
 'Selon la S3 2026, une fistule cryptoglandulaire ne doit pas être traitée de façon conservatrice (grade B), car elle ne se ferme pas spontanément. Ainsi, les fistules superficielles, sous-anodermiques, intersphinctériennes ou transsphinctériennes intéressant moins d’un tiers du sphincter, doivent être mises à plat par ' + w('k60-fistulot', 'fistulotomie') + ' (grade A) ; en effet, plusieurs études rapportent plus de 90 % de guérison, avec des troubles de la continence chez 6 à 12 % des opérés. En revanche, il faut éviter d’ouvrir largement, sans reconstruction, une fistule transsphinctérienne qui intéresse plus d’un tiers du sphincter.',
 'Dès lors, les fistules hautes relèvent de techniques qui épargnent le sphincter. D’abord, un ' + w('k60-seton', 'séton de drainage') + ' peut être posé lors du drainage d’un abcès, afin de préparer une cure définitive ; de plus, il peut rester en place à long terme chez un patient qui refuse d’autres gestes ou dont la fistule est très complexe ; dans tous les cas, il ne doit pas être douloureux. Ensuite, le lambeau d’avancement est une technique validée, et la S3 préfère le lambeau musculo-muqueux au lambeau muqueux simple, en raison de moins de récidives et de troubles de la continence (grade B). Par ailleurs, la technique ' + w('k60-lift', 'LIFT') + ' est une alternative au lambeau pour les fistules transsphinctériennes hautes, avec des taux de guérison et de continence comparables ; enfin, le laser et la radiofréquence ne devraient traiter que des fistules superficielles. De plus, l’intervention se fait sous anesthésie générale ou régionale, et non sous anesthésie locale.')
 + alert('Une fistule associée à une fièvre, une douleur pulsatile et une tuméfaction périanale signe un abcès : il doit être drainé chirurgicalement en urgence, car un antibiotique seul ne vide pas la collection (cours K61).', 'Gravité d’abord.')
 + key('La fistule ne se traite pas médicalement. On met à plat les fistules basses (moins d’un tiers du sphincter), ce qui guérit plus de 90 % des cas avec 6-12 % de troubles de la continence ; les fistules hautes se drainent par séton, puis se ferment par lambeau musculo-muqueux ou par LIFT.')
 + src(FST))

C.a(8, 'Synthèse et retour au cas', P(
 'Pour conclure, reprenons la patiente du début. L’écartement des fesses montre une plaie postérieure, sans repli sentinelle ni bords surélevés, depuis moins de 6 semaines : il s’agit donc d’une fissure aiguë primaire, et sa localisation typique ne demande pas d’examen supplémentaire. Ainsi, elle reçoit des fibres, du psyllium, puis un inhibiteur calcique local pendant 3 à 8 semaines ; de plus, on lui explique de poursuivre les fibres pour prévenir la récidive.',
 'Cependant, si la fissure devenait chronique, la conduite serait prudente. En effet, après un accouchement, le tonus sphinctérien peut être bas, et la S3 demande d’éviter la sphinctérotomie dans cette situation ; c’est pourquoi, après l’échec du traitement local, on discuterait la toxine botulique ou la fissurectomie, mais pas la section du muscle. Par ailleurs, une fièvre ou un écoulement purulent feraient chercher un abcès ou une fistule.')
 + C.pareto('pareto-k60-clinique', 'Fissure et fistule anales', ['k60-1', 'k60-3', 'k60-4', 'k60-5', 'k60-6', 'k60-7'],
     ['La douleur déchirante à la selle et le sang rouge orientent vers une fissure.',
      'Une fissure latérale ou multiple fait chercher une cause secondaire, en particulier un Crohn.',
      'Les fibres ramollissent les selles et préviennent la récidive.',
      'Le premier choix est l’inhibiteur calcique local, que l’on poursuit 6 semaines en cas de fissure chronique.',
      'La fissurectomie est l’opération de premier choix, alors que la sphinctérotomie reste une exception.',
      'On met à plat une fistule basse, mais on épargne le sphincter dans une fistule haute.'])
 + key('La patiente a une fissure aiguë primaire et reçoit des fibres et un inhibiteur calcique local. Si la fissure devient chronique, on préfère la toxine ou la fissurectomie à la sphinctérotomie, car le post-partum expose à l’incontinence.')
 + src(FIS))

C.a(9, 'Critères formels et paramètres clés', alert(
 '<p>Selon la S3 2020, la <b>fissure chronique</b> se distingue de la fissure aiguë par une durée de plus de 6 à 8 semaines et par des modifications morphologiques possibles : papille anale hypertrophique, repli sentinelle, ulcère à bords surélevés et fibres du sphincter interne visibles. Une <b>fissure secondaire</b> complique une maladie sous-jacente et siège plus souvent en position atypique, latérale ou multiple.</p>', 'Critères.')
 + '<div class="key"><b>Paramètres clés.</b> La fissure siège à la commissure postérieure dans 80-90 % des cas. La pression de repos médiane des patients atteint 121 mmHg, contre 69 mmHg chez les témoins. La fissure aiguë guérit dans 60-90 % des cas sans chirurgie, et le son réduit la récidive de 68 % à 16 %. Le traitement conservateur dure 6 semaines avant la chirurgie, et les nitrés provoquent des céphalées chez environ 30 % des patients. Pour les fistules, la fistulotomie guérit plus de 90 % des cas, avec 6-12 % de troubles de la continence.</div>'
 + src(FIS, FST))

# ---------------- Examens
C.e(1, 'Hiérarchie des examens', P(
 'Dans la fissure typique, l’examen clinique suffit ; en revanche, les examens servent à exclure une autre cause ou à cartographier une fistule.')
 + table(['Question', 'Examen', 'Quand ?'], [
   ['Y a-t-il une fissure ?', 'Inspection en écartant les fesses, palpation', 'Toujours, dès la première consultation'],
   ['Le canal est-il normal ?', w('k60-anusco', 'Anuscopie'), 'Si possible d’emblée, et obligatoirement après 6-8 semaines d’échec'],
   ['Le diagnostic est-il douteux ?', 'Examen sous anesthésie', 'Si la douleur empêche l’anuscopie'],
   ['La fissure est-elle secondaire ?', 'Sérologies et prélèvements (VIH, CMV, chlamydia, gonocoque) ; coloscopie avec biopsies', 'Fissure atypique ; suspicion de Crohn'],
   ['Où passe la fistule ?', w('k60-eus', 'Échographie endoanale') + ', IRM', 'Avant toute chirurgie de fistule ; IRM si complexe ou récidivante']])
 + P('<i>Que montre le tableau ?</i> L’imagerie ne sert presque jamais à la fissure, car la plaie se voit ; elle sert en revanche à la fistule, dont le trajet est caché dans le muscle. Or, c’est la relation du trajet au sphincter qui décide du geste ; c’est pourquoi l’échographie endoanale ou l’IRM précèdent la chirurgie.')
 + key('On diagnostique la fissure par l’inspection, puis on fait une anuscopie si elle résiste ; une fissure atypique fait chercher une cause secondaire, et une fistule se cartographie par échographie endoanale ou IRM.')
 + C.pareto('pareto-k60-examens', 'Examens', ['k60-e-1'],
     ['L’écartement des fesses montre la fissure dans la plupart des cas.',
      'On fait une anuscopie après 6 à 8 semaines d’échec.',
      'Une fissure atypique justifie une coloscopie avec biopsies.',
      'On cartographie une fistule avant de l’opérer.'])
 + src(FIS, FST))

# ---------------- Sciences
C.s('anat', 'Anatomie', 'Anatomie : sphincters, cryptes et commissure postérieure', P(
 'Le canal anal est entouré de deux sphincters : le sphincter interne, lisse et involontaire, assure l’essentiel du tonus de repos, alors que le sphincter externe, strié, se contracte volontairement. Ainsi, une fissure entretenue par le tonus de repos se traite en relâchant le sphincter interne. Par ailleurs, les glandes anales s’ouvrent dans les cryptes de la ligne pectinée et traversent parfois le sphincter interne ; c’est pourquoi leur infection donne des abcès et des fistules dont le trajet suit les plans musculaires.')
 + key('Le sphincter interne fait le tonus de repos et la fissure ; les glandes des cryptes font les abcès et les fistules.', 'Science → clinique.'))
C.s('physio', 'Physiologie', 'Physiologie : tonus, perfusion et cicatrisation', P(
 'Un muscle contracté comprime les petits vaisseaux qui le traversent ; ainsi, l’hypertonie du sphincter interne diminue la perfusion de l’anoderme, surtout à la commissure postérieure, où les branches de l’artère rectale inférieure sont rares. Or, une plaie mal perfusée cicatrise mal. Par conséquent, abaisser la pression de repos rétablit la perfusion, ce qui explique l’efficacité commune des inhibiteurs calciques, des dérivés nitrés, de la toxine botulique et de la sphinctérotomie.')
 + key('Le tonus élevé réduit la perfusion, ce qui empêche la cicatrisation ; quand le tonus baisse, la perfusion revient et la plaie guérit.', 'Science → traitement.'))
C.s('pharmaco', 'Pharmacologie fondamentale', 'Pharmacologie fondamentale : trois façons de relâcher un muscle lisse', P(
 'La contraction du sphincter interne dépend de l’entrée du calcium dans la cellule musculaire ; ainsi, un inhibiteur calcique bloque cette entrée et relâche le muscle. Par ailleurs, les dérivés nitrés libèrent du monoxyde d’azote, qui active la voie du GMP cyclique et relâche aussi la fibre lisse ; cependant, ils dilatent également les vaisseaux de la tête, d’où les céphalées. Enfin, la toxine botulique bloque la libération d’acétylcholine par les terminaisons nerveuses ; c’est pourquoi son effet dure plusieurs semaines, le temps que de nouvelles terminaisons se forment.')
 + key('Les inhibiteurs calciques bloquent le calcium, les nitrés agissent par le monoxyde d’azote et provoquent des céphalées, et la toxine bloque l’acétylcholine pendant des semaines.', 'Science → pharmacologie.'))

# ---------------- Pharmacologie
C.p(1, 'Stratégie, doses et statut réglementaire', P(
 'Le traitement médical de la fissure vise à relâcher le sphincter, alors que les fibres en suppriment la cause mécanique. Or, en Suisse, un seul produit relaxant dispose d’une information professionnelle dans la fissure anale : la pommade de trinitrate de glycéryle Rectogesic®. Ainsi, les inhibiteurs calciques recommandés en premier choix par la S3 sont des préparations magistrales hors indication, par exemple la nifédipine à 0,2 % ou le diltiazem à 2 %, comme le précise la S3 pour l’Allemagne.')
 + table(['Médicament', 'Dose et durée', 'Statut et point clé', 'Source'], [
   ['Fibres, psyllium, son', 'Alimentation riche en fibres ou complément ; 15 g de son par jour dans l’essai de prévention des récidives', 'Recommandé en aigu et en prévention', 'S3 2020'],
   ['Nifédipine 0,2 % ou diltiazem 2 % (préparation magistrale)', 'Application locale pendant 3 à 8 semaines en aigu, 6 semaines au moins en chronique ; fréquence non précisée dans la S3 lue (TODO)', 'Hors indication ; premier choix de la S3', 'S3 2020'],
   ['Trinitrate de glycéryle 4 mg/g (Rectogesic®)', '375 mg de pommade (1,5 mg de nitroglycérine), soit une ligne de 2,5 cm, dans le canal anal toutes les 12 h ; au maximum 8 semaines', 'Indiqué pour la douleur de la fissure chronique de l’adulte ; céphalées chez 57 % des patients selon la FI', 'FI Rectogesic®'],
   ['Toxine botulique de type A', '20 à 40 U équivalent Botox® par voie intrasphinctérienne lors d’une première injection si le sphincter est hypertonique', 'Aucune indication anale dans la FI suisse de BOTOX® lue : hors indication', 'S3 2020 ; FI BOTOX®']])
 + P('<i>Que montre le tableau ?</i> La seule spécialité autorisée est aussi celle qui donne le plus de céphalées ; c’est pourquoi la S3 lui préfère un inhibiteur calcique magistral, à efficacité égale. Par ailleurs, la fréquence des céphalées varie selon la source, environ 30 % dans la S3 et 57 % dans l’information de Rectogesic® ; cette différence tient probablement aux populations et aux définitions, et elle reste à vérifier à l’audit (TODO).')
 + trap('Rectogesic® est contre-indiqué avec un inhibiteur de la phosphodiestérase 5 (sildénafil, tadalafil, vardénafil), car l’association peut provoquer une hypotension sévère ; de même, il est contre-indiqué en cas de céphalées fréquentes, de sténose aortique ou mitrale, de cardiomyopathie obstructive, d’anémie sévère ou de glaucome à angle fermé (FI Rectogesic®).', 'Piège')
 + key('Le patient prend des fibres, puis un inhibiteur calcique magistral hors indication en premier choix. Rectogesic® s’applique à 1,5 mg toutes les 12 h pendant 8 semaines au plus et ne se combine jamais avec un inhibiteur de la PDE5 ; la toxine botulique (20-40 U) est hors indication en Suisse.')
 + src(FIS, FI('Rectogesic®'), FI('BOTOX®')))

C.p(2, 'Surveillance', alert(
 'On réévalue la fissure après 6 à 8 semaines ; si elle persiste, on fait une anuscopie, au besoin sous anesthésie, avant de proposer une chirurgie. De plus, sous dérivé nitré, on interroge le patient sur les céphalées, les vertiges et une prise d’inhibiteur de la PDE5 ; enfin, après toute chirurgie anale, on évalue la continence.', 'Sécurité.')
 + P('Par ailleurs, les fibres doivent être maintenues après la guérison, car la récidive est fréquente lorsqu’on les arrête ; ainsi, la prévention est aussi importante que le traitement initial.')
 + key('On réévalue à 6-8 semaines, on cherche les céphalées et les interactions sous nitrés, on évalue la continence après chirurgie, et l’on maintient les fibres.')
 + C.pareto('pareto-k60-pharma', 'Pharmacologie', ['k60-p-1', 'k60-p-2'],
     ['Le premier choix est un inhibiteur calcique local, hors indication en Suisse.',
      'Rectogesic® s’applique à 1,5 mg toutes les 12 h, pendant 8 semaines au plus.',
      'On n’associe jamais un nitré à un inhibiteur de la PDE5.',
      'On maintient les fibres après la guérison.'])
 + src(FIS, FI('Rectogesic®')))

# ---------------- Fenêtres
L = lab
C.pop('k60-fis', 'Fissure anale', L(('Définition', 'C’est une plaie radiaire de l’anoderme, sous la ligne pectinée.'), ('Siège', 'Elle se trouve à la commissure postérieure dans 80 à 90 % des cas, car cette zone est la moins bien vascularisée.'), ('Signes', 'Le patient a une douleur déchirante à la selle, qui dure une à plusieurs heures, et du sang rouge sur le papier.')) + C.img('k60_fissure2.gif', 'Marge anale : une flèche montre une petite plaie radiaire.', 'Fissure anale (flèche).', AIG2) + src(FIS))
C.pop('k60-chr', 'Fissure chronique', L(('Critères', 'Les symptômes durent plus de 6 à 8 semaines, et des lésions secondaires apparaissent : papille hypertrophique, repli sentinelle, bords surélevés, fibres du sphincter interne visibles.'), ('Pourquoi c’est important', 'La forme chronique guérit moins souvent seule ; on prévoit donc 6 semaines de traitement conservateur, puis on discute la chirurgie.')) + C.img('k60_fissure_chron.gif', 'Vue endoscopique d’une fissure.', 'Fissure chronique.', CHR) + src(FIS))
C.pop('k60-sec', 'Fissure secondaire', L(('Définition', 'Elle complique une maladie sous-jacente : maladie de Crohn, infection, traumatisme, chirurgie ou médicament comme le nicorandil.'), ('Indices', 'Elle est plus souvent latérale, atypique et multiple.'), ('Conduite', 'On fait un bilan adapté à l’anamnèse et, si l’on suspecte un Crohn, une coloscopie avec biopsies.')) + src(FIS))
C.pop('k60-sai', 'Sphincter interne', L(('Nature', 'C’est un muscle lisse involontaire qui assure l’essentiel du tonus anal de repos.'), ('Rôle dans la fissure', 'Son hypertonie réduit la perfusion de l’anoderme et empêche la cicatrisation ; c’est pourquoi tous les traitements cherchent à le relâcher.')) + src(FIS))
C.pop('k60-mar', 'Repli sentinelle', L(('Aspect', 'C’est un repli de peau œdémateux et fibreux, à l’extrémité externe de la fissure.'), ('Sens', 'Il signe une fissure chronique ; lors d’une opération, la S3 recommande de le réséquer avec les autres lésions secondaires.')) + src(FIS))
C.pop('k60-anusco', 'Anuscopie', L(('Principe', 'Un instrument court permet de voir l’intérieur du canal anal.'), ('Limite', 'Elle est souvent impossible au début, à cause de la douleur et du spasme.'), ('Indication', 'Elle devient obligatoire si la fissure persiste après 6 à 8 semaines ; si elle reste impossible, on examine le patient sous anesthésie.')) + src(FIS))
C.pop('k60-psyl', 'Psyllium', L(('Nature', 'C’est une fibre soluble qui retient l’eau et ramollit les selles.'), ('Pourquoi dans la fissure ?', 'Une selle molle ne rouvre pas la plaie et déclenche moins de spasme ; de plus, les fibres poursuivies préviennent la récidive.')) + src(FIS))
C.pop('k60-icc', 'Inhibiteurs calciques locaux', L(('Mécanisme', 'Ils bloquent l’entrée du calcium dans la fibre lisse et relâchent le sphincter interne.'), ('Place', 'C’est le premier choix médical de la S3, en aigu pendant 3 à 8 semaines et en chronique pendant au moins 6 semaines.'), ('Statut suisse', 'Il s’agit de préparations magistrales, par exemple la nifédipine 0,2 % ou le diltiazem 2 %, utilisées hors indication.'), ('Tolérance', 'La forme locale provoque des céphalées chez 16 % des patients, contre 37,5 % par voie orale.')) + src(FIS))
C.pop('k60-chim', 'Sphinctérotomie chimique', L(('Principe', 'On relâche le sphincter interne par un médicament, de façon réversible, au lieu de le couper.'), ('Moyens', 'On utilise un inhibiteur calcique ou un dérivé nitré local, puis, si nécessaire, la toxine botulique.'), ('Avantage', 'Ce traitement ne menace pas la continence.')) + src(FIS))
C.pop('k60-gtn', 'Trinitrate de glycéryle (Rectogesic®)', L(('Mécanisme', 'Il libère du monoxyde d’azote, qui relâche le muscle lisse du sphincter.'), ('Dose', 'On applique 375 mg de pommade à 4 mg/g, soit 1,5 mg, dans le canal anal toutes les 12 h, pendant 8 semaines au plus.'), ('Effet indésirable', 'Il provoque des céphalées chez environ 30 % des patients selon la S3, et chez 57 % selon la FI.'), ('Contre-indication', 'On ne l’associe jamais à un inhibiteur de la PDE5.')) + src(FI('Rectogesic®'), FIS))
C.pop('k60-botu', 'Toxine botulique', L(('Mécanisme', 'Elle bloque la libération d’acétylcholine et paralyse le sphincter pendant plusieurs semaines.'), ('Place', 'On la discute en deuxième ligne, après l’échec des pommades, à la place d’une chirurgie.'), ('Dose', 'Lors d’une première injection dans un sphincter hypertonique, on injecte 20 à 40 U équivalent Botox® ; aucun effet dose n’a été démontré.'), ('Statut suisse', 'Elle est utilisée hors indication.')) + src(FIS, FI('BOTOX®')))
C.pop('k60-fissurect', 'Fissurectomie', L(('Geste', 'On excise la fissure et ses lésions secondaires, sans couper le sphincter.'), ('Place', 'C’est l’opération de premier choix, éventuellement associée à la toxine ou à un lambeau d’avancement.'), ('Obligation', 'Le tissu excisé doit être examiné en histologie, afin de ne pas manquer une lésion maligne.')) + src(FIS))
C.pop('k60-lis', 'Sphinctérotomie latérale interne', L(('Geste', 'On sectionne une partie latérale du sphincter interne.'), ('Avantage', 'Elle a le meilleur taux de guérison.'), ('Risque', 'Elle expose davantage à l’incontinence ; on l’évite donc en première ligne, et surtout après un accouchement, en cas de tonus bas ou d’opération anale antérieure.')) + src(FIS))
C.pop('k60-fst', 'Fistule anale', L(('Définition', 'C’est un trajet infecté qui relie le canal anal à la peau périanale.'), ('Origine', 'Plus de 90 % des fistules naissent d’une glande anale infectée.'), ('Traitement', 'Il est chirurgical ; la S3 déconseille le traitement conservateur, car la fistule ne se ferme pas seule.')) + C.img('k60_fistule_irm.gif', 'Échographie endoanale : trajet intersphinctérien marqué F.', 'Fistule intersphinctérienne.', EUS) + src(FST))
C.pop('k60-abces', 'Abcès anorectal', L(('Mécanisme', 'Une glande anale infectée forme une collection de pus entre les plans musculaires.'), ('Lien', 'Un tiers à la moitié des patients qui ont un abcès présentent aussi une fistule.'), ('Conduite', 'On le draine chirurgicalement en urgence ; ce sujet est traité dans le cours K61.')) + src(FST))
C.pop('k60-parks', 'Classification de Parks', L(('Types', 'La fistule est intersphinctérienne, transsphinctérienne ou suprasphinctérienne ; les formes sous-anodermiques et extrasphinctériennes ne sont pas typiques.'), ('Pourquoi', 'Le type indique quelle part du sphincter le trajet traverse, et donc le risque d’incontinence si on l’ouvre.')) + src(FST))
C.pop('k60-eus', 'Échographie endoanale', L(('Principe', 'Une sonde placée dans le canal montre les couches du sphincter et le trajet fistuleux.'), ('Place', 'La S3 2026 la recommande pour évaluer le sphincter et ses défects ; l’IRM complète les fistules complexes ou récidivantes.')) + C.img('k60_fistule_irm.gif', 'Échographie endoanale d’une fistule.', 'F = fistule intersphinctérienne.', EUS) + src(FST))
C.pop('k60-fistulot', 'Fistulotomie', L(('Geste', 'On ouvre le trajet sur toute sa longueur, puis la plaie cicatrise à plat.'), ('Indication', 'On la fait pour les fistules superficielles et pour les transsphinctériennes qui intéressent moins d’un tiers du sphincter.'), ('Résultats', 'Elle guérit plus de 90 % des cas, avec des troubles de la continence chez 6 à 12 % des opérés.')) + src(FST))
C.pop('k60-seton', 'Séton de drainage', L(('Principe', 'Un fil passé dans le trajet empêche l’orifice externe de se fermer, si bien que le pus s’écoule et qu’aucun nouvel abcès ne se forme.'), ('Indications', 'On le pose lors du drainage d’un abcès sur fistule haute, avant une cure définitive, ou à long terme si la fistule est très complexe.'), ('Règle', 'Il ne doit pas provoquer de douleur.')) + src(FST))
C.pop('k60-lift', 'Technique LIFT', L(('Principe', 'On lie et l’on sectionne le trajet dans l’espace entre les deux sphincters, sans couper le muscle.'), ('Place', 'C’est une alternative au lambeau d’avancement dans les fistules transsphinctériennes hautes, réalisée par un chirurgien expérimenté.'), ('Résultats', 'Ses taux de guérison et de continence ne diffèrent pas significativement de ceux des lambeaux.')) + src(FST))

C.termes = [
 (r'fissure anale', 'k60-fis'), (r'fissure chronique', 'k60-chr'), (r'fissure secondaire', 'k60-sec'), (r'sphincter interne', 'k60-sai'),
 (r'repli sentinelle', 'k60-mar'), (r'anuscopie', 'k60-anusco'), (r'psyllium', 'k60-psyl'), (r'inhibiteurs? calciques?', 'k60-icc'),
 (r'dérivés? nitrés?', 'k60-gtn'), (r'Rectogesic', 'k60-gtn'), (r'toxine botulique', 'k60-botu'), (r'fissurectomie', 'k60-fissurect'),
 (r'sphinctérotomie latérale', 'k60-lis'), (r'fistule anale', 'k60-fst'), (r'abcès', 'k60-abces'), (r'Parks', 'k60-parks'),
 (r'échographie endoanale', 'k60-eus'), (r'fistulotomie', 'k60-fistulot'), (r'séton', 'k60-seton'), (r'LIFT', 'k60-lift'),
]

C.write()
