import sys, os; sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__)))); sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from medina_gen import *
from images import credit

C = Chapter('K92', 'Hémorragies digestives',
    'K92 — Autres maladies du système digestif · leçon consacrée à K92.0 — Hématémèse, K92.1 — Méléna et K92.2 — Hémorragie gastro-intestinale, sans précision · CIM-10-GM 2024 · Tube digestif',
    'Adulte · hémorragies hautes non variqueuses, variqueuses et basses · rédaction du 09.10.2026 · référentiels ESGE 2021 et 2022, Baveno VII 2022, BSG 2019, informations professionnelles suisses',
    'Pharmacologie de l’hémorragie digestive')
w = C.w
ESGE21 = ('Gralnek I. M. et al., ESGE, hémorragie digestive haute non variqueuse, mise à jour 2021, Endoscopy 2021;53:300-332', 'https://www.esge.com/assets/downloads/pdfs/guidelines/2021_a_1369_5274.pdf')
ESGE22 = ('Gralnek I. M. et al., ESGE, hémorragie variqueuse œsogastrique, Endoscopy 2022;54:1094-1120', 'https://www.esge.com/assets/downloads/pdfs/guidelines/2022_a-1939-4887.pdf')
BAV7 = ('de Franchis R. et al., Baveno VII, J Hepatol 2022;76:959-974, énoncés 6.1 à 6.38', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11090185/')
BSG19 = ('Oakland K. et al., BSG, hémorragie digestive basse aiguë, Gut 2019;68:776-789', 'https://gut.bmj.com/content/68/5/776')
EASL18 = ('EASL, cirrhose décompensée, J Hepatol 2018;69:406-460', 'https://easl.eu/wp-content/uploads/2018/10/decompensated-cirrhosis-English-report.pdf')
FI = lambda n: ('Information professionnelle suisse ' + n + ', Swissmedic (AIPS via AmiKo), consultée le 09.10.2026', 'https://amiko.oddb.org/fr')

# ---------------- Onglet 1
C.a(0, 'Question clinique et objectifs', P(
 'Un homme de 68 ans arrive aux urgences après deux selles noires et un malaise en se levant. Il prend de l’aspirine depuis un infarctus. Une femme de 55 ans atteinte de cirrhose vomit du sang rouge. <b>Dans les deux cas, la première question n’est pas « où saigne-t-il ? » mais « que reste-t-il de sa volémie ? ».</b> La localisation vient ensuite, et elle conditionne l’endoscopie, les médicaments et la reprise des antithrombotiques.',
 'Le médecin doit savoir : reconnaître une hémorragie grave et réanimer ; distinguer une hémorragie haute d’une hémorragie basse ; reconnaître le contexte de cirrhose qui change tout le traitement ; stratifier le risque par un score validé ; choisir le délai de l’endoscopie ; gérer l’aspirine, les antiagrégants et les anticoagulants ; prévenir la récidive.')
 + key('Deux distinctions guident tout le cours : l’hémorragie est-elle ' + w('k92-haute-basse', 'haute ou basse (le repère anatomique et ses limites)') + ', et le patient saigne-t-il dans le cadre d’une ' + w('k92-cirrhose-contexte', 'cirrhose (pourquoi la conduite change)') + ' ?', 'Point de départ.'))

C.a(1, 'Définitions et classification', P(
 'L’<b>hématémèse</b> est un vomissement de sang rouge ou de sang digéré, d’aspect « marc de café ». Le <b>méléna</b> est l’émission par l’anus de selles noires, goudronneuses et fétides : le sang a séjourné dans le tube digestif et l’hémoglobine a été dégradée. L’<b>hématochézie</b> est l’émission de sang rouge ou foncé par l’anus, pur ou mêlé aux selles.',
 'La classification utile au lit du malade est anatomique et étiologique. Une hémorragie est dite <b>haute</b> quand sa source se situe en amont de l’angle duodéno-jéjunal ; elle est <b>basse</b> en aval. Parmi les hémorragies hautes, la distinction <b>variqueuse</b> ou <b>non variqueuse</b> est décisive, car l’hypertension portale impose des médicaments vasoactifs, une antibioprophylaxie et une ligature.')
 + table(['Présentation', 'Source habituelle', 'Conséquence immédiate'], [
   ['Hématémèse, marc de café', 'Haute', 'Endoscopie haute après réanimation'],
   ['Méléna', 'Haute le plus souvent ; parfois grêle ou côlon droit', 'Endoscopie haute en premier'],
   ['Hématochézie avec choc', 'Basse, ou haute à débit massif', 'Angio-tomodensitométrie, puis endoscopie haute si elle est négative'],
   ['Hématochézie sans retentissement', 'Basse (diverticules, lésions anorectales)', 'Toucher rectal, score d’Oakland, coloscopie']])
 + P('Le tableau se lit par la colonne de droite : une hématochézie associée à un état de choc ne doit jamais être classée trop vite comme basse. La BSG rappelle que 11 à 15 % des hémorragies initialement crues basses ont finalement une source haute. Exemple : un patient sous antiagrégant, en choc, avec du sang rouge par l’anus et un rapport urée/créatinine élevé, saigne probablement d’un ulcère duodénal.')
 + key('La couleur des selles oriente sans localiser. Un état de choc avec hématochézie impose d’exclure une source haute.')
 + src(ESGE21, BSG19))

C.a(2, 'Épidémiologie et pronostic', P(
 'Les causes les plus fréquentes d’hémorragie digestive haute sont non variqueuses : ulcères gastriques et duodénaux, lésions érosives de l’œsophage, de l’estomac ou du duodénum, cancers, syndrome de Mallory-Weiss, lésion de Dieulafoy ; une partie reste sans cause identifiée (ESGE 2021). L’hémorragie basse a une incidence estimée de 33 à 87 pour 100 000 habitants ; sa cause la plus fréquente au Royaume-Uni est le saignement diverticulaire, suivi des lésions anorectales bénignes (BSG 2019).',
 'La mortalité dépend surtout du terrain. Dans l’audit britannique de l’hémorragie basse, la mortalité hospitalière était de 3,4 % ; elle atteignait 18 % quand le saignement survenait chez un patient déjà hospitalisé et 20 % au-delà de quatre culots transfusés. Elle était liée aux comorbidités davantage qu’à l’exsanguination. Chez le cirrhotique, la mortalité à six semaines est le critère de référence ; la classe C de Child-Pugh, le score MELD et l’échec de l’hémostase primaire la prédisent le mieux (Baveno VII, énoncé 6.15).')
 + trap('Aucune série nationale suisse consolidée de l’incidence des hémorragies digestives n’a été retrouvée lors de la rédaction ; les chiffres cités sont européens et britanniques, datés et attribués.', 'Lacune documentaire')
 + key('Le pronostic dépend du terrain (âge, comorbidités, cirrhose) et de l’échec de l’hémostase, plus que du volume initial apparent.')
 + src(ESGE21, BSG19, BAV7))

C.a(3, 'Physiopathologie : de la lésion au choc', P(
 'Normalement, la muqueuse gastroduodénale résiste à l’acide grâce au mucus, aux bicarbonates et à un flux sanguin muqueux abondant. Un ' + w('k92-ulcere-mecanisme', 'ulcère (rupture de la barrière muqueuse)') + ' creuse la paroi jusqu’à la sous-muqueuse : s’il ouvre une artère de la paroi, le saignement peut être artériel et abondant. Le pH acide inhibe l’agrégation plaquettaire et favorise la lyse du caillot ; c’est la base de l’' + w('k92-ipp-caillot', 'inhibition acide à forte dose (stabiliser le caillot)') + '.',
 'Dans la cirrhose, la résistance intrahépatique et l’afflux splanchnique élèvent la pression portale. Des ' + w('k92-varices', 'varices œsophagiennes (collatérales portosystémiques)') + ' se développent et peuvent se rompre. La rupture est un problème de pression, non de coagulation : Baveno VII précise que le traitement doit abaisser la pression portale plutôt que corriger les tests de coagulation (énoncé 6.34).',
 'La perte sanguine réduit le retour veineux. La tachycardie et la vasoconstriction maintiennent d’abord la pression artérielle ; l’hypotension est un signe tardif. L’hémoglobine initiale peut rester normale parce que l’hémodilution n’a pas encore eu lieu. ' + w('k92-uree', 'L’urée s’élève (digestion et réabsorption des protéines du sang)') + ' dans les hémorragies hautes.')
 + C.img('k92_ulcere_duodenal_saignant.gif', 'Méléna abondant dans une cuvette de toilettes, chez un patient atteint d’ulcère duodénal hémorragique.', 'Méléna : selles noires et goudronneuses d’un ulcère duodénal hémorragique. Le sang digéré signe un séjour prolongé dans le tube digestif.', credit({'auteur': 'Ashashyou', 'licence': 'CC BY-SA 4.0', 'url': 'https://commons.wikimedia.org/wiki/File:Melena_Bleeding_DU.jpg'}))
 + key('Une hémoglobine normale à l’admission ne rassure pas. La fréquence cardiaque, la pression artérielle et l’évolution clinique jugent la perte réelle.')
 + src(ESGE21, BAV7))

C.a(4, 'Étiologies et facteurs de risque', P(
 'Le contexte oriente fortement la cause. Le médecin recherche une prise d’' + w('k92-ains-aspirine', 'AINS ou d’aspirine (toxicité muqueuse)') + ', un traitement anticoagulant ou antiagrégant, une infection connue à Helicobacter pylori, une cirrhose ou une consommation d’alcool, des vomissements répétés avant l’hématémèse, une chirurgie aortique ou une polypectomie récente.')
 + table(['Situation', 'Cause à évoquer en premier', 'Indice qui la soutient'], [
   ['Prise d’AINS ou d’aspirine, épigastralgies', 'Ulcère gastroduodénal', 'Méléna, antécédent d’ulcère'],
   ['Cirrhose, ascite, angiomes stellaires', 'Rupture de varices', 'Hématémèse abondante, encéphalopathie'],
   ['Vomissements répétés puis sang rouge', 'Syndrome de Mallory-Weiss', 'Consommation d’alcool, effort de vomissement'],
   ['Sujet âgé, hématochézie indolore', 'Diverticule, angiodysplasie', 'Absence de douleur, épisodes antérieurs'],
   ['Polypectomie récente', 'Saignement post-polypectomie', 'Délai de quelques jours, source connue'],
   ['Prothèse aortique', 'Fistule aorto-digestive', 'Petit saignement « sentinelle » puis massif']])
 + P('Le tableau ne remplace pas l’endoscopie, mais il hiérarchise : un patient cirrhotique qui saigne est traité comme une hémorragie variqueuse jusqu’à preuve du contraire, même si un ulcère reste possible. La fistule aorto-digestive est rare ; la BSG la cite comme une des exceptions où l’on peut aller directement au bloc.')
 + key('Antithrombotiques, AINS et cirrhose sont les trois questions d’anamnèse qui changent immédiatement la conduite.')
 + src(ESGE21, BSG19))

C.a(5, 'Anamnèse', P(
 'L’anamnèse est brève chez un patient instable ; elle se complète après la réanimation. Elle précise l’' + w('k92-hematemese', 'hématémèse (sang rouge ou marc de café)') + ', le ' + w('k92-melena', 'méléna (sang digéré)') + ' ou l’hématochézie, la date de début, un malaise ou une syncope, et les antécédents d’ulcère, de cirrhose ou de saignement.',
 'La liste des médicaments est lue en détail : aspirine et sa raison (prévention primaire ou secondaire), second antiagrégant et date d’un éventuel stent coronaire, antivitamine K, anticoagulant oral direct et heure de la dernière prise, AINS, corticostéroïdes, inhibiteurs sélectifs de la recapture de la sérotonine. Ces informations décident plus tard de la reprise des traitements.')
 + cards(('Forme typique haute', '<p>Le patient sous aspirine ou AINS présente des épigastralgies, un méléna et un malaise orthostatique, car l’ulcère saigne dans l’estomac et la perte de volume fait chuter la pression en position debout.</p>'),
         ('Formes trompeuses', '<p>Une hématochézie massive peut venir d’une source haute, car un débit élevé accélère le transit. À l’inverse, un méléna peut venir du grêle ou du côlon droit. De plus, une syncope peut précéder tout signe digestif, et une anémie ferriprive peut révéler un saignement invisible.</p>'))
 + key('L’indication de chaque antithrombotique et l’heure de la dernière prise sont notées dès l’admission.')
 + src(ESGE21, BSG19))

C.a(6, 'Examen clinique', P(
 'L’examen commence par l’état général et les ' + w('k92-hemodynamique', 'paramètres hémodynamiques (fréquence cardiaque, pression, indice de choc)') + '. L’indice de choc est la fréquence cardiaque divisée par la pression artérielle systolique ; au-dessus de 1, la BSG classe l’hémorragie basse comme instable. Le médecin cherche ensuite les ' + w('k92-signes-cirrhose', 'signes d’hépatopathie chronique (ascite, angiomes, ictère)') + ' et pratique un ' + w('k92-toucher-rectal', 'toucher rectal (voir la couleur des selles)') + '.')
 + cards(('État général et vitaux', '<p>Le médecin recherche une pâleur, des sueurs, une confusion et un temps de recoloration allongé, car ils traduisent une hypoperfusion ; il mesure aussi la fréquence cardiaque, la pression artérielle couchée et la diurèse, qui suivent l’effet du remplissage.</p>'),
         ('Signes ciblés', '<p>Une ascite, une circulation veineuse collatérale ou un astérixis orientent vers une cirrhose, donc vers des varices. De plus, une douleur épigastrique évoque un ulcère, et une défense abdominale fait craindre une perforation associée.</p>'))
 + trap('Un bêtabloquant masque la tachycardie : l’indice de choc doit alors être interprété avec prudence, comme le précise la BSG.')
 + key('Les signes vitaux répétés et le toucher rectal sont les deux gestes d’examen qui modifient le plus la décision initiale.')
 + src(BSG19))

C.a(7, 'Urgence : réanimer avant de localiser', alert(
 'Le médecin évalue immédiatement l’hémodynamique. En cas d’instabilité, il remplit d’abord par des cristalloïdes (ESGE 2021). La transfusion est <b>restrictive</b> : sans maladie cardiovasculaire, on transfuse sous 70 g/L et on vise 70 à 90 g/L ; en cas de maladie cardiovasculaire aiguë ou chronique, on transfuse sous 80 g/L et on vise au moins 100 g/L (ESGE 2021). Dans l’hémorragie variqueuse, Baveno VII vise 70 à 80 g/L, car une transfusion libérale augmente la pression portale. Le patient qui vomit du sang avec une conscience altérée est intubé avant l’endoscopie (Baveno VII, énoncé 6.3).')
 + P('La ' + w('k92-transfusion', 'stratégie restrictive (pourquoi moins de sang protège)') + ' est l’un des acquis majeurs : dans les essais repris par l’ESGE, elle réduisait la mortalité par rapport à une stratégie libérale. Les ' + w('k92-antithrombotiques', 'antithrombotiques (arrêter, maintenir, antagoniser)') + ' sont gérés dès l’admission : l’aspirine de prévention secondaire n’est pas interrompue ; l’antivitamine K est suspendue et, en cas d’instabilité, antagonisée par vitamine K à faible dose et concentré de complexe prothrombinique, sans retarder l’endoscopie.',
 'L’ESGE ne recommande ni l’acide tranexamique ni la transfusion systématique de plaquettes chez le patient sous antiagrégant. Baveno VII déconseille le plasma frais congelé dans l’hémorragie variqueuse : il ne corrige pas l’hémostase et aggrave la surcharge volémique.')
 + key('Pendant la première heure, le médecin remplit, transfuse peu, protège les voies aériennes et ne donne pas d’acide tranexamique.')
 + C.pareto('pareto-k92-urgence', 'Reconnaître et réanimer', ['k92-1', 'k92-3', 'k92-5', 'k92-6', 'k92-7'],
     ['Une hématémèse ou un méléna signent le plus souvent une source haute, et une hématochézie avec choc impose d’exclure une source haute.',
      'L’hémoglobine initiale rassure à tort, car l’hémodilution n’a pas encore eu lieu ; la fréquence cardiaque, la pression et l’indice de choc jugent la perte.',
      'Le médecin demande toujours si le patient prend des antithrombotiques ou des AINS et s’il a une cirrhose, car ces trois réponses changent la conduite.',
      'On transfuse sous 70 g/L, ou sous 80 g/L en cas de maladie cardiovasculaire, et l’on vise 70 à 80 g/L dans l’hémorragie variqueuse.',
      'On ne donne pas d’acide tranexamique, ni de plasma frais congelé dans l’hémorragie variqueuse.'])
 + src(ESGE21, BAV7))

C.a(8, 'Stratifier le risque', P(
 'Le ' + w('k92-gbs', 'score de Glasgow-Blatchford (ce qu’il mesure)') + ' est recommandé par l’ESGE avant l’endoscopie. Il additionne des points pour l’urée, l’hémoglobine, la pression systolique, la fréquence cardiaque, le méléna, la syncope, l’hépatopathie et l’insuffisance cardiaque. Un score ≤ 1 identifie un patient à très faible risque de récidive, de décès à 30 jours ou de geste hospitalier : il peut être pris en charge en ambulatoire avec une endoscopie ambulatoire (recommandation forte).',
 'Pour l’hémorragie basse stable, la BSG propose le ' + w('k92-oakland', 'score d’Oakland (sortie sûre)') + ' : un score ≤ 8 points correspond à 95 % de probabilité de sortie sûre ; le patient sans autre motif d’hospitalisation peut sortir avec une exploration ambulatoire rapide. Chez le cirrhotique, la gravité se juge par le ' + w('k92-child', 'score de Child-Pugh et le MELD (réserve hépatique)') + '.')
 + quiz('Un homme de 40 ans a eu un méléna unique. Fréquence cardiaque 78/min, pression 132 mmHg, hémoglobine normale, urée normale, aucun antécédent. Son score de Glasgow-Blatchford vaut 1. Quelle conduite ?',
   [('Hospitalisation et endoscopie dans les 12 heures', False), ('Prise en charge ambulatoire avec endoscopie ambulatoire', True), ('Angio-tomodensitométrie immédiate', False)],
   'Un score ≤ 1 identifie un très faible risque ; l’ESGE recommande une prise en charge ambulatoire avec endoscopie ambulatoire. Le méléna lui-même vaut des points ; c’est pourquoi le score atteint 1 et non 0.')
 + key('Un score de Glasgow-Blatchford ≤ 1 permet une prise en charge ambulatoire. Un score d’Oakland ≤ 8 définit une hémorragie basse mineure. Chez le cirrhotique, le Child-Pugh et le MELD mesurent la gravité.')
 + src(ESGE21, BSG19))

C.a(9, 'Hémorragie haute non variqueuse : endoscopie et traitement', P(
 'Après réanimation, l’ESGE recommande une endoscopie <b>précoce, dans les 24 heures</b>. Une endoscopie <b>urgente (≤ 12 heures)</b> n’améliore pas le pronostic par rapport à l’endoscopie précoce et n’est pas recommandée de principe. Une ' + w('k92-erythromycine', 'perfusion d’érythromycine (vider l’estomac avant l’endoscopie)') + ' est recommandée avant l’endoscopie chez les patients sélectionnés avec un saignement grave ou actif. Un ' + w('k92-ipp-caillot', 'IPP intraveineux à forte dose') + ' peut être envisagé avant l’endoscopie, sans jamais la retarder.',
 'L’endoscopiste décrit l’ulcère selon la ' + w('k92-forrest', 'classification de Forrest (risque de récidive)') + '. Les ulcères Ia (jet), Ib (suintement) et IIa (vaisseau visible) reçoivent une hémostase endoscopique. Pour un saignement actif, l’ESGE recommande l’injection d’adrénaline <b>associée</b> à une seconde méthode, thermique de contact ou mécanique ; l’adrénaline seule est insuffisante. Le caillot adhérent (IIb) peut être retiré pour traiter la lésion sous-jacente. La tache pigmentée (IIc) et le fond propre (III) ne sont pas traités.')
 + C.img('k92_ulcere_gastrique_jet.gif', 'Vue endoscopique d’un ulcère gastrique recouvert de sang, d’où part un jet artériel pulsatile signalé par une flèche ; un cathéter d’injection est visible à gauche.', 'Ulcère gastrique avec saignement en jet, stade Forrest Ia : stigmate à très haut risque, qui impose une hémostase endoscopique immédiate (ESGE 2021).', credit({'auteur': 'Jeremias', 'licence': 'CC BY-SA 3.0', 'url': 'https://commons.wikimedia.org/wiki/File:Bleeding_gastric_ulcer.png'}))
 + P('Après hémostase, ou devant un caillot adhérent non traité, l’IPP est donné à forte dose pendant 72 heures : bolus puis perfusion continue, par exemple 80 mg puis 8 mg/heure, ou bolus intraveineux deux fois par jour, ou forme orale deux fois par jour (ESGE 2021). Une seconde endoscopie systématique n’est pas recommandée. En cas de ' + w('k92-recidive', 'récidive (nouvelle endoscopie, embolisation, chirurgie)') + ', l’endoscopie est répétée ; en cas d’échec, l’embolisation artérielle est envisagée avant la chirurgie.')
 + key('L’endoscopie se fait dans les 24 heures, et les ulcères Forrest Ia, Ib et IIa sont traités par deux méthodes. Ensuite, l’IPP est donné à forte dose pendant 72 heures. En cas de récidive, on refait l’endoscopie, puis on envisage l’embolisation.')
 + src(ESGE21))

C.a(10, 'Hémorragie variqueuse', alert(
 'Dès la suspicion et avant l’endoscopie, le médecin débute un ' + w('k92-vasoactifs', 'médicament vasoactif (terlipressine, somatostatine, octréotide)') + ' et le poursuit 2 à 5 jours, car il baisse la pression portale. De plus, il prescrit une ' + w('k92-antibioprophylaxie', 'antibioprophylaxie (ceftriaxone 1 g/24 h)') + ' dès l’admission, transfuse pour viser 70 à 80 g/L et fait admettre le patient en soins intensifs ou intermédiaires (Baveno VII).', 'Cirrhotique qui saigne.')
 + P('L’endoscopie est réalisée <b>dans les 12 heures</b> après réanimation, plus tôt si le patient reste instable (Baveno VII, énoncé 6.17). La ' + w('k92-ligature', 'ligature élastique (étrangler la varice)') + ' est le traitement endoscopique de choix des varices œsophagiennes. Les varices gastriques isolées et les varices œsogastriques de type 2 sont traitées par colle tissulaire (cyanoacrylate).',
 'Chez le patient à haut risque, une ' + w('k92-tips', 'dérivation portosystémique intrahépatique transjugulaire précoce (TIPS préemptif)') + ' dans les 72 heures, idéalement en moins de 24 heures, est indiquée : Child-Pugh C de moins de 14 points, ou Child-Pugh B au-delà de 7 points avec saignement actif à l’endoscopie, ou gradient de pression veineuse hépatique supérieur à 20 mmHg. En cas d’hémorragie réfractaire, un ballon de tamponnement ou une prothèse métallique œsophagienne sert de pont vers un TIPS de sauvetage.')
 + C.img('k92_ligature_varices.gif', 'Illustration anatomique : varices de l’œsophage distal et mise en place d’un anneau élastique par endoscopie.', 'Varices œsophagiennes et ligature élastique endoscopique.', credit({'auteur': 'Kel898', 'licence': 'CC BY-SA 4.0', 'url': 'https://commons.wikimedia.org/wiki/File:Endoscopic_Banding_for_Esophageal_Varices.png'}))
 + P('Le lactulose, par voie orale ou en lavement, évacue le sang du tube digestif et prévient l’encéphalopathie (énoncé 6.33). L’IPP débuté avant l’endoscopie est arrêté après le geste, sauf indication stricte (énoncé 6.12). Chaque patient bénéficie d’une imagerie en coupe pour exclure une thrombose portale ou un carcinome hépatocellulaire (énoncé 6.26).')
 + trap('Il ne faut pas corriger l’INR par du plasma frais congelé, car l’INR ne reflète pas l’hémostase du cirrhotique et le plasma augmente la pression portale (Baveno VII, énoncés 6.35 et 6.36).')
 + key('Le cirrhotique qui saigne reçoit un vasoactif, de la ceftriaxone et une transfusion prudente, puis une endoscopie avec ligature dans les 12 heures. S’il est à haut risque, il reçoit un TIPS préemptif.')
 + src(BAV7, ESGE22, EASL18))

C.a(11, 'Hémorragie basse', P(
 'La BSG classe d’abord le patient comme stable ou instable, par l’indice de choc. Le patient <b>instable</b> (indice > 1 après réanimation) bénéficie d’une ' + w('k92-angiotdm', 'angio-tomodensitométrie (localiser une extravasation)') + ' : c’est la manière la plus rapide de localiser le saignement. Si elle ne montre rien, une endoscopie haute est faite immédiatement. Une angiographie avec embolisation suit une angio-tomodensitométrie positive, dans les 60 minutes dans les centres équipés.',
 'Le patient stable est classé par le score d’Oakland. L’hémorragie <b>mineure</b> (≤ 8 points) peut être explorée en ambulatoire, rapidement, car 6 % des hémorragies basses révèlent un cancer colorectal. L’hémorragie <b>majeure</b> est hospitalisée pour une coloscopie sur le premier programme disponible. Aucun patient ne va en laparotomie sans tentative de localisation, sauf circonstance exceptionnelle.')
 + quiz('Une femme de 82 ans a une hématochézie abondante. Après deux litres de cristalloïdes, sa fréquence cardiaque est de 118/min et sa pression systolique de 92 mmHg. Quel est le premier examen ?',
   [('Coloscopie après préparation colique', False), ('Angio-tomodensitométrie', True), ('Scintigraphie aux hématies marquées', False)],
   'L’indice de choc vaut environ 1,3 : la patiente est instable. La BSG recommande l’angio-tomodensitométrie, puis une endoscopie haute immédiate si elle ne montre pas la source.')
 + key('Le patient instable a une angio-tomodensitométrie, puis une gastroscopie si elle est négative. Le patient stable avec une hémorragie majeure a une coloscopie à l’hôpital, alors que l’hémorragie mineure s’explore rapidement en ambulatoire.')
 + src(BSG19))

C.a(12, 'Antithrombotiques : reprendre au bon moment', P(
 'L’arrêt prolongé d’un antithrombotique protège du saignement mais expose à la thrombose. L’ESGE et la BSG proposent donc des délais. L’' + w('k92-antithrombotiques', 'aspirine de prévention secondaire') + ' n’est pas interrompue ; si elle l’a été, elle reprend dès que possible, de préférence dans les 3 à 5 jours. L’aspirine de prévention primaire est interrompue et sa raison réévaluée.',
 'Sous double antiagrégation, l’aspirine est maintenue ; le second antiagrégant est suspendu puis repris de préférence dans les 5 jours, après avis cardiologique. L’anticoagulation reprend dès que le saignement est contrôlé, de préférence dans les 7 jours ou peu après, selon le risque thromboembolique ; l’action rapide des anticoagulants oraux directs est prise en compte. Un IPP est associé chez le patient qui reste sous double antiagrégation ou sous anticoagulant après une hémorragie haute.')
 + table(['Traitement', 'Pendant l’hémorragie', 'Reprise'], [
   ['Aspirine, prévention secondaire', 'Maintenue', 'Si interrompue : 3 à 5 jours'],
   ['Aspirine, prévention primaire', 'Interrompue', 'Après réévaluation de l’indication'],
   ['Second antiagrégant (inhibiteur de P2Y12)', 'Interrompu', 'De préférence dans les 5 jours, avis cardiologique'],
   ['Antivitamine K', 'Suspendue ; antagonisée si instabilité', 'Vers 7 jours selon le risque thrombotique'],
   ['Anticoagulant oral direct', 'Suspendu', 'Vers 7 jours ; action rapide à anticiper']])
 + P('La lecture se fait ligne par ligne, en partant de l’indication. Par exemple, le patient de 68 ans sous aspirine après infarctus garde son aspirine pendant l’épisode ; s’il recevait aussi du clopidogrel pour un stent récent, ce dernier serait suspendu brièvement et repris dans les 5 jours après discussion avec le cardiologue.')
 + key('L’indication décide : la prévention secondaire n’est pas arrêtée, la prévention primaire l’est.')
 + src(ESGE21, BSG19))

C.a(13, 'Suivi et prévention de la récidive', P(
 'Après un ulcère hémorragique, l’ESGE recommande de rechercher ' + w('k92-hp', 'Helicobacter pylori (éradiquer pour prévenir la récidive)') + ' dès l’endoscopie initiale, de traiter s’il est présent, de répéter le test s’il est négatif dans l’épisode aigu et de documenter l’éradication. Les AINS sont arrêtés ou, s’ils sont indispensables, associés à un IPP.',
 'Après une hémorragie variqueuse, la prophylaxie secondaire associe des ligatures répétées toutes les 1 à 4 semaines jusqu’à éradication et un bêtabloquant non sélectif, propranolol ou carvédilol (ESGE 2022). Le patient qui a présenté une hémorragie basse diverticulaire reçoit une information sur les médicaments à éviter et sur la conduite en cas de récidive.')
 + key('Après un ulcère, on recherche, traite et contrôle Helicobacter pylori. Après des varices, on répète les ligatures et on donne un bêtabloquant non sélectif.')
 + src(ESGE21, ESGE22))

C.a(14, 'Situations particulières', P(
 '<b>Pendant la grossesse</b>, la terlipressine est contre-indiquée pendant la grossesse selon l’information professionnelle suisse ; elle n’est envisageable qu’en indication vitale, après échec du traitement endoscopique, en raison du risque de contractions utérines et d’avortement. <b>Chez le sujet âgé</b>, l’hémorragie basse touche surtout des patients âgés et polymédiqués ; la mortalité reflète les comorbidités. La tachycardie peut manquer sous bêtabloquant. <b>En cas d’insuffisance rénale</b>, les demi-vies des anticoagulants oraux directs s’allongent, surtout pour le dabigatran ; l’idarucizumab est l’antidote spécifique du dabigatran (BSG 2019).',
 '<b>Reprenons le cas.</b> L’homme de 68 ans du début a un score de Glasgow-Blatchford élevé. Il reçoit des cristalloïdes, garde son aspirine, n’est pas transfusé à 92 g/L car il est coronarien mais au-dessus de 80 g/L, et bénéficie d’une gastroscopie à 14 heures. Un ulcère duodénal Forrest IIa est traité par adrénaline et clip. Ensuite, il reçoit un IPP à forte dose pendant 72 heures, et Helicobacter pylori est recherché sur des biopsies.')
 + key('La grossesse contre-indique la terlipressine sauf indication vitale ; chez le sujet âgé, le terrain fait le pronostic.')
 + src(FI('Glypressine®'), BSG19, ESGE21))

C.a(15, 'Critères formels du diagnostic et paramètres clés', alert(
 '<p>Une <b>hémorragie digestive haute</b> se manifeste par une hématémèse ou un méléna, et l’endoscopie confirme une source en amont de l’angle duodéno-jéjunal. Un <b>ulcère à haut risque</b> porte un stigmate de Forrest Ia, Ib ou IIa. Une <b>hémorragie variqueuse</b> correspond au saignement actif d’une varice, ou à des varices sans autre source chez un cirrhotique qui saigne. On parle d’<b>échec à cinq jours</b> quand le saignement n’est pas contrôlé ou récidive dans les cinq premiers jours (Baveno VII, énoncé 6.14). Enfin, une <b>hémorragie basse</b> est <b>instable</b> quand l’indice de choc reste > 1 après réanimation (BSG).</p>', 'Critères formels.')
 + '<div class="key"><b>Paramètres clés.</b> Un score de Glasgow-Blatchford ≤ 1 autorise l’ambulatoire, et un score d’Oakland ≤ 8 définit une hémorragie basse mineure. On transfuse à 70 g/L, ou à 80 g/L en cas de maladie cardiovasculaire, et l’on vise 70 à 80 g/L en cas de varices. L’endoscopie se fait dans les 24 h sans varices et dans les 12 h avec varices. Après hémostase, l’IPP se donne à 80 mg puis 8 mg/h pendant 72 h. Le vasoactif dure 2 à 5 jours, la ceftriaxone se donne à 1 g/24 h, et le TIPS préemptif se pose dans les 72 h chez le patient à haut risque.</div>'
 + C.pareto('pareto-k92-traitement', 'Endoscopie, traitement et suivi', ['k92-8', 'k92-9', 'k92-10', 'k92-11', 'k92-12', 'k92-13'],
     ['Un score de Glasgow-Blatchford ≤ 1 autorise l’ambulatoire, et un score d’Oakland ≤ 8 définit une hémorragie basse mineure.',
      'Sans varices, l’endoscopie se fait dans les 24 h, les ulcères Forrest Ia, Ib et IIa sont traités par deux méthodes, puis l’IPP est donné à forte dose pendant 72 h.',
      'Avec varices, le vasoactif et la ceftriaxone sont donnés d’emblée, l’endoscopie avec ligature se fait dans les 12 h, et le TIPS préemptif se discute si le risque est élevé.',
      'Une hémorragie basse instable impose une angio-tomodensitométrie, puis une gastroscopie si elle est négative.',
      'L’aspirine de prévention secondaire est maintenue, et l’anticoagulant reprend vers 7 jours.',
      'Après un ulcère, Helicobacter pylori est recherché, traité et contrôlé.'])
 + src(ESGE21, ESGE22, BAV7, BSG19, EASL18))

# ---------------- Onglet Examens
C.e(1, 'Hiérarchie des examens', P(
 'Chaque examen répond à une question précise. La biologie évalue la perte et le terrain ; l’endoscopie localise et traite ; l’imagerie localise quand l’endoscopie ne peut pas être faite ou a échoué.')
 + table(['Question', 'Examen', 'Statut'], [
   ['Quelle perte, quel terrain ?', w('k92-bio', 'Hémoglobine, urée, créatinine, groupe sanguin, coagulation, fonction hépatique'), 'Indiqué chez tous'],
   ['Où saigne une hémorragie haute ?', w('k92-oeso', 'Œsogastroduodénoscopie (gold standard)'), 'Indiquée, ≤ 24 h ou ≤ 12 h si varices'],
   ['Où saigne un patient instable avec hématochézie ?', w('k92-angiotdm', 'Angio-tomodensitométrie'), 'Indiquée en premier'],
   ['Où saigne une hémorragie basse stable majeure ?', 'Coloscopie après préparation', 'Indiquée, premier programme disponible'],
   ['Endoscopies haute et basse négatives ?', w('k92-capsule', 'Vidéocapsule du grêle'), 'Conditionnelle'],
   ['Ulcère hémorragique : quelle cause ?', w('k92-hp', 'Recherche d’Helicobacter pylori'), 'Indiquée']])
 + P('Le tableau se lit de haut en bas : l’endoscopie haute est le <b>gold standard</b> de l’hémorragie haute, car elle localise, classe et traite dans le même temps. La sonde nasogastrique n’est pas recommandée de routine (BSG) : elle n’améliore ni le diagnostic ni le pronostic.')
 + key('L’œsogastroduodénoscopie est l’examen de référence de l’hémorragie haute ; l’angio-tomodensitométrie est celui du patient instable avec hématochézie.')
 + src(ESGE21, BSG19))

C.e(2, 'Interpréter la biologie', P(
 'L’hémoglobine initiale sous-estime la perte aiguë, car le plasma et les globules sont perdus ensemble ; elle baisse ensuite avec le remplissage et le recrutement de liquide interstitiel. Les seuils de transfusion s’appliquent donc à des mesures répétées. Une ' + w('k92-uree', 'urée élevée') + ' avec une créatinine peu modifiée oriente vers une source haute ; la BSG cite un rapport urée/créatinine élevé parmi les indices d’origine haute.',
 'Chez le cirrhotique, l’INR et le temps de céphaline activée ne mesurent pas le risque hémorragique (Baveno VII, énoncé 6.35). La numération plaquettaire et le fibrinogène ne sont pas corrélés à l’échec de l’hémostase variqueuse (énoncé 6.37). Leur correction n’est discutée qu’au cas par cas, en cas d’échec du contrôle du saignement.')
 + trap('Il ne faut pas transfuser un patient stable parce que son hémoglobine est passée de 105 à 88 g/L sans signe d’instabilité, car le seuil de l’ESGE est ≤ 70 g/L sans maladie cardiovasculaire.', 'Erreur fréquente')
 + quiz('Un cirrhotique Child-Pugh B saigne de varices. INR 1,9, plaquettes 62 G/L. Faut-il transfuser du plasma frais congelé avant la ligature ?',
   [('Oui, pour ramener l’INR sous 1,5', False), ('Non, l’INR ne reflète pas l’hémostase et le plasma élève la pression portale', True)],
   'Baveno VII déconseille le plasma frais congelé dans l’hémorragie variqueuse ; la priorité est d’abaisser la pression portale et de ligaturer.')
 + key('Les seuils transfusionnels s’appliquent à des mesures répétées ; chez le cirrhotique, l’INR n’est pas un guide transfusionnel.')
 + src(ESGE21, BSG19, BAV7))

C.e(3, 'Endoscopie et imagerie : ce qu’il faut lire', P(
 'Le compte rendu d’endoscopie doit nommer la lésion, sa taille, son stigmate de Forrest et le traitement réalisé. Un ulcère de plus de 2 cm, un vaisseau visible de plus de 2 mm ou un siège dans une zone artérielle à risque (artère gastroduodénale, artère gastrique gauche) justifient, selon l’ESGE, d’envisager un clip monté sur capuchon en première intention.',
 'L’angio-tomodensitométrie détecte une extravasation pour des débits de l’ordre de 0,3 à 1,0 mL/min dans les études expérimentales citées par la BSG ; sa sensibilité rapportée est de 79 à 95 %. La vidéocapsule a un rendement de 50 à 72 % dans l’hémorragie occulte manifeste et doit être faite tôt : le rendement peut chuter sous 50 % au-delà de 3 jours (BSG 2019).')
 + quiz('Une angio-tomodensitométrie montre une extravasation dans le côlon droit chez un patient instable. Quelle est l’étape suivante ?',
   [('Coloscopie après préparation de 4 litres', False), ('Angiographie avec embolisation le plus vite possible', True), ('Laparotomie exploratrice', False)],
   'La BSG recommande l’angiographie avec embolisation dès que possible après une angio-tomodensitométrie positive, dans les 60 minutes dans un centre équipé.')
 + quiz('Après une ligature réussie de varices œsophagiennes chez un patient Child-Pugh C à 12 points, que faut-il discuter ?',
   [('Une seconde endoscopie systématique à 24 heures', False), ('Un TIPS préemptif dans les 72 heures', True), ('L’arrêt immédiat du vasoactif', False)],
   'Child-Pugh C de moins de 14 points est un critère de TIPS préemptif dans les 72 heures, idéalement en moins de 24 heures (Baveno VII).')
 + key('La taille de l’ulcère, le vaisseau, le siège et le stigmate de Forrest guident l’hémostase. Ensuite, l’imagerie et la capsule localisent le saignement quand l’endoscopie ne suffit pas.')
 + C.pareto('pareto-k92-examens', 'Examens', ['k92-e-1', 'k92-e-2', 'k92-e-3'],
     ['L’œsogastroduodénoscopie est l’examen de référence de l’hémorragie haute, car elle localise et traite.',
      'L’angio-tomodensitométrie est le premier examen du patient instable avec hématochézie, et une embolisation suit si elle est positive.',
      'L’hémoglobine initiale trompe, alors qu’une urée élevée oriente vers une source haute.',
      'Chez le cirrhotique, l’INR et les plaquettes ne guident pas la transfusion.',
      'La capsule du grêle se fait tôt si les endoscopies sont négatives, car son rendement baisse avec le délai.'])
 + src(ESGE21, BSG19, BAV7))

# ---------------- Onglet Sciences
C.s('anat', 'Anatomie', 'Anatomie : l’angle duodéno-jéjunal et les artères à risque', P(
 'L’angle duodéno-jéjunal, maintenu par le muscle suspenseur du duodénum, sépare par convention le tube digestif haut et bas. La face postérieure du bulbe duodénal est croisée par l’artère gastroduodénale ; un ulcère bulbaire postérieur peut l’éroder et provoquer une hémorragie massive. La petite courbure gastrique reçoit l’artère gastrique gauche. Ces deux territoires sont nommés par l’ESGE comme zones vasculaires à haut risque.',
 'Le système porte draine le tube digestif vers le foie. Quand la pression portale augmente, les anastomoses portosystémiques de la jonction œsogastrique se dilatent : la veine gastrique gauche communique avec les veines œsophagiennes, tributaires du système azygos. Ces veines sous-muqueuses, peu soutenues, deviennent les varices.')
 + key('Un ulcère bulbaire postérieur saigne par l’artère gastroduodénale ; une varice œsophagienne est une anastomose portosystémique dilatée.', 'Science → clinique.')
 + key('Le siège de l’ulcère sur l’endoscopie prédit le risque et oriente vers une méthode d’hémostase plus robuste.', 'Science → traitement.'))
C.s('histo', 'Histologie', 'Histologie : érosion, ulcère et vaisseau visible', P(
 'L’érosion ne dépasse pas la musculaire muqueuse ; elle saigne peu. L’ulcère traverse la musculaire muqueuse et atteint la sous-muqueuse, où cheminent des artères de calibre plus important. Le « vaisseau visible » de Forrest IIa correspond le plus souvent à un moignon artériel obturé par un caillot, dont la lyse provoque la récidive.',
 'Les biopsies réalisées lors de l’endoscopie initiale servent à rechercher Helicobacter pylori, ce que l’ESGE recommande dès l’épisode aigu ; la description histologique détaillée de l’ulcère est traitée dans le cours K25 — Ulcère de l’estomac.')
 + key('Plus l’ulcère est profond, plus l’artère érodée est grosse et plus le risque de récidive est élevé.', 'Science → examen.'))
C.s('phys', 'Physiologie', 'Physiologie : volémie, acide et pression portale', P(
 'La réponse à l’hypovolémie passe par le baroréflexe : tachycardie, vasoconstriction artériolaire et veineuse, puis activation du système rénine-angiotensine-aldostérone et de la vasopressine. Ces mécanismes expliquent qu’un patient jeune perde une part importante de sa volémie avant de devenir hypotendu.',
 'Le caillot formé sur une artère ulcérée est fragile en milieu acide : la pepsine le dégrade et l’agrégation plaquettaire est altérée à pH bas. Élever le pH intragastrique par un IPP à forte dose stabilise le caillot. Dans la cirrhose, la pression portale résulte du produit du débit portal et de la résistance ; les vasoactifs réduisent le débit splanchnique, la ligature supprime la varice, le TIPS supprime la résistance.')
 + key('Vasoactif, ligature et TIPS agissent chacun sur un terme différent de l’équation pression = débit × résistance.', 'Science → traitement.'))
C.s('biochim', 'Biochimie', 'Biochimie : pourquoi l’urée monte', P(
 'Le sang est riche en protéines. Digéré dans l’intestin grêle, il libère des acides aminés absorbés puis désaminés par le foie, qui produit de l’urée. À cela s’ajoute la baisse de la perfusion rénale. L’urée s’élève donc plus que la créatinine dans une hémorragie haute ; c’est pourquoi elle figure dans le score de Glasgow-Blatchford.',
 'La couleur noire du méléna vient de l’oxydation du fer de l’hème en milieu acide et de son transformation par la flore intestinale ; un saignement haut très rapide peut traverser le tube digestif sans avoir le temps de noircir.')
 + key('Une urée élevée avec une créatinine peu modifiée oriente vers une source haute.', 'Science → examen.'))

# ---------------- Onglet Pharmacologie
C.p(1, 'Stratégie et classes', P(
 'La pharmacologie de l’hémorragie digestive vise quatre cibles : stabiliser le caillot (IPP), abaisser la pression portale (vasoactifs), prévenir l’infection du cirrhotique (antibiotique) et améliorer la vision endoscopique (érythromycine). Elle comporte aussi la gestion des antithrombotiques.')
 + table(['Classe', 'Molécule disponible en Suisse', 'Place', 'Fenêtre'], [
   ['Inhibiteur de la pompe à protons intraveineux', 'Pantoprazole', 'Après hémostase d’un ulcère à haut risque ; avant l’endoscopie, sans la retarder', w('k92-d-ipp', 'Monographie')],
   ['Analogue de la vasopressine', 'Terlipressine (Glypressine®)', 'Hémorragie variqueuse, dès la suspicion', w('k92-d-terli', 'Monographie')],
   ['Analogue de la somatostatine', 'Octréotide (Sandostatine®)', 'Alternative vasoactive', w('k92-d-octreo', 'Monographie')],
   ['Céphalosporine de 3e génération', 'Ceftriaxone', 'Antibioprophylaxie du cirrhotique', w('k92-antibioprophylaxie', 'Indication')],
   ['Macrolide (effet prokinétique)', 'Érythromycine intraveineuse', 'Avant l’endoscopie, saignement grave', w('k92-erythromycine', 'Indication et risques')]])
 + P('Le tableau se lit par la colonne « Place » : aucun de ces médicaments ne remplace l’endoscopie, et chacun est lié à un type précis d’hémorragie.')
 + key('L’IPP traite l’ulcère, le vasoactif et la ceftriaxone traitent l’hémorragie variqueuse, et l’érythromycine prépare l’endoscopie.')
 + src(ESGE21, BAV7))

C.p(2, 'Doses et durées', P('Les doses ci-dessous proviennent des recommandations et des informations professionnelles suisses ; l’écart entre les deux est signalé.')
 + table(['Médicament', 'Dose', 'Durée', 'Source'], [
   ['Pantoprazole intraveineux', 'Bolus 80 mg puis 8 mg/heure, ou bolus deux fois par jour', '72 heures après hémostase', 'ESGE 2021 ; schéma hors de la posologie de l’information professionnelle suisse, qui prévoit 40 mg/jour par voie intraveineuse pour l’ulcère et mentionne 2 × 80 mg pour un contrôle rapide de la sécrétion acide'],
   ['Terlipressine', 'Plus de 50 kg : 1 à 2 mg intraveineux toutes les 4 à 6 heures ; moins de 50 kg : 1 mg toutes les 4 à 6 heures ; maximum 12 mg/jour pendant 36 heures, puis 6 mg/jour', 'Jusqu’à 5 jours', 'Information professionnelle suisse Glypressine®'],
   ['Octréotide', '0,025 mg/heure en perfusion intraveineuse continue', 'Au maximum 5 jours', 'Information professionnelle suisse Sandostatine®'],
   ['Ceftriaxone', '1 g/24 heures intraveineux', 'Durée de l’antibioprophylaxie selon le protocole local', 'Baveno VII, énoncé 6.9'],
   ['Érythromycine', '250 mg intraveineux, 30 à 120 minutes avant l’endoscopie', 'Dose unique', 'Baveno VII, énoncé 6.19 ; ESGE 2021 ; usage hors indication en Suisse']])
 + P('Exemple : un cirrhotique de 72 kg reçoit 2 mg de terlipressine toutes les 4 heures pendant 36 heures au plus, puis la dose est réduite ; la natrémie et l’ECG sont surveillés.')
 + key('Les doses du pantoprazole et de l’érythromycine dans l’hémorragie suivent les recommandations, au-delà du texte de l’information professionnelle suisse.')
 + src(ESGE21, BAV7, FI('Glypressine®'), FI('Sandostatine®'), FI('Pantoprazol Nycomed® i.v.')))

C.p(3, 'Interactions, surveillance et médicaments à éviter', alert(
 'La terlipressine allonge l’intervalle QT ; l’association à l’érythromycine, aux antiarythmiques de classe IA ou III ou aux antifongiques azolés exige la plus grande prudence. Elle provoque une hyponatrémie par effet antidiurétique, et des nécroses cutanées ont été rapportées. Elle est contre-indiquée en cas d’insuffisance coronaire ou d’événement ischémique dans les 3 derniers mois, et pendant la grossesse (information professionnelle suisse). L’érythromycine associée à la simvastatine augmente le risque de rhabdomyolyse (ESGE 2021).', 'Interactions dangereuses.')
 + P('La surveillance sous terlipressine comprend la pression artérielle, l’ECG ou la fréquence cardiaque, la saturation, la natrémie, la kaliémie et le bilan hydrique. Sous octréotide, la glycémie est surveillée : l’information professionnelle signale un risque de diabète ou de modification des besoins en insuline après une hémorragie variqueuse.',
 'Plusieurs médicaments sont à éviter : l’acide tranexamique (non recommandé par l’ESGE dans l’hémorragie haute non variqueuse ni par Baveno VII dans l’hémorragie variqueuse) ; la somatostatine et l’octréotide dans l’hémorragie non variqueuse, où l’ESGE ne les recommande pas faute de bénéfice démontré ; le facteur VII activé recombinant dans l’hémorragie variqueuse ; le plasma frais congelé pour « corriger » l’INR du cirrhotique ; les AINS après la sortie.')
 + key('Sous terlipressine, on surveille le QT, la natrémie et les signes d’ischémie. On ne donne pas d’acide tranexamique.')
 + C.pareto('pareto-k92-pharma', 'Pharmacologie', ['k92-p-1', 'k92-p-2', 'k92-p-3'],
     ['Après hémostase, l’IPP se donne à 80 mg puis 8 mg/h pendant 72 h (ESGE).',
      'La terlipressine se donne à 1 à 2 mg toutes les 4 à 6 h pendant 5 jours au plus, sous surveillance du QT, de la natrémie et de l’ischémie.',
      'L’octréotide se donne à 0,025 mg/h pendant 5 jours au plus, sous surveillance de la glycémie.',
      'Le cirrhotique qui saigne reçoit de la ceftriaxone 1 g/24 h.',
      'L’érythromycine 250 mg se donne avant l’endoscopie, et l’acide tranexamique ne se donne pas.'])
 + src(FI('Glypressine®'), FI('Sandostatine®'), ESGE21, BAV7))

# ---------------- Fenêtres
L = lab
C.pop('k92-haute-basse', 'Hémorragie haute ou basse', L(('Définition', 'La limite est l’angle duodéno-jéjunal. Une source en amont est haute ; une source en aval est basse.'), ('Mécanisme', 'Le sang issu d’une source haute est digéré pendant son transit ; il devient noir. Un débit très élevé raccourcit le transit et donne du sang rouge.'), ('Conséquence pratique', 'Une hématochézie avec choc impose d’exclure une source haute ; la BSG cite 11 à 15 % de sources hautes chez des patients initialement crus en hémorragie basse.')) + src(BSG19))
C.pop('k92-cirrhose-contexte', 'Le cirrhotique qui saigne', L(('Pourquoi la conduite change', 'L’hémorragie est le plus souvent liée à l’hypertension portale. C’est pourquoi le traitement vise la pression portale par un vasoactif, une ligature et, si nécessaire, un TIPS.'), ('Mesures spécifiques', 'Le cirrhotique reçoit une antibioprophylaxie dès l’admission, une transfusion qui vise 70 à 80 g/L, une endoscopie dans les 12 heures et du lactulose contre l’encéphalopathie.'), ('Piège', 'Un cirrhotique peut aussi saigner d’un ulcère ; le traitement vasoactif est débuté sur la suspicion et adapté après l’endoscopie.')) + src(BAV7))
C.pop('k92-ulcere-mecanisme', 'Ulcère : rupture de la barrière muqueuse', L(('Normal', 'Mucus, bicarbonates, renouvellement épithélial et flux sanguin protègent la muqueuse contre l’acide et la pepsine.'), ('Perturbation', 'Helicobacter pylori et les AINS affaiblissent ces défenses ; l’agression acidopeptique creuse la paroi.'), ('Conséquence', 'Quand l’ulcère érode une artère sous-muqueuse, le saignement peut être artériel et récidiver.')) + src(ESGE21))
C.pop('k92-ipp-caillot', 'Inhibition acide et stabilité du caillot', L(('Mécanisme', 'Un pH bas altère l’agrégation plaquettaire et favorise la dégradation du caillot par la pepsine. L’IPP bloque la pompe H⁺/K⁺-ATPase et élève le pH.'), ('Preuve et place', 'L’ESGE recommande un IPP à forte dose pendant 72 heures après hémostase endoscopique ou devant un caillot adhérent non traité (recommandation forte, preuve de haute qualité). Avant l’endoscopie, il peut faire régresser les stigmates mais ne doit pas retarder le geste.'), ('Limite', 'Dans l’hémorragie variqueuse, l’IPP débuté avant l’endoscopie est arrêté après le geste, sauf indication stricte (Baveno VII).')) + src(ESGE21, BAV7))
C.pop('k92-varices', 'Varices œsophagiennes', L(('Définition', 'Les varices œsophagiennes sont des veines sous-muqueuses dilatées de l’œsophage distal ; elles forment des collatérales entre le système porte et le système cave supérieur.'), ('Mécanisme', 'L’hypertension portale cliniquement significative est définie par un gradient de pression veineuse hépatique supérieur à 10 mmHg ; elle ouvre ces collatérales.'), ('Prévention primaire', 'L’ESGE 2022 recommande un bêtabloquant non sélectif, de préférence le carvédilol, chez le patient compensé avec hypertension portale cliniquement significative ; la ligature est l’alternative si le bêtabloquant est impossible.')) + C.img('k92_ligature_varices.gif', 'Illustration anatomique de varices de l’œsophage distal et de la pose d’un anneau élastique par endoscopie.', 'Varices œsophagiennes et ligature élastique.', credit({'auteur': 'Kel898', 'licence': 'CC BY-SA 4.0', 'url': 'https://commons.wikimedia.org/wiki/File:Endoscopic_Banding_for_Esophageal_Varices.png'})) + src(ESGE22, BAV7))
C.pop('k92-uree', 'Urée et hémorragie haute', L(('Mécanisme', 'Les protéines du sang sont digérées puis transformées en urée par le foie ; l’hypoperfusion rénale s’y ajoute.'), ('Valeur', 'L’urée est une composante du score de Glasgow-Blatchford ; un rapport urée/créatinine élevé est cité par la BSG comme indice d’origine haute.'), ('Piège', 'Une insuffisance rénale préexistante élève aussi l’urée : l’interprétation tient compte de la créatinine antérieure.')) + src(BSG19))
C.pop('k92-ains-aspirine', 'AINS et aspirine', L(('Mécanisme', 'L’inhibition de la cyclo-oxygénase réduit les prostaglandines muqueuses protectrices ; l’aspirine inhibe en outre l’agrégation plaquettaire de façon irréversible pour la durée de vie des plaquettes (5 à 7 jours).'), ('Conséquence', 'Le risque d’ulcère et de saignement augmente ; l’association à un anticoagulant ou à un second antiagrégant l’accroît encore.'), ('Conduite', 'Arrêter l’AINS ; garder l’aspirine de prévention secondaire ; associer un IPP si l’antithrombotique est poursuivi.')) + src(BSG19, ESGE21))
C.pop('k92-hematemese', 'Hématémèse', L(('Définition', 'L’hématémèse est un vomissement de sang rouge ou de sang digéré, d’aspect « marc de café ».'), ('Valeur', 'Elle signe une source haute. Le sang rouge abondant suggère un saignement actif ; chez le cirrhotique, il fait évoquer des varices.'), ('Piège', 'Une épistaxis déglutie ou une hémoptysie peuvent simuler une hématémèse ; dans ce cas, le contexte et l’examen ORL ou pulmonaire tranchent.')))
C.pop('k92-melena', 'Méléna', L(('Définition', 'Le méléna désigne des selles noires, goudronneuses et fétides.'), ('Mécanisme', 'L’hème est oxydé et transformé pendant un transit de plusieurs heures.'), ('Piège', 'Le fer oral et le bismuth noircissent les selles sans leur donner l’aspect goudronneux ni l’odeur du méléna ; le toucher rectal permet de juger.')))
C.pop('k92-hemodynamique', 'Paramètres hémodynamiques et indice de choc', L(('Technique', 'Mesurer fréquence cardiaque et pression artérielle, répéter, calculer l’indice de choc (fréquence/pression systolique).'), ('Valeur', 'Un indice > 1 après réanimation définit l’hémorragie basse instable (BSG) et prédit une extravasation à l’angiographie.'), ('Piège', 'Bêtabloquants et stimulateurs cardiaques limitent la tachycardie ; l’indice doit alors être interprété avec prudence.')) + src(BSG19))
C.pop('k92-signes-cirrhose', 'Signes d’hépatopathie chronique', L(('Signes', 'Le médecin recherche une ascite, un ictère, des angiomes stellaires, une érythrose palmaire, une circulation veineuse collatérale abdominale et un astérixis.'), ('Conséquence', 'Leur présence fait traiter l’hémorragie comme variqueuse jusqu’à l’endoscopie ; ainsi, le vasoactif et l’antibiotique sont donnés sans attendre.')) + src(BAV7))
C.pop('k92-toucher-rectal', 'Toucher rectal', L(('Technique', 'Le médecin examine le canal anal, recherche une masse et observe le doigtier, qui montre du sang rouge, du sang noir ou des selles normales.'), ('Valeur', 'Il confirme un méléna ou une hématochézie et fait partie du score d’Oakland ; la BSG recommande aussi l’inspection de l’anus et du rectum chez tout patient.'), ('Piège', 'Il ne faut pas attribuer une hémorragie abondante à des hémorroïdes avant d’avoir exclu une autre cause.')) + src(BSG19))
C.pop('k92-transfusion', 'Transfusion restrictive', L(('Principe', 'Transfuser à un seuil bas évite l’excès de volume et, chez le cirrhotique, la hausse de la pression portale.'), ('Seuils', 'L’ESGE 2021 transfuse sous 70 g/L et vise 70 à 90 g/L sans maladie cardiovasculaire ; avec une maladie cardiovasculaire, elle transfuse sous 80 g/L et vise au moins 100 g/L. De son côté, Baveno VII vise 70 à 80 g/L dans l’hémorragie variqueuse, en tenant compte de l’âge, du cœur et du saignement en cours.'), ('Preuve', 'Dans les méta-analyses reprises par l’ESGE, la stratégie restrictive était associée à une mortalité plus basse (risque relatif 0,65).'), ('Limite', 'Le choc hémorragique massif relève d’un protocole de transfusion massive, et non de ces seuils.')) + src(ESGE21, BAV7))
C.pop('k92-antithrombotiques', 'Antithrombotiques pendant et après l’hémorragie', L(('Aspirine', 'En prévention secondaire, l’aspirine est maintenue ; si elle a été arrêtée, elle reprend en 3 à 5 jours. En prévention primaire, elle est interrompue et son indication est réévaluée.'), ('Double antiagrégation', 'L’aspirine est maintenue, et le second antiagrégant reprend de préférence dans les 5 jours, après avis cardiologique.'), ('Anticoagulants', 'L’antivitamine K est suspendue et, en cas d’instabilité, antagonisée par la vitamine K et le concentré de complexe prothrombinique. L’anticoagulant oral direct est suspendu, et son antidote (idarucizumab pour le dabigatran) se donne en cas d’hémorragie menaçante. L’anticoagulation reprend de préférence vers 7 jours selon le risque thromboembolique.'), ('Haut risque thrombotique', 'En cas de valve mécanique mitrale, de fibrillation atriale avec valve ou sténose mitrale, ou de thrombose veineuse de moins de 3 mois, la BSG propose une héparine de bas poids moléculaire vers 48 heures.')) + src(ESGE21, BSG19))
C.pop('k92-gbs', 'Score de Glasgow-Blatchford', L(('Composantes', 'Le score additionne l’urée, l’hémoglobine (selon le sexe), la pression systolique, la fréquence cardiaque, le méléna, la syncope, l’hépatopathie et l’insuffisance cardiaque. Il n’exige pas d’endoscopie.'), ('Valeur', 'Un score ≤ 1 identifie un très faible risque ; dans une cohorte internationale de 3012 patients, ce seuil prédisait la survie sans geste hospitalier avec une sensibilité de 98,6 % et une spécificité de 34,6 % (ESGE 2021).'), ('Limite', 'Sa spécificité est faible : il sert à faire sortir les patients à très bas risque, non à prédire la mortalité.')) + src(ESGE21, ('Blatchford O. et al., Lancet 2000;356:1318-1321', 'https://doi.org/10.1016/S0140-6736(00)02816-6')))
C.pop('k92-oakland', 'Score d’Oakland', L(('Composantes', 'Le score tient compte de l’âge, du sexe, d’une hospitalisation antérieure pour hémorragie basse, du toucher rectal, de la fréquence cardiaque, de la pression systolique et de l’hémoglobine.'), ('Valeur', 'Un score ≤ 8 points correspond à 95 % de probabilité de sortie sûre.'), ('Limite', 'Il a été validé au Royaume-Uni, mais il n’avait pas été testé dans d’autres populations au moment de la recommandation.')) + src(BSG19))
C.pop('k92-child', 'Child-Pugh et MELD', L(('Child-Pugh', 'Le score de Child-Pugh combine la bilirubine, l’albumine, le temps de prothrombine, l’ascite et l’encéphalopathie, et il classe les patients en A, B ou C.'), ('Valeur dans l’hémorragie', 'La classe C, le MELD et l’échec de l’hémostase primaire prédisent la mortalité à six semaines (Baveno VII, énoncé 6.15) ; la classe de Child-Pugh définit l’indication du TIPS préemptif.'), ('Limite', 'Au-delà de 14 points de Child-Pugh, ou avec un MELD > 30 et un lactate > 12 mmol/L, le TIPS peut être futile sauf transplantation proche (énoncé 6.31).')) + src(BAV7))
C.pop('k92-erythromycine', 'Érythromycine avant l’endoscopie', L(('Mécanisme', 'L’érythromycine est un agoniste des récepteurs de la motiline ; elle accélère donc la vidange gastrique et améliore la visibilité.'), ('Indication', 'L’ESGE 2021 la propose chez des patients sélectionnés avec un saignement grave ou actif. Baveno VII prescrit 250 mg par voie intraveineuse 30 à 120 minutes avant l’endoscopie, en l’absence d’allongement du QT.'), ('Risques', 'Elle allonge le QT et interagit avec la simvastatine, avec un risque de rhabdomyolyse. En Suisse, cet usage sort des indications anti-infectieuses de l’information professionnelle.')) + src(ESGE21, BAV7))
C.pop('k92-forrest', 'Classification de Forrest', L(('Stades', 'Le stade Ia correspond à un saignement en jet et le stade Ib à un suintement. Le stade IIa montre un vaisseau visible non hémorragique, le IIb un caillot adhérent et le IIc une tache pigmentée plane. Enfin, le stade III correspond à un fond propre.'), ('Conduite', 'Les stades Ia, Ib et IIa reçoivent une hémostase endoscopique. Pour le stade IIb, on envisage de retirer le caillot puis de traiter la lésion sous-jacente. Les stades IIc et III ne reçoivent pas d’hémostase, et une sortie accélérée est possible dans certains contextes.'), ('Méthode', 'Un saignement actif se traite par adrénaline associée à une seconde méthode, thermique de contact ou mécanique. Un vaisseau visible se traite par une méthode thermique, mécanique ou sclérosante, seule ou avec l’adrénaline.')) + C.img('k92_ulcere_gastrique_jet.gif', 'Vue endoscopique d’un ulcère gastrique d’où part un jet artériel pulsatile.', 'Ulcère Forrest Ia : le jet artériel impose une hémostase immédiate.', credit({'auteur': 'Jeremias', 'licence': 'CC BY-SA 3.0', 'url': 'https://commons.wikimedia.org/wiki/File:Bleeding_gastric_ulcer.png'})) + src(ESGE21))
C.pop('k92-recidive', 'Récidive après hémostase', L(('Définition', 'La récidive est un saignement qui survient après une hémostase endoscopique initialement réussie (ESGE).'), ('Conduite', 'On refait une endoscopie avec hémostase, éventuellement par clip monté sur capuchon. En cas d’échec, on recourt à l’embolisation artérielle, puis à la chirurgie si l’embolisation n’est pas disponible ou échoue.'), ('Piège', 'Une seconde endoscopie systématique sans signe de récidive n’est pas recommandée.')) + src(ESGE21))
C.pop('k92-vasoactifs', 'Médicaments vasoactifs', L(('Mécanisme', 'Ils réduisent le débit sanguin splanchnique et donc la pression portale.'), ('Place', 'On les débute dès la suspicion d’hémorragie variqueuse et on les poursuit 2 à 5 jours (Baveno VII, énoncé 6.5, preuve A).'), ('Choix en Suisse', 'On choisit la terlipressine (Glypressine®) ou l’octréotide (Sandostatine®) selon les informations professionnelles ; l’onglet Pharmacologie détaille les doses.')) + src(BAV7))
C.pop('k92-antibioprophylaxie', 'Antibioprophylaxie du cirrhotique', L(('Pourquoi', 'Les infections bactériennes sont fréquentes chez le cirrhotique qui saigne et aggravent le pronostic ; l’antibioprophylaxie fait partie intégrante du traitement (énoncé 6.7, preuve A).'), ('Schéma', 'Ceftriaxone 1 g/24 h intraveineux chez le patient avec cirrhose avancée, en accord avec l’écologie locale (énoncé 6.9).'), ('Limite', 'Chez le Child-Pugh A, le risque est très faible ; l’abstention n’est pas encore validée (énoncé 6.8).')) + src(BAV7))
C.pop('k92-ligature', 'Ligature élastique des varices', L(('Technique', 'Un anneau élastique est placé à la base de la varice aspirée dans un capuchon ; la varice thrombose puis s’élimine.'), ('Place', 'La ligature est le traitement endoscopique recommandé de l’hémorragie variqueuse œsophagienne aiguë (Baveno VII, preuve A) ; ensuite, on la répète toutes les 1 à 4 semaines jusqu’à éradication (ESGE 2022).'), ('Limite', 'Les varices gastriques isolées relèvent de la colle tissulaire.')) + C.img('k92_ligature_varices.gif', 'Illustration anatomique de varices de l’œsophage distal et de la pose d’un anneau élastique par endoscopie.', 'Varices œsophagiennes et ligature élastique.', credit({'auteur': 'Kel898', 'licence': 'CC BY-SA 4.0', 'url': 'https://commons.wikimedia.org/wiki/File:Endoscopic_Banding_for_Esophageal_Varices.png'})) + src(BAV7, ESGE22))
C.pop('k92-tips', 'TIPS préemptif', L(('Principe', 'Une endoprothèse couverte placée par voie jugulaire relie une branche portale à une veine sus-hépatique et supprime la résistance intrahépatique.'), ('Indication', 'Le TIPS se pose dans les 72 heures, idéalement en moins de 24 heures, chez le patient Child-Pugh C de moins de 14 points, Child-Pugh B de plus de 7 points avec saignement actif, ou avec un gradient supérieur à 20 mmHg (Baveno VII, énoncé 6.27). L’insuffisance hépatique aiguë sur chronique, l’encéphalopathie et l’hyperbilirubinémie à l’admission ne le contre-indiquent pas (énoncé 6.28).'), ('Sauvetage', 'En cas d’échec du traitement combiné, un TIPS couvert de sauvetage est la meilleure option (énoncé 6.30).')) + src(BAV7))
C.pop('k92-angiotdm', 'Angio-tomodensitométrie', L(('Principe', 'L’examen acquiert des images en phase artérielle, qui montrent une extravasation de produit de contraste.'), ('Valeur', 'Sa sensibilité rapportée est de 79 à 95 % et sa spécificité de 95 à 100 % ; de plus, elle explore tout le tube digestif sans préparation.'), ('Conséquence', 'Si elle est positive, une angiographie avec embolisation suit au plus vite. Si elle est négative chez un patient instable, une endoscopie haute se fait immédiatement.')) + src(BSG19))
C.pop('k92-hp', 'Helicobacter pylori après un ulcère hémorragique', L(('Conduite', 'On recherche la bactérie dès l’endoscopie initiale, on la traite si elle est présente, on refait le test s’il est négatif pendant l’épisode aigu, et on documente l’éradication (ESGE 2021, recommandations fortes).'), ('Pourquoi re-tester', 'Le saignement et l’IPP diminuent la sensibilité des tests pendant l’épisode aigu.'), ('Lien', 'Le schéma d’éradication est traité dans le cours K25 — Ulcère de l’estomac.')) + src(ESGE21))
C.pop('k92-bio', 'Biologie initiale', L(('Contenu', 'On dose l’hémoglobine, les plaquettes, l’urée, la créatinine et l’ionogramme ; on détermine le groupe sanguin et recherche des anticorps ; on mesure le temps de prothrombine, l’INR et les tests hépatiques, ainsi que le lactate en cas de choc.'), ('Usage', 'Elle alimente les scores, prépare la transfusion et identifie la cirrhose.')))
C.pop('k92-oeso', 'Œsogastroduodénoscopie', L(('Rôle', 'C’est l’examen de référence, car elle localise, classe selon Forrest, traite et permet les biopsies.'), ('Délai', 'Elle se fait dans les 24 heures après réanimation sans varices, et dans les 12 heures en cas de varices (Baveno VII).'), ('Organisation', 'L’ESGE et Baveno VII recommandent un endoscopiste d’astreinte et une équipe disponible 24 heures sur 24.')) + src(ESGE21, BAV7))
C.pop('k92-capsule', 'Vidéocapsule du grêle', L(('Indication', 'Elle s’indique devant une hémorragie manifeste lorsque des endoscopies haute et basse de bonne qualité sont négatives.'), ('Valeur', 'Son rendement est de 50 à 72 % ; il atteint 87 à 91,9 % dans les 48 heures, mais il tombe sous 50 % au-delà de 3 jours.'), ('Risque', 'La capsule reste bloquée chez environ 2 % des patients explorés pour un saignement du grêle.')) + src(BSG19))
C.pop('k92-d-ipp', 'Pantoprazole intraveineux', L(('Mécanisme', 'Le pantoprazole inhibe de façon irréversible la pompe H⁺/K⁺-ATPase de la cellule pariétale.'), ('Preuves', 'L’ESGE recommande le schéma forte dose après hémostase (recommandation forte, preuve de haute qualité).'), ('Posologie', 'L’ESGE donne 80 mg puis 8 mg/heure pendant 72 heures, ou un bolus deux fois par jour. L’information professionnelle suisse prévoit 40 mg/jour pour l’ulcère, et 2 × 80 mg lorsqu’un contrôle rapide de la sécrétion acide est nécessaire.'), ('Précautions', 'Une perfusion prolongée par la même canule expose à une thrombophlébite.')) + src(ESGE21, FI('Pantoprazol Nycomed® i.v.')))
C.pop('k92-d-terli', 'Terlipressine (Glypressine®)', L(('Mécanisme', 'La terlipressine est un précurseur de la lysine-vasopressine ; elle provoque une vasoconstriction splanchnique par les récepteurs V1.'), ('Indication suisse', 'Elle est indiquée dans le traitement aigu des varices œsophagiennes hémorragiques.'), ('Posologie', 'Au-delà de 50 kg, on donne 1 à 2 mg toutes les 4 à 6 heures, sans dépasser 12 mg/jour pendant 36 heures puis 6 mg/jour, et pendant 5 jours au plus.'), ('Contre-indications et surveillance', 'Elle est contre-indiquée en cas d’insuffisance coronaire, d’ischémie dans les 3 derniers mois et de grossesse. On surveille la pression, l’ECG, la saturation, la natrémie et la kaliémie, car elle expose à un QT long et à des nécroses cutanées.')) + src(FI('Glypressine®')))
C.pop('k92-d-octreo', 'Octréotide (Sandostatine®)', L(('Mécanisme', 'L’octréotide est un analogue de la somatostatine ; il réduit le débit splanchnique, mais l’information professionnelle précise que le mécanisme exact n’est pas établi.'), ('Indication suisse', 'Il est indiqué dans le traitement d’urgence des hémorragies de varices gastro-œsophagiennes du cirrhotique, en association à un traitement endoscopique.'), ('Posologie', 'On le perfuse à 0,025 mg/heure pendant 5 jours au plus ; une perfusion de 0,050 mg/h pendant 5 jours a été bien tolérée.'), ('Surveillance', 'On surveille la glycémie, car il peut provoquer un diabète ou modifier les besoins en insuline après une hémorragie variqueuse.')) + src(FI('Sandostatine®')))

from K92_liaisons import L as _LZ
from K92_termes import ajouter as _termes
_termes(C, ESGE21, ESGE22, BAV7, BSG19, EASL18, FI)
C.liaisons = _LZ
C.write()
