# Connecteurs logiques et transitions du cours K92 (règle linguistique du propriétaire, 09.10.2026).
L = {
 'k92-0': [['', 'Or', 'De son côté', 'Pourtant'], ['Pour y parvenir']],
 'k92-1': [['Avant de traiter, il faut nommer précisément ce que l’on observe.', 'De même', 'Enfin'], ['À partir de ces signes', 'Ainsi', 'Ensuite'], ['', 'En effet', 'Par exemple']],
 'k92-2': [['Ces définitions posées, la fréquence des causes oriente la démarche.', 'Quant à elle'], ['Cependant', 'Ainsi', 'Autrement dit', 'De même']],
 'k92-3': [['Pour comprendre ces chiffres, il faut suivre le saignement de la lésion jusqu’au choc.', 'Lorsque cette barrière cède', 'De plus'], ['Le mécanisme est différent dans la cirrhose.', 'Dès lors', 'Or'], ['Quelle que soit la cause', 'Au début', 'C’est pourquoi']],
 'k92-4': [['De ces mécanismes découle la recherche de la cause.', 'C’est pourquoi'], ['Toutefois', 'Enfin']],
 'k92-5': [['La recherche de la cause commence par l’interrogatoire.', 'Ensuite'], ['Par ailleurs', 'En effet']],
 'k92-6': [['L’examen physique prolonge l’interrogatoire.', 'À cet égard', '']],
 'k92-7': [['Ces premiers éléments recueillis, la réanimation passe avant toute localisation.', 'Ainsi', 'En outre', 'En revanche', 'Enfin'], ['Sur le plan des preuves', 'Parallèlement'], ['À l’inverse', 'De même']],
 'k92-8': [['Une fois le patient stabilisé, il faut estimer son risque.', 'Concrètement', 'Ainsi'], ['De la même façon', 'Enfin']],
 'k92-9': [['Le risque estimé, la conduite dépend du type d’hémorragie, en commençant par l’hémorragie haute non variqueuse.', 'En revanche', 'Par ailleurs', 'En outre'], ['Pendant l’examen', 'Ainsi', 'Cependant', 'Par ailleurs', 'À l’inverse'], ['Ensuite', 'En revanche', 'Enfin']],
 'k92-10': [['Le cirrhotique qui saigne suit une conduite différente.'], ['Ensuite', 'En effet', 'En revanche'], ['De plus', 'Enfin'], ['En complément', 'À l’inverse', 'Enfin']],
 'k92-11': [['L’hémorragie basse obéit à une autre logique.', 'Ainsi'], ['À l’inverse', 'Dans ce groupe', 'En revanche', 'Dans tous les cas']],
 'k92-12': [['Quelle que soit la source, la question des antithrombotiques se pose dès l’admission.', '', 'Ainsi', 'En revanche'], ['De même', 'Par ailleurs', 'Enfin'], ['']],
 'k92-13': [['Après l’épisode aigu, il faut prévenir la récidive.', 'De plus'], ['De son côté', 'Enfin']],
 'k92-14': [['Certaines situations modifient ces règles.', '', 'De plus'], ['Pour conclure, reprenons le premier patient.', 'Ainsi', 'Ensuite', 'Enfin']],
 'k92-15': [['']],
 'k92-e-1': [['Les examens complémentaires prolongent la démarche clinique.', 'Ainsi'], ['Autrement dit', 'En revanche']],
 'k92-e-2': [['Parmi ces examens, la biologie demande une lecture prudente.', '', 'Par ailleurs'], ['Chez le cirrhotique, la prudence est encore plus grande.', 'De même', 'Par conséquent']],
 'k92-e-3': [['Au-delà de la biologie, l’endoscopie et l’imagerie se lisent selon des critères précis.', 'En particulier'], ['Quand l’endoscopie ne localise pas la source, l’imagerie prend le relais.', 'Quant à elle']],
 'k92-p-1': [['Les principes thérapeutiques étant posés, il reste à préciser les médicaments.', ''], ['Ainsi']],
 'k92-p-2': [['Une fois la classe choisie, la dose et la durée décident de l’efficacité.'], ['']],
 'k92-p-3': [['Enfin, la sécurité du traitement dépend des interactions et de la surveillance.', 'De plus', 'En outre', 'Par ailleurs'], ['En pratique', 'De même'], ['Inversement, certains médicaments n’ont pas leur place.']],
 'k92-s-anat': [['', 'Or', 'De même', 'C’est pourquoi'], ['Le système veineux explique les varices.', 'Or', 'Dès lors']],
 'k92-s-histo': [['', 'En revanche', 'Ainsi'], ['Par ailleurs']],
 'k92-s-phys': [['', 'Ainsi'], ['À l’échelle de la lésion', 'Dès lors', 'Enfin']],
 'k92-s-biochim': [['', 'Or', '', 'Par conséquent'], ['Le sang change aussi de couleur.']],
}
