"""Glossaire du cours A04, fondé sur SSI/OFSP et les FI suisses, 8 octobre 2026."""
from cardio_1 import a, G

SSI_G = '<p>Source : <a href="https://ssi.guidelines.ch/guideline/3465/fr" target="_blank" rel="noopener">SSI, Gastro-entérite infectieuse, validée le 19.06.2026</a>.</p>'
SSI_C = '<p>Source : <a href="https://ssi.guidelines.ch/guideline/3120/fr" target="_blank" rel="noopener">SSI, Infection à Clostridioides difficile, validée le 17.04.2026</a>.</p>'
OFSP = '<p>Source : <a href="https://www.bag.admin.ch/dam/fr/sd-web/MDjbgfEN6jEf/250321_BAS_Meldeleitfaden_FR.pdf" target="_blank" rel="noopener">OFSP, Guide de la déclaration obligatoire 2026</a>.</p>'

a('A04', [('A', 'maladies infectieuses et parasitaires'), ('04', 'autres infections intestinales bactériennes')], 'Autres infections intestinales bactériennes', '<p>La rubrique regroupe notamment plusieurs pathotypes intestinaux d’E. coli, Campylobacter, Yersinia enterocolitica et Clostridioides difficile. Ces agents ont des mécanismes et des traitements distincts.</p>'+SSI_G)
a('STEC', [('S', 'Shiga'), ('T', 'toxine'), ('E', 'Escherichia'), ('C', 'coli')], 'Escherichia coli producteur de shigatoxine', '<p>Une souche porteuse de gènes stx1/stx2 ou productrice de shigatoxine peut entraîner une diarrhée sanglante et un syndrome hémolytique et urémique. La SSI indique les antibiotiques contre-indiqués dans cette branche.</p>'+OFSP+SSI_G)
a('EHEC', [('E', 'entéro'), ('H', 'hémorragique'), ('E', 'Escherichia'), ('C', 'coli')], 'Escherichia coli entérohémorragique', '<p>Terme utilisé par l’OFSP pour l’infection à E. coli producteur de vérotoxine ou de shigatoxine dans sa définition de surveillance. Une simple détection d’E. coli ne prouve pas ce pathotype.</p>'+OFSP)
a('CDI', [('C', 'Clostridioides'), ('D', 'difficile'), ('I', 'infection')], 'Infection à Clostridioides difficile', '<p>Le diagnostic réunit des symptômes compatibles, une preuve microbiologique et l’absence d’autre cause. Une amplification moléculaire positive isolée peut refléter un portage.</p>'+SSI_C)
a('GDH', [('G', 'Glutamate'), ('D', 'déshydrogénase'), ('H', 'enzyme')], 'Glutamate déshydrogénase', '<p>Antigène recherché en première étape de l’algorithme suisse de diagnostic de C. difficile, suivi d’une recherche des toxines A/B. La GDH seule ne prouve pas une infection active.</p>'+SSI_C)
a('TAAN', [('T', 'test'), ('A', 'amplification'), ('A', 'acides'), ('N', 'nucléiques')], 'Test d’amplification des acides nucléiques', '<p>Il recherche une séquence génétique microbienne. Pour C. difficile, sa positivité seule peut traduire une colonisation ; les symptômes et les toxines sont à considérer.</p>'+SSI_C)
a('SHU', [('S', 'syndrome'), ('H', 'hémolytique'), ('U', 'urémique')], 'Syndrome hémolytique et urémique', '<p>Complication possible d’une infection STEC, associant anémie hémolytique, thrombopénie et atteinte rénale aiguë. Sa survenue ne se déduit pas de la seule présence de sang dans les selles.</p>'+SSI_G+OFSP)
a('SSI', [('S', 'Société'), ('S', 'suisse'), ('I', 'infectiologie')], 'Société suisse d’infectiologie', '<p>Elle publie les recommandations suisses utilisées ici pour la gastro-entérite infectieuse et l’infection à C. difficile.</p>'+SSI_G+SSI_C)
a('OSAV', [('O', 'Office'), ('S', 'suisse'), ('A', 'affaires'), ('V', 'vétérinaires')], 'Office fédéral de la sécurité alimentaire et des affaires vétérinaires', '<p>Avec l’OFSP, cet office a publié le rapport de surveillance des zoonoses portant sur 2025 en Suisse et au Liechtenstein.</p><p><a href="https://www.bag.admin.ch/dam/fr/sd-web/m58bIhzouDmc/rapport-suisse-sur-les-zoonoses-2025.pdf" target="_blank" rel="noopener">Rapport OFSP–OSAV, juillet 2026</a>.</p>')
a('ECDC', [('E', 'European'), ('C', 'Centre for'), ('D', 'Disease'), ('C', 'Prevention and Control')], 'Centre européen de prévention et de contrôle des maladies', '<p>Agence européenne dont les fiches décrivent les infections à STEC, Campylobacter, Yersinia et C. difficile ; les décisions de traitement du cours suivent les directives suisses SSI.</p><p><a href="https://www.ecdc.europa.eu/en/escherichia-coli-ecoli/facts" target="_blank" rel="noopener">ECDC, STEC</a>.</p>')
a('ETEC', [('E', 'Escherichia'), ('T', 'entérotoxinogène'), ('E', 'Escherichia'), ('C', 'coli')], 'E. coli entérotoxinogène', '<p>Pathotype défini notamment par des entérotoxines thermolabile ou thermostable et associé à une diarrhée aqueuse ; l’aspect des selles ne suffit pas à le diagnostiquer.</p><p><a href="https://cdn.who.int/media/docs/default-source/immunization/final-etec-ppc-2021eng.pdf" target="_blank" rel="noopener">OMS, ETEC, 2021, §3.1</a>.</p>')
a('EPEC', [('E', 'Escherichia'), ('P', 'entéropathogène'), ('E', 'Escherichia'), ('C', 'coli')], 'E. coli entéropathogène', '<p>Un des pathotypes d’E. coli intestinal distingués dans le tableau de traitement de la SSI. Une simple détection de l’espèce E. coli ne prouve pas ce pathotype.</p>'+SSI_G)
a('EIEC', [('E', 'Escherichia'), ('I', 'entéroinvasif'), ('E', 'Escherichia'), ('C', 'coli')], 'E. coli entéroinvasif', '<p>Un des pathotypes d’E. coli intestinal distingués dans le tableau de la SSI, séparé de STEC et de ses précautions thérapeutiques.</p>'+SSI_G)
a('VTEC', [('V', 'vérotoxine'), ('T', 'toxine'), ('E', 'Escherichia'), ('C', 'coli')], 'E. coli producteur de vérotoxine', '<p>Autre nom employé dans la surveillance suisse pour les souches STEC/EHEC productrices de shigatoxine.</p>'+OFSP)
a('ICD', [('I', 'infection'), ('C', 'Clostridioides'), ('D', 'difficile')], 'Infection à Clostridioides difficile', '<p>La SSI exige un syndrome compatible et une preuve microbiologique interprétée, en l’absence d’autre cause plus probable. Une PCR isolée peut détecter un portage.</p>'+SSI_C)
a('FI', [('F', 'Fach'), ('I', 'Information')], 'Information professionnelle suisse du médicament', '<p>Monographie du produit exact utilisée pour vérifier indication, dose, voie, contre-indications et interactions. Une recommandation SSI peut proposer une conduite clinique différente de l’indication autorisée du produit.</p><p><a href="https://www.swissmedicinfo.ch/" target="_blank" rel="noopener">Swissmedicinfo, informations professionnelles</a>.</p>')
a('LT', [('L', 'labile'), ('T', 'toxine')], 'Entérotoxine thermolabile d’ETEC', '<p>L’OMS distingue des ETEC porteurs d’une entérotoxine thermolabile, thermostable ou des deux. Ce marqueur ne prouve pas à lui seul l’origine d’une diarrhée individuelle.</p><p><a href="https://cdn.who.int/media/docs/default-source/immunization/final-etec-ppc-2021eng.pdf" target="_blank" rel="noopener">OMS, ETEC, 2021, §3.1</a>.</p>')
a('O157', [('O', 'antigène somatique'), ('157', 'sérotype')], 'Sérotype O157 de certaines souches E. coli', '<p>Le groupe STEC comprend plusieurs sérotypes ; le résultat « O157 » ne doit pas être utilisé comme synonyme de tous les STEC.</p><p><a href="https://www.ecdc.europa.eu/en/escherichia-coli-ecoli/facts" target="_blank" rel="noopener">ECDC, STEC, 2024</a>.</p>')
a('PDF', [('P', 'Portable'), ('D', 'Document'), ('F', 'Format')], 'Document numérique à mise en page fixe', '<p>Les pages citées du guide OFSP et des recommandations SSI renvoient à leur document PDF. Une pagination PDF peut différer de la numérotation imprimée.</p>'+OFSP)
a('J1', [('J', 'jour'), ('1', 'premier')], 'Premier jour du schéma', '<p>J1 désigne le début du traitement dans le schéma pulsé de fidaxomicine discuté par la SSI. Ce schéma diffère des dix jours continus de la FI Dificlir.</p>'+SSI_C)
a('J7', [('J', 'jour'), ('7', 'septième')], 'Septième jour du schéma', '<p>J7 désigne le début des prises espacées du schéma pulsé de fidaxomicine discuté par la SSI. Il ne s’agit pas du schéma continu de la FI Dificlir.</p>'+SSI_C)
a('Ciprofloxacin-Mepha', [('Ciprofloxacin', 'ciprofloxacine'), ('Mepha', 'nom du fabricant')], 'Ciprofloxacin-Mepha, produit suisse', '<p>Sa FI suisse n°56305 doit être distinguée de la directive SSI pour la durée et l’indication d’une infection digestive sélectionnée.</p><p><a href="https://www.swissmedicinfo.ch/ShowText.aspx?textType=FI&amp;lang=FR&amp;authNr=56305" target="_blank" rel="noopener">FI Ciprofloxacin-Mepha n°56305, août 2025</a>.</p>')
