"""Glossaire A15 sourcé par le guide suisse OFSP–Ligue pulmonaire 2024."""
from cardio_1 import a, G
GUIDE = '<p>Source : <a href="https://www.bag.admin.ch/dam/fr/sd-web/fPW7HAdyOiZ0/tuberkulose-handbuch.pdf" target="_blank" rel="noopener">OFSP–Ligue pulmonaire suisse, Tuberculose en Suisse, V1.2024</a>.</p>'
OFSP = '<p>Source : <a href="https://www.bag.admin.ch/dam/fr/sd-web/MDjbgfEN6jEf/250321_BAS_Meldeleitfaden_FR.pdf" target="_blank" rel="noopener">OFSP, Guide de la déclaration obligatoire 2026, fiche 58</a>.</p>'
a('A15', [('A', 'maladies infectieuses'), ('15', 'tuberculose respiratoire confirmée')], 'Tuberculose respiratoire confirmée', '<p>La nomenclature distingue les formes respiratoires avec preuve bactériologique, moléculaire ou histologique. Des symptômes et une image seuls ne suffisent pas à cette confirmation.</p>'+GUIDE)
a('A16', [('A', 'maladies infectieuses'), ('16', 'tuberculose respiratoire sans cette confirmation')], 'Tuberculose respiratoire non confirmée par ces méthodes', '<p>Cette catégorie exige qu’une maladie tuberculeuse respiratoire soit retenue cliniquement ; elle n’est pas l’étiquette automatique de toute suspicion.</p>'+GUIDE)
a('IGRA', [('I', 'interferon'), ('G', 'gamma'), ('R', 'release'), ('A', 'assay')], 'Test de libération d’interféron gamma', '<p>Il mesure une réponse immunitaire à des antigènes mycobactériens. Positif ou négatif, il ne confirme ni n’exclut seul une tuberculose maladie active.</p>'+GUIDE)
a('PCR', [('P', 'polymerase'), ('C', 'chain'), ('R', 'reaction')], 'Test d’amplification moléculaire', '<p>Sur prélèvement adapté, il recherche le matériel génétique de mycobactéries et parfois une résistance ciblée. Sa négativité isolée ne clôt pas un bilan si la suspicion reste forte.</p>'+GUIDE)
a('BAAR', [('B', 'bacille'), ('A', 'acido'), ('A', 'alcoolo'), ('R', 'résistant')], 'Bacille acido-alcoolo-résistant', '<p>Un frottis positif renseigne sur la présence de bacilles acido-résistants et le risque de transmission, sans identifier à lui seul l’espèce ou la sensibilité.</p>'+GUIDE)
a('HRZE', [('H', 'isoniazide'), ('R', 'rifampicine'), ('Z', 'pyrazinamide'), ('E', 'éthambutol')], 'Quatre médicaments de la phase intensive', '<p>Le guide suisse associe ces quatre molécules pendant la phase intensive standard d’une tuberculose supposée sensible ; les produits et doses exacts demandent contrôle de la sensibilité et des FI suisses.</p>'+GUIDE)
a('OFSP', [('O', 'Office'), ('F', 'fédéral'), ('S', 'santé'), ('P', 'publique')], 'Office fédéral de la santé publique', '<p>L’OFSP coédite le guide national de la tuberculose et fixe les règles de déclaration obligatoire.</p>'+GUIDE+OFSP)
a('FI', [('F', 'Fach'), ('I', 'Information')], 'Information professionnelle suisse du médicament', '<p>Monographie de la spécialité exacte précisant indication, posologie, contre-indications et interactions. Elle doit être confrontée au guide national avant prescription.</p><p><a href="https://www.swissmedicinfo.ch/" target="_blank" rel="noopener">Swissmedicinfo</a>.</p>')
