"""Sigles et termes propres à A54 — Infection gonococcique, travail interne."""
from cardio_1 import a, G

SSI = '<p>Source : <a href="https://ssi.guidelines.ch/guideline/2272/fr" target="_blank" rel="noopener">SSI, Gonococcie, validation du 8 mai 2024</a>.</p>'
OFSP = '<p>Source : <a href="https://www.bag.admin.ch/dam/fr/sd-web/jB29Qf2x7Jme/BU_44_25_FR.pdf" target="_blank" rel="noopener">OFSP, Bulletin 44/2025, données de 2024</a>.</p>'
WHO = '<p>Source : <a href="https://www.ncbi.nlm.nih.gov/books/NBK605896/" target="_blank" rel="noopener">OMS, recommandations gonococcie, 2024, section 3.1</a>.</p>'

a('A54', [('A', 'chapitre des maladies infectieuses de la CIM-10-GM'), ('54', 'catégorie des infections gonococciques')], 'A54 — Infection gonococcique', '<p>Catégorie historique regroupant neuf sous-codes directs dans la CIM-10-GM 2024, selon le site et la forme. Le catalogue de production MEDINA a corrigé l’omission A54.6 ; cela ne démontre aucune correspondance CIM-11.</p><p><a href="https://klassifikationen.bfarm.de/icd-10-gm/kode-suche/htmlgm2024/block-a50-a64.htm" target="_blank" rel="noopener">BfArM, CIM-10-GM 2024, rubrique A54</a>.</p>')
a('TAAN', [('T', 'Test'), ('A', 'd’Amplification'), ('A', 'des Acides'), ('N', 'Nucléiques')], 'Test d’amplification des acides nucléiques', '<p>Recherche du matériel génétique du gonocoque au site prélevé. Un résultat positif soutient le diagnostic à ce site ; il ne donne pas, à lui seul, la sensibilité à la ceftriaxone. La culture permet un antibiogramme lorsque la bactérie pousse.</p>'+SSI)
a('NAAT', [('N', 'Nucleic'), ('A', 'Acid'), ('A', 'Amplification'), ('T', 'Test')], 'Test d’amplification des acides nucléiques, équivalent anglais de TAAN', '<p>Le prélèvement doit correspondre aux sites d’exposition. Un test urinaire ne remplace pas automatiquement un prélèvement pharyngé ou rectal.</p>'+SSI)
a('DGI', [('D', 'Disseminated'), ('G', 'Gonococcal'), ('I', 'Infection')], 'Infection gonococcique disséminée', '<p>Diffusion hors d’une muqueuse, pouvant entraîner dermatite, ténosynovite ou arthrite et, plus rarement, endocardite ou méningite. Une suspicion demande une évaluation et un traitement distincts de la forme muqueuse simple.</p>'+SSI)
a('ANRESIS', [('ANRESIS', 'nom du réseau suisse de surveillance des résistances, non un acronyme développé ici')], 'Réseau suisse de surveillance de l’antibiorésistance', '<p>Ses données reprises par l’OFSP en 2025 portent sur des isolats suisses de 2024. Les pourcentages nationaux ne prédisent pas la sensibilité d’une souche individuelle.</p>'+OFSP)
a('OFSP', [('O', 'Office'), ('F', 'Fédéral'), ('S', 'de la Santé'), ('P', 'Publique')], 'Office fédéral de la santé publique', '<p>Autorité suisse publiant les données et les recommandations de santé publique. Le Bulletin 44/2025 décrit la gonorrhée et la résistance pour l’année 2024.</p>'+OFSP)
a('SSI', [('S', 'Société'), ('S', 'Suisse'), ('I', 'd’Infectiologie')], 'Société suisse d’infectiologie', '<p>Sa directive « Gonococcie » expose le diagnostic, les sites à prélever, le traitement et les partenaires ; elle est distinguée de l’information professionnelle du médicament utilisé.</p>'+SSI)
a('BASHH', [('B', 'British'), ('A', 'Association'), ('S', 'for Sexual'), ('H', 'Health and'), ('H', 'HIV')], 'British Association for Sexual Health and HIV', '<p>Société savante britannique dont la directive gonococcie 2025 apporte un point de comparaison ; elle ne remplace pas la directive suisse applicable.</p><p><a href="https://www.bashh.org/resources/136/gonorrhoea_2025_updated_guideline/" target="_blank" rel="noopener">BASHH, 2025</a>.</p>')
a('Opa', [('Opa', 'nom des protéines gonococciques d’opacité, non un sigle clinique')], 'Protéines d’opacité de Neisseria gonorrhoeae', '<p>Protéines de surface modulant l’adhérence aux cellules et dont l’expression peut varier. Ce mécanisme contribue à l’interaction avec la muqueuse et à l’échappement immunitaire ; il ne permet pas de prédire la gravité chez une personne donnée.</p>'+WHO)
a('penA', [('penA', 'nom du gène bactérien, non un sigle clinique')], 'Gène de la protéine liant la pénicilline 2', '<p>Des variantes de penA, notamment mosaïques, peuvent réduire l’affinité pour les céphalosporines. La conséquence clinique dépend d’autres déterminants et doit être appréciée par la surveillance et, si possible, l’antibiogramme.</p>'+WHO)
a('gyrA', [('gyrA', 'nom du gène bactérien, non un sigle clinique')], 'Gène de la sous-unité A de l’ADN gyrase', '<p>Certaines mutations modifient la cible des fluoroquinolones et contribuent à leur résistance. Une donnée nationale de résistance ne vaut pas résultat individuel.</p>'+OFSP)
a('GyrA', [('Gyr', 'ADN gyrase'), ('A', 'sous-unité A')], 'Sous-unité A de l’ADN gyrase', '<p>La protéine codée par gyrA est une cible des fluoroquinolones ; une mutation pertinente peut modifier la sensibilité, à confirmer dans la situation clinique.</p>'+OFSP)
a('IST', [('I', 'Infection'), ('S', 'Sexuellement'), ('T', 'Transmissible')], 'Infection sexuellement transmissible', '<p>La recherche d’autres IST est recommandée lorsqu’une gonococcie est suspectée ou confirmée ; les résultats ne sont pas déduits du seul tableau clinique.</p>'+SSI)
a('STI', [('S', 'Sexually'), ('T', 'Transmitted'), ('I', 'Infection')], 'Infection sexuellement transmissible, sigle anglais', '<p>Équivalent anglais d’IST dans certaines sources internationales ; le terme ne désigne pas un pathogène particulier.</p>'+WHO)
a('IM', [('I', 'Intra'), ('M', 'Musculaire')], 'Voie intramusculaire', '<p>Injection dans un muscle. La dose clinique de ceftriaxone et la préparation du produit exact sont deux questions distinctes ; une solution préparée avec de la lidocaïne pour l’IM ne doit pas être injectée par voie IV.</p><p><a href="https://www.swissmedicinfo.ch/ShowText.aspx?textType=FI&amp;lang=FR&amp;authNr=59876" target="_blank" rel="noopener">FI suisse Ceftriaxon Labatec, juin 2025</a>.</p>')
a('FI', [('F', 'Information'), ('I', 'Professionnelle')], 'Information professionnelle suisse du médicament', '<p>Texte approuvé pour le produit et la présentation concernés. Pour Ceftriaxon Labatec, sa rubrique blennorragie et sa rubrique de préparation doivent être distinguées de la directive clinique SSI.</p><p><a href="https://www.swissmedicinfo.ch/ShowText.aspx?textType=FI&amp;lang=FR&amp;authNr=59876" target="_blank" rel="noopener">FI suisse n° 59876, mise à jour juin 2025</a>.</p>')
a('J7', [('J', 'Jour'), ('7', 'sept jours après le traitement')], 'Septième jour après le traitement', '<p>Repère du contrôle microbiologique indiqué par la SSI. Le test et son interprétation dépendent du site, des symptômes et de la méthode ; une PCR précoce peut demander une lecture prudente.</p>'+SSI)
a('ECDC', [('E', 'European'), ('C', 'Centre for'), ('D', 'Disease'), ('C', 'Prevention and Control')], 'Centre européen de prévention et de contrôle des maladies', '<p>Ses données européennes sur les résistances gonococciques ne sont pas des estimations suisses ni un antibiogramme individuel.</p><p><a href="https://www.ecdc.europa.eu/en/news-events/drug-resistant-gonorrhoea-rise-europe-ecdc-warns" target="_blank" rel="noopener">ECDC, 16 juillet 2026</a>.</p>')
a('UE', [('U', 'Union'), ('E', 'Européenne')], 'Union européenne', '<p>La surveillance européenne éclaire le contexte des résistances ; les pourcentages du jeu UE ne se substituent pas aux données suisses.</p>'+OFSP)
a('EEE', [('E', 'Espace'), ('E', 'Économique'), ('E', 'Européen')], 'Espace économique européen', '<p>Ensemble de pays souvent regroupés avec l’Union européenne dans les analyses de surveillance ; sa composition n’est pas celle du réseau suisse ANRESIS.</p>'+OFSP)
a('MMS', [('M', 'Mortality'), ('M', 'and Morbidity'), ('S', 'Statistics')], 'Version statistique de la CIM-11', '<p>La CIM-11 MMS utilise sa propre structure de codage. Les sous-codes CIM-10-GM A54 ne doivent pas être convertis automatiquement en codes MMS sans inventaire et vérification.</p><p><a href="https://icd.who.int/browse/2026-01/mms/en" target="_blank" rel="noopener">OMS, navigateur CIM-11 MMS</a>.</p>')
a('ARNr', [('ARN', 'Acide ribonucléique'), ('r', 'ribosomique')], 'ARN ribosomique', '<p>Composant des ribosomes bactériens. Certaines variations de l’ARNr 23S peuvent contribuer à la résistance aux macrolides ; le résultat individuel exige une analyse adaptée.</p>'+OFSP)
a('PilE', [('Pil', 'piline'), ('E', 'sous-unité principale désignée E')], 'Piline majeure du pilus gonococcique', '<p>Une protéine du pilus qui contribue à l’adhérence initiale et présente une variation antigénique. La variation aide le gonocoque à persister dans des populations exposées ; elle ne prédit pas le devenir de M. N.</p>')
a('CEACAM', [('CEA', 'Carcinoembryonic Antigen'), ('CAM', 'Cell Adhesion Molecule')], 'Famille de molécules d’adhérence cellulaire CEACAM', '<p>Certains récepteurs de cette famille interagissent avec des protéines Opa du gonocoque ; cette liaison varie selon la protéine et la cellule considérées.</p>')
a('CEACAM3', [('CEACAM', 'famille de molécules d’adhérence cellulaire'), ('3', 'membre 3')], 'Récepteur CEACAM3', '<p>Récepteur présent sur des neutrophiles, impliqué dans certaines interactions avec les protéines Opa gonococciques. Ce mécanisme expérimental n’établit pas la sensibilité d’une souche aux antibiotiques.</p>')
a('PBP2', [('PBP', 'Penicillin Binding Protein'), ('2', 'protéine 2')], 'Protéine liant la pénicilline 2', '<p>Enzyme de synthèse de la paroi bactérienne, cible des céphalosporines ; des variantes de penA peuvent modifier cette cible et contribuer à la résistance.</p>'+WHO)
