"""Glossaire ciblé A69, à partir de SSI, OFSP et OMS consultés le 8 octobre 2026."""
from cardio_1 import a, G

SSI = '<p>Source : <a href="https://ssi.guidelines.ch/guideline/2274/fr" target="_blank" rel="noopener">SSI, Borréliose de Lyme, validée le 02.05.2025</a>.</p>'
TIQUE = '<p>Source : <a href="https://ssi.guidelines.ch/guideline/5083/fr" target="_blank" rel="noopener">SSI, Piqûre de tique, validée le 25.08.2025</a>.</p>'
OMS = '<p>Source : <a href="https://www.who.int/news-room/fact-sheets/detail/noma" target="_blank" rel="noopener">OMS, Noma, 15.12.2023</a>.</p>'
a('A69', [('A', 'maladies infectieuses et parasitaires'), ('69', 'autres infections à spirochètes')], 'Autres infections à spirochètes', '<p>Dans ce cours, la borréliose de Lyme est étudiée séparément des atteintes bucco-pharyngées nécrosantes. Le regroupement du catalogue ne crée pas de traitement commun.</p>'+SSI+OMS)
a('EM', [('E', 'érythème'), ('M', 'migrant')], 'Érythème migrant', '<p>Plaque cutanée qui s’étend progressivement après une piqûre infectante ; lorsqu’elle est typique, la SSI pose le diagnostic cliniquement, sans sérologie initiale.</p>'+SSI+TIQUE)
a('LCR', [('L', 'liquide'), ('C', 'céphalo'), ('R', 'rachidien')], 'Liquide céphalorachidien', '<p>Une ponction lombaire peut être indiquée lorsqu’une neuroborréliose est suspectée ; la cellule et la recherche d’une synthèse intrathécale d’anticorps sont interprétées selon le tableau clinique.</p>'+SSI)
a('ELISA', [('E', 'enzyme'), ('L', 'linked'), ('I', 'immuno'), ('S', 'sorbent'), ('A', 'assay')], 'Test immuno-enzymatique', '<p>Premier temps d’une stratégie sérologique de Lyme lorsque la sérologie est indiquée. Un résultat positif isolé ne démontre pas une infection active.</p>'+SSI)
a('PCR', [('P', 'polymerase'), ('C', 'chain'), ('R', 'reaction')], 'Amplification génique', '<p>Recherche de matériel génétique microbien dans un prélèvement adapté. Elle n’est pas le test initial de l’érythème migrant typique.</p>'+SSI)
a('OFSP', [('O', 'Office'), ('F', 'fédéral'), ('S', 'santé'), ('P', 'publique')], 'Office fédéral de la santé publique', '<p>L’OFSP publie des informations suisses sur la prévention des piqûres de tiques et les estimations de maladie de Lyme.</p><p><a href="https://www.bag.admin.ch/fr/maladies-transmises-par-les-tiques-situation-en-suisse" target="_blank" rel="noopener">OFSP, situation en Suisse</a>.</p>')
a('SSI', [('S', 'Société'), ('S', 'suisse'), ('I', 'infectiologie')], 'Société suisse d’infectiologie', '<p>La SSI publie les conduites cliniques suisses utilisées ici pour Lyme et les piqûres de tiques.</p>'+SSI+TIQUE)
a('FI', [('F', 'Fach'), ('I', 'Information')], 'Information professionnelle suisse du médicament', '<p>Monographie du produit exact, utilisée ici pour comparer indications, posologies et précautions aux recommandations de la SSI.</p><p><a href="https://www.swissmedicinfo.ch/" target="_blank" rel="noopener">Swissmedicinfo, informations professionnelles</a>.</p>')
a('AV', [('A', 'atrio'), ('V', 'ventriculaire')], 'Atrio-ventriculaire', '<p>Qualifie la conduction électrique entre oreillettes et ventricules. Un trouble de conduction associé à une suspicion de cardite de Lyme change l’urgence et la voie de prise en charge.</p>'+SSI)
a('Noma', [('Noma', 'nom de la maladie')], 'Noma', '<p>Maladie orofaciale rapidement destructrice décrite par l’OMS, surtout chez les jeunes enfants dans des contextes de malnutrition et de privation. Elle ne résulte pas d’une piqûre de tique.</p>'+OMS)
