"""Sigles propres au cours de travail B18 — Hépatite virale chronique.

Les clés déjà chargées depuis A41, B24 et le glossaire commun ne sont pas
redéfinies ici. Sources consultées le 8 octobre 2026 ; les décisions et les
limites cliniques détaillées restent dans les fenêtres du cours.
"""
from cardio_1 import a, G

REF_B = '<p>Source : <a href="https://www.hepb.org/assets/Uploads/EASL-guidelines-May-2025.pdf" target="_blank" rel="noopener">EASL, VHB, 2025</a>.</p>'
REF_C = '<p>Source : <a href="https://easl.eu/wp-content/uploads/2020/10/EASL-recommendations-on-treatment-of-hepatitis-C.pdf" target="_blank" rel="noopener">EASL, VHC, 2020</a>.</p>'
REF_D = '<p>Source : <a href="https://easlcampus.eu/sites/default/files/2023-06/EASL%20Clinical%20Practice%20Guidelines%20on%20hepatitis%20delta%20virus.pdf" target="_blank" rel="noopener">EASL, VHD, 2023</a>.</p>'
REF_E = '<p>Source : <a href="https://easl.eu/wp-content/uploads/2018/10/EASL-CPG-hepatitis-E-virus-infection.pdf" target="_blank" rel="noopener">EASL, VHE, 2018</a>.</p>'
REF_CHC = '<p>Source : <a href="https://easlcampus.eu/sites/default/files/2025-02/EASL_CPG_Management_HCC.pdf" target="_blank" rel="noopener">EASL, cancer hépatocellulaire, 2025</a>.</p>'
REF_SUISSE_VHC = '<p>Source : <a href="https://www.sasl.unibas.ch/guidelines/SASL-SSG-SSI_EOS_HepC_Jan2021.pdf" target="_blank" rel="noopener">SASL/SSG/SSI, avis suisse VHC, janvier 2021</a>.</p>'
REF_HEPCLUDEX = '<p>Source : <a href="https://www.swissmedicinfo.ch/ShowText.aspx?textType=FI&amp;lang=EN&amp;authNr=68338" target="_blank" rel="noopener">Information professionnelle suisse Hepcludex n° 68338, juillet 2026</a>.</p>'

a('B18', [('B', 'chapitre des maladies infectieuses de la CIM-10-GM'), ('18', 'catégorie des hépatites virales chroniques')], 'Catégorie B18 — hépatite virale chronique', '<p>Regroupe les sous-codes pour VHB avec ou sans VHD, VHC, VHE et autres hépatites virales chroniques ; la phase VHB et le virus doivent être documentés avant de choisir le sous-code.</p><p><a href="https://klassifikationen.bfarm.de/icd-10-gm/kode-suche/htmlgm2024/block-b15-b19.htm" target="_blank" rel="noopener">BfArM, CIM-10-GM 2024, B18</a>.</p>')
a('MEDINA', [('MEDINA', 'nom propre de l’atlas, non un sigle médical')], 'MEDINA, atlas de cours de médecine', '<p>Nom du projet pédagogique ; il ne désigne ni une classification ni une recommandation clinique.</p>')

a('VHA', [('V', 'Virus de l’'), ('H', 'Hépatite'), ('A', 'A')], 'Virus de l’hépatite A', '<p>Virus distinct des VHB, VHC, VHD et VHE ; l’immunité ou la vaccination sont pertinentes dans le bilan d’une maladie hépatique chronique.</p>'+REF_C)
a('VHB', [('V', 'Virus de l’'), ('H', 'Hépatite'), ('B', 'B')], 'Virus de l’hépatite B', '<p>Virus à ADN dont l’infection persistante se caractérise par la sérologie, l’ADN sanguin, l’ALT et la fibrose ; le seul antigène HBs ne fixe pas la phase.</p>'+REF_B)
a('VHC', [('V', 'Virus de l’'), ('H', 'Hépatite'), ('C', 'C')], 'Virus de l’hépatite C', '<p>Virus à ARN ; un anticorps positif indique une exposition, tandis que l’ARN détectable établit une infection actuelle.</p>'+REF_C)
a('VHD', [('V', 'Virus de l’'), ('H', 'Hépatite'), ('D', 'D, aussi appelé delta')], 'Virus de l’hépatite D ou delta', '<p>Virus dépendant des protéines de surface du VHB pour former des particules infectieuses ; l’ARN VHD confirme sa réplication active.</p>'+REF_D)
a('VHE', [('V', 'Virus de l’'), ('H', 'Hépatite'), ('E', 'E')], 'Virus de l’hépatite E', '<p>Le plus souvent responsable d’une infection aiguë ; une persistance de son ARN peut survenir sous immunosuppression et demande une évaluation ciblée.</p>'+REF_E)

a('HBs', [('HB', 'Hepatitis B'), ('s', 'surface')], 'Protéine de surface du VHB', '<p>Le terme décrit la composante antigénique de surface ; « Ag HBs » ou HBsAg désigne sa détection sanguine. Cette positivité ne quantifie pas la réplication.</p>'+REF_B)
a('HBc', [('HB', 'Hepatitis B'), ('c', 'core, cœur de la capside')], 'Antigène de capside du VHB', '<p>L’anti-HBc témoigne d’un contact avec le VHB ; il ne résulte pas d’une vaccination isolée. Sa présence seule ne prouve pas une infection active.</p>'+REF_B)
a('HBe', [('HB', 'Hepatitis B'), ('e', 'antigène e sécrété')], 'Antigène e du VHB', '<p>Un résultat HBe positif ou négatif contribue à caractériser la phase, avec ADN VHB, ALT et évolution ; sa négativité n’exclut pas une hépatite active.</p>'+REF_B)
a('HBeAg', [('HB', 'Hepatitis B'), ('e', 'antigène e'), ('Ag', 'Antigen')], 'Antigène e du virus de l’hépatite B', '<p>Marqueur sérologique des phases du VHB. L’ADN et l’ALT restent nécessaires, notamment parce qu’une hépatite HBeAg négative peut être active.</p>'+REF_B)

a('ALAT', [('ALAT', 'sigle français conventionnel de l’alanine aminotransférase')], 'Alanine aminotransférase', '<p>Enzyme libérée lors de lésions hépatocytaires. Une valeur unique ne mesure ni la fibrose ni toute la trajectoire de l’infection.</p>'+REF_B)
a('ALT', [('ALT', 'sigle international conventionnel de l’alanine aminotransférase')], 'Alanine aminotransférase, équivalent d’ALAT', '<p>Marqueur sanguin de cytolyse à interpréter avec le laboratoire, la chronologie et les autres causes possibles d’élévation.</p>'+REF_B)
a('AST', [('AST', 'sigle international conventionnel de l’aspartate aminotransférase')], 'Aspartate aminotransférase', '<p>Enzyme utilisée notamment avec les plaquettes dans l’indice APRI ; non spécifique à elle seule d’une fibrose.</p><p><a href="https://iris.who.int/server/api/core/bitstreams/34470cc8-af90-4d7b-a949-ef27e5d0726f/content" target="_blank" rel="noopener">OMS, VHB, 2024, chapitre 4</a>.</p>')
a('GGT', [('G', 'Gamma'), ('G', 'Glutamyl'), ('T', 'Transférase')], 'Gamma-glutamyl transférase', '<p>Enzyme sanguine qui aide à interpréter une élévation des phosphatases alcalines et une possible cholestase ; elle n’établit pas, isolément, la cause d’un prurit.</p>'+REF_B)
a('APRI', [('A', 'Aspartate aminotransférase'), ('P', 'Platelet, plaquette'), ('R', 'Ratio, rapport'), ('I', 'Index, indice')], 'Indice du rapport AST/plaquettes', '<p>Test non invasif de fibrose ; son interprétation dépend du seuil, de la population et d’une éventuelle poussée hépatique.</p><p><a href="https://iris.who.int/server/api/core/bitstreams/34470cc8-af90-4d7b-a949-ef27e5d0726f/content" target="_blank" rel="noopener">OMS, VHB, 2024, chapitre 4</a>.</p>')
a('AFP', [('A', 'Alpha'), ('F', 'Fœto-'), ('P', 'Protéine')], 'Alpha-fœtoprotéine', '<p>Biomarqueur parfois associé à l’échographie dans la surveillance du carcinome hépatocellulaire ; une valeur isolée ne remplace pas l’imagerie.</p>'+REF_CHC)
a('CHC', [('C', 'Carcinome'), ('H', 'Hépato-'), ('C', 'Cellulaire')], 'Carcinome hépatocellulaire', '<p>Cancer primitif des hépatocytes. Sa surveillance dépend du risque et reste pertinente après contrôle viral chez certains patients.</p>'+REF_CHC)
a('F3', [('F', 'Fibrose selon le score METAVIR'), ('3', 'stade 3')], 'Fibrose avancée METAVIR F3', '<p>Stade histologique avec nombreux septa, sans cirrhose. Ne pas le convertir directement en une valeur d’élastographie valable pour tous les appareils.</p><p><a href="https://iris.who.int/server/api/core/bitstreams/34470cc8-af90-4d7b-a949-ef27e5d0726f/content" target="_blank" rel="noopener">OMS, VHB, 2024, tableau 4.1</a>.</p>')
a('F4', [('F', 'Fibrose selon le score METAVIR'), ('4', 'stade 4')], 'Cirrhose METAVIR F4', '<p>Stade histologique de cirrhose ; l’évaluation clinique et la méthode de mesure restent nécessaires pour diagnostiquer une personne.</p><p><a href="https://iris.who.int/server/api/core/bitstreams/34470cc8-af90-4d7b-a949-ef27e5d0726f/content" target="_blank" rel="noopener">OMS, VHB, 2024, tableau 4.1</a>.</p>')
a('cccDNA', [('ccc', 'covalently closed circular'), ('DNA', 'deoxyribonucleic acid')], 'ADN circulaire fermé de façon covalente', '<p>Forme nucléaire persistante du génome VHB dans l’hépatocyte. La baisse de l’ADN sanguin sous analogue ne prouve pas son élimination.</p>'+REF_B)
a('NS3', [('NS', 'Non-Structural, non structurale'), ('3', 'protéine 3')], 'Protéine non structurale NS3 du VHC', '<p>Sa fonction protéase, avec le cofacteur NS4A, est une cible des antiviraux directs.</p>'+REF_C)
a('NS3/4A', [('NS3', 'protéase virale NS3'), ('/', 'avec'), ('4A', 'cofacteur NS4A')], 'Complexe protéase NS3/4A du VHC', '<p>Découpe la polyprotéine virale ; les inhibiteurs de cette protéase ont des limites importantes en cas de cirrhose décompensée.</p>'+REF_C)
a('NS5A', [('NS', 'Non-Structural, non structurale'), ('5A', 'protéine 5A')], 'Protéine non structurale NS5A du VHC', '<p>Participe à l’organisation de la réplication et constitue une cible des antiviraux directs.</p>'+REF_C)
a('NS5B', [('NS', 'Non-Structural, non structurale'), ('5B', 'protéine 5B')], 'Polymérase non structurale NS5B du VHC', '<p>Copie l’ARN viral ; une autre cible des antiviraux directs.</p>'+REF_C)
a('SVR12', [('S', 'Sustained'), ('V', 'Virologic'), ('R', 'Response'), ('12', 'douze semaines après la fin du traitement')], 'Réponse virologique soutenue à 12 semaines', '<p>ARN VHC indétectable ou non quantifiable douze semaines après la fin du traitement ; signifie guérison virologique de cet épisode, sans protection contre une réinfection.</p>'+REF_C)
a('AAD', [('A', 'Antiviraux'), ('A', 'à Action'), ('D', 'Directe')], 'Antiviraux à action directe', '<p>Traitements du VHC ciblant des protéines virales de réplication ; le schéma dépend du stade hépatique, des traitements antérieurs et des interactions.</p>'+REF_C)
a('ETV', [('ETV', 'abréviation conventionnelle de l’entécavir')], 'Entécavir', '<p>Analogue nucléosidique actif contre le VHB ; son choix dépend notamment des traitements antérieurs et des résistances, de la fonction rénale et du contexte de grossesse.</p>'+REF_B)
a('NTCP', [('NTCP', 'sodium taurocholate cotransporting polypeptide, nom anglais du transporteur')], 'Polypeptide cotransporteur du taurocholate de sodium', '<p>Transporteur hépatocytaire impliqué dans l’entrée du VHB et du VHD ; le bulévirtide s’y fixe. Les interactions qui touchent ce transporteur nécessitent la consultation de la notice du produit.</p>'+REF_D+REF_HEPCLUDEX)
a('OATP', [('O', 'Organic'), ('A', 'Anion'), ('T', 'Transporting'), ('P', 'Polypeptides')], 'Polypeptides transporteurs d’anions organiques', '<p>Famille de transporteurs de médicaments. La notice suisse du bulévirtide signale une prudence avec certains substrats OATP ; le risque s’évalue pour chaque association.</p>'+REF_HEPCLUDEX)
a('SASL', [('SASL', 'Swiss Association for the Study of the Liver')], 'Association suisse pour l’étude du foie', '<p>Société savante cosignataire de l’avis suisse sur le traitement du VHC de janvier 2021.</p>'+REF_SUISSE_VHC)
a('SSG', [('SSG', 'Swiss Society of Gastroenterology')], 'Société suisse de gastroentérologie', '<p>Société savante cosignataire de l’avis suisse sur le traitement du VHC de janvier 2021.</p>'+REF_SUISSE_VHC)

a('JCI', [('J', 'Journal'), ('C', 'Clinical'), ('I', 'Investigation')], 'The Journal of Clinical Investigation', '<p>Revue scientifique citée pour des études primaires sur les hépatocytes ; le résultat d’une étude ne vaut pas une décision individuelle.</p>')
a('MacParland', [('MacParland', 'nom de famille de l’auteur, non un sigle')], 'Sean A. MacParland', '<p>Premier auteur d’un atlas unicellulaire de foie humain. Son étude décrit des populations cellulaires dans les tissus étudiés, sans mesurer la maladie de Mme R.</p><p><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC6197289/" target="_blank" rel="noopener">MacParland et coll., Nature Communications, 2018</a>.</p>')
a('FibroScan', [('FibroScan', 'nom commercial d’un appareil d’élastographie, non un sigle')], 'FibroScan, appareil d’élastographie transitoire', '<p>Mesure une rigidité hépatique utile à l’estimation non invasive de la fibrose. Une poussée inflammatoire peut augmenter la mesure, et les seuils ne s’étendent pas sans contrôle aux autres techniques.</p><p><a href="https://iris.who.int/server/api/core/bitstreams/34470cc8-af90-4d7b-a949-ef27e5d0726f/content" target="_blank" rel="noopener">OMS, VHB, 2024, chapitre 4</a>.</p>')
