"""Sigles propres au cours de travail B18 — Hépatite virale chronique.

Les clés déjà chargées depuis A41, B24 et le glossaire commun ne sont pas
redéfinies ici. Sources consultées le 8 octobre 2026 ; les décisions et les
limites cliniques détaillées restent dans les fenêtres du cours.
"""
from cardio_1 import a, G

REF_B = '<p>Source : <a href="https://easlcampus.eu/sites/default/files/2025-08/EASL_CPGs_on_management_of_HBV_infection.pdf" target="_blank" rel="noopener">EASL, VHB, 2025</a>.</p>'
REF_C = '<p>Source : <a href="https://easl.eu/wp-content/uploads/2020/10/EASL-recommendations-on-treatment-of-hepatitis-C.pdf" target="_blank" rel="noopener">EASL, VHC, 2020</a>.</p>'
REF_D = '<p>Source : <a href="https://easlcampus.eu/sites/default/files/2023-06/EASL%20Clinical%20Practice%20Guidelines%20on%20hepatitis%20delta%20virus.pdf" target="_blank" rel="noopener">EASL, VHD, 2023</a>.</p>'
REF_E = '<p>Source : <a href="https://easl.eu/wp-content/uploads/2018/10/EASL-CPG-hepatitis-E-virus-infection.pdf" target="_blank" rel="noopener">EASL, VHE, 2018</a>.</p>'
REF_CHC = '<p>Source : <a href="https://easlcampus.eu/sites/default/files/2025-02/EASL_CPG_Management_HCC.pdf" target="_blank" rel="noopener">EASL, cancer hépatocellulaire, 2025</a>.</p>'
REF_SUISSE_VHC = '<p>Source : <a href="https://www.sasl.unibas.ch/guidelines/SASL-SSG-SSI_EOS_HepC_Jan2021.pdf" target="_blank" rel="noopener">SASL/SSG/SSI, avis suisse VHC, janvier 2021</a>.</p>'
REF_HEPCLUDEX = '<p>Source : <a href="https://www.swissmedicinfo.ch/ShowText.aspx?textType=FI&amp;lang=EN&amp;authNr=68338" target="_blank" rel="noopener">Information professionnelle suisse Hepcludex n° 68338, juillet 2026</a>.</p>'


a('VHA', [('V', 'Virus de l’'), ('H', 'Hépatite'), ('A', 'A')], 'Virus de l’hépatite A', '<p>Virus distinct des VHB, VHC, VHD et VHE ; l’immunité ou la vaccination sont pertinentes dans le bilan d’une maladie hépatique chronique.</p>'+REF_C)
a('VHB', [('V', 'Virus de l’'), ('H', 'Hépatite'), ('B', 'B')], 'Virus de l’hépatite B', '<p>Virus à ADN dont l’infection persistante se caractérise par la sérologie, l’ADN sanguin, l’ALT et la fibrose ; le seul antigène HBs ne fixe pas la phase.</p>'+REF_B)
a('VHC', [('V', 'Virus de l’'), ('H', 'Hépatite'), ('C', 'C')], 'Virus de l’hépatite C', '<p>Virus à ARN ; un anticorps positif indique une exposition, tandis que l’ARN détectable établit une infection actuelle.</p>'+REF_C)
a('VHD', [('V', 'Virus de l’'), ('H', 'Hépatite'), ('D', 'D, aussi appelé delta')], 'Virus de l’hépatite D ou delta', '<p>Virus dépendant des protéines de surface du VHB pour former des particules infectieuses ; l’ARN VHD confirme sa réplication active.</p>'+REF_D)
a('VHE', [('V', 'Virus de l’'), ('H', 'Hépatite'), ('E', 'E')], 'Virus de l’hépatite E', '<p>Le plus souvent responsable d’une infection aiguë ; une persistance de son ARN peut survenir sous immunosuppression et demande une évaluation ciblée.</p>'+REF_E)

a('HBs', [('HB', 'Hepatitis B'), ('s', 'surface')], 'Protéine de surface du VHB', '<p>Le terme décrit la composante antigénique de surface ; « Ag HBs » ou HBsAg désigne sa détection sanguine. Cette positivité ne quantifie pas la réplication.</p>'+REF_B)
a('HBc', [('HB', 'Hepatitis B'), ('c', 'core, cœur de la capside')], 'Antigène de capside du VHB', '<p>L’anti-HBc témoigne d’un contact avec le VHB ; il ne résulte pas d’une vaccination isolée. Sa présence seule ne prouve pas une infection active.</p>'+REF_B)
a('HBe', [('HB', 'Hepatitis B'), ('e', 'antigène e sécrété')], 'Antigène e du VHB', '<p>Un résultat HBe positif ou négatif contribue à caractériser la phase, avec ADN VHB, ALT et évolution ; sa négativité n’exclut pas une hépatite active.</p>'+REF_B)
a('HBeAg', [('HB', 'Hepatitis B'), ('e', 'antigène e'), ('Ag', 'Antigen')], 'Antigène e du virus de l’hépatite B', '<p>Marqueur sérologique des phases du VHB. L’ADN et l’ALT restent nécessaires, notamment parce qu’une hépatite HBeAg négative peut être active.</p>'+REF_B)

a('ALAT', [('ALAT', 'sigle français conventionnel de l’alanine aminotransférase')], 'Alanine aminotransférase', '<p>Enzyme libérée lors de lésions hépatocytaires. Une valeur unique ne mesure ni la fibrose ni toute la trajectoire de l’infection.</p>'+REF_B)
a('GGT', [('G', 'Gamma'), ('G', 'Glutamyl'), ('T', 'Transférase')], 'Gamma-glutamyl transférase', '<p>Enzyme sanguine qui aide à interpréter une élévation des phosphatases alcalines et une possible cholestase ; elle n’établit pas, isolément, la cause d’un prurit.</p>'+REF_B)
a('APRI', [('A', 'Aspartate aminotransférase'), ('P', 'Platelet, plaquette'), ('R', 'Ratio, rapport'), ('I', 'Index, indice')], 'Indice du rapport AST/plaquettes', '<p>Test non invasif de fibrose ; son interprétation dépend du seuil, de la population et d’une éventuelle poussée hépatique.</p><p><a href="https://iris.who.int/server/api/core/bitstreams/34470cc8-af90-4d7b-a949-ef27e5d0726f/content" target="_blank" rel="noopener">OMS, VHB, 2024, chapitre 4</a>.</p>')
a('AFP', [('A', 'Alpha'), ('F', 'Fœto-'), ('P', 'Protéine')], 'Alpha-fœtoprotéine', '<p>Biomarqueur parfois associé à l’échographie dans la surveillance du carcinome hépatocellulaire ; une valeur isolée ne remplace pas l’imagerie.</p>'+REF_CHC)
a('CHC', [('C', 'Carcinome'), ('H', 'Hépato-'), ('C', 'Cellulaire')], 'Carcinome hépatocellulaire', '<p>Cancer primitif des hépatocytes. Sa surveillance dépend du risque et reste pertinente après contrôle viral chez certains patients.</p>'+REF_CHC)
a('F3', [('F', 'Fibrose selon le score METAVIR'), ('3', 'stade 3')], 'Fibrose avancée METAVIR F3', '<p>Stade histologique avec nombreux septa, sans cirrhose. Ne pas le convertir directement en une valeur d’élastographie valable pour tous les appareils.</p><p><a href="https://iris.who.int/server/api/core/bitstreams/34470cc8-af90-4d7b-a949-ef27e5d0726f/content" target="_blank" rel="noopener">OMS, VHB, 2024, tableau 4.1</a>.</p>')
a('F4', [('F', 'Fibrose selon le score METAVIR'), ('4', 'stade 4')], 'Cirrhose METAVIR F4', '<p>Stade histologique de cirrhose ; l’évaluation clinique et la méthode de mesure restent nécessaires pour diagnostiquer une personne.</p><p><a href="https://iris.who.int/server/api/core/bitstreams/34470cc8-af90-4d7b-a949-ef27e5d0726f/content" target="_blank" rel="noopener">OMS, VHB, 2024, tableau 4.1</a>.</p>')
a('NS3', [('NS', 'Non-Structural, non structurale'), ('3', 'protéine 3')], 'Protéine non structurale NS3 du VHC', '<p>Sa fonction protéase, avec le cofacteur NS4A, est une cible des antiviraux directs.</p>'+REF_C)
a('NS3/4A', [('NS3', 'protéase virale NS3'), ('/', 'avec'), ('4A', 'cofacteur NS4A')], 'Complexe protéase NS3/4A du VHC', '<p>Découpe la polyprotéine virale ; les inhibiteurs de cette protéase ont des limites importantes en cas de cirrhose décompensée.</p>'+REF_C)
a('NS5A', [('NS', 'Non-Structural, non structurale'), ('5A', 'protéine 5A')], 'Protéine non structurale NS5A du VHC', '<p>Participe à l’organisation de la réplication et constitue une cible des antiviraux directs.</p>'+REF_C)
a('NS5B', [('NS', 'Non-Structural, non structurale'), ('5B', 'protéine 5B')], 'Polymérase non structurale NS5B du VHC', '<p>Copie l’ARN viral ; une autre cible des antiviraux directs.</p>'+REF_C)
a('SVR12', [('S', 'Sustained'), ('V', 'Virologic'), ('R', 'Response'), ('12', 'douze semaines après la fin du traitement')], 'Réponse virologique soutenue à 12 semaines', '<p>ARN VHC indétectable ou non quantifiable douze semaines après la fin du traitement ; signifie guérison virologique de cet épisode, sans protection contre une réinfection.</p>'+REF_C)
a('NTCP', [('NTCP', 'sodium taurocholate cotransporting polypeptide, nom anglais du transporteur')], 'Polypeptide cotransporteur du taurocholate de sodium', '<p>Transporteur hépatocytaire impliqué dans l’entrée du VHB et du VHD ; le bulévirtide s’y fixe. Les interactions qui touchent ce transporteur nécessitent la consultation de la notice du produit.</p>'+REF_D+REF_HEPCLUDEX)
a('OATP', [('O', 'Organic'), ('A', 'Anion'), ('T', 'Transporting'), ('P', 'Polypeptides')], 'Polypeptides transporteurs d’anions organiques', '<p>Famille de transporteurs de médicaments. La notice suisse du bulévirtide signale une prudence avec certains substrats OATP ; le risque s’évalue pour chaque association.</p>'+REF_HEPCLUDEX)
a('SASL', [('SASL', 'Swiss Association for the Study of the Liver')], 'Association suisse pour l’étude du foie', '<p>Société savante cosignataire de l’avis suisse sur le traitement du VHC de janvier 2021.</p>'+REF_SUISSE_VHC)
a('SSG', [('SSG', 'Swiss Society of Gastroenterology')], 'Société suisse de gastroentérologie', '<p>Société savante cosignataire de l’avis suisse sur le traitement du VHC de janvier 2021.</p>'+REF_SUISSE_VHC)

a('MacParland', [('MacParland', 'nom de famille de l’auteur, non un sigle')], 'Sean A. MacParland', '<p>Premier auteur d’un atlas unicellulaire de foie humain. Son étude décrit des populations cellulaires dans les tissus étudiés, sans mesurer la maladie de Mme R.</p><p><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC6197289/" target="_blank" rel="noopener">MacParland et coll., Nature Communications, 2018</a>.</p>')
REF_FI_TDF = '<p>Source : <a href="https://www.swissmedicinfo.ch/ShowText.aspx?textType=FI&amp;lang=FR&amp;authNr=56251" target="_blank" rel="noopener">Information professionnelle suisse Viread®, Swissmedic, juin 2024</a>.</p>'
REF_FI_TAF = '<p>Source : <a href="https://www.swissmedicinfo.ch/ShowText.aspx?textType=FI&amp;lang=FR&amp;authNr=66190" target="_blank" rel="noopener">Information professionnelle suisse Vemlidy®, Swissmedic, février 2024</a>.</p>'
a('HBsAg', [('HBs', 'Hepatitis B surface'), ('Ag', 'Antigen')], 'Antigène de surface du virus de l’hépatite B (Ag HBs)', '<p>Protéine d’enveloppe du VHB détectée dans le sang. Sa persistance pendant six mois ou plus définit l’infection chronique (définition OMS) ; sa disparition durable avec un ADN indétectable constitue la guérison fonctionnelle.</p>'+REF_B)
a('ADNccc', [('ADN', 'Acide DésoxyriboNucléique'), ('ccc', 'circulaire clos de façon covalente')], 'ADN circulaire clos de façon covalente du VHB', '<p>Matrice nucléaire stable du génome du VHB dans l’hépatocyte. Les analogues nucléos(t)idiques bloquent la réplication sans l’éliminer, ce qui explique la rareté de la perte de l’Ag HBs et le risque de rechute à l’arrêt.</p>'+REF_B)
a('ASAT', [('ASAT', 'sigle français conventionnel de l’aspartate aminotransférase')], 'Aspartate aminotransférase', '<p>Enzyme du bilan hépatique, moins spécifique du foie que l’ALAT ; elle entre dans l’indice APRI.</p>'+REF_B)
a('F2', [('F', 'Fibrose selon le score METAVIR'), ('2', 'stade 2')], 'Fibrose significative METAVIR F2', '<p>Stade histologique de fibrose portale avec quelques septa. L’EASL 2020 demande un traitement urgent de l’hépatite C dès ce stade ; en élastographie, l’EASL 2025 retient en pratique plus de 7 kPa pour une fibrose significative dans l’hépatite B.</p>'+REF_C)
a('PAGE-B', [('P', 'Platelets'), ('AGE', 'Age'), ('-B', 'hépatite B'), ], 'Score de risque de carcinome hépatocellulaire PAGE-B', '<p>Score fondé sur l’âge, le sexe et les plaquettes, destiné aux porteurs de l’Ag HBs traités. Selon l’EASL 2025, un score d’au moins 10 classe une personne sans cirrhose à risque intermédiaire ou élevé, avec échographie tous les six mois.</p>'+REF_B)

REF_SAS = '<p>Source : <a href="https://doi.org/10.1002/hep.21178" target="_blank" rel="noopener">Sterling et coll., Hepatology 2006</a>.</p>'
a('FIB-4', [('FIB', 'FIBrosis, fibrose'), ('-4', 'quatre variables : âge, ASAT, ALAT, plaquettes')], 'Score de fibrose FIB-4', '<p>Indice sanguin de fibrose calculé par âge × ASAT / (plaquettes × racine carrée de l’ALAT). Dans l’hépatite C, une valeur inférieure à 1,45 exclut une fibrose avancée et une valeur supérieure à 3,25 l’affirme ; ses seuils standards sont déconseillés dans l’hépatite B.</p>'+REF_SAS)
a('MELD', [('M', 'Model for'), ('E', 'End-stage'), ('L', 'Liver'), ('D', 'Disease')], 'Modèle de la maladie hépatique terminale', '<p>Score de gravité de l’insuffisance hépatique. Chez les patients dont le score dépasse 20, l’EASL signale un risque rare d’acidose lactique sous analogue nucléos(t)idique.</p>'+REF_B)
a('ASTRAL-1', [('ASTRAL-1', 'nom propre du premier essai de phase III du programme ASTRAL, non un sigle développable')], 'Essai ASTRAL-1 (sofosbuvir/velpatasvir, 2015)', '<p>Essai de phase III : 12 semaines de sofosbuvir/velpatasvir ont guéri 98 % des patients de génotype 1a (206 sur 210).</p>'+REF_C)
a('ASTRAL-4', [('ASTRAL-4', 'nom propre du quatrième essai de phase III du programme ASTRAL, non un sigle développable')], 'Essai ASTRAL-4 (cirrhose décompensée)', '<p>Essai chez des patients en cirrhose décompensée Child-Pugh B : sofosbuvir/velpatasvir 12 semaines avec ou sans ribavirine, ou 24 semaines sans ribavirine.</p>'+REF_C)
a('ENDURANCE-1', [('ENDURANCE-1', 'nom propre d’un essai de phase III du glécaprévir/pibrentasvir, non un sigle développable')], 'Essai ENDURANCE-1 (glécaprévir/pibrentasvir)', '<p>Essai de phase III : 8 semaines de glécaprévir/pibrentasvir ont guéri 99 % des patients de génotype 1a et 100 % des génotypes 1b sans cirrhose.</p>'+REF_C)
a('EXPEDITION-8', [('EXPEDITION-8', 'nom propre d’un essai de phase III du glécaprévir/pibrentasvir, non un sigle développable')], 'Essai EXPEDITION-8 (cirrhose compensée)', '<p>Essai de phase III : 8 semaines de glécaprévir/pibrentasvir ont guéri 98 % de 343 patients naïfs atteints de cirrhose compensée.</p>'+REF_C)
a('MYR202', [('MYR', 'Myrcludex, ancien nom du bulévirtide'), ('202', 'numéro de l’essai de phase II')], 'Essai MYR202 (bulévirtide, phase II)', '<p>Essai de phase II : après 24 semaines de bulévirtide 2 mg, l’ARN du VHD a baissé d’au moins 2 log₁₀ chez 53 % des patients ; 89 % des répondeurs ont rechuté à l’arrêt.</p>'+REF_D)
a('MYR301', [('MYR', 'Myrcludex, ancien nom du bulévirtide'), ('301', 'numéro de l’essai de phase III')], 'Essai MYR301 (bulévirtide, phase III)', '<p>Essai de phase III : à 48 semaines, le bulévirtide 2 mg a fait baisser l’ARN du VHD d’au moins 2 log₁₀ chez 71 % des patients ; la dose de 10 mg n’apportait pas d’avantage.</p>'+REF_D)
