"""Glossaire du cours interne B24 ; les fenêtres portent les références détaillées.

Repères du cycle consultés : NIH HIVinfo, The HIV Life Cycle, revue du
9 avril 2025, consultation du 8 octobre 2026. Les noms de molécules et
de techniques sont développés ici ; doses et décisions restent dans les
fenêtres contextualisées et leurs sources professionnelles.
"""
from cardio_1 import a, G

# Définitions communes bornées à la lecture infectiologique de cet aperçu.
a('VIH', [('V', 'Virus de l’'), ('I', 'Immunodéficience'), ('H', 'Humaine')], 'Virus de l’immunodéficience humaine', '<p>Rétrovirus ciblant notamment les lymphocytes T CD4.</p>')
a('CD3', [('CD', 'Cluster of Differentiation'), ('3', 'numéro de l’antigène')], 'Complexe CD3 des lymphocytes T', '<p>Participe à la transmission du signal du récepteur T.</p>')
a('CD4', [('CD', 'Cluster of Differentiation'), ('4', 'numéro de l’antigène')], 'Antigène de surface CD4', '<p>Marqueur des lymphocytes T auxiliaires, utilisé pour l’évaluation immunitaire.</p>')
a('CD8', [('CD', 'Cluster of Differentiation'), ('8', 'numéro de l’antigène')], 'Antigène de surface CD8', '<p>Marqueur des lymphocytes T cytotoxiques.</p>')
a('ARN', [('A', 'Acide'), ('R', 'Ribo-'), ('N', 'Nucléique')], 'Acide ribonucléique', '<p>Molécule impliquée dans l’expression génétique et support du génome de certains virus.</p>')
a('ADN', [('A', 'Acide'), ('D', 'Désoxyribo-'), ('N', 'Nucléique')], 'Acide désoxyribonucléique', '<p>Support du génome cellulaire et du provirus intégré.</p>')
a('B24', [('B', 'chapitre des maladies infectieuses'), ('24', 'catégorie de classification')], 'Immunodéficience humaine virale [VIH], sans précision', '<p>Libellé CIM-10-GM. Le titre pédagogique du cours ne remplace pas les règles de codage.</p>')
a('VIH-1', [('V', 'Virus de l’'), ('I', 'Immunodéficience'), ('H', 'Humaine'), ('1', 'type 1')], 'Virus de l’immunodéficience humaine de type 1', '<p>Rétrovirus dont la multiplication dépend de cellules hôtes.</p>')
a('VIH-2', [('V', 'Virus de l’'), ('I', 'Immunodéficience'), ('H', 'Humaine'), ('2', 'type 2')], 'Virus de l’immunodéficience humaine de type 2', '<p>Type viral distinct ; tests et traitements doivent lui être adaptés.</p>')
a('SIDA', [('S', 'Syndrome d’'), ('I', 'Immuno-'), ('D', 'Déficience'), ('A', 'Acquise')], 'Syndrome d’immunodéficience acquise', '<p>Stade avancé ; préciser le système de classification utilisé.</p>')
a('ART', [('A', 'Anti'), ('R', 'Retroviral'), ('T', 'Therapy')], 'Traitement antirétroviral', '<p>Association qui bloque plusieurs étapes de multiplication virale.</p>')
a('I=I', [('I', 'Indétectable'), ('=', 'équivaut à'), ('I', 'Intransmissible')], 'Indétectable = intransmissible', '<p>Principe de prévention de la transmission sexuelle sous suppression virale durable.</p>')
a('GALT', [('G', 'Gut-'), ('A', 'Associated'), ('L', 'Lymphoid'), ('T', 'Tissue')], 'Tissu lymphoïde associé à l’intestin', '<p>Compartiment immunitaire de la muqueuse intestinale.</p>')
a('CCR5', [('CC', 'famille CC des chimiokines'), ('R', 'Receptor'), ('5', 'type 5')], 'Récepteur de chimiokines CCR5', '<p>Corécepteur d’entrée de certains variants viraux.</p>')
a('CXCR4', [('CXC', 'famille CXC des chimiokines'), ('R', 'Receptor'), ('4', 'type 4')], 'Récepteur de chimiokines CXCR4', '<p>Autre corécepteur d’entrée ; le tropisme dépend du variant.</p>')
a('INTI', [('I', 'Inhibiteur'), ('N', 'Nucléosidique ou nucléotidique de la'), ('T', 'Transcriptase'), ('I', 'Inverse')], 'Inhibiteur nucléosidique ou nucléotidique de la transcriptase inverse', '<p>Entrave la synthèse d’ADN viral.</p>')
a('INNTI', [('I', 'Inhibiteur'), ('N', 'Non'), ('N', 'Nucléosidique de la'), ('T', 'Transcriptase'), ('I', 'Inverse')], 'Inhibiteur non nucléosidique de la transcriptase inverse', '<p>Inhibe cette enzyme par un mécanisme distinct.</p>')
a('INI', [('INI', 'sigle conventionnel de la classe des inhibiteurs de l’intégrase ; pas trois mots français')], 'Inhibiteur de l’intégrase', '<p>La classe utilisée bloque le transfert de brin.</p>')
a('INSTI', [('IN', 'INtegrase'), ('S', 'Strand'), ('T', 'Transfer'), ('I', 'Inhibitor')], 'Inhibiteur du transfert de brin de l’intégrase', '<p>Empêche l’intégration de l’ADN viral.</p>')
a('IRIS', [('I', 'Immune'), ('R', 'Reconstitution'), ('I', 'Inflammatory'), ('S', 'Syndrome')], 'Syndrome inflammatoire de reconstitution immunitaire', '<p>Réaction inflammatoire associée à la restauration de l’immunité.</p>')
a('TAF', [('TAF', 'code conventionnel du ténofovir alafénamide, non trois mots')], 'Ténofovir alafénamide', '<p>Prodrogue du ténofovir ; distincte du ténofovir disoproxil.</p>')
a('TDF', [('T', 'Ténofovir'), ('D', 'Disoproxil'), ('F', 'Fumarate')], 'Ténofovir disoproxil', '<p>Prodrogue du ténofovir ; formulation distincte de TAF.</p>')
a('FTC', [('FTC', 'code conventionnel de l’emtricitabine, non trois mots')], 'Emtricitabine')
a('3TC', [('3TC', 'code conventionnel de la lamivudine, non trois mots')], 'Lamivudine')
a('DTG', [('DTG', 'code conventionnel du dolutégravir, non trois mots')], 'Dolutégravir')
a('BIC', [('BIC', 'code conventionnel du bictégravir, non trois mots')], 'Bictégravir')
a('NAT', [('N', 'Nucleic'), ('A', 'Acid'), ('T', 'Test')], 'Test d’amplification des acides nucléiques', '<p>Recherche moléculaire à distinguer d’un test sérologique.</p>')
a('CrAg', [('Cr', 'Cryptococcal'), ('Ag', 'Antigen')], 'Antigène cryptococcique')
a('PJP', [('P', 'Pneumocystis'), ('J', 'Jirovecii'), ('P', 'Pneumonia')], 'Pneumonie à Pneumocystis jirovecii')
a('TMP/SMX', [('TMP', 'Triméthoprime'), ('/', 'associé au'), ('SMX', 'Sulfaméthoxazole')], 'Cotrimoxazole, triméthoprime–sulfaméthoxazole')
a('TMP', [('TMP', 'code conventionnel du triméthoprime')], 'Triméthoprime')
a('SMX', [('SMX', 'code conventionnel du sulfaméthoxazole')], 'Sulfaméthoxazole')
a('EACS', [('E', 'European'), ('A', 'AIDS'), ('C', 'Clinical'), ('S', 'Society')], 'European AIDS Clinical Society')
a('MMS', [('M', 'Mortality'), ('M', 'Morbidity'), ('S', 'Statistics')], 'Classification pour les statistiques de mortalité et de morbidité')
a('PrEP', [('Pr', 'Pre-'), ('E', 'Exposure'), ('P', 'Prophylaxis')], 'Prophylaxie préexposition')
a('PEP', [('P', 'Post-'), ('E', 'Exposure'), ('P', 'Prophylaxis')], 'Prophylaxie postexposition')
a('IST', [('I', 'Infections'), ('S', 'Sexuellement'), ('T', 'Transmissibles')], 'Infections sexuellement transmissibles')
a('EDTA', [('E', 'Ethylene'), ('D', 'Diamine'), ('T', 'Tetraacetic'), ('A', 'Acid')], 'Acide éthylènediaminetétraacétique')
a('APHL', [('A', 'Association'), ('P', 'Public'), ('H', 'Health'), ('L', 'Laboratories')], 'Association of Public Health Laboratories')
a('IP', [('I', 'Inhibiteur de'), ('P', 'Protéase')], 'Inhibiteur de protéase')
a('DRV', [('DRV', 'code conventionnel du darunavir')], 'Darunavir')
a('RTV', [('RTV', 'code conventionnel du ritonavir')], 'Ritonavir')
a('COBI', [('COBI', 'code conventionnel du cobicistat')], 'Cobicistat')
a('RPV', [('RPV', 'code conventionnel de la rilpivirine')], 'Rilpivirine')
a('FI', [('FI', 'Fachinformation, abréviation allemande utilisée pour la notice professionnelle')], 'Information professionnelle')
a('HIV', [('H', 'Human'), ('I', 'Immunodeficiency'), ('V', 'Virus')], 'Virus de l’immunodéficience humaine, sigle anglais')
a('HIV-1', [('HIV', 'Human Immunodeficiency Virus'), ('1', 'type 1')], 'VIH de type 1, sigle anglais')
a('HIV-2', [('HIV', 'Human Immunodeficiency Virus'), ('2', 'type 2')], 'VIH de type 2, sigle anglais')
a('RNA', [('R', 'Ribo-'), ('N', 'Nucleic'), ('A', 'Acid')], 'Acide ribonucléique, sigle anglais')
a('MAC', [('M', 'Mycobacterium'), ('A', 'Avium'), ('C', 'Complex')], 'Complexe Mycobacterium avium')
a('HBsAg', [('HB', 'Hepatitis B'), ('s', 'surface'), ('Ag', 'Antigen')], 'Antigène de surface du virus de l’hépatite B')
a('CAB-LA', [('CAB', 'Cabotégravir'), ('LA', 'Long-Acting')], 'Cabotégravir à action prolongée')
a('OCT2', [('O', 'Organic'), ('C', 'Cation'), ('T', 'Transporter'), ('2', 'type 2')], 'Transporteur de cations organiques de type 2')
a('CYP3A', [('CYP', 'Cytochrome P450'), ('3', 'famille 3'), ('A', 'sous-famille A')], 'Sous-famille CYP3A des cytochromes P450')
a('AI', [('A', 'recommandation forte, dans le système NIH'), ('I', 'preuve issue d’au moins un essai randomisé avec critère clinique ou biologique validé')], 'Grade NIH A–I', '<p>La force de la recommandation et la nature des preuves sont deux dimensions distinctes.</p><p><a href="https://clinicalinfo.hiv.gov/en/guidelines/hiv-clinical-guidelines-adult-and-adolescent-opportunistic-infections/introduction" target="_blank" rel="noopener">NIH, système de cotation des recommandations</a>, consulté le 8 octobre 2026.</p>')
a('AII', [('A', 'recommandation forte, dans le système NIH'), ('II', 'preuve non randomisée ou cohorte avec résultats cliniques à long terme ; certaines extrapolations hors VIH')], 'Grade NIH A–II', '<p>Une recommandation forte ne signifie pas automatiquement une preuve randomisée.</p><p><a href="https://clinicalinfo.hiv.gov/en/guidelines/hiv-clinical-guidelines-adult-and-adolescent-opportunistic-infections/introduction" target="_blank" rel="noopener">NIH, système de cotation des recommandations</a>, consulté le 8 octobre 2026.</p>')
