from cardio_1 import a, G
# Glossaire J90 — Épanchements pleuraux (P-02-Pneumologie). Clés absentes du glossaire du dépôt au 08.10.2026.
a('BTS', [('B', 'British'), ('T', 'Thoracic'), ('S', 'Society')], 'British Thoracic Society (Société britannique de pneumologie)', '<p>Société savante britannique de pneumologie. Sa recommandation de 2023 sur les maladies pleurales et sa déclaration clinique de 2023 sur les gestes pleuraux, publiées dans Thorax, servent de référentiel européen principal pour les épanchements.</p>')
a('ECOG', [('E', 'Eastern'), ('C', 'Cooperative'), ('O', 'Oncology'), ('G', 'Group')], 'Échelle de l’Eastern Cooperative Oncology Group', '<p>Échelle de 0 à 5 de l’état fonctionnel d’un patient atteint de cancer : 0 correspond à une activité normale, 4 à un alitement permanent, 5 au décès. Elle entre dans le score LENT.</p>')
a('LENT', [('L', 'LDH pleurale (Lactate déshydrogénase)'), ('E', 'ECOG (état fonctionnel)'), ('N', 'Neutrophil-to-lymphocyte ratio (rapport neutrophiles sur lymphocytes)'), ('T', 'Tumour type (type de tumeur)')], 'Score pronostique LENT de l’épanchement pleural malin', '<p>Score publié en 2014 qui classe les patients atteints d’épanchement malin en risque faible, modéré ou élevé ; les survies médianes étaient de 319, 130 et 44 jours.</p>', 'j90-lent')
a('TIME1', [('T', 'Therapeutic'), ('I', 'Interventions in'), ('M', 'Malignant'), ('E', 'Effusion'), ('1', 'essai numéro 1')], 'Essai TIME1 (2015)', '<p>Essai randomisé britannique de 320 patients : après pleurodèse, un anti-inflammatoire non stéroïdien est non inférieur à un opioïde sur l’échec de la symphyse.</p>', 'j90-ains-pleurodese')
a('TIME2', [('T', 'Therapeutic'), ('I', 'Interventions in'), ('M', 'Malignant'), ('E', 'Effusion'), ('2', 'essai numéro 2')], 'Essai TIME2 (2012)', '<p>Essai randomisé britannique de 106 patients comparant cathéter pleural tunnellisé et talc : dyspnée identique à 42 jours, meilleure à 6 mois avec le cathéter, hospitalisation initiale plus courte.</p>', 'j90-catheter')
a('TAPPS', [('TAPPS', 'nom de l’essai comparant le talc en poudrage et en suspension ; acronyme non développé dans la publication principale')], 'Essai TAPPS (2020)', '<p>Essai randomisé britannique de 330 patients : le poudrage de 4 g de talc en thoracoscopie et la suspension de 4 g par drain donnent le même taux d’échec à 90 jours (22 % et 24 %).</p>', 'j90-talc')
a('AMPLE', [('AMPLE', 'nom de l’essai australasien sur l’épanchement pleural malin ; acronyme non développé lettre à lettre dans la publication')], 'Essai AMPLE (2017)', '<p>Essai randomisé australasien de 146 patients : le cathéter tunnellisé réduit les journées d’hospitalisation et les nouveaux gestes pleuraux par rapport au talc.</p>', 'j90-catheter')
a('IPC-PLUS', [('I', 'Indwelling'), ('P', 'Pleural'), ('C', 'Catheter'), ('PLUS', 'plus talc (nom de l’essai)')], 'Essai IPC-PLUS (2018)', '<p>Essai randomisé britannique : 4 g de talc instillés par le cathéter tunnellisé doublent presque le taux de symphyse au 35e jour (43 % contre 23 %).</p>', 'j90-talc-catheter')
for code, title in [('J94.0', 'Épanchement chyleux (chylothorax)'), ('J94.1', 'Fibrothorax'), ('J94.2', 'Hémothorax non traumatique'), ('J94.8', 'Autres affections pleurales précisées, dont l’hydrothorax'), ('J94.9', 'Affection pleurale, sans précision')]:
    a(code, [(code, 'code CIM-10-GM')], title, '<p>Sous-code de J94 — Autres affections pleurales, développé dans le cours J90 — Épanchements pleuraux.</p>')
a('S27.1', [('S27.1', 'code CIM-10-GM')], 'Hémothorax traumatique', '<p>Code du chapitre des lésions traumatiques. Un hémothorax traumatique ne se code pas en J94.2.</p>', 'j90-hemothorax')
a('Romero-Candeira', [('Romero-Candeira', 'nom propre : Santiago Romero-Candeira, pneumologue espagnol, non une abréviation')], 'Romero-Candeira, auteur d’études sur les critères de Light', '<p>Ses travaux de 2001 et 2002 ont montré que les diurétiques concentrent le liquide pleural cardiaque et réduisent l’exactitude des critères de Light.</p>', 'j90-gradient-albumine')
