"""Sigles propres à A15 — Tuberculose pulmonaire (I-03-Infectiologie)."""
from cardio_1 import a, G

LPS = '<p>Source : <a href="https://www.bag.admin.ch/dam/fr/sd-web/fPW7HAdyOiZ0/tuberkulose-handbuch.pdf" target="_blank" rel="noopener">Ligue pulmonaire suisse et OFSP, Tuberculose en Suisse, V1.2024</a>.</p>'
if 'HRZE' not in G: a('HRZE', [('H', 'isoniazide (de l’allemand <i>Hydrazid</i>, notation internationale)'), ('R', 'Rifampicine'), ('Z', 'pyraZinamide'), ('E', 'Éthambutol')], 'Isoniazide, rifampicine, pyrazinamide et éthambutol', '<p>Notation internationale de la phase intensive du traitement standard de la tuberculose : quatre médicaments chaque jour pendant 2 mois, suivis de 4 mois d’isoniazide et de rifampicine.</p>' + LPS)
if 'B6' not in G: a('B6', [('B', 'vitamine du groupe B'), ('6', 'sixième de la série')], 'Vitamine B6 (pyridoxine)', '<p>Vitamine hydrosoluble donnée avec l’isoniazide pour réduire le risque de neuropathie périphérique.</p>' + LPS)
if 'MTB' not in G: a('MTB', [('M', 'Mycobacterium'), ('T', 'Tu'), ('B', 'Berculosis')], '<i>Mycobacterium tuberculosis</i> (cible du test)', '<p>Composante du test Xpert® MTB/RIF Ultra qui détecte l’ADN du complexe <i>M. tuberculosis</i>.</p>' + LPS)
if 'RIF' not in G: a('RIF', [('RIF', 'RIFampicine')], 'Rifampicine (cible du test)', '<p>Composante du test Xpert® MTB/RIF Ultra qui détecte les mutations du gène <i>rpoB</i> associées à la résistance à la rifampicine.</p>' + LPS)
if 'Ziehl-Neelsen' not in G: a('Ziehl-Neelsen', [('Ziehl', 'Franz Ziehl, bactériologiste allemand'), ('Neelsen', 'Friedrich Neelsen, pathologiste allemand')], 'Coloration de Ziehl-Neelsen (nom propre composé)', '<p>Coloration à chaud par la fuchsine phéniquée, résistante à la décoloration acide et alcoolique, qui colore en rouge les mycobactéries.</p>' + LPS)
if 'katG' not in G: a('katG', [('kat', 'catalase'), ('G', 'désignation du gène')], 'Gène katG (catalase-peroxydase)', '<p>Gène de la catalase-peroxydase qui active l’isoniazide ; ses mutations confèrent une résistance à l’isoniazide (3 à 5 % des cas confirmés en Suisse, 2020–2025).</p>' + LPS)
if 'inhA' not in G: a('inhA', [('inh', 'cible de l’isoniazide (INH)'), ('A', 'désignation du gène')], 'Gène inhA (énoyl-ACP réductase)', '<p>Gène de l’enzyme de synthèse des acides mycoliques inhibée par l’isoniazide ; les mutations de son promoteur confèrent une résistance à l’isoniazide, d’environ 2 % des cas confirmés en Suisse.</p>' + LPS)
