from cardio_1 import a, G

a('SOFA', [('S','Sequential'),('O','Organ'),('F','Failure'),('A','Assessment')], 'Score séquentiel de défaillance d’organe', '<p>Évalue six fonctions : respiration, coagulation, foie, circulation, système nerveux central et rein. Dans Sepsis-3, une augmentation aiguë d’au moins deux points attribuable à une infection est la représentation opérationnelle de la défaillance.</p>', 'a41-sofa')
a('A41', [('A','chapitre des maladies infectieuses de la classification'),('41','catégorie des autres sepsis')], 'Catégorie A41 de la CIM-10-GM', '<p>Autres sepsis ou sepsis d’agent non précisé ; ne couvre pas à elle seule A40 (streptocoques) ni le code complémentaire R57.2 du choc septique.</p>')
a('A40', [('A','chapitre des maladies infectieuses de la classification'),('40','catégorie des sepsis streptococciques')], 'Catégorie A40 de la CIM-10-GM', '<p>Code de la classification pour les sepsis streptococciques, distinct de A41.</p>')
a('R57.2', [('R','chapitre des symptômes, signes et résultats anormaux'),('57.2','sous-catégorie du choc septique')], 'Code R57.2 du choc septique dans la CIM-10-GM', '<p>Code complémentaire selon les règles de la classification en vigueur ; son usage relève d’une documentation diagnostique et de règles de codage applicables au lieu de soins.</p>')
a('SIRS', [('S','Systemic'),('I','Inflammatory'),('R','Response'),('S','Syndrome')], 'Syndrome de réponse inflammatoire systémique', '<p>Des critères inflammatoires peuvent aider au dépistage, mais ne définissent pas à eux seuls le sepsis selon Sepsis-3.</p>')
a('Sepsis-3', [('Sepsis','nom international de la définition de sepsis'),('3','troisième consensus')], 'Troisième consensus international de définition du sepsis', '<p>Consensus publié en 2016 par Singer et collaborateurs ; distingue infection et dysfonction d’organe aiguë attribuable à l’infection.</p>', 'a41-sepsis3')
# Corrections de fusion Claude — 26.09.2026
a('V1a', [('V','Vasopressine'),('1a','récepteur de sous-type 1a')], 'Récepteur V1a de la vasopressine', '<p>Récepteur couplé aux protéines G situé sur le muscle lisse vasculaire ; sa stimulation par la vasopressine (argipressine) provoque une vasoconstriction indépendante des récepteurs adrénergiques. À ne pas confondre avec la dérivation précordiale V1 de l’électrocardiogramme.</p>')
a('R57.0', [('R','chapitre des symptômes, signes et résultats anormaux'),('57.0','sous-catégorie du choc cardiogénique')], 'Code R57.0 du choc cardiogénique dans la CIM-10-GM', '<p>Choc cardiogénique ; relève des cours de cardiologie et non du cours sur le sepsis.</p>')
a('R57.1', [('R','chapitre des symptômes, signes et résultats anormaux'),('57.1','sous-catégorie du choc hypovolémique')], 'Code R57.1 du choc hypovolémique dans la CIM-10-GM', '<p>Choc hypovolémique ; relève d’autres cours que celui du sepsis.</p>')
a('VASST', [('V','Vasopressin'),('A','And'),('S','Septic'),('S','Shock'),('T','Trial')], 'Essai VASST (2008)', '<p>Argipressine 0,01–0,03 unité internationale/min contre supplément de noradrénaline chez 778 patients en choc septique : mortalité à 28 jours 35,4 % contre 39,3 %, différence non significative.</p>')
a('ADRENAL', [('ADRENAL','nom d’essai arrangé à partir de « ADjunctive coRticosteroid trEatment iN criticAlly iLl patients with septic shock », non strictement lettre à lettre')], 'Essai ADRENAL (2018)', '<p>Hydrocortisone 200 mg/jour en perfusion continue pendant 7 jours chez 3 800 patients ventilés en choc septique : mortalité à 90 jours 27,9 % contre 28,8 % sous placebo, résolution plus rapide du choc.</p>')
a('APROCCHSS', [('A','Activated'),('PRO','PROtein'),('C','C and'),('C','Corticosteroids for'),('H','Human'),('S','Septic'),('S','Shock')], 'Essai APROCCHSS (2018)', '<p>Hydrocortisone 50 mg toutes les 6 heures et fludrocortisone 50 µg par jour pendant 7 jours chez 1 241 patients en choc septique : mortalité à 90 jours 43,0 % contre 49,1 % sous placebo.</p>')
a('SEPSISPAM', [('SEPSIS','sepsis'),('PAM','Pression Artérielle Moyenne')], 'Essai SEPSISPAM (2014)', '<p>Essai français : pression artérielle moyenne cible de 80–85 mmHg contre 65–70 mmHg chez 776 patients en choc septique, sans différence de mortalité à 28 jours (36,6 % contre 34,0 %).</p>')
a('MERINO', [('MERINO','nom d’essai tiré du titre « MEropenem versus piperacillin-tazobactam for definitive treatment of bloodstream infections due to ceftriaxone non-susceptible Escherichia coli and Klebsiella spp », non strictement lettre à lettre')], 'Essai MERINO (2018)', '<p>Pipéracilline/tazobactam contre méropénem dans les bactériémies à entérobactéries résistantes à la ceftriaxone : mortalité à 30 jours 12,3 % contre 3,7 %, non-infériorité non démontrée.</p>')
a('BLING', [('B','Beta'),('L','Lactam'),('IN','InfusioN'),('G','Group')], 'Essais BLING (Beta-Lactam InfusioN Group)', '<p>BLING III (2024) : perfusion continue contre intermittente de pipéracilline/tazobactam ou de méropénem chez 7 031 patients en sepsis ; mortalité à 90 jours 24,9 % contre 26,8 %, différence non significative ; guérison clinique plus fréquente.</p>')
a('Solu-Cortef', [('Solu-Cortef','nom commercial composé d’une hydrocortisone injectable, non une abréviation')], 'Solu-Cortef, hydrocortisone injectable', '<p>Hydrogénosuccinate sodique d’hydrocortisone, substance sèche de 100 mg avec 2 mL de solvant, pour injection ou perfusion intraveineuse ; ses indications suisses comprennent le choc (compendium.ch).</p>')
