"""Sigles propres à A54 — Infection gonococcique (I-03-Infectiologie)."""
from cardio_1 import a, G

SSI = '<p>Source : <a href="https://ssi.guidelines.ch/guideline/2272/fr" target="_blank" rel="noopener">SSI, « Gonococcie », validée le 8 mai 2024</a>.</p>'
OFSP = '<p>Source : <a href="https://www.bag.admin.ch/dam/fr/sd-web/jB29Qf2x7Jme/BU_44_25_FR.pdf" target="_blank" rel="noopener">OFSP, Bulletin 44/2025, données de 2024</a>.</p>'
ECDC = '<p>Source : <a href="https://www.ecdc.europa.eu/sites/default/files/documents/ra-ceftriaxone-neisseria-gonorrhoeae.pdf" target="_blank" rel="noopener">ECDC, évaluation du risque du 16 juillet 2026</a>.</p>'
IUSTI_SRC = '<p>Source : <a href="https://iusti.org/wp-content/uploads/2020/10/IUSTI-Gonorrhoea-2020.pdf" target="_blank" rel="noopener">Unemo M et al., 2020 European guideline for the diagnosis and treatment of gonorrhoea in adults, Int J STD AIDS 2020</a>.</p>'
ALCOTT = '<p>Source : <a href="https://doi.org/10.1128/jb.00035-22" target="_blank" rel="noopener">Alcott AM et al., J Bacteriol 2022</a>.</p>'

a('TAAN', [('T', 'Test'), ('A', 'd’Amplification'), ('A', 'des Acides'), ('N', 'Nucléiques')], 'Test d’amplification des acides nucléiques', '<p>Recherche, le plus souvent par PCR, d’une séquence d’ADN propre au gonocoque dans le prélèvement. Sensibilité supérieure à 95 % ; le test ne mesure ni la sensibilité aux antibiotiques ni la viabilité de la bactérie.</p>' + IUSTI_SRC)
a('HSH', [('H', 'Hommes'), ('S', 'ayant des relations Sexuelles'), ('H', 'avec des Hommes')], 'Hommes ayant des relations sexuelles avec des hommes', '<p>Catégorie épidémiologique définie par les pratiques, non par l’identité. En Suisse en 2024, elle représentait 58,3 % des gonorrhées de voie connue, pour environ 3 % de la population masculine sexuellement active.</p>' + OFSP)
a('ANRESIS', [('ANRESIS', 'nom propre du Centre suisse pour le contrôle de l’antibiorésistance, non développable lettre à lettre')], 'Centre suisse pour le contrôle de l’antibiorésistance', '<p>Réseau national de surveillance des résistances bactériennes. En 2024, 70 % des gonocoques suisses surveillés résistaient aux quinolones et 21 % à l’azithromycine.</p>' + OFSP)
a('J7', [('J', 'Jour'), ('7', 'septième jour après le traitement')], 'Septième jour après le traitement', '<p>Date du contrôle microbiologique recommandé par la SSI après le traitement d’une gonococcie.</p>' + SSI)
a('Opa', [('Opa', 'opacity-associated (associées à l’opacité des colonies), nom de famille de protéines, non développable lettre à lettre')], 'Protéines d’opacité de Neisseria gonorrhoeae', '<p>Adhésines et invasines de la membrane externe, soumises à une variation de phase. La plupart se lient aux récepteurs humains CEACAM.</p>' + ALCOTT)
a('PilE', [('Pil', 'piline'), ('E', 'lettre du gène de la sous-unité majeure')], 'Piline majeure du pilus de type IV', '<p>Sous-unité principale du pilus gonococcique. Sa séquence varie par recombinaison programmée : c’est la variation antigénique.</p><p>Source : <a href="https://doi.org/10.1021/acs.biochem.9b01038" target="_blank" rel="noopener">Prister LL et al., Biochemistry 2020</a>.</p>')
a('CEACAM', [('C', 'Carcino-'), ('E', 'Embryonic'), ('A', 'Antigen-related'), ('C', 'Cell'), ('A', 'Adhesion'), ('M', 'Molecule')], 'Molécule d’adhérence cellulaire apparentée à l’antigène carcino-embryonnaire', '<p>Famille de récepteurs humains auxquels se lient la plupart des protéines Opa du gonocoque.</p>' + ALCOTT)
a('CEACAM1', [('CEACAM', 'molécule d’adhérence cellulaire apparentée à l’antigène carcino-embryonnaire'), ('1', 'membre 1')], 'Récepteur CEACAM1', '<p>Récepteur exprimé notamment par les neutrophiles et les cellules épithéliales, lié par certaines protéines Opa.</p>' + ALCOTT)
a('CEACAM3', [('CEACAM', 'molécule d’adhérence cellulaire apparentée à l’antigène carcino-embryonnaire'), ('3', 'membre 3')], 'Récepteur CEACAM3', '<p>Récepteur propre aux granulocytes. Les gonocoques dont l’Opa le lie sont davantage phagocytés et tués par les neutrophiles.</p>' + ALCOTT)
a('PBP2', [('P', 'Penicillin'), ('B', 'Binding'), ('P', 'Protein'), ('2', 'numéro 2')], 'Protéine liant la pénicilline 2', '<p>Enzyme de la synthèse du peptidoglycane et cible de la ceftriaxone chez le gonocoque ; codée par le gène penA.</p>' + ECDC)
a('penA', [('pen', 'pénicilline'), ('A', 'premier gène décrit de ce locus')], 'Gène de la protéine liant la pénicilline 2', '<p>Ses allèles mosaïques, notamment 60.001 et 237.001, portent la résistance à la ceftriaxone des souches européennes de 2025 et 2026.</p>' + ECDC)
a('gyrA', [('gyr', 'gyrase'), ('A', 'sous-unité A')], 'Gène de la sous-unité A de l’ADN gyrase', '<p>Ses mutations modifient la cible des fluoroquinolones et rendent la ciprofloxacine inefficace.</p><p>Source : <a href="https://www.swissmedicinfo.ch/ShowText.aspx?textType=FI&amp;lang=FR&amp;authNr=47795" target="_blank" rel="noopener">Information professionnelle suisse Ciproxine®, août 2025</a>.</p>')
a('ARNr', [('ARN', 'Acide RiboNucléique'), ('r', 'ribosomique')], 'ARN ribosomique', '<p>Constituant des ribosomes. Des mutations de l’ARN ribosomique 23S contribuent à la résistance à l’azithromycine.</p><p>Source : <a href="https://doi.org/10.3390/ijms27052258" target="_blank" rel="noopener">Shaskolskiy B et al., Int J Mol Sci 2026</a>.</p>')
a('PorB', [('Por', 'porine'), ('B', 'type B')], 'Porine B de la membrane externe', '<p>Canal de la membrane externe du gonocoque ; certains variants réduisent l’entrée de l’azithromycine et participent à sa résistance.</p><p>Source : <a href="https://doi.org/10.3390/ijms27052258" target="_blank" rel="noopener">Shaskolskiy B et al., Int J Mol Sci 2026</a>.</p>')
a('IL-8', [('IL', 'InterLeukine'), ('8', 'numéro 8')], 'Interleukine 8', '<p>Cytokine qui attire les polynucléaires neutrophiles. Dans un modèle cornéen, l’infection gonococcique en augmentait la sécrétion.</p><p>Source : <a href="https://doi.org/10.1128/iai.00735-25" target="_blank" rel="noopener">Kafuri L et al., Infect Immun 2026</a>.</p>')
a('Doxycyclin-Mepha', [('Doxycyclin-Mepha', 'nom commercial suisse, non développable lettre à lettre')], 'Spécialité suisse de doxycycline (Mepha Pharma)', '<p>Comprimés de doxycycline dont l’information professionnelle suisse (février 2024) fonde les doses et les précautions citées dans ce cours.</p><p>Source : <a href="https://www.swissmedicinfo.ch/ShowText.aspx?textType=FI&amp;lang=FR&amp;authNr=65952" target="_blank" rel="noopener">Information professionnelle suisse Doxycyclin-Mepha®</a>.</p>')
