"""Sigles propres à B50 — Paludisme (I-03-Infectiologie)."""
from cardio_1 import a, G

WHO = '<p>Source : <a href="https://iris.who.int/server/api/core/bitstreams/26a6af2d-060c-4449-8207-1f25e63c6cc3/content" target="_blank" rel="noopener">OMS, WHO guidelines for malaria, 13 août 2025</a>.</p>'
CEMV = '<p>Source : <a href="https://www.bag.admin.ch/dam/fr/sd-web/KtpVYMPLq-by/malaria-nsb-prophylaxe.pdf" target="_blank" rel="noopener">Bull OFSP 2019;30:8-12</a>.</p>'
if 'CEMV' not in G: a('CEMV', [('C', 'Comité'), ('E', 'd’Experts'), ('M', 'en Médecine'), ('V', 'des Voyages')], 'Comité suisse d’experts en médecine des voyages', '<p>Comité qui élabore, avec la commission allemande de médecine des voyages, les recommandations suisses de prévention du paludisme publiées par l’OFSP.</p>' + CEMV)
if 'CTA' not in G: a('CTA', [('C', 'Combinaison'), ('T', 'Thérapeutique'), ('A', 'à base d’Artémisinine')], 'Combinaison thérapeutique à base d’artémisinine', '<p>Association d’un dérivé de l’artémisinine, d’action rapide, et d’une molécule partenaire d’élimination lente, administrée pendant 3 jours ; traitement recommandé par l’OMS du paludisme non compliqué à <i>P. falciparum</i>.</p>' + WHO)
if 'G6PD' not in G: a('G6PD', [('G', 'Glucose'), ('6', '-6-'), ('P', 'Phosphate'), ('D', 'Déshydrogénase')], 'Glucose-6-phosphate déshydrogénase', '<p>Enzyme érythrocytaire de la voie des pentoses phosphates ; son déficit expose à une hémolyse sous primaquine ou tafénoquine, d’où la détermination du statut avant ces médicaments.</p>' + WHO)
if 'PfHRP2' not in G: a('PfHRP2', [('Pf', '<i>Plasmodium falciparum</i>'), ('H', 'Histidine'), ('R', 'Rich (riche)'), ('P', 'Protein (protéine)'), ('2', 'type 2')], 'Protéine 2 riche en histidine de <i>Plasmodium falciparum</i>', '<p>Antigène spécifique de <i>P. falciparum</i> détecté par les tests de diagnostic rapide ; il persiste après un traitement incomplet, ce qui rend le test utile lorsque le frottis est négatif.</p>' + WHO)
if 'pLDH' not in G: a('pLDH', [('p', 'plasmodiale'), ('L', 'Lactate'), ('D', 'Déshydrogénase'), ('H', '(H de l’anglais <i>dehydrogenase</i>)')], 'Lactate déshydrogénase plasmodiale', '<p>Enzyme du parasite détectée par certains tests de diagnostic rapide, sous forme spécifique de <i>P. vivax</i> ou commune à toutes les espèces (pan-pLDH).</p>' + WHO)
if 'mEq' not in G: a('mEq', [('m', 'milli'), ('Eq', 'Équivalent')], 'Milliéquivalent', '<p>Unité de quantité de charge ionique ; le déficit en bases du paludisme grave s’exprime en mEq/L, un déficit supérieur à 8 mEq/L étant un critère de gravité de l’OMS.</p>' + WHO)
for c, t in [('B51', 'Paludisme à <i>Plasmodium vivax</i>'), ('B52', 'Paludisme à <i>Plasmodium malariae</i>'), ('B53.0', 'Paludisme à <i>Plasmodium ovale</i>'), ('B53.1', 'Paludisme à plasmodies simiennes'), ('B54', 'Paludisme, sans précision')]:
    if c not in G: a(c, [(c, 'code de la CIM-10-GM 2024')], t, '<p>Code de la classification internationale des maladies, 10e révision, modification allemande 2024 (édition française OFS).</p>')
