from cardio_1 import a, G
# C45 — Mésothéliome (P-02-Pneumologie). Clés absentes du glossaire au 09.10.2026.
a('BAP1', [('BAP', 'BRCA1-Associated Protein (protéine associée à BRCA1)'), ('1', 'numéro 1')], 'Protéine 1 associée à BRCA1', '<p>Enzyme nucléaire de désubiquitination qui participe à la réparation de l’ADN ; sa perte en immunohistochimie est un argument de malignité dans une prolifération mésothéliale.</p>', 'c45-bap1')
a('CDKN2A', [('CDK', 'Cyclin-Dependent Kinase (kinase dépendante des cyclines)'), ('N', 'iNhibitor (inhibiteur)'), ('2A', 'famille 2, membre A')], 'Inhibiteur 2A des kinases dépendantes des cyclines', '<p>Gène suppresseur de tumeur situé en 9p21.3, qui code la protéine p16 ; sa délétion homozygote est fréquente dans le mésothéliome, surtout sarcomatoïde.</p>', 'c45-bap1')
a('MTAP', [('M', 'Méthyl'), ('T', 'Thio'), ('A', 'Adénosine'), ('P', 'Phosphorylase')], 'Méthylthioadénosine phosphorylase', '<p>Enzyme dont le gène jouxte CDKN2A ; la perte de son marquage en immunohistochimie sert de témoin de la délétion de CDKN2A (spécificité 96 %, sensibilité 78 %, ESMO 2022).</p>', 'c45-bap1')
a('WT-1', [('W', 'Wilms'), ('T', 'Tumour (tumeur)'), ('1', 'gène 1')], 'Protéine du gène 1 de la tumeur de Wilms', '<p>Facteur de transcription nucléaire exprimé par les cellules mésothéliales ; son marquage est un marqueur positif de la lignée mésothéliale.</p>', 'c45-ihc')
a('Ber-EP4', [('Ber-EP4', 'nom de clone d’anticorps, non développable lettre à lettre')], 'Anticorps Ber-EP4 dirigé contre la molécule d’adhésion épithéliale', '<p>Anticorps monoclonal qui reconnaît la molécule d’adhésion des cellules épithéliales ; il marque la plupart des adénocarcinomes et rarement le mésothéliome.</p>', 'c45-ihc')
a('MOC-31', [('MOC-31', 'nom de clone d’anticorps, non développable lettre à lettre')], 'Anticorps MOC-31 dirigé contre la molécule d’adhésion épithéliale', '<p>Anticorps monoclonal utilisé comme marqueur de carcinome dans le panel qui distingue un mésothéliome d’une métastase.</p>', 'c45-ihc')
a('ESTRO', [('E', 'European (européenne)'), ('S', 'Society for (société de)'), ('T', 'Therapeutic (thérapeutique)'), ('R', 'Radiology (radiologie)'), ('O', 'and Oncology (et oncologie)')], 'Société européenne de radiologie thérapeutique et d’oncologie, aujourd’hui société européenne de radiothérapie et d’oncologie', '<p>Société savante européenne de radiothérapie, coautrice des recommandations de 2020 sur le mésothéliome pleural avec l’ERS, l’ESTS et l’EACTS.</p>')
