# Glossaire MEDINA — abréviations (partie 1 : clinique, examens, pharmacologie)
# format : clé -> (lit=[(lettres, développement)], full, def_html, ref_popup)
G = {}
def a(k, lit, full, d='', ref=None):
    G[k] = {'lit': [list(x) for x in lit], 'full': full, 'def': d, 'ref': ref}

a('FEVG',[('F','Fraction'),('E','d’Éjection'),('V','du Ventricule'),('G','Gauche')],'Fraction d’éjection du ventricule gauche',
 '<p>Pourcentage du volume télédiastolique du ventricule gauche éjecté à chaque systole : (volume télédiastolique − volume télésystolique) / volume télédiastolique. Normale ≥ 50 % (ESC 2026). Mesurée par échocardiographie (méthode de Simpson biplan) ou par IRM, qui est la référence.</p>','echo')
a('ICFEr',[('I','Insuffisance'),('C','Cardiaque'),('F','à Fraction'),('E','d’Éjection'),('r','réduite')],'Insuffisance cardiaque à fraction d’éjection réduite',
 '<p>Depuis l’ESC 2026 : FEVG &lt; 50 %. Équivalent anglais : HFrEF. Relève de la thérapie médicamenteuse fondamentale à quatre classes.</p>')
a('ICFEp',[('I','Insuffisance'),('C','Cardiaque'),('F','à Fraction'),('E','d’Éjection'),('p','préservée')],'Insuffisance cardiaque à fraction d’éjection préservée',
 '<p>FEVG ≥ 50 % avec des preuves objectives de pressions de remplissage élevées. Équivalent anglais : HFpEF. Maladie souvent systémique (obésité, hypertension, diabète).</p>','h2fpef')
a('HFrEF',[('H','Heart'),('F','Failure'),('r','with reduced'),('E','Ejection'),('F','Fraction')],'Heart failure with reduced ejection fraction (insuffisance cardiaque à fraction d’éjection réduite)',
 '<p>Terme anglais de l’ICFEr ; FEVG &lt; 50 % depuis l’ESC 2026.</p>')
a('HFpEF',[('H','Heart'),('F','Failure'),('p','with preserved'),('E','Ejection'),('F','Fraction')],'Heart failure with preserved ejection fraction (insuffisance cardiaque à fraction d’éjection préservée)',
 '<p>Terme anglais de l’ICFEp ; FEVG ≥ 50 %.</p>')
a('HFmrEF',[('H','Heart'),('F','Failure'),('mr','with mildly reduced'),('E','Ejection'),('F','Fraction')],'Heart failure with mildly reduced ejection fraction (insuffisance cardiaque à fraction d’éjection légèrement réduite)',
 '<p>Ancienne catégorie intermédiaire (FEVG 41–49 %), supprimée par l’ESC 2026 et fusionnée avec l’ICFEr.</p>')
a('IC',[('I','Insuffisance'),('C','Cardiaque')],'Insuffisance cardiaque','<p>Syndrome clinique associant symptômes, signes et anomalie cardiaque structurelle ou fonctionnelle, avec preuve objective (peptide natriurétique élevé ou congestion).</p>')
a('NT-proBNP',[('N','N-'),('T','Terminal (extrémité amino-terminale)'),('pro','du propeptide'),('B','de type B'),('N','Natriuretic (natriurétique)'),('P','Peptide')],'Fragment N-terminal du propeptide natriurétique de type B',
 '<p>Fragment inactif libéré à parts égales avec le BNP lors du clivage du pro-BNP. Éliminé surtout par le rein, non dégradé par la néprilysine : c’est le marqueur à suivre sous sacubitril/valsartan.</p>','np')
a('BNP',[('B','B-type (de type B ; historiquement « Brain », car découvert dans le cerveau de porc)'),('N','Natriuretic (natriurétique)'),('P','Peptide')],'Peptide natriurétique de type B',
 '<p>Hormone active sécrétée par les cardiomyocytes ventriculaires étirés : natriurèse, vasodilatation, inhibition du SRAA. Dégradée par la néprilysine.</p>','np')
a('pro-BNP',[('pro','propeptide (précurseur)'),('B','de type B'),('N','Natriurétique'),('P','Peptide')],'Propeptide natriurétique de type B','<p>Précurseur clivé par la corine et la furine en BNP actif et NT-proBNP inactif.</p>','np')
a('pré-pro-BNP',[('pré','pré- (porteur du peptide signal)'),('pro','propeptide'),('B','de type B'),('N','Natriurétique'),('P','Peptide')],'Pré-propeptide natriurétique de type B','<p>Forme initiale synthétisée dans le cardiomyocyte ; la perte du peptide signal donne le pro-BNP.</p>','np')
a('NPR-A',[('N','Natriuretic'),('P','Peptide'),('R','Receptor'),('A','type A')],'Récepteur des peptides natriurétiques de type A','<p>Récepteur à activité guanylate cyclase : sa stimulation par le BNP produit du GMPc (natriurèse, vasodilatation).</p>')
a('NPR-C',[('N','Natriuretic'),('P','Peptide'),('R','Receptor'),('C','type C (clairance)')],'Récepteur de clairance des peptides natriurétiques','<p>Internalise et dégrade les peptides natriurétiques ; voie d’élimination du BNP avec la néprilysine.</p>')
a('ESC',[('E','European'),('S','Society of'),('C','Cardiology')],'European Society of Cardiology (Société européenne de cardiologie)',
 '<p>Société savante qui publie les recommandations européennes de cardiologie, reprises par la Société suisse de cardiologie. Recommandations de l’insuffisance cardiaque : 2021, mise à jour 2023, puis ESC 2026 (28.08.2026).</p>')
a('NYHA',[('N','New'),('Y','York'),('H','Heart'),('A','Association')],'New York Heart Association','<p>Société savante américaine ayant proposé la classification fonctionnelle en quatre classes de la dyspnée cardiaque.</p>','nyha')
a('ECG',[('É','Électro-'),('C','Cardio-'),('G','Gramme')],'Électrocardiogramme','<p>Enregistrement de l’activité électrique du cœur par 12 dérivations. Un ECG normal rend une ICFEr très improbable.</p>','ecg-ic')
a('QRS',[('Q','onde Q (première déflexion négative)'),('R','onde R (première déflexion positive)'),('S','onde S (déflexion négative après R)')],'Complexe QRS de l’électrocardiogramme',
 '<p>Dépolarisation ventriculaire ; durée normale &lt; 120 ms. Un QRS ≥ 150 ms avec aspect de bloc de branche gauche signe un asynchronisme accessible à la resynchronisation.</p>','crt')
a('ST',[('S','fin de l’onde S'),('T','début de l’onde T')],'Segment ST de l’électrocardiogramme','<p>Segment compris entre la fin du QRS et le début de l’onde T ; ses déplacements traduisent une ischémie ou une lésion myocardique.</p>')
a('BBG',[('B','Bloc'),('B','de Branche'),('G','Gauche')],'Bloc de branche gauche','<p>Retard de conduction dans la branche gauche du faisceau de His : QRS ≥ 120 ms, aspect QS ou rS en V1, R large crocheté en V6. Crée un asynchronisme de contraction.</p>','crt')
a('IRM',[('I','Imagerie'),('R','par Résonance'),('M','Magnétique')],'Imagerie par résonance magnétique','<p>Référence pour les volumes, la FEVG et la caractérisation tissulaire myocardique.</p>','irm')
a('Ciné-IRM',[('Ciné','Cinématographique (images animées)'),('I','Imagerie'),('R','par Résonance'),('M','Magnétique')],'Imagerie par résonance magnétique en mode cinématographique','<p>Séquences animées sur le cycle cardiaque : mesure de référence des volumes et de la FEVG.</p>','irm')
a('T1',[('T','Temps de relaxation'),('1','longitudinale')],'Temps de relaxation longitudinale (IRM)','<p>Le T1 natif augmente avec la fibrose, l’œdème et l’amylose ; le calcul du volume extracellulaire en dérive.</p>','irm')
a('T2',[('T','Temps de relaxation'),('2','transversale')],'Temps de relaxation transversale (IRM)','<p>Le T2 augmente avec l’œdème myocardique (myocardite, infarctus aigu).</p>','irm')
a('GLS',[('G','Global'),('L','Longitudinal'),('S','Strain')],'Strain longitudinal global','<p>Déformation longitudinale moyenne du ventricule gauche en systole, mesurée par suivi des marqueurs acoustiques. Normale plus négative que −18 % environ ; s’altère avant la FEVG.</p>','echo')
a('TAPSE',[('T','Tricuspid'),('A','Annular'),('P','Plane'),('S','Systolic'),('E','Excursion')],'Excursion systolique du plan de l’anneau tricuspide','<p>Déplacement systolique de l’anneau tricuspide vers l’apex, mesuré en mode TM. Normale ≥ 17 mm ; plus basse : dysfonction ventriculaire droite.</p>','echo')
a('E/e′',[('E','onde E : vitesse du flux mitral en début de diastole (Early)'),('e′','e prime : vitesse tissulaire de l’anneau mitral en début de diastole')],'Rapport de l’onde E mitrale sur la vitesse tissulaire e′',
 '<p>Estimation non invasive de la pression de remplissage du ventricule gauche : moyenne &lt; 9 normale, &gt; 14 élevée.</p>','echo')
a('OG',[('O','Oreillette'),('G','Gauche')],'Oreillette gauche','<p>Son volume indexé (normal ≤ 34 mL/m²) intègre la chronicité des pressions de remplissage élevées.</p>','echo')
a('VG',[('V','Ventricule'),('G','Gauche')],'Ventricule gauche')
a('VD',[('V','Ventricule'),('D','Droit')],'Ventricule droit')
a('POD',[('P','Pression'),('O','de l’Oreillette'),('D','Droite')],'Pression de l’oreillette droite','<p>Normale ≤ 8 mmHg ; reflet de la pression veineuse centrale ; estimée cliniquement par la turgescence jugulaire.</p>','e-jugulaire')
a('PTD',[('P','Pression'),('T','Télé-'),('D','Diastolique')],'Pression télédiastolique','<p>Pression intraventriculaire en fin de diastole ; reflet de la précharge et de la compliance.</p>','pvloop')
a('RPVTS',[('R','Relation'),('P','Pression-'),('V','Volume'),('T','Télé-'),('S','Systolique')],'Relation pression-volume télésystolique','<p>Droite reliant les points télésystoliques pour différentes charges ; sa pente (élastance) mesure la contractilité.</p>','pvloop')
a('RPVTD',[('R','Relation'),('P','Pression-'),('V','Volume'),('T','Télé-'),('D','Diastolique')],'Relation pression-volume télédiastolique','<p>Courbe exponentielle ; sa raideur reflète la compliance ventriculaire, anormalement raide dans l’ICFEp.</p>','pvloop')
a('PAS',[('P','Pression'),('A','Artérielle'),('S','Systolique')],'Pression artérielle systolique','<p>&lt; 90 mmHg avec hypoperfusion : choc ; &gt; 110 mmHg en décompensation : vasodilatateurs possibles.</p>','v-ta')
a('PA',[('P','Pression'),('A','Artérielle')],'Pression artérielle','','v-ta')
a('PAPS',[('P','Pression'),('A','Artérielle'),('P','Pulmonaire'),('S','Systolique')],'Pression artérielle pulmonaire systolique','<p>Estimée en échocardiographie à partir de la vitesse de l’insuffisance tricuspide (4V² + pression de l’oreillette droite).</p>')
a('PAPi',[('P','Pulmonary'),('A','Artery'),('P','Pulsatility'),('i','index')],'Index de pulsatilité de l’artère pulmonaire','<p>(Pression artérielle pulmonaire systolique − diastolique) / pression de l’oreillette droite. &lt; 1,85 : défaillance ventriculaire droite probable.</p>')
a('FA',[('F','Fibrillation'),('A','Auriculaire')],'Fibrillation auriculaire','<p>Arythmie auriculaire désorganisée ; cause et conséquence fréquente de l’insuffisance cardiaque ; élève les peptides natriurétiques.</p>')
a('FC',[('F','Fréquence'),('C','Cardiaque')],'Fréquence cardiaque')
a('B2',[('B','Bruit'),('2','deuxième')],'Deuxième bruit du cœur','<p>Fermeture des valves aortique et pulmonaire, début de la diastole.</p>')
a('B3',[('B','Bruit'),('3','troisième')],'Troisième bruit du cœur','<p>Bruit protodiastolique sourd, à la pointe ; très spécifique d’une dysfonction ventriculaire après 40 ans.</p>','e-b3')
a('SpO₂',[('S','Saturation'),('p','pulsée (mesurée par oxymétrie de pouls)'),('O₂','en dioxygène')],'Saturation pulsée en oxygène','<p>Estimation non invasive de la saturation artérielle en oxygène ; oxygène indiqué si &lt; 90 % en décompensation.</p>')
a('O₂',[('O','Oxygène'),('₂','deux atomes (molécule de dioxygène)')],'Dioxygène')
a('VO₂',[('V','Volume (débit)'),('O₂','d’oxygène consommé')],'Consommation d’oxygène','<p>Mesurée à l’épreuve cardiorespiratoire ; le pic (VO₂ pic) exprime la capacité aérobie maximale.</p>','cpet')
a('VE/VCO₂',[('VE','Ventilation minute Expirée'),('VCO₂','production de dioxyde de carbone')],'Pente ventilation / production de dioxyde de carbone','<p>Efficacité ventilatoire ; &gt; 35 : pronostic défavorable dans l’insuffisance cardiaque.</p>','cpet')
a('DFG',[('D','Débit'),('F','de Filtration'),('G','Glomérulaire')],'Débit de filtration glomérulaire','<p>Estimé par l’équation CKD-EPI à partir de la créatinine ; normal ≥ 90, insuffisance rénale si &lt; 60 mL/min/1,73 m² pendant plus de 3 mois.</p>')
a('CKD-EPI',[('C','Chronic'),('K','Kidney'),('D','Disease'),('EPI','EPIdemiology collaboration')],'Chronic Kidney Disease Epidemiology Collaboration','<p>Groupe ayant établi l’équation d’estimation du DFG utilisée en routine.</p>')
a('Hb',[('H','Hémo-'),('b','-globine')],'Hémoglobine','<p>Anémie si Hb &lt; 130 g/L (homme) ou &lt; 120 g/L (femme) selon l’OMS.</p>')
a('HbA1c',[('H','Hémo-'),('b','-globine'),('A1c','fraction A1c, glyquée')],'Hémoglobine glyquée','<p>Reflet de la glycémie moyenne des 2 à 3 derniers mois ; diabète si ≥ 6,5 % (48 mmol/mol).</p>')
a('TSH',[('T','Thyroid-'),('S','Stimulating'),('H','Hormone')],'Thyréostimuline (hormone thyréotrope)','<p>Dosage de dépistage des dysthyroïdies, causes curables d’insuffisance cardiaque.</p>')
a('IMC',[('I','Indice'),('M','de Masse'),('C','Corporelle')],'Indice de masse corporelle','<p>Poids (kg) / taille² (m²). Obésité si ≥ 30 kg/m².</p>')
a('K⁺',[('K','Kalium (nom latin du potassium)'),('⁺','ion chargé positivement')],'Ion potassium','<p>Kaliémie normale 3,5–5,0 mmol/L ; cible 4,0–5,0 sous thérapie fondamentale.</p>')
a('Na⁺',[('Na','Natrium (nom latin du sodium)'),('⁺','ion chargé positivement')],'Ion sodium','<p>Natrémie normale 135–145 mmol/L ; l’hyponatrémie est un marqueur pronostique péjoratif.</p>')
a('HBPM',[('H','Héparine'),('B','de Bas'),('P','Poids'),('M','Moléculaire')],'Héparine de bas poids moléculaire','<p>Anticoagulant injectable ; en prophylaxie chez le patient hospitalisé et alité.</p>')
a('VNI',[('V','Ventilation'),('N','Non'),('I','Invasive')],'Ventilation non invasive','<p>Ventilation en pression positive au masque ; réduit le travail respiratoire et la précharge dans l’œdème pulmonaire.</p>')
a('DAI',[('D','Défibrillateur'),('A','Automatique'),('I','Implantable')],'Défibrillateur automatique implantable','','dai')
a('CRT',[('C','Cardiac'),('R','Resynchronization'),('T','Therapy')],'Thérapie de resynchronisation cardiaque','','crt')
a('TEER',[('T','Transcatheter'),('E','Edge-to-'),('E','Edge'),('R','Repair')],'Réparation valvulaire bord à bord par voie percutanée',
 '<p>Rapprochement des feuillets mitraux par un clip introduit par voie veineuse fémorale et transseptale. Indiqué dans l’insuffisance mitrale secondaire sévère persistante sous traitement optimal (critères de l’essai COAPT).</p>')
a('TAVI',[('T','Transcatheter'),('A','Aortic'),('V','Valve'),('I','Implantation')],'Implantation d’une valve aortique par voie percutanée','<p>Traitement du rétrécissement aortique sévère, alternative à la chirurgie selon l’âge et le risque.</p>')
a('SRAA',[('S','Système'),('R','Rénine-'),('A','Angiotensine-'),('A','Aldostérone')],'Système rénine-angiotensine-aldostérone','','raas')
a('ECA',[('E','Enzyme'),('C','de Conversion'),('A','de l’Angiotensine')],'Enzyme de conversion de l’angiotensine','<p>Dipeptidyl-carboxypeptidase qui transforme l’angiotensine I en angiotensine II et dégrade la bradykinine.</p>','raas')
a('AT1',[('AT','récepteur de l’AngioTensine II'),('1','de type 1')],'Récepteur de type 1 de l’angiotensine II','<p>Récepteur couplé à la protéine Gq : vasoconstriction, aldostérone, hypertrophie, fibrose. Bloqué par les ARA II et le valsartan.</p>','raas')
a('RM',[('R','Récepteur'),('M','Minéralocorticoïde')],'Récepteur minéralocorticoïde','<p>Récepteur nucléaire de l’aldostérone, bloqué par les ARM.</p>','d-arm')
a('IEC',[('I','Inhibiteur'),('E','de l’Enzyme'),('C','de Conversion')],'Inhibiteur de l’enzyme de conversion','','d-arni')
a('ARA',[('A','Antagoniste'),('R','des Récepteurs'),('A','de l’Angiotensine')],'Antagoniste des récepteurs de l’angiotensine (II)','<p>Toujours suivi du chiffre romain II : bloque le récepteur AT1 de l’angiotensine II. Candésartan, valsartan, losartan dans l’insuffisance cardiaque.</p>','d-arni')
a('ARNI',[('A','Angiotensin'),('R','Receptor–'),('N','Neprilysin'),('I','Inhibitor')],'Inhibiteur du récepteur de l’angiotensine et de la néprilysine (sacubitril/valsartan)','','d-arni')
a('ARM',[('A','Antagoniste'),('R','des Récepteurs'),('M','Minéralocorticoïdes')],'Antagoniste des récepteurs minéralocorticoïdes','','d-arm')
a('SGLT2',[('S','Sodium-'),('GL','GLucose'),('T','coTransporteur'),('2','de type 2')],'Cotransporteur sodium-glucose de type 2','<p>Transporteur du tube contourné proximal qui réabsorbe environ 90 % du glucose filtré, couplé au sodium.</p>','d-sglt2')
a('iSGLT2',[('i','inhibiteur du'),('S','Sodium-'),('GL','GLucose'),('T','coTransporteur'),('2','de type 2')],'Inhibiteur du cotransporteur sodium-glucose de type 2','','d-sglt2')
a('AINS',[('A','Anti-'),('I','Inflammatoire'),('N','Non'),('S','Stéroïdien')],'Anti-inflammatoire non stéroïdien','<p>Ibuprofène, diclofénac, naproxène… Rétention sodée, baisse du DFG : cause classique de décompensation, à éviter.</p>')
a('COX-2',[('COX','CycloOXygénase'),('2','isoforme 2 (inductible)')],'Cyclo-oxygénase de type 2','<p>Enzyme de synthèse des prostaglandines inflammatoires ; ses inhibiteurs sélectifs (coxibs) partagent les risques rénaux et cardiovasculaires des AINS.</p>')
a('BB',[('B','Bêta-'),('B','Bloquant')],'Bêtabloquant','','d-bb')
a('TMF',[('T','Thérapie'),('M','Médicamenteuse'),('F','Fondamentale')],'Thérapie médicamenteuse fondamentale (ESC 2026)','<p>Traitements de classe I pour l’ensemble des patients, avec bénéfice démontré sur la morbi-mortalité. ICFEr : IEC ou ARNI, bêtabloquant, ARM, iSGLT2. ICFEp : ARM, iSGLT2.</p>')
a('TMA',[('T','Thérapie'),('M','Médicamenteuse'),('A','Additionnelle')],'Thérapie médicamenteuse additionnelle (ESC 2026)','<p>Traitements bénéfiques dans des sous-groupes ou sur les symptômes : glycosides, vériciguat, ivabradine, fer intraveineux, hydralazine-dinitrate d’isosorbide.</p>')
a('TIG',[('T','Thérapie'),('I','Interventionnelle'),('G','Guidée')],'Thérapie interventionnelle guidée (ESC 2026)','<p>Dispositifs implantables et procédures : défibrillateur, resynchronisation, réparation valvulaire percutanée, assistance ventriculaire.</p>')
a('GLP-1',[('G','Glucagon-'),('L','Like'),('P','Peptide'),('-1','de type 1')],'Peptide apparenté au glucagon de type 1','<p>Incrétine intestinale ; ses agonistes (sémaglutide) réduisent le poids et améliorent les symptômes de l’ICFEp chez l’obèse (classe IIa, ESC 2026).</p>')
a('GIP',[('G','Glucose-dependent'),('I','Insulinotropic'),('P','Polypeptide')],'Polypeptide insulinotrope dépendant du glucose','<p>Seconde incrétine ; le tirzépatide est un double agoniste GIP/GLP-1.</p>')
a('sGC',[('s','soluble'),('G','Guanylate'),('C','Cyclase')],'Guanylate cyclase soluble','<p>Enzyme cible du monoxyde d’azote qui produit le GMPc ; stimulée par le vériciguat.</p>','d-veri')
a('CYP3A4',[('CYP','CYtochrome P450'),('3','famille 3'),('A','sous-famille A'),('4','isoenzyme 4')],'Cytochrome P450 3A4','<p>Principale enzyme hépatique et intestinale de métabolisme des médicaments ; sa forte inhibition (clarithromycine, kétoconazole) augmente les concentrations de l’ivabradine.</p>')
a('HCN4',[('H','Hyperpolarization-activated'),('C','Cyclic nucleotide-gated'),('N','(canal)'),('4','isoforme 4')],'Canal activé par l’hyperpolarisation et modulé par les nucléotides cycliques, isoforme 4','<p>Canal porteur du courant If du nœud sinusal ; bloqué par l’ivabradine.</p>','d-iva')
a('NKCC2',[('N','Na⁺ (sodium)'),('K','K⁺ (potassium)'),('CC','Chloride Cotransporter (cotransporteur du chlore)'),('2','isoforme 2 (rénale)')],'Cotransporteur sodium-potassium-2 chlorures de type 2','<p>Situé dans la branche ascendante large de l’anse de Henle ; bloqué par les diurétiques de l’anse.</p>','d-diur')
a('ATP',[('A','Adénosine'),('T','Tri-'),('P','Phosphate')],'Adénosine triphosphate','<p>Molécule énergétique cellulaire ; la relaxation myocardique consomme de l’ATP.</p>')
a('ATPase',[('ATP','Adénosine TriPhosphate'),('ase','enzyme qui l’hydrolyse')],'Adénosine triphosphatase','<p>Enzyme qui hydrolyse l’ATP pour transporter des ions (pompe Na⁺/K⁺, pompe SERCA2a).</p>')
a('AMPc',[('A','Adénosine'),('M','Mono-'),('P','Phosphate'),('c','cyclique')],'Adénosine monophosphate cyclique','<p>Second messager des récepteurs β1 : augmente fréquence et contractilité.</p>')
a('GMPc',[('G','Guanosine'),('M','Mono-'),('P','Phosphate'),('c','cyclique')],'Guanosine monophosphate cyclique','<p>Second messager des peptides natriurétiques et du monoxyde d’azote : vasodilatation, natriurèse, effet antifibrosant.</p>')
a('GMP',[('G','Guanosine'),('M','Mono-'),('P','Phosphate')],'Guanosine monophosphate (ici sous sa forme cyclique, GMPc)','','')
a('SERCA2a',[('S','Sarco/'),('E','Endoplasmic'),('R','Reticulum'),('C','Calcium'),('A','ATPase'),('2a','isoforme 2a (cardiaque)')],'Pompe calcique du réticulum sarcoplasmique, isoforme cardiaque 2a','<p>Recapture le calcium en diastole : moteur de la relaxation active ; son activité diminue dans l’insuffisance cardiaque.</p>','diastole')
a('V2',[('V','récepteur de la Vasopressine'),('2','de type 2')],'Récepteur de la vasopressine de type 2','<p>Récepteur du tube collecteur qui insère les aquaporines 2 et réabsorbe l’eau libre ; bloqué par le tolvaptan.</p>','tolvaptan')
