# Glossaire MEDINA — G-04-Gastroentérologie et hépatologie (auteur unique de ce fichier : agent G-04).
from cardio_1 import a, G
def code(k, titre, cours):
    a(k, [(k, 'code CIM-10-GM 2024')], titre, '<p>Sous-catégorie couverte par le cours ' + cours + ' (catalogue OFS, version française 2024).</p>')
def nom(k, auteurs, full, d):
    a(k, [(k, 'noms propres (' + auteurs + '), non une abréviation')], full, d)

# Sociétés et référentiels
a('ESGE', [('E', 'European'), ('S', 'Society of'), ('G', 'Gastrointestinal'), ('E', 'Endoscopy')], 'Société européenne d’endoscopie digestive', '<p>Société savante qui publie les recommandations européennes d’endoscopie : hémorragies hautes non variqueuses (2021) et variqueuses (2022), notamment.</p>')
a('BSG', [('B', 'British'), ('S', 'Society of'), ('G', 'Gastroenterology')], 'Société britannique de gastroentérologie', '<p>Société savante européenne (Royaume-Uni) ; auteur de la recommandation de 2019 sur l’hémorragie digestive basse aiguë.</p>')
a('IPP', [('I', 'Inhibiteur de la'), ('P', 'Pompe à'), ('P', 'Protons')], 'Inhibiteur de la pompe à protons', '<p>Médicament qui bloque de façon irréversible la H⁺/K⁺-ATPase de la cellule pariétale gastrique et réduit fortement la sécrétion acide (oméprazole, ésoméprazole, pantoprazole, lansoprazole, rabéprazole).</p>')
a('TIPS', [('T', 'Transjugular (transjugulaire)'), ('I', 'Intrahepatic (intrahépatique)'), ('P', 'Portosystemic (portosystémique)'), ('S', 'Shunt (dérivation)')], 'Dérivation portosystémique intrahépatique par voie transjugulaire', '<p>Endoprothèse couverte placée par voie jugulaire entre une branche de la veine porte et une veine sus-hépatique ; elle abaisse la pression portale.</p>', 'k92-tips')
a('ORL', [('O', 'Oto-'), ('R', 'Rhino-'), ('L', 'Laryngologie')], 'Oto-rhino-laryngologie', '<p>Spécialité de l’oreille, du nez et de la gorge.</p>')
a('CC', [('C', 'Creative'), ('C', 'Commons')], 'Licences Creative Commons', '<p>Famille de licences libres qui autorisent la réutilisation d’une œuvre à des conditions précisées (attribution, partage dans les mêmes conditions).</p>')
a('BY-SA', [('BY', 'attribution (« by », citer l’auteur)'), ('SA', 'Share Alike (partage dans les mêmes conditions)')], 'Attribution, partage dans les mêmes conditions', '<p>Conditions d’une licence Creative Commons : citer l’auteur et diffuser toute adaptation sous la même licence.</p>')
a('GIF', [('G', 'Graphics'), ('I', 'Interchange'), ('F', 'Format')], 'Format d’échange graphique', '<p>Format d’image à palette limitée, compact, utilisé pour les illustrations des cours.</p>')
a('MEDINA', [('MEDINA', 'nom du projet (atlas de médecine), non une abréviation')], 'Atlas de cours MEDINA', '<p>Nom de l’atlas pédagogique dans lequel ce cours est publié.</p>')
a('IIc', [('II', 'classe II de Forrest'), ('c', 'sous-type c')], 'Forrest IIc : tache pigmentée plane', '<p>Stigmate d’ulcère à faible risque de récidive ; pas d’hémostase endoscopique (ESGE 2021).</p>', 'k92-forrest')
nom('Mallory-Weiss', 'George Kenneth Mallory, Soma Weiss', 'Syndrome de Mallory-Weiss', '<p>Déchirure longitudinale de la muqueuse de la jonction œsogastrique après des efforts de vomissement ; cause d’hématémèse.</p>')
nom('Glasgow-Blatchford', 'ville de Glasgow et Oliver Blatchford', 'Score de Glasgow-Blatchford', '<p>Score de risque de l’hémorragie digestive haute, calculé avant l’endoscopie ; ≤ 1 : très faible risque (ESGE 2021).</p>', )
a('Royaume-Uni', [('Royaume-Uni', 'nom de pays, non une abréviation')], 'Royaume-Uni de Grande-Bretagne et d’Irlande du Nord', '<p>Pays des recommandations BSG et NICE citées.</p>')
code('K92.0', 'Hématémèse', 'K92 — Hémorragies digestives')
code('K92.1', 'Méléna', 'K92 — Hémorragies digestives')
code('K92.2', 'Hémorragie gastro-intestinale, sans précision', 'K92 — Hémorragies digestives')
# K25 — Ulcère gastroduodénal
a('DGVS', [('D', 'Deutsche (allemande)'), ('G', 'Gesellschaft für (société de)'), ('V', 'Gastroenterologie, Verdauungs- (digestive)'), ('S', 'und Stoffwechselkrankheiten (et métabolique)')], 'Société allemande de gastroentérologie, des maladies digestives et métaboliques', '<p>Société savante européenne (Allemagne) ; auteure de la recommandation S2k 2023 sur Helicobacter pylori et la maladie ulcéreuse gastroduodénale.</p>')
a('WSES', [('W', 'World'), ('S', 'Society of'), ('E', 'Emergency'), ('S', 'Surgery')], 'Société mondiale de chirurgie d’urgence', '<p>Société savante de chirurgie d’urgence ; auteure de la recommandation de 2020 sur l’ulcère peptique perforé et hémorragique.</p>')
a('ASA', [('A', 'American'), ('S', 'Society of'), ('A', 'Anesthesiologists')], 'Classification de l’état physique de l’American Society of Anesthesiologists', '<p>Classe de I à VI de l’état général préopératoire ; utilisée comme score de risque de l’ulcère perforé (WSES 2020).</p>')
a('PULP', [('P', 'Peptic'), ('U', 'Ulcer'), ('L', 'Perforation (le L reprend « ulcer perforation »)'), ('P', 'score')], 'Score PULP (Peptic Ulcer Perforation)', '<p>Score pronostique de mortalité de l’ulcère perforé, fondé sur l’âge, les comorbidités, le délai, le choc, la créatinine et la classe ASA.</p>')
a('H2', [('H', 'Histamine'), ('2', 'récepteur de type 2')], 'Récepteur H2 de l’histamine', '<p>Récepteur de la cellule pariétale qui stimule la sécrétion acide ; cible des antihistaminiques H2.</p>')
a('NEM', [('N', 'Néoplasie'), ('E', 'Endocrinienne'), ('M', 'Multiple')], 'Néoplasie endocrinienne multiple', '<p>Syndrome héréditaire de tumeurs endocrines ; le type 1 associe hyperparathyroïdie, tumeurs hypophysaires et tumeurs neuroendocrines pancréatiques ou duodénales, dont le gastrinome.</p>')
a('MD', [('M', 'Medicinae'), ('D', 'Doctor (docteur en médecine)')], 'Titre de docteur en médecine', '<p>Titre universitaire anglo-saxon figurant dans le nom d’un auteur d’image.</p>')
a('CC0', [('CC', 'Creative Commons'), ('0', 'zéro droit réservé')], 'Licence Creative Commons zéro', '<p>Renonciation de l’auteur à ses droits : l’œuvre est versée dans le domaine public.</p>')
nom('Zollinger-Ellison', 'Robert Zollinger, Edwin Ellison', 'Syndrome de Zollinger-Ellison', '<p>Hypersécrétion acide due à un gastrinome ; ulcères multiples, distaux ou réfractaires.</p>')
a('HALT-IT', [('HALT-IT', 'nom d’essai : Haemorrhage ALleviation with Tranexamic acid – InTestinal system')], 'Essai HALT-IT', '<p>Essai randomisé international de l’acide tranexamique contre placebo dans l’hémorragie digestive aiguë (Lancet 2020) : aucun bénéfice sur la mortalité.</p>', 'k92-tranexamique')
a('MALT', [('M', 'Mucosa-'), ('A', 'Associated'), ('L', 'Lymphoid'), ('T', 'Tissue')], 'Tissu lymphoïde associé aux muqueuses', '<p>Tissu lymphoïde des muqueuses ; le lymphome du MALT gastrique est lié à Helicobacter pylori et régresse souvent après éradication.</p>')
# K21 — Reflux gastro-œsophagien et Barrett
a('GERD', [('G', 'Gastro-'), ('E', 'Esophageal (œsophagien)'), ('R', 'Reflux'), ('D', 'Disease (maladie)')], 'Maladie de reflux gastro-œsophagien', '<p>Terme anglais repris dans les titres des sources ; reflux du contenu gastrique qui provoque des symptômes gênants ou des lésions de l’œsophage.</p>', 'k21-rgo-def')
a('AFIP', [('A', 'Armed'), ('F', 'Forces'), ('I', 'Institute of'), ('P', 'Pathology')], 'Institut de pathologie des forces armées américaines', '<p>Institution auteure d’images histologiques versées dans le domaine public.</p>')
a('HUNT', [('HUNT', 'nom d’étude : Helseundersøkelsen i Nord-Trøndelag (enquête de santé du Nord-Trøndelag, Norvège)')], 'Étude HUNT', '<p>Grande cohorte populationnelle norvégienne ; elle a montré l’effet de la perte de poids sur les symptômes de reflux.</p>')
a('C2M5', [('C2', 'extension circonférentielle de 2 cm'), ('M5', 'extension maximale de 5 cm')], 'Barrett C2M5 selon Prague', '<p>Notation de la classification de Prague : C pour l’extension circonférentielle, M pour l’extension maximale, en centimètres.</p>', 'k21-prague')
a('pT1', [('p', 'pathologique (stade établi sur pièce)'), ('T1', 'tumeur limitée à la muqueuse ou à la sous-muqueuse')], 'Stade pT1', '<p>Stade TNM d’une tumeur limitée à la muqueuse (T1a) ou à la sous-muqueuse (T1b), établi sur la pièce de résection.</p>')
code('K22.7', 'Œsophage de Barrett', 'K21 — Reflux gastro-œsophagien et œsophage de Barrett')
# K85 — Pancréatite aiguë
a('CPRE', [('C', 'Cholangio-'), ('P', 'Pancréatographie'), ('R', 'Rétrograde'), ('E', 'Endoscopique')], 'Cholangiopancréatographie rétrograde endoscopique', '<p>Opacification et traitement endoscopique des voies biliaires et pancréatiques par la papille : sphinctérotomie, extraction de calcul, drainage.</p>', 'k85-cpre')
a('BISAP', [('B', 'Bedside (au lit du patient)'), ('I', 'Index of'), ('S', 'Severity in'), ('A', 'Acute'), ('P', 'Pancreatitis')], 'Index de sévérité au lit de la pancréatite aiguë', '<p>Score de 0 à 5 calculé dans les 24 premières heures : urée, conscience, réponse inflammatoire systémique, âge, épanchement pleural.</p>', 'k85-bisap')
a('APACHE', [('A', 'Acute'), ('P', 'Physiology'), ('A', 'And'), ('C', 'Chronic'), ('H', 'Health'), ('E', 'Evaluation')], 'Score APACHE', '<p>Score de gravité de réanimation (version II) fondé sur des paramètres physiologiques, l’âge et les comorbidités.</p>')
a('BY', [('BY', 'by (attribution) : mention obligatoire de l’auteur')], 'Clause d’attribution Creative Commons', '<p>Élément des licences Creative Commons CC BY et CC BY-SA : l’œuvre peut être réutilisée à condition de citer son auteur.</p>')
nom('Grey-Turner', 'George Grey Turner', 'Signe de Grey-Turner', '<p>Ecchymose des flancs traduisant une diffusion hémorragique rétropéritonéale, notamment au cours d’une pancréatite aiguë.</p>')
a('J4', [('J', 'jour'), ('4', 'quatrième jour d’évolution')], 'Quatrième jour', '<p>Quatrième jour après le début des symptômes.</p>')
# K80 — Lithiase biliaire
a('KSSG', [('K', 'Kantons-'), ('S', 'spital'), ('S', 'St.'), ('G', 'Gallen')], 'Hôpital cantonal de Saint-Gall', '<p>Hôpital cantonal suisse (aujourd’hui HOCH Health Ostschweiz) dont le service d’infectiologie publie des directives cliniques sur guidelines.ch.</p>')
a('HOCH', [('HOCH', 'nom de l’entité hospitalière HOCH Health Ostschweiz')], 'HOCH Health Ostschweiz', '<p>Groupe hospitalier de Suisse orientale qui réunit l’hôpital cantonal de Saint-Gall et des hôpitaux régionaux.</p>')
a('ASGE', [('A', 'American'), ('S', 'Society for'), ('G', 'Gastrointestinal'), ('E', 'Endoscopy')], 'Société américaine d’endoscopie digestive', '<p>Société savante américaine ; sa grille de risque de calcul cholédocien est reprise et modifiée par la WSES 2020.</p>')
a('SAGES', [('S', 'Society of'), ('A', 'American'), ('G', 'Gastrointestinal and'), ('E', 'Endoscopic'), ('S', 'Surgeons')], 'Société américaine des chirurgiens digestifs et endoscopistes', '<p>Société savante américaine ; coauteure de la grille de risque cholédocien reprise par la WSES 2020.</p>')
a('HIDA', [('H', 'Hepatobiliary (hépatobiliaire)'), ('I', 'Iminodiacetic'), ('A', 'Acid (acide iminodiacétique)')], 'Scintigraphie hépatobiliaire à l’acide iminodiacétique', '<p>Scintigraphie dont le traceur est excrété dans la bile ; l’absence de remplissage vésiculaire signe l’obstruction du canal cystique.</p>', 'k80-hida')
nom('Rokitansky-Aschoff', 'Carl von Rokitansky, Ludwig Aschoff', 'Sinus de Rokitansky-Aschoff', '<p>Invaginations de la muqueuse vésiculaire dans la musculeuse, typiques de la cholécystite chronique.</p>')
a('FI', [('F', 'Fachinformation (information'), ('I', 'professionnelle)')], 'Information professionnelle', '<p>Notice destinée aux professionnels, approuvée par Swissmedic, qui fixe les indications et posologies autorisées en Suisse.</p>')
# K74 — Fibrose et cirrhose
a('cACLD', [('c', 'compensated (compensée)'), ('A', 'Advanced (avancée)'), ('C', 'Chronic (chronique)'), ('L', 'Liver (hépatique)'), ('D', 'Disease (maladie)')], 'Maladie hépatique chronique avancée compensée', '<p>Terme de Baveno VI et VII désignant le continuum fibrose sévère-cirrhose chez le patient compensé, défini par l’élastographie (≥ 10 kPa).</p>', 'k74-cacld')
nom('ANTICIPATE', 'étude ANTICIPATE (Abraldes J. G. et al., 2016)', 'Modèle ANTICIPATE', '<p>Modèle qui estime le risque d’hypertension portale cliniquement significative à partir de l’élastographie et des plaquettes.</p>')
a('TODO', [('TO', 'to (à)'), ('DO', 'do (faire)')], 'Point à compléter', '<p>Marqueur éditorial Medina : information non retrouvée dans les sources lues, laissée volontairement en blanc plutôt qu’inventée.</p>')
# K70 — Maladie alcoolique du foie
code('K70.0', 'Stéatose hépatique alcoolique', 'K70 — Maladie alcoolique du foie')
code('K70.1', 'Hépatite alcoolique', 'K70 — Maladie alcoolique du foie')
code('K70.2', 'Fibrose et sclérose alcooliques du foie', 'K70 — Maladie alcoolique du foie')
code('K70.3', 'Cirrhose alcoolique du foie', 'K70 — Maladie alcoolique du foie')
code('K70.4', 'Insuffisance hépatique alcoolique', 'K70 — Maladie alcoolique du foie')
code('K70.9', 'Maladie alcoolique du foie, sans précision', 'K70 — Maladie alcoolique du foie')
nom('Mallory-Denk', 'Frank Burr Mallory, Helmut Denk', 'Corps de Mallory-Denk', '<p>Inclusions éosinophiles des hépatocytes ballonnisés, formées surtout de kératines 8 et 18 ; évocatrices de stéatohépatite.</p>')
a('PNPLA3', [('P', 'Patatin-like'), ('P', 'Phospholipase'), ('L', 'domain-containing (domaine)'), ('A3', 'protéine 3 (Adiponutrine)')], 'Gène PNPLA3', '<p>Gène dont certains variants augmentent le risque de lésions hépatiques alcooliques et métaboliques.</p>', 'k70-pnpla3')
a('NAD⁺', [('N', 'Nicotinamide'), ('A', 'Adénine'), ('D', 'Dinucléotide'), ('⁺', 'forme oxydée')], 'Nicotinamide adénine dinucléotide, forme oxydée', '<p>Coenzyme accepteur d’électrons ; son oxydation de l’éthanol produit du NADH.</p>')
a('NADH', [('NAD', 'Nicotinamide adénine dinucléotide'), ('H', 'forme réduite (hydrogénée)')], 'Nicotinamide adénine dinucléotide, forme réduite', '<p>Forme réduite du NAD⁺ ; son excès, lors de l’oxydation de l’éthanol, bloque la β-oxydation et favorise la stéatose.</p>')
a('CYP2E1', [('CYP', 'Cytochrome P450'), ('2E1', 'famille 2, sous-famille E, enzyme 1')], 'Cytochrome P450 2E1', '<p>Enzyme microsomale inductible par l’alcool ; elle oxyde l’éthanol et produit des espèces réactives de l’oxygène.</p>')
a('DSM-5', [('D', 'Diagnostic and'), ('S', 'Statistical'), ('M', 'Manual of Mental Disorders'), ('5', 'cinquième édition')], 'Manuel diagnostique et statistique des troubles mentaux, 5e édition', '<p>Classification de l’Association américaine de psychiatrie ; elle définit le trouble de l’usage d’alcool.</p>')
a('AUDIT', [('A', 'Alcohol'), ('U', 'Use'), ('D', 'Disorders'), ('I', 'Identification'), ('T', 'Test')], 'Test d’identification des troubles de l’usage d’alcool', '<p>Questionnaire de dix questions de l’OMS ; outil de dépistage recommandé par l’EASL.</p>', 'k70-audit')
a('AUDIT-C', [('AUDIT', 'Alcohol Use Disorders Identification Test'), ('C', 'Consumption (consommation)')], 'AUDIT, version consommation', '<p>Les trois premières questions de l’AUDIT, centrées sur la consommation.</p>', 'k70-audit')
a('PEIR', [('P', 'Pathology'), ('E', 'Education'), ('I', 'Informational'), ('R', 'Resource')], 'Banque d’images PEIR', '<p>Banque d’images pédagogiques de pathologie de l’université d’Alabama à Birmingham.</p>')
a('ABIC', [('A', 'Age (âge)'), ('B', 'Bilirubine'), ('I', 'INR'), ('C', 'Créatinine')], 'Score ABIC', '<p>Score pronostique de l’hépatite alcoolique (risque de décès à 90 jours).</p>', 'k70-abic')
a('STOPAH', [('STOPAH', 'nom d’essai : STeroids Or Pentoxifylline for Alcoholic Hepatitis')], 'Essai STOPAH', '<p>Essai randomisé britannique (N Engl J Med 2015) de la prednisolone et de la pentoxifylline dans l’hépatite alcoolique sévère.</p>', 'k70-stopah')
a('VGM', [('V', 'Volume'), ('G', 'Globulaire'), ('M', 'Moyen')], 'Volume globulaire moyen', '<p>Taille moyenne des globules rouges ; sa hausse est un marqueur indirect de consommation chronique d’alcool.</p>')
a('CDT', [('C', 'Carbohydrate-'), ('D', 'Deficient'), ('T', 'Transferrin')], 'Transferrine carboxy-déficiente', '<p>Marqueur sérique indirect de consommation chronique excessive d’alcool.</p>', 'k70-cdt')
a('J0', [('J', 'jour'), ('0', 'jour du début du traitement')], 'Jour zéro', '<p>Premier jour du traitement, référence des calculs dynamiques comme le score de Lille.</p>')
