# Glossaire MEDINA — chapitre I25 (syndromes coronariens chroniques et angor)
from cardio_1 import a, G

def t(k, lit, full, d, ref=None):
    a(k, lit, full, d, ref)

# --- concepts cliniques ---
a('SCC',[('S','Syndrome'),('C','Coronarien'),('C','Chronique')],'Syndrome coronarien chronique',
 '<p>Terme ESC (2019, redéfini en 2024) : présentations dues à des anomalies structurelles ou fonctionnelles des coronaires épicardiques ou de la microcirculation, responsables d’un déséquilibre transitoire et réversible entre apports et besoins en oxygène.</p>')
a('ANOCA',[('A','Angina (angor)'),('NO','with No Obstructive (sans sténose obstructive)'),('C','Coronary (coronaire)'),('A','Arteries (des artères)')],'Angor sans sténose coronaire obstructive',
 '<p>Angor avec des coronaires sans sténose obstructive (&lt; 50 % ou FFR &gt; 0,80). Mécanismes : dysfonction microvasculaire, spasme microvasculaire, vasospasme épicardique.</p>','i25-endotypes')
a('INOCA',[('I','Ischaemia (ischémie)'),('NO','with No Obstructive (sans sténose obstructive)'),('C','Coronary (coronaire)'),('A','Arteries (des artères)')],'Ischémie sans sténose coronaire obstructive',
 '<p>Ischémie myocardique objectivée (imagerie, ECG, tests invasifs) avec des coronaires sans sténose obstructive.</p>','i25-endotypes')
a('RF-CL',[('RF','Risk Factor-weighted (pondérée par les facteurs de risque)'),('C','Clinical (clinique)'),('L','Likelihood (probabilité)')],'Probabilité clinique pondérée par les facteurs de risque',
 '<p>Modèle de l’ESC 2024 qui estime la probabilité de maladie coronaire obstructive à partir du sexe, de l’âge, du type de symptôme et du nombre de facteurs de risque.</p>','i25-rfcl')
a('CACS-CL',[('CACS','Coronary Artery Calcium Score (score calcique coronaire)'),('C','Clinical (clinique)'),('L','Likelihood (probabilité)')],'Probabilité clinique ajustée par le score calcique',
 '<p>Modèle qui combine le RF-CL et le score calcique coronaire ; il classe davantage de patients en probabilité très basse.</p>','i25-cac')
a('IMR',[('I','Index of (indice de)'),('M','Microcirculatory (microcirculatoire)'),('R','Resistance (résistance)')],'Indice de résistance microvasculaire',
 '<p>Pression distale en hyperhémie × temps de transit moyen par thermodilution. ≥ 25 : résistances microvasculaires élevées.</p>','i25-imr')
a('FFR-CT',[('F','Fractional (fractionnelle)'),('F','Flow (du flux)'),('R','Reserve (réserve)'),('CT','Computed Tomography (dérivée du scanner)')],'Réserve coronaire fractionnelle dérivée du coroscanner',
 '<p>FFR calculée par modélisation de l’écoulement à partir des images du coroscanner ; ≤ 0,80 en aval d’une sténose suggère une signification hémodynamique.</p>','i25-ffrct')
a('CAD-RADS',[('CAD','Coronary Artery Disease (maladie coronaire)'),('R','Reporting (compte rendu)'),('A','And (et)'),('D','Data (données)'),('S','System (système)')],'Système standardisé de compte rendu du coroscanner',
 '<p>Classification de la sténose maximale au coroscanner de 0 (aucune plaque) à 5 (occlusion), version 2.0 (2022), avec des modificateurs (charge en plaque, plaque à haut risque, stent, pontage).</p>','i25-ccta')
a('TEP',[('T','Tomographie'),('E','par Émission de'),('P','Positons')],'Tomographie par émission de positons',
 '<p>Imagerie nucléaire qui mesure la perfusion et le débit myocardique absolu (mL/min/g) et la réserve de débit ; utile dans l’ischémie équilibrée et la dysfonction microvasculaire.</p>','i25-stressimg')
a('SPECT',[('S','Single'),('P','Photon'),('E','Emission'),('C','Computed'),('T','Tomography')],'Tomoscintigraphie par émission monophotonique',
 '<p>Scintigraphie de perfusion myocardique : un défaut réversible entre stress et repos signe une ischémie, un défaut fixe une cicatrice.</p>','i25-stressimg')
a('STS',[('S','Society of'),('T','Thoracic'),('S','Surgeons')],'Society of Thoracic Surgeons (score de risque opératoire)',
 '<p>Société américaine de chirurgie thoracique ; son score estime la mortalité opératoire d’un pontage ou d’une chirurgie valvulaire.</p>','i25-heartteam')
a('EuroSCORE II',[('Euro','European (européen)'),('S','System for'),('C','Cardiac'),('O','Operative'),('R','Risk'),('E','Evaluation'),('II','deuxième version')],'Système européen d’évaluation du risque opératoire cardiaque, version II',
 '<p>Score qui estime la mortalité hospitalière après une chirurgie cardiaque à partir de variables cliniques et opératoires.</p>','i25-heartteam')
a('EACTS',[('E','European'),('A','Association for'),('C','Cardio-'),('T','Thoracic'),('S','Surgery')],'European Association for Cardio-Thoracic Surgery (Association européenne de chirurgie cardiothoracique)',
 '<p>Société savante qui a coécrit avec l’ESC les recommandations sur la revascularisation myocardique (2018) et approuvé celles de 2024 sur le SCC.</p>')
a('EAPCI',[('E','European'),('A','Association of'),('P','Percutaneous'),('C','Cardiovascular'),('I','Interventions')],'Association européenne des interventions cardiovasculaires percutanées',
 '<p>Association de l’ESC consacrée à la cardiologie interventionnelle ; elle a publié des consensus sur les tests fonctionnels coronaires invasifs.</p>','i25-ifct')
a('COVADIS',[('CO','COronary (coronaire)'),('VA','VAsomotion (vasomotricité)'),('DIS','DISorders (troubles)')],'Groupe international d’étude des troubles de la vasomotricité coronaire',
 '<p>Groupe qui a proposé les critères diagnostiques de l’angor vasospastique et de l’angor microvasculaire.</p>','i25-vsa')
a('CIM-10',[('C','Classification'),('I','Internationale des'),('M','Maladies'),('10','dixième révision')],'Classification internationale des maladies, dixième révision',
 '<p>Classification de l’OMS ; la Suisse utilise pour le codage hospitalier la version allemande modifiée (CIM-10-GM).</p>')

# --- essais ---
t('ISCHEMIA',[('ISCHEMIA','nom d’essai arrangé à partir de « International Study of Comparative Health Effectiveness with Medical and Invasive Approaches », non strictement lettre à lettre')],'Essai ISCHEMIA (2020)','<p>Ischémie modérée à sévère : une stratégie invasive initiale n’a pas réduit les décès cardiovasculaires ni les infarctus par rapport au traitement médical optimal, mais a mieux soulagé l’angor.</p>')
t('SYNTAX',[('SYNTAX','nom d’essai arrangé à partir de « SYNergy between PCI with TAXus and cardiac surgery », non strictement lettre à lettre')],'Essai et score SYNTAX (2009)','<p>Comparaison de l’angioplastie et du pontage dans le tronc commun et l’atteinte tritronculaire ; a donné son nom au score angiographique de complexité.</p>','i25-syntax')
t('STICH',[('STICH','nom d’essai arrangé à partir de « Surgical Treatment for Ischemic Heart failure », non strictement lettre à lettre')],'Essai STICH (2011)','<p>Cardiomyopathie ischémique à FEVG ≤ 35 % : pontage + traitement médical comparé au traitement médical seul ; bénéfice de survie à long terme.</p>')
t('STICHES',[('STICH','Surgical Treatment for Ischemic Heart failure'),('ES','Extension Study (suivi prolongé)')],'Suivi prolongé de l’essai STICH (2016)','<p>À 10 ans, le pontage a réduit la mortalité totale chez les patients à FEVG ≤ 35 %.</p>')
t('REVIVED-BCIS2',[('REVIVED','REVascularization for Ischemic VEntricular Dysfunction (revascularisation de la dysfonction ventriculaire ischémique), non strictement lettre à lettre'),('BCIS','British Cardiovascular Intervention Society'),('2','deuxième essai de ce groupe')],'Essai REVIVED-BCIS2 (2022)','<p>Cardiomyopathie ischémique à FEVG ≤ 35 % : l’angioplastie n’a pas réduit les décès ni les hospitalisations pour insuffisance cardiaque par rapport au traitement médical.</p>')
t('FAME',[('F','Fractional flow reserve (réserve coronaire fractionnelle)'),('A','versus Angiography for'),('M','Multivessel'),('E','Evaluation')],'Essais FAME (2009), FAME 2 (2012), FAME 3 (2022)','<p>FAME : angioplastie guidée par la FFR supérieure au guidage angiographique. FAME 2 : sténoses à FFR ≤ 0,80, moins de revascularisations urgentes avec l’angioplastie. FAME 3 : dans l’atteinte tritronculaire, l’angioplastie guidée par la FFR n’a pas été non inférieure au pontage à un an.</p>','i25-ffr')
t('DEFER',[('DEFER','nom d’essai anglais signifiant « différer » (report de l’angioplastie), non développable lettre à lettre')],'Étude DEFER (2001)','<p>Différer l’angioplastie d’une sténose à FFR non significative est sûr à long terme.</p>','i25-ffr')
t('DEFINE-FLAIR',[('DEFINE','nom d’essai (« définir »)'),('FLAIR','Functional Lesion Assessment of Intermediate stenosis to guide Revascularisation (évaluation fonctionnelle des sténoses intermédiaires)')],'Essai DEFINE-FLAIR (2017)','<p>Stratégie guidée par l’iFR non inférieure à la FFR à un an ; mortalité plus élevée dans le groupe iFR au suivi à 5 ans.</p>','i25-ifr')
t('iFR-SWEDEHEART',[('iFR','instantaneous wave-Free Ratio (rapport instantané sans onde)'),('SWEDEHEART','registre national suédois des maladies cardiaques, utilisé comme plateforme d’essai (nom arrangé, non strictement lettre à lettre)')],'Essai iFR-SWEDEHEART (2017)','<p>Stratégie guidée par l’iFR non inférieure à la FFR.</p>','i25-ifr')
t('SCOT-HEART',[('S','Scottish (écossais)'),('CO','COmputed'),('T','Tomography (tomodensitométrie)'),('HEART','of the HEART (du cœur)')],'Essai SCOT-HEART (2015 ; suivi à 5 ans 2018)','<p>Ajout du coroscanner au bilan de la douleur thoracique stable : moins de décès coronaires et d’infarctus non mortels à 5 ans.</p>','i25-ccta')
t('PROMISE',[('PROMISE','PROspective Multicenter Imaging Study for Evaluation of chest pain, non strictement lettre à lettre')],'Essai PROMISE (2015)','<p>Coroscanner et épreuve fonctionnelle en première intention : résultats cliniques semblables.</p>','i25-ccta')
t('DISCHARGE',[('DISCHARGE','Diagnostic Imaging Strategies for Patients With Stable Chest Pain and Intermediate Risk of Coronary Artery Disease, nom arrangé non strictement lettre à lettre')],'Essai DISCHARGE (2022)','<p>Probabilité intermédiaire : coroscanner et coronarographie invasive ont donné des événements semblables, avec moins de complications pour le scanner.</p>','i25-ccta')
t('CorMicA',[('Cor','Coronary (coronaire)'),('Mic','Microvascular (microvasculaire)'),('A','Angina (angor)')],'Essai CorMicA (2018)','<p>Chez des patients sans sténose obstructive, un traitement guidé par les tests fonctionnels invasifs a amélioré l’angor et la qualité de vie.</p>','i25-endotypes')
t('SIGNIFY',[('SIGNIFY','Study assessInG the morbidity-mortality beNefits of the If inhibitor ivabradine in patients with coronarY artery disease, non strictement lettre à lettre')],'Essai SIGNIFY (2014)','<p>Ivabradine chez des coronariens sans insuffisance cardiaque : pas de bénéfice ; hausse des événements chez les patients ayant un angor limitant.</p>','i25-d-iva')
t('BEAUTIFUL',[('BEAUTIFUL','morBidity-mortality EvAlUaTion of the If inhibitor ivabradine in patients with coronary disease and left ventricULar dysfunction, non strictement lettre à lettre')],'Essai BEAUTIFUL (2008)','<p>Ivabradine chez des coronariens à FEVG &lt; 40 % : pas de réduction du critère principal.</p>','i25-d-iva')
t('CARISA',[('C','Combination'),('A','Assessment of'),('R','Ranolazine'),('I','In'),('S','Stable'),('A','Angina')],'Essai CARISA (2004)','<p>Ranolazine ajoutée aux anti-angineux : amélioration de la durée d’effort et moins de crises.</p>','i25-d-rano')
t('ERICA',[('E','Efficacy of'),('R','Ranolazine'),('I','In'),('C','Chronic'),('A','Angina')],'Essai ERICA (2006)','<p>Ranolazine ajoutée à l’amlodipine : réduction de la fréquence des crises d’angor.</p>','i25-d-rano')
t('MERLIN-TIMI 36',[('MERLIN','Metabolic Efficiency with Ranolazine for Less Ischemia in Non-ST-elevation acute coronary syndromes, non strictement lettre à lettre'),('TIMI','Thrombolysis In Myocardial Infarction'),('36','36e essai du groupe')],'Essai MERLIN-TIMI 36 (2007)','<p>Ranolazine après un SCA sans sus-décalage : pas de réduction des événements majeurs, moins d’ischémie récidivante.</p>','i25-d-rano')
t('ATPCI',[('ATPCI','nom d’essai (trimétazidine après angioplastie, « PCI »), non développé lettre à lettre dans sa publication')],'Essai ATPCI (2020)','<p>Trimétazidine après angioplastie : pas de réduction des événements ni de la récidive d’angor.</p>','i25-d-tmz')
t('IONA',[('I','Impact'),('O','Of'),('N','Nicorandil in'),('A','Angina')],'Essai IONA (2002)','<p>Nicorandil chez des patients angineux : réduction d’un critère composite incluant les hospitalisations pour douleur thoracique.</p>','i25-d-nico')
t('CAPRIE',[('C','Clopidogrel versus'),('A','Aspirin in'),('P','Patients at'),('R','Risk of'),('I','Ischaemic'),('E','Events')],'Essai CAPRIE (1996)','<p>Clopidogrel comparé à l’acide acétylsalicylique chez des patients vasculaires : réduction relative modeste des événements ischémiques.</p>','i25-d-clopi')
t('HOST-EXAM',[('HOST','Harmonizing Optimal Strategy for Treatment of coronary artery stenosis, non strictement lettre à lettre'),('EXAM','EXtended Antiplatelet Monotherapy (monothérapie antiplaquettaire prolongée)')],'Essai HOST-EXAM (2021)','<p>Après la double antiagrégation suivant une angioplastie : clopidogrel en monothérapie supérieur à l’acide acétylsalicylique sur un critère composite ischémique et hémorragique.</p>','i25-d-clopi')
t('AFIRE',[('AF','Atrial Fibrillation (fibrillation auriculaire)'),('I','and Ischemic events with'),('R','Rivaroxaban in'),('E','patiEnts with stable coronary artery disease')],'Essai AFIRE (2019)','<p>Fibrillation auriculaire et coronaropathie stable : rivaroxaban seul non inférieur à l’association avec un antiplaquettaire sur l’efficacité, et plus sûr.</p>')
t('COSIRA',[('CO','COronary'),('SI','SInus'),('R','Reducer for treatment of refractory'),('A','Angina')],'Essai COSIRA (2015)','<p>Réducteur du sinus coronaire comparé à une procédure simulée : amélioration de la classe d’angor.</p>','i25-reducer')
t('ORBITA-2',[('ORBITA','Objective Randomised Blinded Investigation with optimal medical Therapy of Angioplasty in stable angina, non strictement lettre à lettre'),('2','deuxième essai')],'Essai ORBITA-2 (2023)','<p>Angioplastie contre procédure simulée, sans anti-angineux : réduction de la fréquence de l’angor.</p>')
t('ORBITA-COSMIC',[('ORBITA','Objective Randomised Blinded Investigation with optimal medical Therapy of Angioplasty in stable angina (plateforme d’essais)'),('COSMIC','COronary Sinus reducer objective iMpact on symptoms, MRI Ischaemia and microvascular resistanCe, non strictement lettre à lettre')],'Essai ORBITA-COSMIC (2024)','<p>Réducteur du sinus coronaire contre procédure simulée : moins d’épisodes d’angor, sans amélioration démontrée de la perfusion.</p>','i25-reducer')
t('ABYSS',[('ABYSS','Assessment of β-blocker interruption one Year after an uncomplicated myocardial infarction on Safety and Symptomatic cardiac events, non strictement lettre à lettre')],'Essai ABYSS (2024)','<p>Interruption du bêtabloquant un an ou plus après un infarctus non compliqué : non-infériorité non démontrée, surtout du fait des hospitalisations cardiovasculaires.</p>')
t('FREEDOM',[('FREEDOM','Future REvascularization Evaluation in patients with Diabetes mellitus: Optimal management of Multivessel disease, non strictement lettre à lettre')],'Essai FREEDOM (2012)','<p>Diabétiques pluritronculaires : le pontage a réduit la mortalité et les infarctus par rapport à l’angioplastie, avec plus d’AVC.</p>')
t('EXCEL',[('EXCEL','Evaluation of XIENCE versus Coronary artery bypass surgery for Effectiveness of Left main revascularization, non strictement lettre à lettre')],'Essai EXCEL (2016)','<p>Tronc commun de complexité faible à intermédiaire : angioplastie et pontage comparables sur le critère principal à 3 ans.</p>')
t('NOBLE',[('NOBLE','NOrdic-Baltic-British LEft main revascularization study, non strictement lettre à lettre')],'Essai NOBLE (2016)','<p>Tronc commun : plus d’événements à 5 ans après angioplastie qu’après pontage, surtout infarctus et nouvelles revascularisations.</p>')
t('TNT',[('T','Treating to'),('N','New'),('T','Targets')],'Essai TNT (2005)','<p>Coronariens stables : atorvastatine 80 mg supérieure à 10 mg sur les événements cardiovasculaires majeurs.</p>','i25-d-statine')
t('LEADER',[('LEADER','Liraglutide Effect and Action in Diabetes: Evaluation of cardiovascular outcome Results, non strictement lettre à lettre')],'Essai LEADER (2016)','<p>Liraglutide chez le diabétique de type 2 à haut risque : réduction des événements cardiovasculaires majeurs.</p>','i25-d-cardiomet')
t('SUSTAIN-6',[('SUSTAIN','nom d’essai du programme sémaglutide (« soutenir »), non développable lettre à lettre'),('6','sixième essai du programme')],'Essai SUSTAIN-6 (2016)','<p>Sémaglutide chez le diabétique de type 2 à haut risque : réduction des événements cardiovasculaires majeurs.</p>','i25-d-cardiomet')
t('EMPA-REG OUTCOME',[('EMPA','EMPAgliflozine'),('REG','REGistration program (programme d’enregistrement)'),('OUTCOME','essai de résultats cliniques')],'Essai EMPA-REG OUTCOME (2015)','<p>Empagliflozine chez le diabétique de type 2 avec maladie cardiovasculaire : réduction de la mortalité cardiovasculaire.</p>','i25-d-cardiomet')
t('SELECT',[('SELECT','Semaglutide Effects on Cardiovascular Outcomes in People with Overweight or Obesity, nom arrangé non strictement lettre à lettre')],'Essai SELECT (2023)','<p>Sémaglutide 2,4 mg par semaine chez des patients cardiovasculaires en surpoids ou obèses, sans diabète : − 20 % d’événements cardiovasculaires majeurs.</p>','i25-d-cardiomet')
t('REDUCE-IT',[('REDUCE','REDUction of Cardiovascular Events with icosapent ethyl, non strictement lettre à lettre'),('IT','Intervention Trial (essai d’intervention)')],'Essai REDUCE-IT (2019)','<p>Icosapent éthyl 2 g × 2/jour chez des patients à haut risque ayant des triglycérides élevés sous statine : réduction des événements cardiovasculaires.</p>')
t('4S',[('4S','Scandinavian Simvastatin Survival Study : quatre mots commençant par S')],'Essai 4S (1994)','<p>Simvastatine chez le coronarien : réduction de la mortalité totale.</p>')
a('Pd',[('P','Pression'),('d','distale')],'Pression distale','<p>Pression mesurée par le guide en aval de la sténose.</p>','i25-ffr')
a('Pa',[('P','Pression'),('a','aortique')],'Pression aortique','<p>Pression mesurée par le cathéter à l’ostium coronaire.</p>','i25-ffr')
t('DIAD',[('D','Detection of'),('I','Ischemia in'),('A','Asymptomatic'),('D','Diabetics')],'Essai DIAD (2009)','<p>Dépistage de l’ischémie par scintigraphie chez des diabétiques de type 2 asymptomatiques : pas de réduction des infarctus ni des décès cardiaques.</p>')
t('FACTOR-64',[('FACTOR','nom d’essai (« facteur »), non développable lettre à lettre'),('64','référence au coroscanner à 64 coupes')],'Essai FACTOR-64 (2014)','<p>Dépistage par coroscanner chez des diabétiques asymptomatiques : pas de réduction des événements cardiovasculaires.</p>')
a('ERA',[('E','European'),('R','Renal'),('A','Association')],'European Renal Association (Association rénale européenne)','<p>Société savante européenne de néphrologie ; coautrice des recommandations ESC 2026 sur la maladie cardiovasculaire et rénale chronique.</p>')
a('MET',[('M','Metabolic (métabolique)'),('E','Equivalent (équivalent)'),('T','of Task (de la tâche)')],'Équivalent métabolique','<p>Unité de dépense énergétique : 1 MET correspond à la consommation d’oxygène de repos, environ 3,5 mL/kg/min. Une marche rapide correspond à environ 4 à 5 METs.</p>')
a('PharmaWiki',[('PharmaWiki','nom propre d’un site suisse d’information sur les médicaments, formé de « Pharma » et « Wiki » ; pas une abréviation')],'PharmaWiki','<p>Site suisse indépendant d’information sur les médicaments et leur statut de commercialisation en Suisse.</p>')
a('ILIAS',[('ILIAS','acronyme officiel du registre Inclusive Invasive Physiological Assessment in Angina Syndromes, formé à partir des mots du titre anglais')],'Registre ILIAS – Inclusive Invasive Physiological Assessment in Angina Syndromes',
 '<p>Registre international de patients angineux explorés par coronarographie et tests fonctionnels invasifs ; l’ESC 2024 en cite les prévalences d’ANOCA, de dysfonction endothéliale et de spasme.</p>')
a('PRECISE',[('PRE','PREdicting (prédiction)'),('C','bleeding Complications (des complications hémorragiques)'),('I','In patients undergoing (chez les patients recevant)'),('S','Stent implantation (un stent)'),('E','and subsEquent (puis une)')],'Score PRECISE-DAPT – prédiction des hémorragies sous double antiagrégation après stent',
 '<p>Score de risque hémorragique sous double antiagrégation après la pose d’un stent ; une valeur ≥ 25 désigne un haut risque hémorragique selon l’ESC 2023.</p>')
