from cardio_1 import a, G

a('I26',[('I','chapitre des maladies cardiovasculaires'),('26','catégorie de l’embolie pulmonaire')],'Code I26 de l’embolie pulmonaire','<p>Code CIM-10-GM 2024 de l’embolie pulmonaire, subdivisé en I26.0 (avec mention de cœur pulmonaire aigu, qui inclut l’embolie massive ou fulminante) et I26.9 (sans mention de cœur pulmonaire aigu).</p>')
a('PERC',[('P','Pulmonary'),('E','Embolism'),('R','Rule-out'),('C','Criteria')],'Critères d’exclusion d’embolie pulmonaire','<p>Huit critères dont l’utilisation exige une probabilité clinique initiale très faible ; ne pas appliquer chez un patient à risque élevé.</p>','i26-perc')
a('YEARS',[('YEARS','nom d’une stratégie diagnostique validée ; non présenté comme un acronyme lettre par lettre')],'Stratégie YEARS','<p>Algorithme combinant trois items cliniques et un seuil de D-dimères dépendant des items ; sa variante pour la grossesse suit un protocole spécifique.</p>')
a('sPESI',[('s','simplified (simplifié)'),('P','Pulmonary'),('E','Embolism'),('S','Severity'),('I','Index')],'Indice simplifié de gravité de l’embolie pulmonaire','<p>Score de pronostic précoce à six variables ; ne sert pas à confirmer le diagnostic.</p>','i26-spesi')
a('AMPLIFY',[('AMPLIFY','nom de l’essai clinique, sans développement lettre par lettre établi ici')],'Essai apixaban dans la maladie thromboembolique','<p>Essai publié en 2013 chez 5 395 adultes présentant une thrombose veineuse profonde ou une embolie pulmonaire symptomatique : l’apixaban était non inférieur à l’énoxaparine suivie de warfarine pour la récidive (2,3 % contre 2,7 %) et causait moins d’hémorragies majeures (0,6 % contre 1,8 %).</p>')
a('EINSTEIN-PE',[('EINSTEIN','nom d’un programme d’essais, sans développement lettre par lettre établi ici'),('PE','Pulmonary Embolism')],'Essai rivaroxaban dans l’embolie pulmonaire','<p>Essai publié en 2012 chez 4 832 patients présentant une embolie pulmonaire symptomatique, avec ou sans thrombose veineuse profonde : le rivaroxaban (15 mg deux fois par jour pendant trois semaines, puis 20 mg une fois par jour) était non inférieur à l’énoxaparine relayée par un antagoniste de la vitamine K pour la récidive (2,1 % contre 1,8 %) et causait moins d’hémorragies majeures (1,1 % contre 2,2 %).</p>')
a('PEITHO',[('PEITHO','nom de l’essai clinique, sans développement lettre par lettre établi ici')],'Essai de thrombolyse dans l’embolie à risque intermédiaire','<p>Essai de 2014 évaluant la ténectéplase, et non l’altéplase, chez 1 006 patients normotendus à risque intermédiaire-élevé : décès ou décompensation hémodynamique à sept jours 2,6 % contre 5,6 %, au prix de davantage d’hémorragies extracrâniennes (6,3 % contre 1,2 %) et d’accidents vasculaires cérébraux (2,4 % contre 0,2 %, hémorragiques pour 10 des 12 survenus sous ténectéplase).</p>')
a('PubMed',[('PubMed','nom propre de la base bibliographique de la National Library of Medicine des États-Unis (non abréviatif)')],'Base bibliographique PubMed','<p>Base bibliographique en libre accès de la National Library of Medicine des États-Unis ; elle donne accès aux références et aux résumés des articles biomédicaux et renvoie au texte intégral lorsqu’il est disponible.</p>')
