# Glossaire MEDINA — chapitre I48 Fibrillation et flutter auriculaires
from cardio_1 import a, G

# ---- abréviations cliniques et examens
a('AOD',[('A','Anticoagulant'),('O','Oral'),('D','Direct')],'Anticoagulant oral direct',
 '<p>Inhibiteur direct du facteur Xa (apixaban, rivaroxaban, édoxaban) ou de la thrombine (dabigatran). Premier choix de l’anticoagulation de la fibrillation auriculaire (ESC 2024), sauf prothèse mécanique et rétrécissement mitral modéré à sévère.</p>','i48-aod')
a('INR',[('I','International'),('N','Normalized'),('R','Ratio')],'International Normalized Ratio (rapport normalisé international)',
 '<p>Temps de prothrombine du patient rapporté à celui d’un témoin, corrigé par la sensibilité du réactif. Cible 2,0–3,0 sous antivitamine K dans la fibrillation auriculaire.</p>','i48-inr')
a('ETO',[('É','Échocardiographie'),('T','Trans-'),('O','Œsophagienne')],'Échocardiographie transœsophagienne',
 '<p>Échographie cardiaque par une sonde placée dans l’œsophage ; examen de référence pour exclure un thrombus de l’auricule gauche avant une cardioversion précoce.</p>','i48-eto')
a('ETT',[('É','Échocardiographie'),('T','Trans-'),('T','Thoracique')],'Échocardiographie transthoracique',
 '<p>Échographie cardiaque à travers la paroi thoracique ; recommandée dans la fibrillation auriculaire pour chercher une valvulopathie, mesurer la FEVG et l’oreillette gauche. Elle ne permet pas d’exclure un thrombus de l’auricule.</p>','echo')
a('EHRA',[('E','European'),('H','Heart'),('R','Rhythm'),('A','Association')],'European Heart Rhythm Association (Association européenne du rythme cardiaque)',
 '<p>Association de l’ESC consacrée à la rythmologie. Auteur du guide pratique des AOD (2021) et du score de symptômes de la fibrillation auriculaire.</p>','i48-ehra')
a('AF-CARE',[('AF','Atrial Fibrillation (fibrillation auriculaire)'),('C','Comorbidity and risk factor management (comorbidités et facteurs de risque)'),('A','Avoid stroke and thromboembolism (éviter l’AVC et la thrombo-embolie)'),('R','Reduce symptoms by rate and rhythm control (réduire les symptômes par le contrôle de la fréquence et du rythme)'),('E','Evaluation and dynamic reassessment (évaluation et réévaluation)')],'Parcours de soins de la fibrillation auriculaire (ESC 2024)','','i48-afcare')
a('CHA₂DS₂-VASc',[('C','Congestive heart failure : 1'),('H','Hypertension : 1'),('A₂','Âge ≥ 75 ans : 2'),('D','Diabète : 1'),('S₂','Stroke (AVC, accident ischémique transitoire) : 2'),('V','maladie Vasculaire : 1'),('A','Âge 65–74 ans : 1'),('Sc','Sex category (sexe féminin) : 1')],'Ancien score de risque thromboembolique (ESC 2016–2020), remplacé par le CHA₂DS₂-VA en 2024',
 '<p>Identique au CHA₂DS₂-VA avec un point supplémentaire pour le sexe féminin, retiré par l’ESC 2024.</p>','i48-cha')
a('HAS-BLED',[('H','Hypertension non contrôlée'),('A','Abnormal renal or liver function (fonction rénale ou hépatique anormale)'),('S','Stroke (AVC)'),('B','Bleeding (antécédent ou prédisposition hémorragique)'),('L','Labile INR (INR instable)'),('E','Elderly (âge > 65 ans)'),('D','Drugs or alcohol (médicaments ou alcool)')],'Score de risque hémorragique sous anticoagulant','','i48-hasbled')
a('ABC',[('A','Âge ≥ 80 ans'),('B','Body weight (poids) ≤ 60 kg'),('C','Créatinine ≥ 133 µmol/L')],'Aide-mémoire des critères de dose réduite de l’apixaban (deux sur trois)','<p>Aide pédagogique, non critère officiel.</p>','i48-mnemo-abc')
a('PIRATES',[('P','Pulmonaire'),('I','Ischémie'),('R','Rhumatismale (valvulopathie)'),('A','Anémie, âge'),('T','Thyroïde'),('E','Éthanol'),('S','Sepsis, Sleep apnoea (apnées), Surgery (chirurgie)')],'Aide-mémoire des causes de fibrillation auriculaire','<p>Aide pédagogique, non critère officiel.</p>','i48-pirates')
a('UI',[('U','Unités'),('I','Internationales')],'Unités internationales','<p>Unité d’activité biologique standardisée, utilisée pour les héparines et les concentrés de facteurs de coagulation.</p>')
a('VIH',[('V','Virus de l’'),('I','Immunodéficience'),('H','Humaine')],'Virus de l’immunodéficience humaine','<p>Plusieurs antirétroviraux (inhibiteurs de protéase potentialisés) inhibent fortement le CYP3A4 et la glycoprotéine P : interaction majeure avec les AOD.</p>')
a('VP',[('V','Veine'),('P','Pulmonaire')],'Veine pulmonaire','<p>Les veines pulmonaires se jettent dans l’oreillette gauche ; leurs manchons myocardiques déclenchent la plupart des accès de fibrillation auriculaire.</p>','i48-vp')
a('T3',[('T','Triiodothyronine'),('3','trois atomes d’iode')],'Triiodothyronine','<p>Hormone thyroïdienne active, produite surtout par désiodation périphérique de la T4.</p>','i48-tsh')
a('T4',[('T','Thyroxine (tétraiodothyronine)'),('4','quatre atomes d’iode')],'Thyroxine','<p>Principale hormone sécrétée par la thyroïde ; la T4 libre se dose après une TSH anormale. Valeurs usuelles ≈ 12–22 pmol/L.</p>','i48-tsh')
a('B1',[('B','Bruit'),('1','premier')],'Premier bruit du cœur','<p>Fermeture des valves mitrale et tricuspide ; son intensité varie d’un battement à l’autre en fibrillation auriculaire.</p>','i48-e-b1')
a('B4',[('B','Bruit'),('4','quatrième')],'Quatrième bruit du cœur','<p>Bruit télédiastolique dû à la contraction auriculaire contre un ventricule rigide ; absent en fibrillation auriculaire.</p>')
a('IX',[('IX','neuf en chiffres romains')],'Facteur IX de la coagulation','<p>Facteur antihémophilique B, vitamine K-dépendant ; son activité baisse sous antivitamine K.</p>')

# ---- électrocardiogramme
a('RR',[('R','onde R'),('R','onde R suivante')],'Intervalle RR','<p>Intervalle entre deux complexes QRS successifs ; son irrégularité sans périodicité caractérise la fibrillation auriculaire.</p>','i48-ecg-fa')
a('PR',[('P','début de l’onde P'),('R','début du QRS (onde R ou Q)')],'Intervalle PR','<p>Temps de conduction auriculoventriculaire, normal 120–200 ms ; court avec une onde delta dans la pré-excitation.</p>','i48-preexc')
a('QT',[('Q','début du QRS'),('T','fin de l’onde T')],'Intervalle QT','<p>Durée de la dépolarisation et de la repolarisation ventriculaires ; son allongement expose aux torsades de pointes (sotalol, amiodarone).</p>')
a('QTc',[('Q','début du QRS'),('T','fin de l’onde T'),('c','corrigé pour la fréquence cardiaque')],'Intervalle QT corrigé','<p>QT rapporté à la fréquence (formule de Bazett ou de Fridericia). Normal &lt; 450 ms chez l’homme, &lt; 460 ms chez la femme ; au-delà de 500 ms, risque élevé de torsades.</p>')
a('aVF',[('a','augmentée'),('V','dérivation unipolaire (Voltage)'),('F','du pied gauche (Foot)')],'Dérivation unipolaire augmentée du membre inférieur','<p>Dérivation inférieure avec II et III ; ondes F négatives en dents de scie dans le flutter typique antihoraire.</p>','i48-ecg-flutter')

# ---- noms propres composés
a('Cockcroft-Gault',[('Cockcroft-Gault','noms des deux auteurs de la formule (Donald Cockcroft et Henry Gault, 1976), non une abréviation')],'Formule de Cockcroft-Gault (clairance de la créatinine)','','i48-cg')
a('Child-Pugh',[('Child-Pugh','noms des auteurs (Charles Child, Ralph Pugh), non une abréviation')],'Classification de Child-Pugh de l’insuffisance hépatocellulaire','<p>Classes A, B, C selon la bilirubine, l’albumine, le temps de prothrombine, l’ascite et l’encéphalopathie ; les AOD sont contre-indiqués en classe C.</p>')
a('Wolff-Parkinson-White',[('Wolff-Parkinson-White','noms des trois auteurs (Louis Wolff, John Parkinson, Paul Dudley White, 1930), non une abréviation')],'Syndrome de Wolff-Parkinson-White','<p>Pré-excitation ventriculaire par une voie accessoire, avec PR court et onde delta, associée à des tachycardies.</p>','i48-preexc')
a('CoLaus',[('Co','Cohorte'),('Laus','Lausannoise')],'Cohorte populationnelle lausannoise CoLaus','','i48-colaus')
a('PsyCoLaus',[('Psy','volet Psychiatrique'),('Co','de la Cohorte'),('Laus','Lausannoise')],'Volet psychiatrique de la cohorte CoLaus','','i48-colaus')
a('Swiss-AF',[('Swiss','suisse'),('AF','Atrial Fibrillation (fibrillation auriculaire)')],'Cohorte suisse de la fibrillation auriculaire','<p>Cohorte nationale prospective de 2 415 patients en FA recrutés dans 14 centres suisses (recrutement clos en 2020), centrée sur les lésions cérébrales et la cognition.</p>','i48-colaus')

# ---- gènes et enzymes
a('PITX2',[('PITX2','nom HGNC « paired like homeodomain 2 », historiquement « PITuitary homeoboX 2 », non strictement lettre à lettre')],'Gène PITX2 (facteur de transcription à homéoboîte)','<p>Situé en 4q25, près du locus génétique le plus fortement associé à la fibrillation auriculaire ; contrôle le développement de l’oreillette gauche et des veines pulmonaires.</p>')
a('KCNQ1',[('K','potassium (Kalium)'),('CN','Channel (canal)'),('Q','sous-famille Q (KQT)'),('1','membre 1')],'Gène du canal potassique KCNQ1','<p>Canal du courant potassique lent ; certains variants à gain de fonction causent des FA familiales.</p>')
a('SCN5A',[('SCN','symbole HGNC de la famille des canaux sodiques voltage-dépendants (Sodium ChaNnel), non strictement lettre à lettre'),('5','type 5'),('A','sous-unité Alpha')],'Gène du canal sodique cardiaque','<p>Code le canal sodique rapide ; ses variants causent le syndrome de Brugada, des troubles de conduction et certaines FA familiales.</p>')
a('VKORC1',[('VKOR','Vitamin K epOxide Reductase (vitamine K époxyde réductase)'),('C','Complex (complexe)'),('1','sous-unité 1')],'Gène de la vitamine K époxyde réductase','<p>Cible des antivitamines K ; ses variants modifient la dose nécessaire.</p>')
a('CYP2C9',[('CYP','CYtochrome P450'),('2','famille 2'),('C','sous-famille C'),('9','isoenzyme 9')],'Cytochrome P450 2C9','<p>Métabolise la warfarine et l’acénocoumarol ; ses variants lents exposent au surdosage.</p>')
a('CYP2D6',[('CYP','CYtochrome P450'),('2','famille 2'),('D','sous-famille D'),('6','isoenzyme 6')],'Cytochrome P450 2D6','<p>Métabolise la flécaïnide et la propafénone ; inhibé par la fluoxétine et la paroxétine.</p>')

# ---- essais
def t(k, lit, full, d, ref=None):
    a(k, lit, full, d, ref)
t('RE-LY',[('R','Randomized'),('E','Evaluation of'),('L','Long-term anticoagulation therapy'),('Y','(dernière lettre de « therapY »)')],'Essai RE-LY (2009)','<p>Dabigatran 110 et 150 mg × 2/jour contre warfarine dans la fibrillation auriculaire.</p>','i48-aod')
t('ROCKET AF',[('ROCKET','nom d’essai arrangé à partir de « Rivaroxaban Once daily oral direct factor Xa inhibition Compared with vitamin K antagonism for prevention of stroke and Embolism Trial », non strictement lettre à lettre'),('AF','in Atrial Fibrillation')],'Essai ROCKET AF (2011)','<p>Rivaroxaban contre warfarine : non-infériorité sur l’AVC et l’embolie.</p>','i48-aod')
t('ARISTOTLE',[('ARISTOTLE','nom d’essai arrangé à partir de « Apixaban for Reduction In STroke and Other ThromboemboLic Events in atrial fibrillation », non strictement lettre à lettre')],'Essai ARISTOTLE (2011)','<p>Apixaban contre warfarine : moins d’AVC et d’embolies, moins d’hémorragies majeures, mortalité réduite.</p>','i48-aod')
t('ENGAGE AF-TIMI 48',[('ENGAGE','nom arrangé à partir de « Effective aNticoaGulation with factor xA next GEneration »'),('AF','in Atrial Fibrillation'),('TIMI','Thrombolysis In Myocardial Infarction (groupe d’étude)'),('48','48e étude du groupe')],'Essai ENGAGE AF-TIMI 48 (2013)','<p>Édoxaban contre warfarine dans la fibrillation auriculaire.</p>','i48-aod')
t('EAST-AFNET 4',[('E','Early treatment of'),('A','Atrial fibrillation for'),('S','Stroke prevention'),('T','Trial'),('AFNET','Atrial Fibrillation NETwork (réseau allemand)'),('4','quatrième essai du réseau')],'Essai EAST-AFNET 4 (2020)','<p>Contrôle du rythme précoce (dans l’année du diagnostic) contre soins usuels : réduction du critère composite décès cardiovasculaire, AVC, hospitalisation pour insuffisance cardiaque ou syndrome coronarien.</p>','i48-remod')
t('NOAH-AFNET 6',[('NOAH','Non-vitamin K antagonist Oral anticoagulants in patients with Atrial High rate episodes'),('AFNET','Atrial Fibrillation NETwork'),('6','sixième essai du réseau')],'Essai NOAH-AFNET 6 (2023)','<p>Édoxaban contre placebo dans les épisodes auriculaires rapides détectés par dispositif : arrêt pour futilité, davantage de saignements.</p>','i48-infraclin')
t('ARTESiA',[('A','Apixaban for the'),('R','Reduction of'),('TE','ThromboEmbolism in patients with device-detected'),('S','Subclinical'),('iA','atrIal fibrillAtion')],'Essai ARTESiA (2023)','<p>Apixaban contre acide acétylsalicylique dans la FA infraclinique : moins d’AVC et d’embolies, davantage d’hémorragies majeures.</p>','i48-infraclin')
t('LAAOS III',[('L','Left'),('A','Atrial'),('A','Appendage'),('O','Occlusion'),('S','Study'),('III','troisième essai')],'Essai LAAOS III (2021)','<p>Fermeture chirurgicale de l’auricule gauche pendant une chirurgie cardiaque, en plus de l’anticoagulation : réduction d’environ un tiers des AVC et embolies.</p>','i48-laao')
t('CHAMPION-AF',[('CHAMPION','nom d’essai arrangé (comparaison du dispositif Watchman FLX aux AOD pour la protection embolique), non strictement lettre à lettre'),('AF','Atrial Fibrillation')],'Essai CHAMPION-AF (2026)','<p>Fermeture percutanée de l’auricule contre AOD : non-infériorité sur un critère composite, moins d’hémorragies non procédurales, davantage d’AVC ischémiques.</p>','i48-laao')
t('ELAN',[('E','Early versus'),('L','Late initiation of direct oral'),('A','Anticoagulants in post-ischaemic stroke patients with atrial fibrillatio'),('N','N (dernière lettre)')],'Essai ELAN (2023)','<p>Essai dirigé depuis Berne : reprise précoce d’un AOD après un AVC ischémique lié à la FA, sans excès d’hémorragies.</p>','i48-elan')
t('FRAIL-AF',[('FRAIL','FRAIL (fragile) elderly patients'),('AF','with Atrial Fibrillation')],'Essai FRAIL-AF (2023)','<p>Chez des sujets âgés fragiles stables sous antivitamine K, le passage à un AOD a augmenté les hémorragies.</p>','i48-avk')
t('INVICTUS',[('INVICTUS','nom d’essai arrangé à partir de « INVestIgation of rheumatiC AF Treatment Using vitamin K antagonists, rivaroxaban or aspirin Studies », non strictement lettre à lettre')],'Essai INVICTUS (2022)','<p>Cardiopathie rhumatismale avec FA : rivaroxaban inférieur à l’antivitamine K.</p>','i48-mitral')
t('RE-ALIGN',[('RE-ALIGN','nom d’essai arrangé à partir de « Randomized, phase II study to Evaluate the sAfety and pharmacokinetics of oraL dabIGatran etexilate in patients after heart valve replacemeNt », non strictement lettre à lettre')],'Essai RE-ALIGN (2013)','<p>Dabigatran chez les porteurs de prothèse mécanique : plus de thromboses et d’hémorragies que la warfarine ; essai arrêté.</p>','i48-mitral')
t('RACE II',[('RACE','RAte Control Efficacy in permanent atrial fibrillation'),('II','deuxième essai')],'Essai RACE II (2010)','<p>Contrôle de fréquence souple (&lt; 110/min au repos) non inférieur au contrôle strict (&lt; 80/min).</p>','i48-d-frein')
t('RACE 7',[('RACE','Rate Control versus Electrical cardioversion (programme néerlandais)'),('7','septième essai (RACE 7 ACWAS : Acute Cardioversion versus Wait And See)')],'Essai RACE 7 ACWAS (2019)','<p>FA récente stable : une stratégie d’attente avec cardioversion différée si besoin est non inférieure à la cardioversion immédiate ; environ 70 % de conversions spontanées en 48 heures.</p>','i48-24h')
t('RATE-AF',[('RATE','RAte control Therapy Evaluation'),('AF','in permanent Atrial Fibrillation')],'Essai RATE-AF (2020)','<p>Digoxine contre bisoprolol chez des sujets âgés en FA permanente avec symptômes d’insuffisance cardiaque : qualité de vie comparable à 6 mois, moins d’effets indésirables sous digoxine.</p>','i48-d-dig')
t('CAST',[('C','Cardiac'),('A','Arrhythmia'),('S','Suppression'),('T','Trial')],'Essai CAST (1989)','<p>Flécaïnide et encaïnide après infarctus pour supprimer les extrasystoles ventriculaires : surmortalité. Origine de la contre-indication de la classe Ic dans la coronaropathie.</p>','i48-d-flec')
t('ATHENA',[('ATHENA','nom d’essai arrangé à partir de « A placebo-controlled, double-blind, parallel arm Trial to assess the efficacy of dronedarone for the prevention of cardiovascular Hospitalization or death from any cause in patiENts with Atrial fibrillation », non strictement lettre à lettre')],'Essai ATHENA (2009)','<p>Dronédarone : réduction des hospitalisations cardiovasculaires et des décès dans la FA non permanente.</p>','i48-d-drone')
t('PALLAS',[('PALLAS','nom d’essai arrangé à partir de « Permanent Atrial fibriLLAtion outcome Study using dronedarone on top of standard therapy », non strictement lettre à lettre')],'Essai PALLAS (2011)','<p>Dronédarone dans la FA permanente : excès de décès, d’AVC et d’insuffisance cardiaque ; essai arrêté.</p>','i48-d-drone')
t('ANDROMEDA',[('ANDROMEDA','nom d’essai arrangé à partir de « ANtiarrhythmic trial with DROnedarone in Moderate to severe congestive heart failure Evaluating morbidity DecreAse », non strictement lettre à lettre')],'Essai ANDROMEDA (2008)','<p>Dronédarone dans l’insuffisance cardiaque sévère récemment décompensée : surmortalité.</p>','i48-d-drone')
t('ANNEXA-I',[('ANNEXA','nom d’essai arrangé à partir de « ANdexanet alfa, a Novel Antidote to the anticoagulation Effects of factor Xa inhibitors »'),('I','Intracranial hemorrhage (hémorragie intracrânienne)')],'Essai ANNEXA-I (2024)','<p>Andexanet alfa contre soins usuels dans l’hémorragie intracérébrale sous inhibiteur du facteur Xa : meilleure hémostase, davantage d’événements thrombotiques dont des AVC ischémiques.</p>','i48-antidote')
t('AFFIRM',[('AFFIRM','nom d’essai arrangé à partir de « Atrial Fibrillation Follow-up Investigation of Rhythm Management », non strictement lettre à lettre')],'Essai AFFIRM (2002)','<p>Contrôle du rythme contre contrôle de la fréquence dans la FA de patients âgés à risque d’AVC : pas de différence de mortalité ; les AVC survenaient surtout après arrêt de l’anticoagulation ou sous INR infrathérapeutique.</p>','i48-cha')
t('AVERROES',[('AVERROES','nom d’essai arrangé à partir de « Apixaban VERsus acetylsalicylic acid to pRevent strOkE in atrial fibrillation patientS who have failed or are unsuitable for vitamin K antagonist treatment », non strictement lettre à lettre')],'Essai AVERROES (2011)','<p>Apixaban contre aspirine chez des patients en FA inéligibles à l’antivitamine K : réduction d’environ 55 % des AVC et embolies systémiques, sans excès significatif d’hémorragie majeure.</p>','i48-aod')
a('DIG',[('D','Digitalis'),('I','Investigation'),('G','Group')],'Essai DIG (1997)','<p>Digoxine contre placebo dans l’insuffisance cardiaque en rythme sinusal : mortalité inchangée, hospitalisations pour insuffisance cardiaque réduites.</p>','i48-d-dig')
a('XII',[('XII','douze en chiffres romains')],'Facteur XII de la coagulation','<p>Facteur Hageman, qui amorce la voie de contact de la coagulation au contact d’une surface artificielle chargée négativement.</p>')
a('Wolff-Chaikoff',[('Wolff-Chaikoff','noms des deux auteurs (Jan Wolff, Israel Lyon Chaikoff, 1948), non une abréviation')],'Effet Wolff-Chaikoff','<p>Blocage transitoire de l’organification de l’iode par la thyroïde après une charge iodée importante ; la glande normale s’en échappe en quelques jours.</p>','i48-thyr')
a('SSC',[('S','Société'),('S','Suisse de'),('C','Cardiologie')],'Société suisse de cardiologie','<p>Société savante nationale de cardiologie ; coauteur des directives suisses sur l’aptitude à la conduite (2e édition, 2024).</p>')
a('SSML',[('S','Société'),('S','Suisse de'),('M','Médecine'),('L','Légale')],'Société suisse de médecine légale','<p>Société savante coautrice, avec la Société suisse de cardiologie, des directives sur l’aptitude à la conduite et les maladies cardiovasculaires (2e édition, octobre 2024).</p>')

a('HUG',[('H','Hôpitaux'),('U','Universitaires de'),('G','Genève')],'Hôpitaux universitaires de Genève','<p>Établissement universitaire suisse. Sa pharmacie publie des guides hospitaliers d’administration des médicaments.</p>')

a('DOI',[('D','Digital'),('O','Object'),('I','Identifier')],'Identifiant numérique permanent d’une publication','<p>Identifiant bibliographique qui permet de retrouver une publication, indépendamment de l’adresse de sa page web.</p>')
