from cardio_1 import a, G
# Abréviations nouvelles du cours I78 (télangiectasie hémorragique héréditaire) ; ENG, ACVRL1, BMP sont réutilisées.
a('SMAD4',[('SMAD','fusion de Sma (Caenorhabditis elegans) et de MAD, Mothers Against Decapentaplegic (drosophile)'),('4','membre 4')],'Gène SMAD4, messager intracellulaire des voies du facteur de croissance transformant bêta','<p>Gène d’un messager intracellulaire commun aux voies du facteur de croissance transformant bêta et des protéines morphogénétiques osseuses ; ses mutations causent le syndrome associant polypose juvénile et télangiectasie hémorragique héréditaire, ce qui impose un dépistage colique dès 15 ans.</p>','i78-smad4')
a('ALK1',[('A','Activin receptor-'),('L','Like'),('K','Kinase'),('1','1')],'Récepteur ALK1 (kinase 1 apparentée au récepteur de l’activine), codé par ACVRL1','<p>Récepteur endothélial de type I, activé par la protéine morphogénétique osseuse 9 ; ses mutations, par le gène ACVRL1, causent la télangiectasie hémorragique héréditaire de type 2.</p>','i78-acvrl1')
a('BMP9',[('B','Bone'),('M','Morphogenetic'),('P','Protein'),('9','9')],'Protéine morphogénétique osseuse 9','<p>Ligand circulant, codé par le gène GDF2, qui active le récepteur ALK1 et son corécepteur l’endogline sur la cellule endothéliale ; il stabilise les vaisseaux matures.</p>','i78-bmp9')
a('GDF2',[('G','Growth'),('D','Differentiation'),('F','Factor'),('2','2')],'Gène GDF2 (facteur de croissance et de différenciation 2), qui code la protéine morphogénétique osseuse 9','<p>Gène du ligand BMP9 ; ses variants causent une forme rare de syndrome apparenté à la télangiectasie hémorragique héréditaire.</p>','i78-bmp9')
a('ESS',[('E','Epistaxis'),('S','Severity'),('S','Score')],'Score de sévérité des épistaxis','<p>Questionnaire validé (Hoag et al., 2010) de 0 à 10, qui combine fréquence, durée et intensité des épistaxis, recours aux soins, anémie et transfusions ; critère de jugement des essais de la télangiectasie hémorragique héréditaire.</p>','i78-ess')
a('Rendu-Osler',[('Rendu-Osler','noms propres : Henri Rendu, médecin français (1896), et William Osler, médecin canadien (1901)')],'Maladie de Rendu-Osler (télangiectasie hémorragique héréditaire)','<p>Éponyme usuel en français de la télangiectasie hémorragique héréditaire, d’après les descriptions d’Henri Rendu et de William Osler.</p>','i78-hht')
a('Rendu-Osler-Weber',[('Rendu-Osler-Weber','noms propres : Henri Rendu, William Osler et Frederick Parkes Weber, médecins (1896-1907)')],'Syndrome de Rendu-Osler-Weber (télangiectasie hémorragique héréditaire)','<p>Éponyme complet de la télangiectasie hémorragique héréditaire, qui ajoute le nom de Frederick Parkes Weber, médecin britannique.</p>','i78-hht')
a('Garcia-Tsao',[('Garcia-Tsao','nom propre : Guadalupe Garcia-Tsao, hépatologue, coautrice des recommandations de 2011')],'Guadalupe Garcia-Tsao (nom d’auteur)','<p>Hépatologue de l’Université Yale, coautrice des premières recommandations internationales sur la télangiectasie hémorragique héréditaire (2011).</p>')
