from cardio_1 import a, G
# Abréviations nouvelles du cours I89 (lymphoedème) ; les clés existantes (FOXC2, S2k, AWMF, CIM-10-GM) sont réutilisées.
a('ISL',[('I','International'),('S','Society of'),('L','Lymphology')],'Société internationale de lymphologie','<p>Société savante internationale de lymphologie ; publie et révise régulièrement le document de consensus sur le diagnostic et le traitement du lymphoedème périphérique (version 2023, revue Lymphology).</p>')
a('FLT4',[('FLT','Fms-Like Tyrosine kinase'),('4','4')],'Gène FLT4, codant le récepteur VEGFR-3','<p>Gène du récepteur 3 du facteur de croissance de l’endothélium vasculaire, indispensable au développement des vaisseaux lymphatiques. Ses mutations causent certaines formes de lymphoedème congénital primaire (maladie de Nonne et Milroy).</p>')
a('SOX18',[('SOX','SRY-related HMG-bOX (boîte HMG apparentée à SRY)'),('18','membre 18')],'Gène du facteur de transcription SOX18','<p>Facteur de transcription du développement lymphatique ; ses mutations causent le syndrome hypotrichose-lymphoedème-télangiectasies.</p>')
a('OpenStax',[('OpenStax','nom propre de l’éditeur, non une abréviation')],'OpenStax, éditeur universitaire de manuels en libre accès','<p>Éditeur à but non lucratif de l’Université Rice (Houston) qui publie des manuels universitaires sous licence Creative Commons Attribution, dont <i>Anatomy &amp; Physiology</i>, source de plusieurs figures de l’atlas.</p>')
a('SGUL',[('S','St'),('G','George’s'),('U','University of'),('L','London')],'St George’s, University of London','<p>Université londonienne dont le groupe de recherche lymphovasculaire a publié sous licence libre la figure du capillaire et du collecteur lymphatiques reprise dans ce cours.</p>')

# Codes ajoutés le 10.10.2026 : repli de I88 dans I89 et de R03 dans I95 (CIM-10-GM 2024, BfArM).
a('B23.8',[('B23.8','code de la Classification internationale des maladies, 10e révision, modification allemande')],'Lymphadénopathie généralisée liée au VIH','<p>Code CIM-10-GM 2024 ; une cause virale identifiée exclut le code I88.</p>','i89-i88')
a('R03.0',[('R03.0','code de la Classification internationale des maladies, 10e révision, modification allemande')],'Élévation de la tension sans diagnostic d’hypertension','<p>Code CIM-10-GM 2024 d’une constatation isolée, à confirmer par une mesure hors cabinet (cours I10).</p>','i95-r03')
a('R03.1',[('R03.1','code de la Classification internationale des maladies, 10e révision, modification allemande')],'Baisse non spécifique de la tension','<p>Code CIM-10-GM 2024 d’une pression basse constatée sans diagnostic d’hypotension ; exclu de I95.</p>','i95-r03')
a('R57.9',[('R57.9','code de la Classification internationale des maladies, 10e révision, modification allemande')],'Choc, sans précision','<p>Code CIM-10-GM 2024 ; le collapsus cardiovasculaire avec hypoperfusion est exclu de I95.</p>','i95-r03')
a('O26.5',[('O26.5','code de la Classification internationale des maladies, 10e révision, modification allemande')],'Syndrome hypotensif de la mère','<p>Code CIM-10-GM 2024 ; exclu de I95.</p>','i95-r03')
