from cardio_1 import a, G
# Glossaire du cours J21 — Bronchiolite aiguë et infections respiratoires basses non précisées (P-02-Pneumologie).
# Ajout conditionnel : une clé déjà définie par un autre module n’est jamais écrasée (vérification de l’absence
# de collision le 09.10.2026). CFV et mRESVIA sont déjà définis par glossary/j12.py, injecté en parallèle et
# chargé avant ce fichier : leurs entrées ne sont pas écrasées. Revue IA ; ne vaut pas validation médicale.

def _a(k, *args):
    if k not in G:
        a(k, *args)

_a('J21.0', [('J21.0', 'code CIM-10-GM 2024')], 'Bronchiolite aiguë due au virus respiratoire syncytial', '<p>Sous-catégorie couverte par le cours J21 — Bronchiolite aiguë et infections respiratoires basses non précisées (catalogue BfArM, version 2024).</p>')
_a('J21.1', [('J21.1', 'code CIM-10-GM 2024')], 'Bronchiolite aiguë due au métapneumovirus humain', '<p>Sous-catégorie couverte par le cours J21 — Bronchiolite aiguë et infections respiratoires basses non précisées (catalogue BfArM, version 2024).</p>')
_a('J21.8', [('J21.8', 'code CIM-10-GM 2024')], 'Bronchiolite aiguë due à d’autres micro-organismes précisés', '<p>Sous-catégorie couverte par le cours J21 — Bronchiolite aiguë et infections respiratoires basses non précisées (catalogue BfArM, version 2024).</p>')
_a('J21.9', [('J21.9', 'code CIM-10-GM 2024')], 'Bronchiolite aiguë, sans précision', '<p>Sous-catégorie couverte par le cours J21 — Bronchiolite aiguë et infections respiratoires basses non précisées (catalogue BfArM, version 2024).</p>')
_a('SSPP', [('S', 'Société'), ('S', 'Suisse de'), ('P', 'Pneumologie'), ('P', 'Pédiatrique')], 'Société suisse de pneumologie pédiatrique', '<p>Société savante suisse de pneumologie de l’enfant. Trois pneumologues pédiatres suisses ont publié en 2020 la mise à jour sur la bronchiolite aiguë (Barben, Regamey et Hammer, Forum Médical Suisse), qui succède aux recommandations de 2003.</p>', 'j21-sspp')
_a('SAPP', [('S', 'Schweizerische (suisse)'), ('A', 'Arbeitsgemeinschaft für (groupe de travail de)'), ('P', 'Pädiatrische (pédiatrique)'), ('P', 'Pneumologie')], 'Groupe de travail suisse de pneumologie pédiatrique', '<p>Groupe qui a publié en 2003 les recommandations suisses de traitement de la bronchiolite aiguë du nourrisson (Paediatrica, vol. 14, n° 6). La mise à jour de 2020 attribue ces recommandations à la SSPP.</p>', 'j21-sspp')
_a('CFV', [('C', 'Commission'), ('F', 'Fédérale pour les'), ('V', 'Vaccinations')], 'Commission fédérale pour les vaccinations', '<p>Commission d’experts qui élabore, avec l’Office fédéral de la santé publique, le Plan de vaccination suisse et les recommandations sur l’immunisation contre le virus respiratoire syncytial.</p>', 'j21-algorithme')
_a('NS2', [('N', 'Non-'), ('S', 'Structural (non structurale)'), ('2', 'protéine numéro 2')], 'Protéine non structurale 2 du virus respiratoire syncytial', '<p>Protéine virale qui provoque l’arrondissement et l’extrusion des cellules ciliées infectées ; ces cellules desquamées s’accumulent dans la lumière des bronchioles et l’obstruent (Pickles et al., 2015).</p>', 'j21-ns2')
_a('NaCl', [('Na', 'Natrium (sodium)'), ('Cl', 'Chlore (chlorure)')], 'Chlorure de sodium', '<p>Sel dont la solution à 0,9 % (sérum physiologique) sert au lavage nasal ; les solutions à 3 % ou plus sont dites hypertoniques.</p>', 'j21-desobstruction')
_a('mRESVIA', [('mRESVIA', 'nom commercial du vaccin, non développable lettre à lettre')], 'Vaccin à ARN messager contre le virus respiratoire syncytial', '<p>Vaccin autorisé en Suisse chez l’adulte dès 18 ans ; son ARN messager code la protéine F du virus de sous-groupe A, stabilisée en conformation préfusionnelle. Il est contre-indiqué avant l’âge de 8 mois.</p>', 'j21-d-mresvia')
_a('MELODY', [('MELODY', 'nom propre de l’essai de phase 3 du nirsévimab chez le nourrisson né à 35 semaines ou plus, non développable lettre à lettre')], 'Essai MELODY (nirsévimab, 2022)', '<p>Essai randomisé contre placebo chez 1490 nourrissons : infection respiratoire basse à virus respiratoire syncytial médicalement prise en charge chez 1,2 % contre 5,0 %, soit une efficacité de 74,5 % (Hammitt, 2022).</p>', 'j21-d-nirsevimab')
_a('HARMONIE', [('HARMONIE', 'nom propre de l’essai pragmatique du nirsévimab en France, en Allemagne et au Royaume-Uni, non développable lettre à lettre')], 'Essai HARMONIE (nirsévimab, 2023)', '<p>Essai randomisé ouvert chez 8058 nourrissons, contre les soins habituels : hospitalisation pour infection respiratoire basse à virus respiratoire syncytial chez 0,3 % contre 1,5 %, soit une efficacité de 83,2 % (Drysdale, 2023).</p>', 'j21-d-nirsevimab')
_a('MEDLEY', [('MEDLEY', 'nom propre de l’essai du nirsévimab contre le palivizumab chez le nourrisson à haut risque, non développable lettre à lettre')], 'Essai MEDLEY (nirsévimab contre palivizumab)', '<p>Essai randomisé chez 925 nourrissons à haut risque (grande prématurité, maladie pulmonaire chronique, cardiopathie) : profil de sécurité comparable et infections graves à VRS chez 0,6 % contre 1,0 % (information professionnelle Beyfortus® et bulletin OFSP 2026).</p>', 'j21-d-palivizumab')
_a('MUSIC', [('MUSIC', 'nom propre de l’étude ouverte du nirsévimab chez l’enfant immunodéprimé, non développable lettre à lettre')], 'Étude MUSIC (nirsévimab chez l’enfant immunodéprimé)', '<p>Étude ouverte chez 100 enfants immunodéprimés de 24 mois ou moins : chez 14 % d’entre eux, la concentration de nirsévimab a chuté plus vite, ce qui peut raccourcir la protection (information professionnelle Beyfortus®).</p>', 'j21-d-nirsevimab')
_a('MATISSE', [('MATISSE', 'nom propre de l’essai de phase 3 du vaccin maternel bivalent, non développable lettre à lettre')], 'Essai MATISSE (vaccin maternel bivalent, 2023)', '<p>Essai de phase 3 chez des femmes enceintes de 24 à 36 semaines : efficacité de 81,8 % contre l’infection respiratoire basse sévère du nourrisson dans les 90 jours suivant la naissance et de 69,4 % dans les 180 jours (Kampmann, 2023).</p>', 'j21-d-abrysvo')
_a('CLEVER', [('CLEVER', 'nom propre de l’essai de phase 2b/3 du clesrovimab, non développable lettre à lettre')], 'Essai CLEVER (clesrovimab, 2025)', '<p>Essai randomisé contre placebo chez 3614 nourrissons : efficacité de 60,4 % contre l’infection respiratoire basse médicalement prise en charge et de 84,2 % contre l’hospitalisation dans les 150 jours (Zar, 2025).</p>', 'j21-d-clesrovimab')
_a('ProHOSP', [('Pro', 'Procalcitonine'), ('HOSP', 'HOSPitalier (essai mené dans les urgences hospitalières suisses)')], 'Essai ProHOSP (procalcitonine, 2009)', '<p>Essai suisse de non-infériorité chez 1359 adultes atteints d’infection respiratoire basse : un algorithme fondé sur la procalcitonine a réduit l’exposition aux antibiotiques de 8,7 à 5,7 jours sans augmenter les événements indésirables (Schuetz, 2009).</p>', 'j21-prohosp')
_a('NG9', [('NG', 'NICE Guideline (recommandation du NICE)'), ('9', 'numéro 9 de la série')], 'Recommandation NICE n° 9 : bronchiolite de l’enfant', '<p>Recommandation britannique « Bronchiolitis in children: diagnosis and management », publiée en juin 2015 et mise à jour en août 2021 pour les seuils de saturation.</p>', 'j21-nice')
_a('AS01E', [('AS01E', 'nom du « système adjuvant AS01E » de l’information professionnelle, non développable lettre à lettre')], 'Système adjuvant du vaccin Arexvy®', '<p>Adjuvant fait d’un extrait de <i>Quillaja saponaria</i> et d’un lipide A monophosphorylé issu de <i>Salmonella minnesota</i>, qui renforce la réponse immunitaire au vaccin (information professionnelle Arexvy, bulletin OFSP 2026).</p>', 'j21-d-arexvy')
