from cardio_1 import a, G
from cardio_2 import t
a('GOLD',[('G','Global'),('O','initiative for chronic Obstructive'),('L','Lung'),('D','Disease')],'Global Initiative for Chronic Obstructive Lung Disease','<p>Organisation qui publie chaque année la stratégie internationale de la BPCO ; version de référence ici : rapport 2026.</p>')
a('mMRC',[('m','modified (modifiée)'),('M','Medical'),('R','Research'),('C','Council')],'Échelle de dyspnée du Medical Research Council modifiée','<p>Échelle de 0 à 4 ; ≥ 2 = patient symptomatique.</p>','j44-mmrc')
a('CAT',[('C','COPD (BPCO)'),('A','Assessment'),('T','Test')],'COPD Assessment Test','<p>Questionnaire de 8 items, score 0 à 40 ; ≥ 10 = patient symptomatique. Désormais nommé Chronic Airways Assessment Test (CAAT), nom employé par GOLD 2026 ; scores interchangeables avec ceux du CAT.</p>','j44-cat')
a('CAAT',[('C','Chronic'),('A','Airways'),('A','Assessment'),('T','Test')],'Chronic Airways Assessment Test','<p>Nom actuel du questionnaire historique CAT : huit items et scores interchangeables ; ≥ 10 indique une gêne symptomatique importante dans GOLD 2026.</p>','j44-cat')
a('BODE',[('B','Body mass index (indice de masse corporelle)'),('O','Obstruction'),('D','Dyspnée'),('E','Exercise (capacité d’effort)')],'Indice BODE','<p>Score pronostique de 0 à 10.</p>','j44-bode')
a('PRISm',[('P','Preserved'),('R','Ratio'),('I','Impaired'),('Sm','Spirometry')],'Preserved ratio impaired spirometry','<p>Rapport conservé avec VEMS &lt; 80 % : état à risque, non BPCO.</p>','j44-prism')
a('VNI',[('V','Ventilation'),('N','Non'),('I','Invasive')],'Ventilation non invasive','<p>Ventilation par masque sans intubation ; indication clé : acidose respiratoire de l’exacerbation de BPCO.</p>','j44-vni')
a('SaO₂',[('S','Saturation'),('a','artérielle'),('O₂','en Oxygène')],'Saturation artérielle en oxygène','<p>Mesurée sur un prélèvement artériel ; la SpO₂ en est l’estimation par oxymétrie de pouls.</p>')
a('CPT',[('C','Capacité'),('P','Pulmonaire'),('T','Totale')],'Capacité pulmonaire totale','<p>Volume d’air dans les poumons après inspiration maximale, mesuré de préférence par pléthysmographie en présence d’obstruction. Comparer aux limites de référence adaptées à l’âge, à la taille et au sexe : au-dessus de la limite supérieure de la normale, distension (un repère historique de 120 % de la valeur prédite est parfois cité ; il ne remplace pas la limite supérieure de la normale) ; sous la limite inférieure de la normale, restriction démontrée.</p>')
a('MMP-12',[('M','Matrix (matricielle)'),('M','Metallo'),('P','Protéinase'),('12','n° 12')],'Métalloprotéase matricielle 12','<p>Élastase des macrophages impliquée dans l’emphysème.</p>')
a('CXCL8',[('C','Chimiokine'),('X','à motif'),('C','C-X-C'),('L','Ligand'),('8','8')],'Chimiokine CXCL8 (interleukine 8)','<p>Principal facteur de recrutement des neutrophiles dans la BPCO.</p>','j44-inflam')
a('SERPINA1',[('SERPIN','SERine Protease INhibitor'),('A1','clade A, membre 1')],'Gène de l’alpha-1 antitrypsine','<p>Chromosome 14 ; allèles M (normal), S et Z (déficitaires).</p>','j44-aat')
a('PiZZ',[('Pi','Protease inhibitor'),('ZZ','deux allèles Z')],'Génotype ZZ de l’alpha-1 antitrypsine','<p>Déficit sévère ; emphysème précoce, hépatopathie possible.</p>','j44-aat')
a('PiMZ',[('Pi','Protease inhibitor'),('MZ','un allèle M normal et un allèle Z')],'Génotype hétérozygote MZ','<p>Porteur ; risque modérément accru chez le fumeur.</p>','j44-aat')
a('TNF-α',[('T','Tumor'),('N','Necrosis'),('F','Factor'),('α','alpha')],'Facteur de nécrose tumorale alpha','<p>Cytokine pro-inflammatoire.</p>')
for k,full,d in [('UPLIFT','Understanding Potential Long-term Impacts on Function with Tiotropium','Tiotropium sur 4 ans : moins d’exacerbations, pas d’effet sur le déclin du VEMS.'),('FLAME','nom d’essai (glycopyrronium-indacatérol versus salmétérol-fluticasone)','Double bronchodilatation supérieure sur les exacerbations.'),('IMPACT','InforMing the PAthway of COPD Treatment','Trithérapie fixe une fois par jour : moins d’exacerbations.'),('ETHOS','Efficacy and Safety of Triple Therapy in Obstructive Lung Disease','Trithérapie budésonide-glycopyrronium-formotérol : moins d’exacerbations, signal de mortalité favorable.'),('BOREAS','nom d’essai (dupilumab dans la BPCO de type 2)','Dupilumab : moins d’exacerbations chez les éosinophiliques.'),('NOTUS','nom d’essai (dupilumab, réplication de BOREAS)','Confirmation de l’effet du dupilumab.'),('MATINEE','nom d’essai (mépolizumab dans la BPCO)','Mépolizumab : moins d’exacerbations chez les éosinophiliques.'),('NOTT','Nocturnal Oxygen Therapy Trial','Oxygène continu supérieur à nocturne sur la survie.'),('LOTT','Long-Term Oxygen Treatment Trial','Pas de bénéfice de l’oxygène dans l’hypoxémie modérée.'),('HOT-HMV','Home Oxygen Therapy – Home Mechanical Ventilation','VNI à domicile ajoutée à l’oxygène chez l’hypercapnique persistant (PaCO₂ &gt; 53 mmHg) 2 à 4 semaines après une exacerbation acidosique : délai jusqu’à réadmission ou décès prolongé (médiane 4,3 contre 1,4 mois) ; pas de preuve isolée sur la mortalité.'),('REDUCE','REduction in the Use of Corticosteroids in Exacerbated COPD','5 jours de prednisone non inférieurs à 14 jours.'),('EAGLES','Evaluating Adverse Events in a Global Smoking Cessation Study','Sécurité neuropsychiatrique de la varénicline et du bupropion.')]:
    t(k,[(k,full+' (non strictement lettre à lettre)')],'Essai '+k,'<p>'+d+'</p>')
a('LTB₄',[('LT','LeucoTriène'),('B₄','B4')],'Leucotriène B4','<p>Médiateur chimiotactique des neutrophiles.</p>')
for c,tt in [('J44.0','BPCO avec infection aiguë des voies respiratoires inférieures'),('J44.1','BPCO avec exacerbation aiguë'),('J44.8','Autres BPCO précisées'),('J44.9','BPCO, sans précision')]:
    a(c,[(c,'code de la Classification internationale des maladies, 10e révision, modification allemande')],tt,'<p>Code CIM-10-GM.</p>')
a('COPD',[('C','Chronic'),('O','Obstructive'),('P','Pulmonary'),('D','Disease')],'Chronic obstructive pulmonary disease (bronchopneumopathie chronique obstructive)','<p>Terme anglais de la BPCO, employé dans les titres des références et des questionnaires.</p>')
