from cardio_1 import a, G
# J69 — Pneumopathies d’inhalation et atteintes respiratoires toxiques (P-02-Pneumologie). Clés absentes du glossaire au 09.10.2026.
a('RADS', [('R', 'Reactive (réactive)'), ('A', 'Airways (des voies aériennes)'), ('D', 'Dysfunction (dysfonction)'), ('S', 'Syndrome')], 'Syndrome de dysfonction réactive des voies aériennes', '<p>Asthme sans période de latence, apparu dans les heures qui suivent une exposition unique et massive à un irritant inhalé (chlore, ammoniac, fumées), sans sensibilisation immunologique. Le terme a été forgé par Brooks en 1985 ; il désigne aujourd’hui la forme aiguë de l’asthme induit par les irritants (Suva, 2026).</p>', 'j69-rads')
a('CTCAE', [('C', 'Common (communs)'), ('T', 'Terminology (terminologie)'), ('C', 'Criteria for (critères de)'), ('A', 'Adverse (indésirables)'), ('E', 'Events (événements)')], 'Critères communs de terminologie des événements indésirables', '<p>Échelle de gravité des effets indésirables des traitements anticancéreux, publiée par l’Institut national du cancer des États-Unis (version 5.0, 2017). Elle cote la pneumopathie médicamenteuse ou radique de 1 (anomalie radiologique sans symptôme) à 5 (décès).</p>', 'j69-ctcae')
a('ESMO', [('E', 'European (européenne)'), ('S', 'Society for (société d’)'), ('M', 'Medical (médicale)'), ('O', 'Oncology (oncologie)')], 'Société européenne d’oncologie médicale', '<p>Société savante européenne d’oncologie. Sa revue <i>ESMO Open</i> a publié en 2022 l’avis d’experts de Conte et collaborateurs sur les pneumopathies interstitielles médicamenteuses des traitements anticancéreux.</p>')
a('ECHM', [('E', 'European (européen)'), ('C', 'Committee for (comité de)'), ('H', 'Hyperbaric (hyperbare)'), ('M', 'Medicine (médecine)')], 'Comité européen de médecine hyperbare', '<p>Comité qui fixe, par conférences de consensus, les indications européennes de l’oxygénothérapie hyperbare. La dixième conférence (avril 2016, publiée en 2017) recommande l’oxygène hyperbare dans l’intoxication au monoxyde de carbone avec trouble de conscience ou signe neurologique, cardiaque, respiratoire ou psychologique, et chez toute femme enceinte intoxiquée.</p>', 'j69-ohb')
a('Arroyo-Hernández', [('Arroyo-Hernández', 'nom propre : Marisol Arroyo-Hernández, oncologue, première autrice, non une abréviation')], 'Arroyo-Hernández et collaborateurs, BMC Pulm Med 2021', '<p>Revue « Radiation-induced lung injury: current evidence » (BMC Pulmonary Medicine 2021 ; 21 : 9) : facteurs de risque, phases physiopathologiques, imagerie, cotation et traitement de la lésion pulmonaire radique.</p>', 'j69-pneumopathie-radique')
a('Perez-Lauterbach', [('Perez-Lauterbach', 'nom propre : D. Perez-Lauterbach, urgentiste, premier auteur, non une abréviation')], 'Perez-Lauterbach et collaborateurs, J Emerg Med 2019', '<p>Série de trois patients exposés au dioxyde d’azote après la détonation d’un explosif : lésion pulmonaire dépendante de la dose, retardée de plusieurs heures, jusqu’au SDRA chez le plus exposé.</p>', 'j69-no2')
a('Co-Amoxicilline', [('Co-Amoxicilline', 'nom de spécialité suisse de l’association amoxicilline-acide clavulanique, non une abréviation')], 'Co-Amoxicilline (amoxicilline et acide clavulanique)', '<p>Nom de spécialités suisses associant l’amoxicilline et l’acide clavulanique, inhibiteur de bêtalactamases.</p>', 'j69-d-coamox')
a('STOP', [('S', 'Substitution'), ('T', 'mesures Techniques'), ('O', 'mesures Organisationnelles'), ('P', 'Protection individuelle')], 'Principe STOP de prévention au travail', '<p>Hiérarchie des mesures de prévention de la Suva : substituer le produit dangereux, puis agir par des mesures techniques, organisationnelles, et enfin par la protection individuelle, la moins efficace.</p>', 'j69-stop')
