from cardio_1 import a, G
# Glossaire J86 — Pleurésies purulentes et abcès du poumon (P-02-Pneumologie). Rédaction du 08.10.2026.
# La clé BTS est définie dans glossary/j90.py (injecté avant J86) ; elle n'est pas redéfinie ici.
a('ESTS', [('E', 'European'), ('S', 'Society of'), ('T', 'Thoracic'), ('S', 'Surgeons')], 'Société européenne des chirurgiens thoraciques', '<p>Société savante européenne de chirurgie thoracique. Elle a publié en 2023, avec l’ERS, une déclaration sur la prise en charge de l’infection pleurale de l’adulte.</p>')
a('MIST1', [('M', 'Multicenter'), ('I', 'Intrapleural'), ('S', 'Sepsis'), ('T', 'Trial'), ('1', 'premier essai')], 'Premier essai multicentrique sur le sepsis intrapleural', '<p>Essai randomisé britannique publié en 2005 : la streptokinase intrapleurale n’a réduit ni la mortalité ni le recours chirurgical chez 454 patients atteints d’infection pleurale.</p>', 'j86-mist1')
a('MIST2', [('M', 'Multicenter'), ('I', 'Intrapleural'), ('S', 'Sepsis'), ('T', 'Trial'), ('2', 'deuxième essai')], 'Deuxième essai multicentrique sur le sepsis intrapleural', '<p>Essai randomisé factoriel publié en 2011 : l’association alteplase et dornase alfa intrapleurales a amélioré le drainage et réduit le recours chirurgical, contrairement à chaque molécule seule.</p>', 'j86-mist2')
a('RAPID', [('R', 'Renal (urée)'), ('A', 'Age'), ('P', 'Purulence du liquide'), ('I', 'Infection source (origine)'), ('D', 'Dietary factors (albumine)')], 'Score pronostique de l’infection pleurale', '<p>Score de 0 à 7 points calculé à l’admission à partir de l’urée, de l’âge, de la purulence du liquide, de l’origine communautaire ou nosocomiale et de l’albumine. Il stratifie la mortalité à trois mois.</p>', 'j86-rapid')
a('PILOT', [('PILOT', 'nom de l’étude, non développé lettre à lettre par ses auteurs')], 'Étude prospective de validation du score RAPID', '<p>Cohorte prospective internationale de 546 adultes atteints d’infection pleurale (542 analysés), publiée en 2020 dans l’European Respiratory Journal. La mortalité atteignait 10 % à trois mois ; le score RAPID la prédisait avec une statistique C de 0,78.</p>')
a('SLIM', [('S', 'Short versus'), ('L', 'Long antibiotic course for pleural'), ('I', 'Infection'), ('M', 'Management')], 'Essai comparant une antibiothérapie courte ou longue de l’infection pleurale', '<p>Essai pilote randomisé publié en 2023 (50 patients) : 14 à 21 jours contre 28 à 42 jours d’antibiotiques chez des patients médicalement stables, sans différence significative d’échec.</p>', 'j86-duree')
