from cardio_1 import a, G
# R05 — Toux aiguë, subaiguë et chronique (P-02-Pneumologie). Clés absentes de glossary/*.py et des dossiers de travail au 09.10.2026.
a('P2X3', [('P2', 'récepteur Purinergique de type 2'), ('X', 'famille X (canaux ioniques activés par l’ATP)'), ('3', 'sous-unité 3')], 'Récepteur purinergique P2X3', '<p>Canal ionique activé par l’ATP extracellulaire, exprimé sur les fibres sensitives vagales des voies aériennes et sur les neurones gustatifs. Le géfapixant, son antagoniste, réduit la toux chronique réfractaire et altère le goût.</p>', 'r05-d-gefapixant')
a('TRPV1', [('TRP', 'Transient Receptor Potential (potentiel de récepteur transitoire)'), ('V', 'Vanilloïde'), ('1', 'membre 1')], 'Canal à potentiel de récepteur transitoire de type vanilloïde 1', '<p>Canal ionique des terminaisons sensitives qui détecte des irritants chimiques ; son expression augmente dans les neurones vagaux au cours de l’inflammation chez l’animal.</p>', 'r05-trp')
a('TRPA1', [('TRP', 'Transient Receptor Potential (potentiel de récepteur transitoire)'), ('A', 'Ankyrine'), ('1', 'membre 1')], 'Canal à potentiel de récepteur transitoire de type ankyrine 1', '<p>Canal ionique des terminaisons sensitives qui détecte des irritants chimiques inhalés ; ses antagonistes n’ont pas réduit la toux en clinique.</p>', 'r05-trp')
a('LCQ', [('L', 'Leicester'), ('C', 'Cough (toux)'), ('Q', 'Questionnaire')], 'Questionnaire de toux de Leicester', '<p>Questionnaire validé de qualité de vie spécifique de la toux, utilisé en consultation et comme critère de jugement des essais thérapeutiques.</p>', 'r05-lcq')
a('COUGH-1', [('COUGH-1', 'nom propre du premier essai de phase 3 du géfapixant (toux en anglais), non développable lettre à lettre')], 'Essai COUGH-1 (géfapixant, 2022)', '<p>Essai randomisé de 730 patients atteints de toux chronique réfractaire ou inexpliquée : à 12 semaines, le géfapixant 45 mg deux fois par jour a réduit la fréquence de la toux de 18,5 % de plus que le placebo (McGarvey, 2022).</p>', 'r05-d-gefapixant')
a('COUGH-2', [('COUGH-2', 'nom propre du second essai de phase 3 du géfapixant (toux en anglais), non développable lettre à lettre')], 'Essai COUGH-2 (géfapixant, 2022)', '<p>Essai randomisé de 1314 patients : à 24 semaines, le géfapixant 45 mg deux fois par jour a réduit la fréquence de la toux de 14,6 % de plus que le placebo (McGarvey, 2022).</p>', 'r05-d-gefapixant')
a('McGarvey', [('McGarvey', 'nom propre du premier auteur, non une abréviation')], 'McGarvey (premier auteur)', '<p>Lorcan McGarvey, premier auteur de la publication des essais de phase 3 du géfapixant (Lancet, 2022).</p>', 'r05-d-gefapixant')
a('MST', [('MST', 'nom commercial de spécialité (MST® Continus®), non développable lettre à lettre')], 'MST® Continus® (sulfate de morphine retard)', '<p>Nom commercial suisse de comprimés de sulfate de morphine à libération prolongée, dosés de 10 à 200 mg ; autorisés pour les douleurs.</p>', 'r05-d-morphine')
a('Sevre-Long', [('Sevre-Long', 'nom commercial de spécialité, non développable lettre à lettre')], 'Sevre-Long® (sulfate de morphine retard)', '<p>Nom commercial suisse de capsules de sulfate de morphine à libération prolongée en une prise quotidienne, dosées de 30 à 200 mg ; autorisées pour les douleurs prolongées et le traitement de substitution aux opioïdes.</p>', 'r05-d-morphine')
