from cardio_1 import a, G
a('BTS',[('B','British'),('T','Thoracic'),('S','Society')],'British Thoracic Society (Société thoracique britannique)','<p>Société savante britannique de pneumologie. Ses textes servent de référence dans plusieurs cours du fragment : maladies pleurales (Thorax, août 2023), bronchiectasies de l’adulte (2019), macrolides au long cours (2020), oxygénothérapie d’urgence de l’adulte (2017) et toux chronique de l’adulte (prise de position, Thorax 2023).</p>','j90-bts')
a('ESTS',[('E','European'),('S','Society of'),('T','Thoracic'),('S','Surgeons')],'European Society of Thoracic Surgeons (Société européenne des chirurgiens thoraciques)','<p>Société savante européenne de chirurgie thoracique. Avec l’ERS, elle a publié la déclaration de 2023 sur l’infection pleurale de l’adulte et la recommandation de 2025 sur l’aptitude au traitement à visée curative du cancer bronchique.</p>')
a('TIPS',[('T','Transjugular'),('I','Intrahepatic'),('P','Portosystemic'),('S','Shunt')],'Shunt portosystémique intrahépatique transjugulaire','<p>Prothèse posée par voie jugulaire entre une veine sus-hépatique et une branche de la veine porte ; elle abaisse la pression portale et réduit l’ascite et l’hydrothorax hépatique réfractaires.</p>','j90-hydrothorax')
a('LENT',[('L','Lactate déshydrogénase pleurale'),('E','ECOG, indice de performance de l’Eastern Cooperative Oncology Group'),('N','Neutrophiles sur lymphocytes, rapport sanguin'),('T','Type tumoral')],'Score pronostique LENT de l’épanchement pleural malin','<p>Score de 0 à 7 (Clive, Thorax 2014) ; survie médiane de 319, 130 et 44 jours pour les risques faible, modéré et élevé.</p>','j90-lent')
a('RAPID',[('R','Renal (urée)'),('A','Age (âge)'),('P','Purulence'),('I','Infection source (origine communautaire ou nosocomiale)'),('D','Dietary factors (albumine)')],'Score pronostique RAPID de l’infection pleurale','<p>Score de 0 à 7 calculé à l’admission (Rahman, Chest, 2014). Risque faible de 0 à 2, intermédiaire de 3 à 4, élevé de 5 à 7 ; mortalité à trois mois de 2,3 %, 9,2 % et 29,3 % dans la cohorte prospective de validation (Corcoran, 2020).</p>','j90-rapid')
a('MIST',[('M','Multicenter'),('I','Intrapleural'),('S','Sepsis'),('T','Trial')],'Essais MIST sur l’infection pleurale','<p>Série d’essais britanniques multicentriques sur le traitement intrapleural de l’infection pleurale.</p>','j90-d-iet')
a('TIME1',[('T','Therapeutic'),('I','Interventions in'),('M','Malignant'),('E','Effusion'),('1','premier essai')],'Essai TIME1 (2015)','<p>Anti-inflammatoires non stéroïdiens contre opioïdes et drains de 12 ou 24 French lors du talcage : anti-inflammatoires non inférieurs pour la symphyse.</p>','j90-d-ains')
a('TIME2',[('T','Therapeutic'),('I','Intervention in'),('M','Malignant'),('E','Effusion'),('2','deuxième essai')],'Essai TIME2 (2012)','<p>Cathéter pleural tunnelisé contre drain et talc dans l’épanchement malin : dyspnée équivalente à 42 jours, hospitalisation plus courte sous cathéter.</p>','j90-cath')
a('IPC-PLUS',[('IPC','Indwelling Pleural Catheter (cathéter pleural à demeure)'),('PLUS','nom d’essai, non développable lettre à lettre')],'Essai IPC-PLUS (2018)','<p>Talc ou placebo administré par cathéter pleural tunnelisé : symphyse à 35 jours chez 43 % contre 23 % des patients.</p>','j90-talc')
for c,t in [('J92.0','Plaque pleurale avec mise en évidence d’amiante'),('J92.9','Plaque pleurale sans mise en évidence d’amiante'),('J94.0','Épanchement chyleux'),('J94.1','Fibrothorax'),('J94.2','Hémothorax, hémopneumothorax (non traumatique)'),('J94.8','Autres affections pleurales précisées'),('J94.9','Affection pleurale, sans précision'),('R09.1','Pleurésie'),('S27.1','Hémothorax traumatique'),('S27.2','Hémopneumothorax traumatique'),('C78.2','Tumeur maligne secondaire de la plèvre'),('C45.0','Mésothéliome de la plèvre')]:
    a(c,[(c,'code de la Classification internationale des maladies, 10e révision, modification allemande')],t,'<p>Code CIM-10-GM 2024.</p>')
