from cardio_1 import a, G
from cardio_2 import t
# J95 — Affections respiratoires après actes médicaux et autres maladies de l’appareil respiratoire (P-02-Pneumologie)
a('CIM',[('C','Classification'),('I','Internationale des'),('M','Maladies')],'Classification internationale des maladies','<p>Classification de l’Organisation mondiale de la santé ; la Suisse code les diagnostics hospitaliers avec la version allemande modifiée CIM-10-GM.</p>')
a('ICD-10-GM',[('ICD','International Classification of Diseases'),('10','10e révision'),('GM','German Modification (modification allemande)')],'Classification internationale des maladies, 10e révision, modification allemande','<p>Version publiée par le BfArM et utilisée en Suisse pour le codage hospitalier ; équivalent français : CIM-10-GM.</p>')
a('ICD-10-CM',[('ICD','International Classification of Diseases'),('10','10e révision'),('CM','Clinical Modification (modification clinique)')],'Classification internationale des maladies, 10e révision, modification clinique américaine','<p>Version des États-Unis ; certains de ses codes, comme celui de la pneumonie sous ventilation mécanique, n’existent pas en version allemande.</p>')
a('ARISCAT',[('A','Assess'),('R','Respiratory'),('I','rIsk in'),('S','Surgical patients in'),('CAT','CATalonia')],'Évaluation du risque respiratoire des patients chirurgicaux en Catalogne','<p>Score préopératoire de sept facteurs qui estime le risque de complications pulmonaires postopératoires (Canet et collaborateurs, 2010).</p>','j95-ariscat')
a('ACP',[('A','American'),('C','College of'),('P','Physicians')],'American College of Physicians (Collège américain des médecins internistes)','<p>Société savante américaine de médecine interne ; sa recommandation de 2006 porte sur la réduction des complications pulmonaires périopératoires.</p>','j95-acp')
a('ESAIC',[('E','European'),('S','Society of'),('A','Anaesthesiology and'),('IC','Intensive Care')],'Société européenne d’anesthésiologie et de soins intensifs','<p>Société savante européenne ; auteure de la recommandation de 2023 sur la gestion périopératoire du bloc neuromusculaire.</p>')
a('H2',[('H','Histamine'),('2','récepteur de type 2')],'Récepteur histaminique de type 2','<p>Récepteur de la cellule pariétale gastrique ; ses antagonistes réduisent la sécrétion acide.</p>','j95-d-antiacide')
a('VEGF-D',[('V','Vascular'),('E','Endothelial'),('G','Growth'),('F','Factor'),('D','type D')],'Facteur de croissance de l’endothélium vasculaire de type D','<p>Facteur lymphangiogénique ; un taux sérique d’au moins 800 pg/mL soutient le diagnostic de lymphangioléiomyomatose dans un contexte compatible.</p>','j95-kystes')
a('ROC',[('R','Receiver'),('O','Operating'),('C','Characteristic')],'Courbe caractéristique de fonctionnement du récepteur','<p>Courbe de sensibilité en fonction de 1 − spécificité ; l’aire sous la courbe mesure la capacité d’un score à discriminer.</p>')
a('LAS VEGAS',[('LAS','Local ASsessment of'),('VE','VEntilatory management during'),('G','General'),('A','Anaesthesia for'),('S','Surgery')],'Étude internationale LAS VEGAS','<p>Étude observationnelle menée en 2013 dans 146 hôpitaux de 29 pays ; 10,9 % des 6063 patients analysés ont présenté au moins une complication pulmonaire postopératoire.</p>')
a('StEP-COMPAC',[('StEP','Standardised Endpoints in Perioperative medicine'),('COMPAC','COre Outcome Measures for Perioperative and Anaesthetic Care')],'Initiative de standardisation des critères de jugement périopératoires','<p>Groupe international qui a proposé en 2018 des définitions de critères de jugement, dont les complications pulmonaires postopératoires.</p>','j95-cpp')
a('Fuchs-Buder',[('Fuchs-Buder','nom propre : Thomas Fuchs-Buder, anesthésiste')],'Fuchs-Buder T.','<p>Premier auteur de la recommandation européenne de 2023 sur la gestion du bloc neuromusculaire.</p>')
a('McGrath',[('McGrath','nom propre : Brendan McGrath, anesthésiste britannique')],'McGrath B.','<p>Premier auteur des algorithmes d’urgence de la trachéotomie du National Tracheostomy Safety Project (2012).</p>','j95-trach')
a('Robinul-Neostigmine',[('Robinul-Neostigmine','nom de marque')],'Robinul-Neostigmine','<p>Spécialité suisse associant néostigmine 2,5 mg et glycopyrronium 0,5 mg par millilitre.</p>','j95-d-neostig')
a('Vareniclin-DALITA',[('Vareniclin-DALITA','nom de marque')],'Vareniclin-DALITA','<p>Spécialité suisse de varénicline en comprimés de 0,5 mg et de 1 mg.</p>','j95-d-varen')
t('PROVHILO',[('PROVHILO','PROtective Ventilation using HIgh versus LOw positive end-expiratory pressure')],'Essai PROVHILO (2014)','<p>Chez 900 patients opérés par laparotomie, une PEP de 12 cm H₂O avec recrutements n’a pas réduit les complications pulmonaires par rapport à une PEP d’au plus 2 cm H₂O, et a provoqué plus d’hypotensions.</p>','j95-ventprot')
t('PRISM',[('PRISM','Prevention of Respiratory Insufficiency after Surgical Management')],'Essai PRISM (2021)','<p>Chez 4806 patients opérés d’une chirurgie abdominale majeure ouverte, la pression positive continue préventive n’a pas réduit les pneumonies, réintubations ou décès.</p>','j95-cpap')
t('BiPOP',[('BiPOP','nom de l’essai, formé sur BiPAP (ventilation à deux niveaux de pression) et Optiflow ; développement littéral officiel non retrouvé')],'Essai BiPOP (2015)','<p>Après chirurgie cardiothoracique, l’oxygénothérapie nasale à haut débit a été non inférieure à la ventilation non invasive.</p>','j95-cpap')
t('REACH3',[('REACH','nom du programme d’essais du ruxolitinib dans la maladie du greffon contre l’hôte, sans développement littéral publié'),('3','troisième essai du programme')],'Essai REACH3 (2021)','<p>Dans la maladie du greffon contre l’hôte chronique réfractaire, le ruxolitinib a donné plus de réponses que la meilleure thérapie disponible.</p>','j95-cont-rux')
t('ALLOZITHRO',[('ALLO','ALLOgreffe'),('ZITHRO','aZITHROmycine')],'Essai ALLOZITHRO (2017)','<p>L’azithromycine prophylactique après allogreffe n’a pas amélioré la survie sans déclin respiratoire et a augmenté les rechutes hématologiques.</p>')
for c,tt in [('J95.0','Fonctionnement défectueux d’un trachéostome'),('J95.1','Insuffisance pulmonaire aiguë après chirurgie thoracique'),('J95.2','Insuffisance pulmonaire aiguë après chirurgie non thoracique'),('J95.3','Insuffisance pulmonaire chronique après chirurgie'),('J95.4','Syndrome de Mendelson'),('J95.5','Sténose sous-glottique après des actes médicaux'),('J95.81','Sténose trachéale après des actes médicaux'),('J95.82','Insuffisance d’anastomose ou de suture après chirurgie de la trachée, des bronches ou du poumon'),('J95.88','Autres troubles respiratoires après des actes médicaux'),('J95.9','Trouble respiratoire après un acte médical, sans précision'),
 ('J98.0','Affections des bronches, non classées ailleurs'),('J98.10','Dystélectasie'),('J98.11','Atélectasie partielle'),('J98.12','Atélectasie totale'),('J98.18','Collapsus pulmonaire, autre et sans précision'),('J98.3','Emphysème compensateur'),('J98.4','Autres affections du poumon'),('J98.5','Maladies du médiastin, non classées ailleurs'),('J98.58','Autres maladies du médiastin, non classées ailleurs'),('J98.6','Maladies du diaphragme'),('J98.8','Autres troubles respiratoires précisés'),('J98.9','Trouble respiratoire, sans précision'),
 ('J99.0','Maladie pulmonaire au cours de la polyarthrite rhumatoïde séropositive (astérisque)'),('J99.1','Troubles respiratoires au cours d’autres connectivites (astérisque)'),('J99.21','Stade 1 de la maladie du greffon contre l’hôte pulmonaire chronique (astérisque)'),('J99.22','Stade 2 de la maladie du greffon contre l’hôte pulmonaire chronique (astérisque)'),('J99.23','Stade 3 de la maladie du greffon contre l’hôte pulmonaire chronique (astérisque)'),('J99.8','Troubles respiratoires au cours d’autres maladies classées ailleurs (astérisque)'),
 ('J39.80','Sténose trachéale acquise'),('J70.0','Affections pulmonaires aiguës dues à une irradiation'),('M05.1','Polyarthrite rhumatoïde séropositive avec atteinte pulmonaire (dague)'),('O29.0','Complications pulmonaires de l’anesthésie au cours de la grossesse'),('O74.0','Pneumopathie d’inhalation due à l’anesthésie au cours du travail et de l’accouchement'),('O89.0','Complications pulmonaires de l’anesthésie au cours de la puerpéralité'),('Q79.0','Hernie diaphragmatique congénitale'),('Q79.1','Autres malformations congénitales du diaphragme'),('T81.8','Autres complications d’un acte à visée diagnostique ou thérapeutique'),('T86.06','Maladie du greffon contre l’hôte chronique, forme modérée (dague)'),('T86.07','Maladie du greffon contre l’hôte chronique, forme sévère (dague)'),('U69.01','Code supplémentaire de relation temporelle entre une pneumonie et l’admission (point d’exclamation)'),('U69.04','Code supplémentaire de relation temporelle entre une pneumonie et l’admission (point d’exclamation)')]:
    a(c,[(c,'code de la Classification internationale des maladies, 10e révision, modification allemande')],tt,'<p>Code CIM-10-GM 2024.</p>')
