from cardio_1 import a, G
# D50 — Anémie par carence en fer (H-08-Hématologie). Clés absentes de glossary/*.py et des glossaires des dossiers de travail au 09.10.2026.
a('VGM', [('V', 'Volume'), ('G', 'Globulaire'), ('M', 'Moyen')], 'Volume globulaire moyen', '<p>Volume moyen des hématies, exprimé en femtolitres. Chez l’adulte, une valeur inférieure à 80 fl définit la microcytose ; il baisse tardivement dans la carence martiale et peut rester normal si une carence en vitamine B12 ou en folates s’y associe.</p>', 'd50-stades')
a('TCMH', [('T', 'Teneur'), ('C', 'Corpusculaire'), ('M', 'Moyenne'), ('H', 'en Hémoglobine')], 'Teneur corpusculaire moyenne en hémoglobine', '<p>Quantité moyenne d’hémoglobine par hématie, exprimée en picogrammes. Une valeur inférieure à 28 pg définit l’hypochromie ; elle est plus fiable que le VGM pour repérer une carence martiale, car elle dépend moins du délai d’analyse et de l’automate (BSG 2021).</p>', 'd50-stades')
a('TSAT', [('T', 'Transferrine'), ('SAT', 'SATuration')], 'Saturation de la transferrine', '<p>Rapport du fer sérique à la capacité totale de fixation de la transferrine, exprimé en pour cent. Une valeur inférieure à 20 % signe un fer insuffisant pour l’érythropoïèse, que les réserves soient vides ou séquestrées par l’inflammation. Abréviation d’usage international (transferrin saturation).</p>', 'd50-tsat')
a('MICI', [('M', 'Maladies'), ('I', 'Inflammatoires'), ('C', 'Chroniques de l’'), ('I', 'Intestin')], 'Maladies inflammatoires chroniques de l’intestin', '<p>Maladie de Crohn et rectocolite hémorragique. L’anémie, mêlant pertes sanguines, malabsorption et inflammation, en est la complication systémique la plus fréquente.</p>', 'd50-mici')
a('BSG', [('B', 'British (britannique)'), ('S', 'Society (société)'), ('G', 'of Gastroenterology (de gastroentérologie)')], 'Société britannique de gastroentérologie', '<p>Société savante du Royaume-Uni, autrice des recommandations de 2021 sur la prise en charge de l’anémie par carence en fer de l’adulte (Snook et al., Gut 2021).</p>', None)
a('ESGE', [('E', 'European (européenne)'), ('S', 'Society of (société d’)'), ('G', 'Gastrointestinal (digestive)'), ('E', 'Endoscopy (endoscopie)')], 'Société européenne d’endoscopie digestive', '<p>Société savante européenne qui publie les recommandations d’endoscopie digestive, dont celle de 2022 sur la capsule endoscopique et l’entéroscopie de l’intestin grêle.</p>')
a('DMT1', [('D', 'Divalent (divalent)'), ('M', 'Metal (des métaux)'), ('T', 'Transporter (transporteur)'), ('1', 'type 1')], 'Transporteur des métaux divalents de type 1', '<p>Protéine de la membrane apicale de l’entérocyte qui fait entrer le fer alimentaire ; son expression augmente en cas d’hypoxie et de carence.</p>', 'd50-hepcidine')
a('FGF23', [('F', 'Fibroblast (des fibroblastes)'), ('G', 'Growth (de croissance)'), ('F', 'Factor (facteur)'), ('23', 'numéro 23')], 'Facteur de croissance des fibroblastes 23', '<p>Hormone phosphaturique produite par l’os. Certaines préparations de fer intraveineux, surtout le carboxymaltose, élèvent sa forme intacte : le rein perd du phosphate et l’activation de la vitamine D diminue.</p>', 'd50-hypophos')
a('TMPRSS6', [('TM', 'TransMembrane (transmembranaire)'), ('PRSS', 'PRotease, Serine (protéase à sérine)'), ('6', 'membre 6')], 'Gène de la protéase transmembranaire à sérine 6 (matriptase-2)', '<p>Gène codant la matriptase-2, qui freine la synthèse hépatique d’hepcidine par la voie BMP–SMAD. Ses variants pathogènes causent l’anémie ferriprive réfractaire au fer.</p>', 'd50-irida')
