from cardio_1 import a, G
from cardio_2 import t
# K92 — Hémorragie digestive et autres maladies de l’appareil digestif (G-04-Gastroentérologie et hépatologie) : clés propres au cours, absentes des glossaires canoniques et des glossaires G-04 de travail au 08.10.2026.
# Clés déjà définies et réutilisées sans redéfinition : ESGE, ACG, IIc (k25/k57/k80), AOD, INR, Hb, AINS, PAS, P2Y12, CYP2C19, CYP3A4, QT, ECG, UI, pH, H⁺, K⁺, ATP, Child-Pugh, FA.

a('BSG',[('B','British'),('S','Society of'),('G','Gastroenterology')],'British Society of Gastroenterology (Société britannique de gastroentérologie)','<p>Société savante britannique ; sa recommandation de 2019 sur l’hémorragie digestive basse a introduit le score d’Oakland et le seuil d’indice de choc supérieur à 1 pour l’angioscanner.</p>','k92-shock')
a('ATLS',[('A','Advanced'),('T','Trauma'),('L','Life'),('S','Support')],'Advanced Trauma Life Support (programme de réanimation avancée du traumatisé)','<p>Programme de formation de l’American College of Surgeons ; sa 10e édition (2018) classe la perte sanguine en quatre classes selon les constantes.</p>')
a('AIMS65',[('A','Albumine inférieure à 30 g/L'),('I','INR supérieur à 1,5'),('M','état Mental altéré'),('S','pression Systolique de 90 mmHg ou moins'),('65','âge de 65 ans ou plus')],'Score AIMS65 de mortalité de l’hémorragie digestive haute','<p>Score de 0 à 5 points qui prédit la mortalité hospitalière ; moins sensible que le score de Glasgow-Blatchford pour décider d’une sortie.</p>','k92-rockall')
t('HALT-IT',[('HALT-IT','nom d’essai : « Haemorrhage ALleviation with Tranexamic acid – InTestinal system », non strictement lettre à lettre')],'Essai HALT-IT (Lancet 2020)','<p>Essai randomisé de 12 009 patients avec hémorragie digestive importante : l’acide tranexamique (1 g puis 3 g sur 24 heures) n’a pas réduit la mortalité par hémorragie et a doublé les thromboses veineuses.</p>','k92-txa')
a('Glasgow-Blatchford',[('Glasgow-Blatchford','nom propre : ville de Glasgow et Oliver Blatchford, auteur principal du score (Lancet 2000)')],'Score de Glasgow-Blatchford','<p>Score de 0 à 23 points qui prédit, avant l’endoscopie, le besoin d’une intervention hospitalière dans l’hémorragie digestive haute ; un score de 0 ou 1 autorise une prise en charge ambulatoire selon l’ESGE 2021.</p>','k92-gbs')
a('Mallory-Weiss',[('Mallory-Weiss','nom propre : George Kenneth Mallory et Soma Weiss, qui l’ont décrit en 1929')],'Syndrome de Mallory-Weiss','<p>Déchirure muqueuse de la jonction œso-gastrique provoquée par des efforts de vomissement ; elle saigne et cesse le plus souvent spontanément.</p>','k92-mw')
a('Rendu-Osler',[('Rendu-Osler','nom propre : Henri Rendu et William Osler')],'Maladie de Rendu-Osler (télangiectasie hémorragique héréditaire)','<p>Maladie génétique autosomique dominante qui forme des télangiectasies cutanées, muqueuses et digestives, responsables d’épistaxis et de saignements digestifs récidivants.</p>')
a('K92.0',[('K92.0','code CIM-10-GM : K92 = autres maladies du système digestif ; .0 = hématémèse')],'Code K92.0 : hématémèse','<p>Vomissement de sang de cause non précisée ; remplacé par le code de la lésion dès qu’elle est identifiée.</p>','k92-codage')
a('K92.1',[('K92.1','code CIM-10-GM : K92 = autres maladies du système digestif ; .1 = méléna')],'Code K92.1 : méléna','<p>Selles noires de sang digéré, de cause non précisée ; le sang occulte dans les selles est exclu (R19.5).</p>','k92-codage')
a('K92.2',[('K92.2','code CIM-10-GM : K92 = autres maladies du système digestif ; .2 = hémorragie gastro-intestinale, sans précision')],'Code K92.2 : hémorragie gastro-intestinale, sans précision','<p>Hémorragie gastrique ou intestinale sans autre précision ; plusieurs causes précises en sont exclues et ont leur propre code.</p>','k92-codage')
a('K92.8',[('K92.8','code CIM-10-GM : K92 = autres maladies du système digestif ; .8 = autres maladies précisées du système digestif')],'Code K92.8 : autres maladies précisées du système digestif','<p>Code résiduel pour une maladie digestive précisée sans code propre ailleurs.</p>','k92-codage')
a('K92.9',[('K92.9','code CIM-10-GM : K92 = autres maladies du système digestif ; .9 = sans précision')],'Code K92.9 : maladie du système digestif, sans précision','<p>Code résiduel d’un diagnostic digestif non précisé ; son emploi doit rester exceptionnel.</p>','k92-codage')
a('K62.5',[('K62.5','code CIM-10-GM : K62 = autres maladies de l’anus et du rectum ; .5 = hémorragie de l’anus et du rectum')],'Code K62.5 : hémorragie de l’anus et du rectum','<p>Exclu de K92.2 ; traité dans le cours K63 — Polypes colorectaux et autres maladies de l’intestin.</p>','k92-codage')
a('K22.81',[('K22.81','code CIM-10-GM : K22 = autres maladies de l’œsophage ; .81 = hémorragie de l’œsophage')],'Code K22.81 : hémorragie de l’œsophage','<p>Exclu de K92.2 ; traité dans le cours K22 — Troubles moteurs et autres maladies de l’œsophage.</p>','k92-codage')
a('K29.0',[('K29.0','code CIM-10-GM : K29 = gastrite et duodénite ; .0 = gastrite hémorragique aiguë')],'Code K29.0 : gastrite hémorragique aiguë','<p>Exclue de K92.2 ; traitée dans le cours K29 — Gastrites, duodénites et autres maladies de l’estomac.</p>','k92-codage')
a('K31.82',[('K31.82','code CIM-10-GM : K31 = autres maladies de l’estomac et du duodénum ; .82 = angiodysplasie de l’estomac et du duodénum avec saignement')],'Code K31.82 : angiodysplasie de l’estomac et du duodénum avec saignement','<p>Exclue de K92.2 ; traitée dans le cours K29, qui couvre K29 et K31.</p>','k92-codage')
a('K55.22',[('K55.22','code CIM-10-GM : K55 = troubles vasculaires de l’intestin ; .22 = angiodysplasie du côlon avec hémorragie')],'Code K55.22 : angiodysplasie du côlon avec hémorragie','<p>Exclue de K92.2 ; traitée dans le cours K55 — Ischémie intestinale.</p>','k92-codage')
a('K55.32',[('K55.32','code CIM-10-GM : K55 = troubles vasculaires de l’intestin ; .32 = angiodysplasie de l’intestin grêle avec hémorragie')],'Code K55.32 : angiodysplasie de l’intestin grêle avec hémorragie','<p>Exclue de K92.2 ; traitée dans le cours K55 — Ischémie intestinale.</p>','k92-codage')
a('R19.5',[('R19.5','code CIM-10-GM : R19 = autres symptômes concernant l’appareil digestif et l’abdomen ; .5 = autres anomalies des matières fécales, dont le sang occulte')],'Code R19.5 : autres anomalies des matières fécales (sang occulte)','<p>Exclu de K92.1 ; traité dans le cours R19 — Autres symptômes digestifs.</p>','k92-codage')
