"""Termes propres à B50 — Paludisme à Plasmodium falciparum.

Sources consultées le 8 octobre 2026. Certaines entrées communes sont
neutralisées lorsqu'elles renvoient à une fenêtre d'une autre spécialité.
"""
from cardio_1 import a, G

BFARM = '<p>Source : <a href="https://klassifikationen.bfarm.de/icd-10-gm/kode-suche/htmlgm2024/block-b50-b64.htm" target="_blank" rel="noopener">BfArM, CIM-10-GM 2024, B50</a>.</p>'
SWISS = '<p>Source : <a href="https://www.swisstph.ch/fileadmin/user_upload/SwissTPH/Documents/Travel_Clinic/SwissTPH_Malaria_Tx_recommendations_1._September_2026.pdf" target="_blank" rel="noopener">SSTTM et Swiss TPH, Malaria Treatment Recommendations, 1er septembre 2026</a>.</p>'
RIAMET = '<p>Source : <a href="https://www.swissmedicinfo.ch/ShowText.aspx?textType=FI&amp;lang=FR&amp;authNr=54594" target="_blank" rel="noopener">Information professionnelle suisse Riamet n° 54594, mise à jour décembre 2019</a>.</p>'
OMS = '<p>Source : <a href="https://iris.who.int/server/api/core/bitstreams/d3c6488b-3ee6-41cb-960f-ddf0202cd74d/content" target="_blank" rel="noopener">OMS, WHO guidelines for malaria, 10 septembre 2026, § 5.1 et 5.2.2</a>.</p>'

a('B50', [('B', 'maladies infectieuses et parasitaires'), ('50', 'paludisme à Plasmodium falciparum')], 'B50 — Paludisme à Plasmodium falciparum', '<p>La CIM-10-GM 2024 regroupe ici le paludisme dû à P. falciparum, y compris les infections mixtes comportant cette espèce. Les sous-codes distinguent les complications cérébrales, les autres formes graves et la forme sans précision. La gravité se détermine cliniquement, pas par le seul code.</p>'+BFARM+SWISS)
a('B50.0', [('B50', 'paludisme à Plasmodium falciparum'), ('.0', 'complications cérébrales')], 'Paludisme à Plasmodium falciparum avec complications cérébrales', '<p>Une altération de conscience ou des convulsions lors d’un paludisme confirmé impose le parcours du paludisme grave. Le sous-code décrit la complication cérébrale documentée ; le diagnostic différentiel d’une altération de conscience reste nécessaire.</p>'+BFARM+SWISS)
a('B50.8', [('B50', 'paludisme à Plasmodium falciparum'), ('.8', 'autres formes graves ou complications')], 'Autres formes graves ou complications du paludisme à Plasmodium falciparum', '<p>La défaillance grave doit être décrite dans le dossier. L’insuffisance rénale, l’acidose, le choc ou une autre complication non cérébrale demandent une prise en charge hospitalière selon la recommandation suisse.</p>'+BFARM+SWISS)
a('B50.9', [('B50', 'paludisme à Plasmodium falciparum'), ('.9', 'sans précision')], 'Paludisme à Plasmodium falciparum, sans précision', '<p>Ce code ne prouve pas à lui seul qu’une forme grave a été exclue. La parasitémie, l’état de conscience et la fonction des organes sont évalués séparément pour choisir la voie thérapeutique.</p>'+BFARM+SWISS)
a('SSTTM', [('S', 'Swiss'), ('S', 'Society of'), ('T', 'Tropical'), ('T', 'Travel'), ('M', 'Medicine')], 'Société suisse de médecine tropicale et de médecine des voyages', '<p>Cette société publie avec Swiss TPH les recommandations suisses de traitement du paludisme datées du 1er septembre 2026. Elles prolongent à cinq jours le traitement par artéméther/luméfantrine du paludisme à P. falciparum non compliqué.</p>'+SWISS)
a('Swiss TPH', [('Swiss', 'Suisse'), ('T', 'Tropical'), ('P', 'Public'), ('H', 'Health')], 'Swiss Tropical and Public Health Institute', '<p>Institut suisse associé au Centre national de référence pour le paludisme. Avec la SSTTM, il fournit la recommandation clinique suisse de septembre 2026 et un circuit d’avis spécialisé.</p>'+SWISS)
a('FI', [('F', 'Fach'), ('I', 'Information')], 'Information professionnelle suisse du médicament', '<p>« FI » est le type de texte Fachinformation du portail Swissmedicinfo ; en français, il s’agit de l’information professionnelle du produit. Celle de Riamet, mise à jour en décembre 2019, décrit six prises sur trois jours chez l’adulte d’au moins 35 kg. La recommandation clinique suisse de septembre 2026 en propose dix sur cinq jours.</p>'+RIAMET+SWISS)
a('IV', [('I', 'Intra'), ('V', 'Veineux')], 'Voie intraveineuse', '<p>Administration directement dans une veine. La recommandation suisse 2026 réserve l’artésunate intraveineux au paludisme grave en milieu hospitalier, suivi d’un traitement oral complet lorsque les critères de relais sont remplis. La préparation suit le produit effectivement disponible à l’hôpital.</p>'+SWISS)
a('A/L', [('A', 'Artéméther'), ('L', 'Luméfantrine')], 'Association artéméther/luméfantrine', '<p>L’artéméther élimine rapidement les formes sanguines asexuées ; la luméfantrine poursuit l’action sur les parasites restants. Une prise avec un aliment ou une boisson contenant des lipides améliore l’absorption de la luméfantrine. Le schéma suisse 2026 de cinq jours pour P. falciparum diffère de la FI Riamet de 2019.</p>'+SWISS+RIAMET)
a('Riamet', [('Riamet', 'nom commercial, non un sigle')], 'Riamet, artéméther 20 mg et luméfantrine 120 mg', '<p>Produit utilisé pour traiter un paludisme à P. falciparum non compliqué. Sa FI suisse décrit six prises sur trois jours, 24 comprimés pour un adulte d’au moins 35 kg ; la recommandation SSTTM/Swiss TPH 2026 porte à dix prises, 40 comprimés. Riamet n’est pas une prophylaxie.</p>'+RIAMET+SWISS)
a('TDR', [('T', 'Test'), ('D', 'de Diagnostic'), ('R', 'Rapide')], 'Test de diagnostic rapide du paludisme', '<p>Il détecte des antigènes parasitaires, notamment HRP2 ou pLDH selon la cassette. Un résultat négatif unique ne suffit pas à exclure le paludisme si la suspicion reste élevée ; la microscopie permet de déterminer l’espèce et de quantifier la parasitémie. HRP2 peut persister après guérison.</p>'+SWISS+OMS)
a('HRP2', [('H', 'Histidine'), ('R', 'Rich'), ('P', 'Protein'), ('2', 'type 2')], 'Protéine parasitaire riche en histidine 2', '<p>Antigène de Plasmodium falciparum recherché par certains tests rapides. Les délétions des gènes pfhrp2/3 peuvent rendre le test faussement négatif ; l’antigène peut aussi persister après la disparition des formes asexuées sanguines.</p>'+SWISS+OMS)
a('HRP3', [('H', 'Histidine'), ('R', 'Rich'), ('P', 'Protein'), ('3', 'type 3')], 'Protéine parasitaire riche en histidine 3', '<p>Une délétion conjointe des gènes parasitaires pfhrp2 et pfhrp3 peut faire perdre la cible d’un test rapide fondé sur HRP2 et conduire à un faux résultat négatif ; le frottis microscopique reste nécessaire selon la suspicion.</p>'+SWISS+OMS)
a('PfHRP2', [('Pf', 'Plasmodium falciparum'), ('H', 'Histidine'), ('R', 'Rich'), ('P', 'Protein'), ('2', 'type 2')], 'Protéine 2 riche en histidine de Plasmodium falciparum', '<p>Autre notation de HRP2. Le test rapide qui la cible n’est ni une quantification de la parasitémie ni un marqueur fiable de guérison immédiate.</p>'+SWISS+OMS)
a('pLDH', [('p', 'parasitaire'), ('LDH', 'lactate dehydrogenase, lactate déshydrogénase')], 'Lactate déshydrogénase parasitaire', '<p>Enzyme de Plasmodium détectée par certains tests rapides. Elle complète la détection de HRP2, notamment si celui-ci manque, mais un test rapide ne remplace pas le frottis pour identifier précisément l’espèce et mesurer la parasitémie.</p>'+SWISS+OMS)
a('PfEMP1', [('Pf', 'Plasmodium falciparum'), ('E', 'Erythrocyte'), ('M', 'Membrane'), ('P', 'Protein'), ('1', 'type 1')], 'Protéine 1 de membrane érythrocytaire de Plasmodium falciparum', '<p>Famille de protéines exposées à la surface des globules rouges infectés. Elle favorise leur adhérence à l’endothélium et leur séquestration microvasculaire ; une parasitémie mesurée dans le sang périphérique ne reflète donc pas toute la charge parasitaire.</p>'+OMS)
a('EPCR', [('E', 'Endothelial'), ('P', 'Protein'), ('C', 'C'), ('R', 'Receptor')], 'Récepteur endothélial de la protéine C', '<p>Récepteur endothélial auquel certaines variantes de PfEMP1 peuvent se lier. Cette adhérence participe à la séquestration microvasculaire et peut perturber la microcirculation ; elle n’est pas un test clinique de routine pour diagnostiquer le paludisme cérébral.</p>'+OMS)
a('NFS', [('N', 'Numération'), ('F', 'Formule'), ('S', 'Sanguine')], 'Numération formule sanguine', '<p>Elle suit notamment l’hémoglobine et les plaquettes. La recommandation suisse 2026 demande une numération avec microscopie parasitaire toutes les 24 heures jusqu’à négativation dans le traitement du paludisme non compliqué.</p>'+SWISS)
a('PCR', [('P', 'Polymerase'), ('C', 'Chain'), ('R', 'Reaction')], 'Réaction de polymérisation en chaîne', '<p>Cette technique amplifie des séquences d’acides nucléiques pour aider à identifier un agent infectieux. Dans le paludisme, elle peut préciser une espèce ou une infection mixte, mais son délai ne remplace pas le diagnostic microscopique urgent ni la quantification de la parasitémie.</p>'+SWISS+OMS)
a('CYP3A4', [('CYP', 'cytochrome P450'), ('3', 'famille 3'), ('A', 'sous-famille A'), ('4', 'isoenzyme 4')], 'Cytochrome P450 3A4', '<p>Enzyme du métabolisme de nombreux médicaments. Les inducteurs puissants comme la rifampicine peuvent diminuer l’exposition à l’artéméther et à la luméfantrine ; la FI suisse Riamet les contre-indique dans les situations citées.</p>'+RIAMET)
a('QTc', [('Q', 'début du complexe QRS'), ('T', 'fin de l’onde T'), ('c', 'corrigé selon la fréquence cardiaque')], 'Intervalle QT corrigé', '<p>Mesure de repolarisation sur l’électrocardiogramme corrigée pour la fréquence. Une prolongation ou des facteurs qui la favorisent, dont certains médicaments et troubles électrolytiques, modifient la sécurité du choix de Riamet selon sa FI.</p>'+RIAMET)
a('OFSP', [('O', 'Office'), ('F', 'fédéral'), ('S', 'de la santé'), ('P', 'publique')], 'Office fédéral de la santé publique', '<p>Autorité sanitaire suisse qui rappelle l’urgence d’une fièvre après exposition au paludisme et édite le Guide de la déclaration obligatoire 2026. Le délai administratif de déclaration ne retarde pas les soins.</p><p><a href="https://www.bag.admin.ch/dam/fr/sd-web/MDjbgfEN6jEf/250321_BAS_Meldeleitfaden_FR.pdf" target="_blank" rel="noopener">Guide 2026, paludisme, p. 88–89</a>.</p>')
