from cardio_1 import a, G
# R06 — Dyspnée et anomalies de la respiration (P-02-Pneumologie). Clés absentes du glossaire et des dossiers de travail au 09.10.2026.
a('ESMO', [('E', 'European (européenne)'), ('S', 'Society for (société de)'), ('M', 'Medical (médicale)'), ('O', 'Oncology (oncologie)')], 'Société européenne d’oncologie médicale', '<p>Société savante européenne d’oncologie. Sa recommandation de 2020 sur la dyspnée du patient atteint de cancer (ESMO Open) fixe l’évaluation, les mesures non médicamenteuses et la place de la morphine.</p>', 'r06-contentieux-opioides')
a('SFMU', [('S', 'Société'), ('F', 'Française de'), ('M', 'Médecine d’'), ('U', 'Urgence')], 'Société française de médecine d’urgence', '<p>Société savante française de médecine d’urgence. Avec la Société de réanimation de langue française, elle a publié en 2025 des recommandations sur la prise en charge de la dyspnée aiguë en urgence.</p>', 'r06-gravite')
a('SRLF', [('S', 'Société de'), ('R', 'Réanimation de'), ('L', 'Langue'), ('F', 'Française')], 'Société de réanimation de langue française', '<p>Société savante francophone de médecine intensive et de réanimation, coautrice des recommandations de 2025 sur la dyspnée aiguë en urgence.</p>')
a('ORL', [('O', 'Oto-'), ('R', 'Rhino-'), ('L', 'Laryngologie')], 'Oto-rhino-laryngologie', '<p>Spécialité médicale et chirurgicale de l’oreille, du nez, du pharynx et du larynx. Le spécialiste ORL participe à la sécurisation des voies aériennes en cas d’obstruction haute.</p>', 'r06-obstruction')
a('ELS', [('E', 'European (européenne)'), ('L', 'Laryngological (de laryngologie)'), ('S', 'Society (société)')], 'Société européenne de laryngologie', '<p>Société savante européenne de laryngologie, coautrice avec l’ERS de la déclaration de 2017 sur l’obstruction laryngée induite.</p>', 'r06-oli')
a('ESRS', [('E', 'European (européenne)'), ('S', 'Sleep (du sommeil)'), ('R', 'Research (de recherche)'), ('S', 'Society (société)')], 'Société européenne de recherche sur le sommeil', '<p>Société savante européenne de médecine du sommeil, coautrice avec l’ERS de la déclaration de 2025 sur la servo-ventilation auto-adaptative dans l’apnée centrale du sommeil.</p>', 'r06-contentieux-asv')
a('HAS', [('H', 'Haute'), ('A', 'Autorité de'), ('S', 'Santé')], 'Haute Autorité de santé (France)', '<p>Autorité publique française d’évaluation en santé. Son guide du parcours de soins de la BPCO (2014, actualisé en 2019) donne la version française de l’échelle de dyspnée mMRC.</p>', 'r06-mmrc')
a('BEAMS', [('BEAMS', 'nom propre d’essai ; son développement n’est pas donné dans la publication lue')], 'Essai BEAMS (2022)', '<p>Essai randomisé australien, en double aveugle, chez 160 patients atteints de BPCO et de dyspnée chronique sévère : 8 ou 16 mg par jour de morphine à libération prolongée n’ont pas réduit la pire dyspnée après une semaine par rapport au placebo (Ekström et al., 2022).</p>', 'r06-contentieux-opioides')
a('MORDYC', [('MOR', 'MORphine'), ('DY', 'for treatment of DYspnea (pour le traitement de la dyspnée)'), ('C', 'in patients with COPD (chez les patients atteints de BPCO)')], 'Essai MORDYC (2020)', '<p>Essai randomisé néerlandais en double aveugle : 10 mg de morphine à libération prolongée deux fois par jour pendant quatre semaines ont amélioré l’état de santé spécifique de la BPCO, sans modifier significativement la PaCO₂ ; la pire dyspnée ne s’est améliorée qu’aux degrés 3 et 4 de l’échelle mMRC (Verberkt et al., 2020).</p>', 'r06-contentieux-opioides')
