from cardio_1 import a, G
L=[
('ESVS',[('E','European'),('S','Society for'),('V','Vascular'),('S','Surgery')],'Société européenne de chirurgie vasculaire','<p>Recommandations 2024 sur les anévrismes aorto-iliaques.</p>'),
('EVAR',[('E','EndoVascular'),('V','(endovasculaire)'),('A','Aneurysm'),('R','Repair')],'Réparation endovasculaire d’un anévrisme','<p>Endoprothèse introduite par voie fémorale.</p>'),
('TEVAR',[('T','Thoracic'),('EVAR','EndoVascular Aortic Repair')],'Endoprothèse de l’aorte thoracique','<p>Traitement des dissections de type B compliquées et de certains anévrismes thoraciques.</p>'),
('IRAD',[('I','International'),('R','Registry of'),('A','Acute Aortic'),('D','Dissection')],'Registre international des dissections aortiques aiguës','<p>Source principale des données de mortalité des dissections.</p>'),
('ADD-RS',[('A','Aortic'),('D','Dissection'),('D','Detection'),('RS','Risk Score')],'Score de risque de dissection aortique','<p>Score de 0 à 3 ; associé aux D-dimères pour exclure une dissection.</p>','i71-addrs'),
('ADvISED',[('ADvISED','nom d’étude (ADD-RS et D-dimères), non strictement lettre à lettre')],'Étude ADvISED (2018)','<p>Validation de la stratégie ADD-RS + D-dimères.</p>'),
('MASS',[('M','Multicentre'),('A','Aneurysm'),('S','Screening'),('S','Study')],'Essai MASS (2002)','<p>Dépistage échographique des hommes de 65 à 74 ans : mortalité liée à l’anévrisme réduite.</p>'),
('UKSAT',[('UK','United Kingdom'),('S','Small'),('A','Aneurysm'),('T','Trial')],'Essai britannique des petits anévrismes','<p>Pas de bénéfice à opérer les anévrismes asymptomatiques de moins de 55 mm.</p>'),
('ADAM',[('A','Aneurysm'),('D','Detection'),('A','And'),('M','Management')],'Essai ADAM','<p>Résultat concordant avec UKSAT.</p>'),
('EVAR-1',[('EVAR','EndoVascular Aneurysm Repair'),('1','essai n° 1')],'Essai EVAR-1','<p>Endoprothèse versus chirurgie ouverte.</p>'),
('DREAM',[('D','Dutch'),('R','Randomized'),('E','Endovascular'),('A','Aneurysm'),('M','Management')],'Essai DREAM','<p>Endoprothèse versus chirurgie ouverte (Pays-Bas).</p>'),
('OVER',[('O','Open'),('V','Versus'),('E','Endovascular'),('R','Repair')],'Essai OVER','<p>Endoprothèse versus chirurgie ouverte (États-Unis).</p>'),
('IMPROVE',[('IMPROVE','nom d’essai (endoprothèse dans la rupture), non strictement lettre à lettre')],'Essai IMPROVE','<p>Stratégie endovasculaire dans la rupture d’anévrisme.</p>'),
('CADISS',[('C','Cervical'),('A','Artery'),('DIS','DISsection'),('S','Stroke Study')],'Essai CADISS (2015)','<p>Antiagrégant versus anticoagulant dans la dissection cervicale : pas de différence.</p>'),
('TREAT-CAD',[('TREAT','TREATment'),('CAD','Cervical Artery Dissection')],'Essai suisse TREAT-CAD (2021)','<p>Aspirine versus antivitamine K dans la dissection cervicale.</p>'),
('BBEST',[('B','Beta-Blockers in'),('E','Ehlers-Danlos'),('S','Syndrome'),('T','Treatment')],'Essai BBEST','<p>Céliprolol dans l’Ehlers-Danlos vasculaire.</p>'),
('FBN1',[('F','FiBrilliNe'),('1','1')],'Gène de la fibrilline-1','<p>Syndrome de Marfan.</p>'),
('TGFBR1',[('TGF','Transforming Growth Factor'),('BR1','Bêta Récepteur 1')],'Gène du récepteur 1 du TGF-β','<p>Syndrome de Loeys-Dietz.</p>'),
('TGFBR2',[('TGF','Transforming Growth Factor'),('BR2','Bêta Récepteur 2')],'Gène du récepteur 2 du TGF-β','<p>Syndrome de Loeys-Dietz.</p>'),
('TGFB2',[('TGF','Transforming Growth Factor'),('B2','Bêta 2')],'Gène du TGF-β2','<p>Syndrome de Loeys-Dietz.</p>'),
('TGFB3',[('TGF','Transforming Growth Factor'),('B3','Bêta 3')],'Gène du TGF-β3','<p>Syndrome de Loeys-Dietz.</p>'),
('SMAD3',[('SMAD','homologue des protéines SMA et MAD'),('3','3')],'Gène SMAD3','<p>Signalisation du TGF-β ; Loeys-Dietz avec arthrose précoce.</p>'),
('COL3A1',[('COL','COLlagène'),('3','type III'),('A1','chaîne alpha 1')],'Gène du collagène de type III','<p>Ehlers-Danlos vasculaire.</p>'),
('ACTA2',[('ACT','ACTine'),('A2','alpha 2 du muscle lisse')],'Gène de l’actine alpha 2','<p>Anévrismes thoraciques familiaux.</p>'),
('MYH11',[('MYH','MYosine, chaîne lourde (Heavy)'),('11','11')],'Gène MYH11','<p>Anévrismes thoraciques familiaux avec canal artériel.</p>'),
('MYLK',[('MYLK','MYosin Light chain Kinase')],'Gène de la kinase des chaînes légères de myosine','<p>Anévrismes thoraciques familiaux.</p>'),
('MMP-9',[('M','Matrix'),('M','Metallo'),('P','Protéinase'),('9','9')],'Métalloprotéase matricielle 9','<p>Dégrade l’élastine de la paroi aortique.</p>'),
('dP/dt',[('dP/dt','dérivée de la pression par rapport au temps')],'Pente de montée de la pression','<p>Vitesse d’augmentation de la pression pendant l’éjection ; réduite par les bêtabloquants.</p>'),
('DeBakey',[('DeBakey','nom propre : Michael DeBakey, chirurgien')],'Classification de DeBakey','<p>Types I, II, III selon l’extension de la dissection.</p>'),
('TEM',[('T','Type'),('E','Entry (porte d’entrée)'),('M','Malperfusion')],'Classification TEM','<p>Complète la classification de Stanford.</p>'),
('Loeys-Dietz',[('Loeys-Dietz','nom propre : Bart Loeys et Harry Dietz')],'Syndrome de Loeys-Dietz','<p>Aortopathie héréditaire de la voie du TGF-β.</p>'),
('Claude-Bernard',[('Claude-Bernard','nom propre : Claude Bernard')],'Claude Bernard','<p>Physiologiste ; syndrome de Claude Bernard-Horner.</p>'),
('Bernard-Horner',[('Bernard-Horner','nom propre : Claude Bernard et Johann Horner')],'Syndrome de Claude Bernard-Horner','<p>Ptosis, myosis, énophtalmie par atteinte sympathique.</p>'),
]
for x in L: a(*x)
for c,tt in [('I71.0','Dissection de l’aorte'),('I71.1','Anévrisme de l’aorte thoracique, rompu'),('I71.2','Anévrisme de l’aorte thoracique, sans mention de rupture'),('I71.3','Anévrisme de l’aorte abdominale, rompu'),('I71.4','Anévrisme de l’aorte abdominale, sans mention de rupture'),('I71.5','Anévrisme de l’aorte thoraco-abdominale, rompu'),('I71.6','Anévrisme de l’aorte thoraco-abdominale, sans mention de rupture')]:
    a(c,[(c,'code de la Classification internationale des maladies, 10e révision, modification allemande')],tt,'<p>Code CIM-10-GM.</p>')
